### ISSUE TITLE
Request to create a standard_name discussion forum

### ISSUE THREAD

**Issue by kenkehoe** [cf-convention/discuss#1]
I like this idea and suggest making a different forum for standard_name discussion to allow more granularity in subscriptions.

**Comment by kenkehoe** [comment]
Other option was to create a template for standard_name and general discussion that would allow separating the discussions. That may work too.

**Comment by japamment** [comment]
Dear Ken

I don't have a strong opinion about the need for creating a separate discussion forum for standard names, but do support the idea of having a standard names issue template. If a "standard names" label were created (as requested in issue [#7](https://github.com/cf-convention/discuss/issues/7)) we could then also create a template which automatically adds such a label. I suggest that the template should add the string "Standard names: " as the first part of the title. This would help those viewing issues via email to sort messages automatically.

Best wishes,
Alison

**Comment by davidhassell** [comment]
I think that setting up some templates for the "discuss" issues (like has been done at https://github.com/cf-convention/cf-conventions/issues/new/choose) is a good idea (as is creating a "standard name" label in the "discuss" and "cf-conventions" repos - see #7).

Might I suggest that @japamment, @feggleton and any other interested parties design the template, and then we can just add it to repository?

**Comment by japamment** [comment]
Dear David (@davidhassell),

Francesca and I plan to spend some time next week putting together a template for standard names issues. Please could you or @ethanrd give us both write access to the discuss repo as I think we might need it to be able to create a template.

At the moment it seems we can only open issues or add comments in this repo. Currently we can't close issues that were opened by other people, nor can we add the 'standard names' label to issues opened by others. I've looked at the GitHub help pages and they seem to imply that a user needs write access to be able to do any of these things.

**Comment by davidhassell** [comment]
Hi Alison and Francesca,

I've given @japamment and @feggleton write access to "discuss". Let me know if the functionality doesn't appear. I think you should also have it on this repo, so you can set labels here, too.

**Comment by japamment** [comment]
Hi David,

Thanks for giving us write access. We can now close issues and add the standard name label to any issue as needed.

I've been looking further into how to create an issue template. Apparently this is done by using the Settings button under the title of the main page on a repo. I can see this under cf-convention/cf-conventions (see attached screenshot) but it's not visible to me under cf-convention/discuss.
![settings_button](https://user-images.githubusercontent.com/7838433/70711486-93b7d200-1cd9-11ea-8856-824eb78154f3.jpg)

I'm not sure why it works for one repo and not the other. Could this be to do with membership of different teams within the organization?

**Comment by davidhassell** [comment]
Hi Alison, Fran,

I've done something - do you have access in cf-convention/discuss, now?

**Comment by japamment** [comment]
Hi David,

Thanks for your help. The Settings button has appeared (at least for me) in the discuss repo, so we should be able to add a template now.

-----------------------------------------------------------------------------------------------------------
Alison Pamment                                                               Tel: +44 1235 778065
NCAS/Centre for Environmental Data Analysis    Email: alison.pamment@stfc.ac.uk<mailto:alison.pamment@stfc.ac.uk>
STFC Rutherford Appleton Laboratory
R25, 2.22
Harwell Oxford, Didcot, OX11 0QX, U.K.

**Comment by japamment** [comment]
A standard names template has now been created and can be selected when opening a new discussion issue. We tried to followed a similar format to the issue templates in the cf-conventions repo.

**Comment by davidhassell** [comment]
The template looks good to me - thanks.

**Comment by feggleton** [comment]
Thanks, I can also see the settings tab.

**Comment by neumannd** [comment]
The template uses the name *Definition* for the text that is called *Description* in the CF Standard Name list. Shouldn't it be called *Description* instead of *Definition* in the standard name template to be consistent?

**Comment by roy-lowry** [comment]
@neumannd Good point.

**Comment by erget** [comment]
I do agree that it would be nice to have a separate repository for this, because there's a lot of traffic on standard names that doesn't necessarily interest all.

**Comment by davidhassell** [comment]
Hi,

This issue has, sort of, come up a few times over the years - but previously in relation to whether or not Trac tickets for enhancements should be forwarded to the e-mail list. The argument for doing so is that you can't join in if you don't know that the discussion is going on! Many enhancement and standard name discussions have benefited greatly from input by interested, but not involved, parties.

If we did have another repository, I would hope the advice would be to "watch" that, too. In this case the traffic e-mail would not be reduced. However, we already know that standard name discussions may occur on the "discuss" and "cf-conventions" repos, so I think adding a third place may complicate things a bit too much.

Thanks,
David
