### ISSUE TITLE
 Standard names: Volume Mixing Ratio for CH2Br2, CHBr3,  CH2BrCl, CHBr2Cl, CHbrCL2

### ISSUE THREAD

**Issue by martinjuckes** [cf-convention/discuss#102]
**Proposer's name** : Martin Juckes
**Date** 9th April 2021

**- Term** `mole_fraction_of_dibromomethane_in_air`

**- Description** 
"Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula for dibromomethane is CH2Br2. The IUPAC name is dibromomethane. 

**- Units** mol mol-1

**- Term** `mole_fraction_of_tribromomethane_in_air`

**- Description** 
"Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula for tribromomethane is CHBr3. The IUPAC name is tribromomethane. 

**- Units** mol mol-1

**- Term** `mole_fraction_of_bromochloromethane_in_air`

**- Description** 
"Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula for bromochloromethane is CH2BrCl. The IUPAC name is bromochloromethane. 

**- Units** mol mol-1

**- Term** `mole_fraction_of_dibromochloromethane_in_air`

**- Description** 
"Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula for dibromochloromethane is CHBr2Cl. The IUPAC name is dibromochloromethane. 

**- Units** mol mol-1

**- Term** `mole_fraction_of_bromodichloromethane_in_air`

**- Description** 
"Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula for bromodichloromethane is CHBrCl2. The IUPAC name is bromodichloromethane. 

**- Units** mol mol-1

These are very similar to the existing term `mole_fraction_of_dichloromethane_in_air` for CH2Cl2.

The terms are needed by the WCRP Coupled Chemistry Model Intercomparison 2022 project which is running simulations to support the 2022 WMO Ozone Assessment.

**Comment by feggleton** [comment]
Hi Martin,

Thanks for the proposals. These terms have now been added to the cfeditor. 

Comments welcome.

Thanks,

Fran

**Comment by feggleton** [comment]
These terms look fine to me and follow the definitions of already existing terms that are very similar. I would say if there are no further comments in the next 7 days then these can be accepted.

**Comment by feggleton** [comment]
Thanks these can now be accepted @japamment

**Comment by feggleton** [comment]
These terms were added to the Standard Name Table Version 80 on the 7th of Feb 2023.
