### ISSUE TITLE
 Standard names: request for ammonia concentration in sea water

### ISSUE THREAD

**Issue by StephaneTarot** [cf-convention/discuss#103]
Proposer's name: Stéphane Tarot
Date: 11/04/2021

Term: mole_concentration_of_ammonia_in_sea_water
Description: Mole concentration means moles (amount of substance) per unit volume and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. The chemical formula of ammonia is NH3-N.
Units: mol m-3

I was an occasional contributor to the mailing list. This is my first time on GitHub. I hope this is the correct way to request a new standard_name.

Best regards
Stéphane Tarot

**Comment by roy-lowry** [comment]
There is already a Standard Name mole_concentration_of_ammonium_in_sea_water. Unlike gases such as oxygen and nitrogen ammonia does not dissolve in sea water as a gas. Instead it reacts chemically to form ammonium ions (NH4+).  Dissolved ammonia and ammonium are frequently used as synonyms, even in the scientific literature. However, for a standard name the pedantically correct term should be used.
So Stéphane please use the existing Standard Name.

**Comment by StephaneTarot** [comment]
Dear @roy-lowry,

Thank you for your detailed and relevant answer.
I was not aware of this. It is now also confirmed by the scientist I'm working with.
Sorry for this wrong request.

Best regards
Stéphane Tarot
