### ISSUE TITLE
The 2021 on-line CF workshop - 21-23 September

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#104]
Dear CF community,

We are pleased to announce the provisional dates for this year's CF workshop:

**Tuesday-Thursday 21-23 September 2021**

The meeting will be **on-line** and will comprise a three hour session on each day: **15:00-1800 UTC**, plus an informal hour at the end of each day. If you know of any significant clashes with other events, then please let us know very soon (by the 18th April).

The workshop agenda will be determined by what is of interest to the community and is completely open at this stage, but will certainly comprise a mix of presentations and breakout discussions, similar to the structure of [last year's on-line meeting](https://cfconventions.org/Meetings/2020-Workshop.html).

If you have any ideas for agenda items, or would like to present some work or lead a discussion then please reply on this thread by **Wednesday 5th May**.

The Organizing Committee understands that the scheduled meeting times inconvenience potential attendees living in East Asia, Australia, and the Pacific Islands. To encourage participation from these regions, we are considering holding a special breakout session at a more convenient time to be decided. Please express your interest in attending a special session for Western Pacific time zones, either as a comment on this issue or by contacting the Organizing Committee directly (via _david.hassell_ at _ncas.ac.uk_), letting us know your time zone.

All the best,
The organising committee:

_Aleksandar Jelenak
Alison Pamment
Antonio Cofiño
Charlie Zender
Daniel Lee
David Hassell
Ethan Davis
Fernando Carvalho Pacheco
Guilherme Castelao
Kevin O'Brien_

**Comment by japamment** [comment]
Hi David, All,

I'd like to suggest a couple of items for the September meeting.

Firstly, I'd like to present something on work I've been doing with an RDA group called I-ADOPT (InteroperAbility of Observable Property Terminology) which offers an opportunity for making CF Standard Names more interoperable with other environmental vocabularies and ontologies. A working title for this could be "Steps toward wider interoperability of CF standard names in environmental science".

Secondly, I propose a breakout session on standard names (similar to the 2020 workshop) as there always seems to be plenty to discuss.

Best wishes,
Alison

**Comment by davidhassell** [comment]
Thanks, Alison - this sounds ideal - both the angle of the presentation and the inclusion of a breakout topic.

**Comment by ajelenak** [comment]
Registration form link for the workshop is in issue #121.
