### ISSUE TITLE
Small correction to the description of a group of standard names 

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/discuss#105]
**Proposer's name**
Lars Bärring

**Date**
2021-05-04

**Overview**
In the description of several standard names I have seen a small typo:

 > ... a coordinate variable or scalar coordinate variable with **the a** standard name of X ...

 This phrase appears in the description of the following standard names:
``number_of_days_with_air_temperature_above_threshold``
``number_of_days_with_air_temperature_below_threshold``
``number_of_days_with_lwe_thickness_of_precipitation_amount_above_threshold``
``number_of_days_with_surface_temperature_below_threshold``
``number_of_days_with_wind_speed_above_threshold``
``spell_length_of_days_with_air_temperature_above_threshold``
``spell_length_of_days_with_air_temperature_below_threshold``
``spell_length_of_days_with_lwe_thickness_of_precipitation_amount_above_threshold``
``spell_length_of_days_with_lwe_thickness_of_precipitation_amount_below_threshold``

I guess this issue is rather uncontroversial and should be labelled as a `defect`, but whether the correction should be 
*...with **the** standard name of X...*, *...with **a** standard name of X...*, or maybe just *... with standard name X ...* I leave [obviously] to someone else to decide.

**Comment by JonathanGregory** [comment]
Thanks. I agree that this is a defect which should be corrected.

**Comment by davidhassell** [comment]
Thanks, Lars. I also agree.

**Comment by feggleton** [comment]
Thank you for picking this up! I have made the decision for you and added these all to the cfeditor. I have just marked these as accepted as I don't think anyone will mind!

Thanks all

**Comment by japamment** [comment]
Changes applied in version 78 of the standard name table.
