### ISSUE TITLE
 Standard names: change in land ice mass

### ISSUE THREAD

**Issue by andreasgroh** [cf-convention/discuss#108]
Dear all,

I propose to add new standard names describing the change in land ice mass with respect to an arbitrary reference value over a particular ice-covered region (e.g. an entire ice sheet, a single drainage basin or any arbitrarily defined region) as well as its time derivative. This quantity is the spatial integral of what is already defined as the change_in_land_ice_amount. Therefore I propose the following definitions:

**Proposer's name** Andreas Groh
**Date** 2021-05-19

**- Term** change_in_land_ice_mass
**- Description** Zero change in land ice mass is an arbitrary level. "Land ice" means glaciers, ice-caps and ice-sheets resting on bedrock and also includes ice-shelves.
**- Units** kg

**- Term** tendency_of_change_in_land_ice_mass
**- Description** Zero change in land ice mass is an arbitrary level. "Land ice" means glaciers, ice-caps and ice-sheets resting on bedrock and also includes ice-shelves. "tendency_of_X" means derivative of X with respect to time.
**- Units** kg/s

Maybe the following comment needs to be added to the description of both definitions (taken from the standard name land_ice_mass):
The geographical extent of the ice over which the mass is calculated is defined by the horizontal coordinates and any associated coordinate bounds or by a string valued auxiliary coordinate variable with a standard name of "region".

As already mentioned, the standard name land_ice_mass is already available. However, this seems to be an absolute quantity rather than a change of this quantity. For the time derivative, comparable standard names already exist for different components of the overall mass change, e.g. tendency_of_land_ice_mass_due_to_surface_mass_balance.

I am looking forward to your thoughts about the proposed names.

Best regards,

Andreas

**Comment by JonathanGregory** [comment]
Dear @andreasgroh 

Thanks for your proposals. I agree with `change_in_land_ice_mass`, which is analogous to other `change_in_`*X* standard names. I suggest that the tendency should be just `tendency_of_land_ice_mass` because the reference mass makes no difference to the tendency i.e. a constant vanishes on differentiation. Omitting `change_in` makes this more like the existing names with `due_to` that you mention.

Best wishes

Jonathan

**Comment by andreasgroh** [comment]
Dear @JonathanGregory 

Thanks for your prompt reply. I agree with your proposed modifications: `<tendency_of_land_ice_mass>` is more suitable.

Best,
Andreas

**Comment by feggleton** [comment]
Hi all,

Thank you Andreas for your proposal. I have now added these to the cfeditor and made the changes proposed above. The phrase in the term 'land_ice_mass' is:

"The horizontal domain over which the quantity is calculated is described by the associated coordinate variables and coordinate bounds or by a coordinate variable or scalar coordinate variable with the standard name of "region" supplied according to section 6.1.1 of the CF conventions."

Would you like me to add this or your suggestion:

The geographical extent of the ice over which the mass is calculated is defined by the horizontal coordinates and any associated coordinate bounds or by a string valued auxiliary coordinate variable with a standard name of "region".

Thanks,

Francesca

**Comment by andreasgroh** [comment]
Dear @feggleton,

Thanks for spotting this discrepancy. I thought I copied the phrase from 'land_ice_mass', which is obviously not the case. Please add the phrase you have quoted. Thanks.

Best,
Andreas

**Comment by feggleton** [comment]
Great, thanks. I have added that. tendency_of_land_ice_mass and change_in_land_ice_mass are now in the cfeditor (http://cfeditor.ceda.ac.uk/proposals/1). Please let me know if everyone is happy with these terms.

**Comment by andreasgroh** [comment]
Thanks @feggleton, `change_in_land_ice_mass` looks good to me. 

For `tendency_of_land_ice_mass` I think we can remove the sentences "Zero change in land ice mass is an arbitrary level.". This is probably a leftover from my initial proposal, where is proposed `tendency_of_change_in_land_ice_mass` instead of `tendency_of_land_ice_mass`. As mentioned by @JonathanGregory, the time derivative is independent from the absolute level, so there is no need to mention it in the description. 
Moreover, everything following "The geographical extent ..." can be replaced by "The horizontal domain over which the quantity is calculated is described by the associated coordinate variables and coordinate bounds or by a coordinate variable or scalar coordinate variable with the standard name of "region" supplied according to section 6.1.1 of the CF conventions." as you already did for `change_in_land_ice_mass`.

Best,
Andreas

**Comment by feggleton** [comment]
Ah thank you for pointing that out! I must have forgotten to change that last part around. I have removed that sentence too. That makes perfect sense.

Thank you,

Fran

**Comment by feggleton** [comment]
To confirm:

Term:change_in_land_ice_mass
Definition:Zero change in land ice mass is an arbitrary level. "Land ice" means glaciers, ice-caps and ice-sheets resting on bedrock and also includes ice-shelves. The horizontal domain over which the quantity is calculated is described by the associated coordinate variables and coordinate bounds or by a coordinate variable or scalar coordinate variable with the standard name of "region" supplied according to section 6.1.1 of the CF conventions.

Term:tendency_of_land_ice_mass 
Definition:The phrase "tendency_of_X" means derivative of X with respect to time. "Land ice" means glaciers, ice-caps and ice-sheets resting on bedrock and also includes ice-shelves. The horizontal domain over which the quantity is calculated is described by the associated coordinate variables and coordinate bounds or by a coordinate variable or scalar coordinate variable with the standard name of "region" supplied according to section 6.1.1 of the CF conventions.

If there are no further comments in the next 7 days then these terms can be accepted.

**Comment by feggleton** [comment]
These terms have now been accepted.

**Comment by japamment** [comment]
Changes applied in version 78 of the standard name table.
