### ISSUE TITLE
The 2020 CF meeting - save the date

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#12]
Dear CF community,

I am happy to announce that next year's CF meeting will be in **Santander, Spain** with proposed dates:

**Tuesday-Thursday, 9-11 June 2020**

Please put these dates in your diary.

The meeting will last for 2 or 3 days, with the duration and format being settled on early next year.

If you know of any good reason why having the meeting this week is _not_ a good idea (such as there being another conference already happening at that time which might be attended by many with an interest in CF) then do let us know soon, so we can consider working on new dates.

Many thanks and all the best,
David

**Comment by balaji-gfdl** [comment]
My only suggestion might be to try to host it alongside the IS-ENES3 general assembly in Toulouse in the penultimate week of March 2020. I don't see myself making a separate trip just for CF (much as I'd like to visit Cantabria!) But my concerns are quite secondary to the active CF-ers.

**Comment by dblodgett-usgs** [comment]
I have a prior commitment in June and also would have a hard time justifying travel. Another event that could be considered is the ESIP Summer Meeting July 14-17 in Burlington Vermont.

**Comment by davidhassell** [comment]
@balaji-gfdl and @dblodgett-usgs Not bad ideas at all, but the Santander part is non-negotiable, I'm afraid, due to institutional support from Universidad de Cantabria, and EU project funding already being in place. It's also nice to try to have, if possible, the meetings in different continents in different years (we were the US last year).

Remote participation will be possible! 

Given the venue of Santander, the potential flexibility with the dates is of the order plus or minus a week or two.

I hope that makes sense,
David

**Comment by feggleton** [comment]
I am unavailable from 28th May-10th June (in US) but would like to join if the dates do change so I'll keep an eye out. If not then no worries there is always next year.

**Comment by davidhassell** [comment]
The dates have been announced in #35 (see that issue for a possible reschedule due to Covid-19).
