### ISSUE TITLE
 Standard names: Vertical Drainage Amount

### ISSUE THREAD

**Issue by deacud** [cf-convention/discuss#120]
**Proposer's name** Daniel Deacu
**Date** Aug 4th, 2021

We are proposing a standard name for the vertical drainage amount at the bottom of the soil profile. This quantity is calculated in numerous land surface models (e.g. Clark et al., 2015).

Clark et al. (2015): A unified approach for process-based hydrologic modeling: 2. Model implementation and case studies
https://agupubs.onlinelibrary.wiley.com/doi/10.1002/2015WR017200

**- Term:** vertical_drainage_amount

**- Description:** “Drainage” is the process of removal of excess water from soil by gravitational flow. "Amount" means mass per unit area. The vertical drainage amount is the amount of water that drains through the bottom of the soil profile.

**- Units:** kg m-2

**Comment by taylor13** [comment]
Someone might be interested in drainage at a level different from the "bottom of the soil profile".   Also, perhaps "drainage" implies downward, but if it is ever defined as positive up, then "downward" should probably appear in the standard name.  I noticed there are currently definitions for ``baseflow_amount``, ``subsurface_runoff_amount``, ``runoff_flux``, and ``subsurface_runoff_flux``, but it appears they all account for flows both downward and horizontally out of a column or grid cell.  

As I understand it "drainage" is limited to the (downward) vertical component of the flow out of a grid cell *and* limited to only the gravitationally-driven component (*not* diffusively driven).   Would it be better to define it as the *total* amount of water flowing (over some specified time interval, I presume) across a "horizontal" surface at a depth specified by a vertical coordinate?

I'm curious why it isn't usual practice to specify this as a downward flux of water (units: kg m-2 s-1), which to me seems like the natural representation.

**Comment by deacud** [comment]
Thanks for the very useful comments, @taylor13.

The bottom of the soil profile is not necessarily the bottom of the soil column considered in land-surface models. Any level above the bottom-most one defines a soil profile/column whose lower limit is set by that level. 

Since natural drainage is downward, I am not sure if there is a real need to specify the flow direction.

However, what you are proposing, a total amount of water flowing across a horizontal surface at a specified depth, is probably better due to its generality. A standard name for the corresponding flux of water could be defined, as well.

**Comment by JonathanGregory** [comment]
Thanks for your proposal, @deacud.

"Drainage" is a rather general word and there is one standard name that already uses it in a somewhat different way viz. `water_flux_into_sea_water_due_to_surface_drainage`. Hence I suggest that this new standard name should include the phrase `in_soil` to be clear what sort of drainage we mean.

I agree with Karl @taylor13 that it would be sensible to allow for the possibility of a standard name for drainage at a particular depth. However, I understand that the present proposal is for drainage at a geophysically defined level (rather than one which could be specified by a depth coordinate), namely the "bottom of the soil profile." Could you please explain a bit about what that means? Thanks.

**Comment by deacud** [comment]
A soil profile consists of vertically-stacked soil layers. Here is its definition taken from Schoonover and Crim (2015):

"The vertical section of soil that shows the presence of distinct horizontal layers is known as the **soil profile** (SSSA 2008). The term horizon refers to the individual or distinct layers within the soil profile."

Schoonover and Crim (2015): An Introduction to Soil Concepts and the Role of Soils in Watershed Management
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1936-704X.2015.03186.x

In many land-surface/hydrological models, the soil profile is assumed to extend from the surface to a specified depth rather than to the bedrock. In this context, the more generic 'soil column' may be more appropriate than 'soil profile'. That would remove the extent to the bedrock and thus a geophysically defined depth (depth to bedrock) which could be implied by the soil profile. The bottom of the soil column could then be set by a depth coordinate, as suggested by @JonathanGregory and @taylor13. 

Below are the modified standard name and description:

Term: vertical_drainage_amount_in_soil

Description: “Drainage” is the process of removal of excess water from soil by gravitational flow. "Amount" means mass per unit area. The vertical drainage amount in soil is the amount of water that drains through the bottom of a soil column extending from the surface to a specified depth.

**Comment by JonathanGregory** [comment]
Thanks for the definition of "soil profile". If you would like to use this term in models in general, I suppose you would rather not choose a particular numerical level, as that might be model-dependent. Would it be more helpful to describe the level as `base_of_soil_model`? (Similarly, we have standard names which mention `base_of_ice_sheet_model` and `top_of_atmosphere_model` for example.)

If it was a flux, we could describe it as "at" a level, meaning the flux through that level, but I don't think it would be clear what was meant by an amount "at" a level. Perhaps the quantity you have in mind could be called `drainage_amount_through_base_of_soil_model`?

A different point: I wonder if this quantity is identical to `subsurface_runoff_amount`, which is an existing standard name?

Jonathan

**Comment by deacud** [comment]
Thanks for your suggestion, @JonathanGregory. `Drainage_amount_through_base_of_soil_model` describes very well the quantity used not only in our model but likely also in other models.

As for the `subsurface_runoff_amount`, its description in the CF standard name table is:
"Amount" means mass per unit area. Runoff is the liquid water which drains from land. If not specified, "runoff" refers to the sum of surface runoff and subsurface drainage.

Therefore, in the context of a typical land-surface/hydrological model, the quantity represented by `subsurface_runoff_amount` includes the the quantity represented by `drainage_amount_through_base_of_soil_model`. The latter is supposed to represent the vertical component of the drainage.

**Comment by JonathanGregory** [comment]
OK then. Others may comment and either Fran @feggleton or Alison @japamment will summarise in due course. Thanks again for the proposal.

**Comment by taylor13** [comment]
Thanks, @deacud, for providing the helpful information.   In case you are a new CF user, it will be important to include as part of the file metadata, bounds on the time-intervals over which "drainage amount" is accumulated.  So, for example, if you are reporting annual drainage amount, you would have a time coordinate with bounds spanning a year. 

[Also, although for an extensive quantity "sum" is the default cell_method, it wouldn't hurt to explicitly include an attribute similar to ``cell_methods = time: sum".]

**Comment by deacud** [comment]
Thanks for your suggestion, @taylor13. Having the time bounds and the cell method 'time: sum' would be quite useful. I will do that.

**Comment by feggleton** [comment]
Thanks @deacud for your request. As far as I can see the latest version of the term is:

drainage_amount_through_base_of_soil_model

Does this description need amending since:

Description: “Drainage” is the process of removal of excess water from soil by gravitational flow. "Amount" means mass per unit area. The vertical drainage amount in soil is the amount of water that drains through the bottom of a soil column extending from the surface to a specified depth.
?

**Comment by deacud** [comment]
Hi @feggleton. There is no need for any amends.

**Comment by feggleton** [comment]
Perfect thanks. As there have been no further comments since February, this can now be accepted.

**Comment by feggleton** [comment]
I do apologies, this term has gone into the table as vertical_drainage_amount_in_soil and the latest update of the name to drainage_amount_through_base_of_soil_model has been missed. This is my fault. I have added the updated name into the editor and added as accepted so will go straight into the next update.

**Comment by JonathanGregory** [comment]
I see `drainage_amount_through_base_of_soil_model` in the standard name table now. Apparently you have fixed it, Fran. Thanks.

**Comment by deacud** [comment]
Thank you, everyone!

**Comment by JonathanGregory** [comment]
This name is now in the table (I can see it at version 81).
