### ISSUE TITLE
 Standard names: dry_atmosphere_mole_fraction_of_ ..CO2 / CO / CH4 / NO2 ... _in_air

### ISSUE THREAD

**Issue by claudiodonofrio** [cf-convention/discuss#122]
Name: Claudio D'Onofrio
Date: 6th September 2021
Label: EnvriFAIR

- Term: **dry_mole_fraction_of_carbon_dioxide_in_air**
Description:  Based on http://vocab.nerc.ac.uk/collection/P07/current/ZV42E2GH/ for a localized measurement.
Unit: (1) dimensionless
- Term: **dry_mole_fraction_of_carbon_monoxide_in_air**
Description:  Closely related is http://vocab.nerc.ac.uk/collection/P07/current/CFSN0812/ but here explicitly for dry air and  localized measurement
Unit: (1) dimensionless
- Term: **dry_mole_fraction_of_methane_in_air**
Description: Closely related is http://vocab.nerc.ac.uk/collection/P07/current/CFV7N55/ but here explicitly for dry air and  localized measurement
Unit: (1) dimensionless
- Term: **dry_mole_fraction_of_nitrogen_dioxide_in_air**
Description: Closely related is http://vocab.nerc.ac.uk/collection/P07/current/CFSN0817/ but here explicitly for dry air and  localized measurement
Unit: (1) dimensionless

**Comment by JonathanGregory** [comment]
Dear @claudiodonofrio 

Thanks for these proposals. In the corresponding quantities, which you refer to, for the vertical integral over the atmospheric column, we have the phrase `dry_atmosphere`, in which it's clear that "dry" refers to "atmosphere". I would say that your quantities should be of the form `mole_fraction_of_`X`_in_dry_air`. Would that make sense?

Best wishes

Jonathan

**Comment by claudiodonofrio** [comment]
@JonathanGregory. Absolutely. I am happy with your suggestion, it is more intuitive and reads better.

**Comment by japamment** [comment]
Dear @claudiodonofrio

Thank you for your proposals. I also support the suggestion by @JonathanGregory of using "in_dry_air". I've added some descriptions, based on our usual text:

- Term: **mole_fraction_of_carbon_dioxide_in_dry_air**
   Unit: 1
   Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapor is excluded. The chemical formula for carbon dioxide is CO2.

- Term: **mole_fraction_of_carbon_monoxide_in_dry_air**
   Unit: 1
   Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapor is excluded. The chemical formula of carbon monoxide is CO.

- Term: **mole_fraction_of_methane_in_dry_air**
   Unit: 1 
   Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapor is excluded. The chemical formula for methane is CH4. Methane is a member of the group of hydrocarbons known as alkanes. There are standard names for the alkane group as well as for some of the individual species.

- Term: **mole_fraction_of_nitrogen_dioxide_in_dry_air**
   Unit: 1
   Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapor is excluded. The chemical formula for nitrogen dioxide is NO2.

These proposals seem quite straight forward, so if you are happy with them I think we can start the 7 day countdown to accepting the names for publication.

Best wishes

Alison

**Comment by atverm** [comment]
Thanks for this, I agree with the suggestion to use in_dry_air, which I was just about to propose. 
However, the gas that is important to add for ICOS as greenhouse gas is N2O, with IUPAC standard name nitrous oxide, which is not the same as NO2 nitrogen dioxide, which is the proposed fourth term.  So the term to add instead of that for NO2 is mole_fraction_of_nitrous_oxide_in_dry_air. The standard name for NO2 without in_dry_air is ok as this is usually not measured in dry air and the correction of around 1% is small compared to the usual measurement precision. 

While we are at this, I'd like to add also similar entries for important greenhouse or related gases like SF6, H2: mole_fraction_of_sulfur_hexafluoride_in_dry_air
mole_fraction_of_hydrogen_in_dry_air

Please note that for all these measurements we relate to a globally agreed scale that is maintained at the global Central Calibration Laboratory linked to the WMO GAW programme. If we would add this information also to the standard names we come to a problem of the CF concept in that it serializes many dimensions into single terms, which can lead to an explosion of terms. And then I did not mention yet the measurement of isotopic composition or ratios like O2/N2 (all relative to agreed standards). But I guess I should raise a different issue for that.

**Comment by claudiodonofrio** [comment]
@atverm. thanks for the clarification (sorry for the mix up of N2O and NO2..my bad). To be consistent with ICOS (where we explicitly state dry, https://meta.icos-cp.eu/resources/cpmeta/n2oMixingRatioPpb ) I assembled  the following entry (which is closely related to http://vocab.nerc.ac.uk/collection/P07/current/CFV8N44/ ). In regards to your proposals for SF6 and H2, I will open a new issue. 

- Term: **mole_fraction_of_nitrous_oxide_in_dry_air**
Unit: 1
Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y.  The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapour is excluded. The chemical formula for nitrous oxide is N2O.

**Comment by RobertPincus** [comment]
Standard names for concentrations that explicitly specified dry air would be very welcome in the radiative transfer community.

**Comment by japamment** [comment]
Hi @claudiodonofrio, many apologies that this ticket seems to have been agreed over two years ago(!) but the names haven't been added to the standard name table. I will rectify this in time for the next update, planned for late January 2024.

With the correction to the 4th proposal, I think we are agreed on:
Term: **mole_fraction_of_carbon_dioxide_in_dry_air**
Unit: 1
Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapor is excluded. The chemical formula for carbon dioxide is CO2.

Term: **mole_fraction_of_carbon_monoxide_in_dry_air**
Unit: 1
Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapor is excluded. The chemical formula of carbon monoxide is CO.

Term: **mole_fraction_of_methane_in_dry_air**
Unit: 1
Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapor is excluded. The chemical formula for methane is CH4. Methane is a member of the group of hydrocarbons known as alkanes. There are standard names for the alkane group as well as for some of the individual species.

Term: **mole_fraction_of_nitrous_oxide_in_dry_air**
Unit: 1
Description: "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "in_dry_air" means that the quantity is calculated as the number of particles of X divided by the number of dry air particles, i.e. the effect of water vapour is excluded. The chemical formula for nitrous oxide is N2O.

Unless there are any further comments on this issue within 7 days, these names will be accepted for publication in the standard name table.

Best wishes,
Alison

**Comment by efisher008** [comment]
Hello @claudiodonofrio and @japamment,

Just a note to say I have marked these names as accepted and Alison and I will work on getting these into the next update to the CF standard names table this month. Thanks again for the proposal!

Best regards,
Ellie

**Comment by efisher008** [comment]
This issue has been closed as the above names were published in version 84 of the standard names table (visible [here](https://cfconventions.org/Data/cf-standard-names/84/build/cf-standard-name-table.html)).
