### ISSUE TITLE
Default branch names?

### ISSUE THREAD

**Issue by erget** [cf-convention/discuss#125]
Dear community,

Language is changing, as it is wont to do, and in recent years several major software initiatives have pivoted in order to match the evolution of our society's values. One such area is the default branch name in git, which historically has been "master". The Software Freedom Conservancy released [a statement](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) last year detailing why they are encouraging projects to shift from "master" to "main" and lay out some good reasons for it; [GitHub has gone the same direction](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/), as have several other git hosters.

I think that this is progress, while realising that updating such names involves a bit of technical work on the part of the repository maintainers, as well as updates to remote references for everybody who's cloned a repository. There is no danger of data loss in doing so, however, so I think that a migration from "master" to "main" is very low-risk.

How is this seen in the wider community? Is it worthwhile to switch the default branch names in the CF repositories to "main"? If there is support for this I would be happy to participate in its implementation in a way that doesn't pull the rug out from people's feet.

Regards,
Daniel

**Comment by MathewBiddle** [comment]
👍

**Comment by davidhassell** [comment]
Hi @erget, I think that this is indeed worthwhile. Should we go ahead, thanks for offering to help facilitate it.
David

**Comment by sethmcg** [comment]
My organization has made this change, and I think it's a good idea.

**Comment by erget** [comment]
Done! PRs have been updated, but your local environment will not have been. I also wouldn't be particularly surprised if some of our automations broke although I had a look and it all looks safe to me.

You should also see an info badge when you reload the page telling you that the default branch has been renamed and giving some guidance on updating your local environment to match the one on the server. Copy-paste the commands and you'll be good to go.

Thanks all for participating in this thread and happy New Year!
