### ISSUE TITLE
Broken URL on Standard Name Table page

### ISSUE THREAD

**Issue by squaregoldfish** [cf-convention/discuss#126]
On the page: http://cfconventions.org/Data/cf-standard-names/78/build/cf-standard-name-table.html

In the "A note about units" section there is the sentence "For the full range of supported units, refer to the Udunits documentation." The linked page give a 404 error.

**Comment by japamment** [comment]
Hi @squaregoldfish

Thank you for reporting this. I have updated the links to Udunits from [http://cfconventions.org/Data/cf-standard-names/78/build/cf-standard-name-table.html](http://cfconventions.org/Data/cf-standard-names/78/build/cf-standard-name-table.html) and [http://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html](http://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html).

Best wishes
Alison
