### ISSUE TITLE
 Standard names: particle number size distribution terms

### ISSUE THREAD

**Issue by markusfiebig** [cf-convention/discuss#127]
**Proposer's name** Markus Fiebig
**Date** 2021-09-22

* **Term:** number_size_distribution_of_aerosol_particles_in_air
**Unit:** m-3
**Description:** The aerosol particle number size distribution is the number concentration of aerosol particles as a function of particle diameter. A coordinate variable with the standard name of electrical_mobility_particle_diameter, aerodynamic_particle_diameter, or optical_particle_diameter should be specified to indicate that the property applies at specific particle sizes selected by the indicated method. To specify the relative humidity at which the particle sizes were selected, provide a scalar coordinate variable with the standard name of relative_humidity_for_aerosol_particle_size_selection.

* **Term:** number_size_distribution_of_aerosol_particles_at_stp_in_air
**Unit:** m-3
**Description:** The aerosol particle number size distribution is the number concentration of aerosol particles as a function of particle diameter. A coordinate variable with the standard name of electrical_mobility_particle_diameter, aerodynamic_particle_diameter, or optical_particle_diameter should be specified to indicate that the property applies at specific particle sizes selected by the indicated method. To specify the relative humidity at which the particle sizes were selected, provide a scalar coordinate variable with the standard name of relative_humidity_for_aerosol_particle_size_selection. "log10_X" means common logarithm (i.e. base 10) of X. "stp" means standard temperature (0 degC) and pressure (101325 Pa).

* **Term:** log10_size_interval_based_number_size_distribution_of_aerosol_particles_in_air
**Unit:** m-3
**Description:** The aerosol particle number size distribution is the number concentration of aerosol particles, normalised to the decadal logarithmic size interval the concentration applies to, as a function of particle diameter. A coordinate variable with the standard name of electrical_mobility_particle_diameter, aerodynamic_particle_diameter, or optical_particle_diameter should be specified to indicate that the property applies at specific particle sizes selected by the indicated method. To specify the relative humidity at which the particle sizes were selected, provide a scalar coordinate variable with the standard name of relative_humidity_for_aerosol_particle_size_selection. "log10_X" means common logarithm (i.e. base 10) of X.

* **Term:** log10_size_interval_based_number_size_distribution_of_aerosol_particles_at_stp_in_air
**Unit:** m-3
**Description:** The aerosol particle number size distribution is the number concentration of aerosol particles, normalised to the decadal logarithmic size interval the concentration applies to, as a function of particle diameter. A coordinate variable with the standard name of electrical_mobility_particle_diameter, aerodynamic_particle_diameter, or optical_particle_diameter should be specified to indicate that the property applies at specific particle sizes selected by the indicated method. To specify the relative humidity at which the particle sizes were selected, provide a scalar coordinate variable with the standard name of relative_humidity_for_aerosol_particle_size_selection. "log10_X" means common logarithm (i.e. base 10) of X. "stp" means standard temperature (0 degC) and pressure (101325 Pa).

* **Term:** number_size_distribution_of_cloud_condensation_nuclei_in_air
**Unit:** m-3
**Description:** The cloud condensation nuclei number size distribution is the number concentration of aerosol particles as a function of particle diameter, where the particle acts as condensation nucleus for liquid-phase clouds. A coordinate variable with the standard name of relative_humidity should be specified to indicate that the property refers to a specific supersaturation with respect to liquid water. A coordinate variable with the standard name of electrical_mobility_particle_diameter should be specified to indicate that the property applies at specific mobility particle sizes. To specify the relative humidity at which the particle sizes were selected, provide a scalar coordinate variable with the standard name of relative_humidity_for_aerosol_particle_size_selection. The ability of a particle to act as a condensation nucleus is determined by its size, chemical composition, and morphology.

* **Term:** number_size_distribution_of_cloud_condensation_nuclei_at_stp_in_air
**Unit:** m-3
**Description:** The cloud condensation nuclei number size distribution is the number concentration of aerosol particles as a function of particle diameter, where the particle acts as condensation nucleus for liquid-phase clouds. A coordinate variable with the standard name of relative_humidity should be specified to indicate that the property refers to a specific supersaturation with respect to liquid water. A coordinate variable with the standard name of electrical_mobility_particle_diameter should be specified to indicate that the property applies at specific mobility particle sizes. To specify the relative humidity at which the particle sizes were selected, provide a scalar coordinate variable with the standard name of relative_humidity_for_aerosol_particle_size_selection. The ability of a particle to act as a condensation nucleus is determined by its size, chemical composition, and morphology. "stp" means standard temperature (0 degC) and pressure (101325 Pa).

* **Term:** log10_size_interval_based_number_size_distribution_of_cloud_condensation_nuclei_in_air
**Unit:** m-3
**Description:** The cloud condensation nuclei number size distribution is the number concentration of aerosol particles, normalised to the decadal logarithmic size interval the concentration applies to, as a function of particle diameter, where the particle acts as condensation nucleus for liquid-phase clouds. A coordinate variable with the standard name of relative_humidity should be specified to indicate that the property refers to a specific supersaturation with respect to liquid water. A coordinate variable with the standard name of electrical_mobility_particle_diameter should be specified to indicate that the property applies at specific mobility particle sizes. To specify the relative humidity at which the particle sizes were selected, provide a scalar coordinate variable with the standard name of relative_humidity_for_aerosol_particle_size_selection. The ability of a particle to act as a condensation nucleus is determined by its size, chemical composition, and morphology. "log10_X" means common logarithm (i.e. base 10) of X.

**Comment by markusfiebig** [comment]
Since there aren't any comments, could these names be accepted?

**Comment by feggleton** [comment]
Thanks for your proposals. These have been added to the cfeditor (https://cfeditor.ceda.ac.uk/proposals/1). My only question would be (whilst thinking on the topic of stp) is, do we need both versions of the term or is there a way to have the term without referring to stp and reference this someone else in the metadata? If not, these seem fine to me.

**Comment by markusfiebig** [comment]
Hi Francesca,

I copy my response from task [#129](https://github.com/cf-convention/discuss/issues/129#issuecomment-1104885587)

> I think we should add these terms as new ones. The new ones are definitely not aliases to the existing version with the STP statement. These versions should exist in parallel and serve different use cases. Once Allison progresses to atomising these terms according to I-ADOPT, the more specific versions will be connected to the less specific ones with skos:broader relations.

Regards,
Markus

**Comment by feggleton** [comment]
Thanks for confirming. So if there are no further comments on these terms in the next 7 days then they can be accepted.

**Comment by feggleton** [comment]
Thanks these can now be accepted @japamment

**Comment by japamment** [comment]
Closing this issue as these names were published in V81 of the standard name table.
