### ISSUE TITLE
 Standard names: particle number concentration terms

### ISSUE THREAD

**Issue by markusfiebig** [cf-convention/discuss#129]
**Proposer's name:** Markus Fiebig
**Date:** 2021-09-22

* **Term:** number_concentration_of_aerosol_particles_in_air
**Unit:** m-3
**Description:** "Number concentration" means the number of particles or other specified objects per unit volume. "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself.

* **Term:** number_concentration_of_cloud_condensation_nuclei_in_air
**Unit:** m-3
**Description:** The cloud condensation nuclei number concentration is the total number of aerosol particles per unit volume independent of and integrated over particle size that act as condensation nuclei for liquid-phase clouds. A coordinate variable with the standard name of relative_humidity should be specified to indicate that the property refers to a specific supersaturation with respect to liquid water. The ability of a particle to act as a condensation nucleus is determined by its size, chemical composition, and morphology.

**Comment by feggleton** [comment]
We have these terms which are similar, would this cover what you are looking for:

[number_concentration_of_aerosol_particles_at_stp_in_air]
"Number concentration" means the number of particles or other specified objects per unit volume. "Aerosol" means the system of suspended liquid or solid particles in air (except cloud droplets) and their carrier gas, the air itself. "stp" means standard temperature (0 degC) and pressure (101325 Pa). The surface called "surface" means the lower boundary of the atmosphere.

[number_concentration_of_cloud_condensation_nuclei_at_stp_in_air]
The cloud condensation nuclei number concentration is the total number of aerosol particles per unit volume independent of and integrated over particle size that act as condensation nuclei for liquid-phase clouds. A coordinate variable with the standard name of relative_humidity should be specified to indicate that the property refers to a specific supersaturation with respect to liquid water. The ability of a particle to act as a condensation nucleus is determined by its size, chemical composition, and morphology. "stp" means standard temperature (0 degC) and pressure (101325 Pa).

they are just at a standard temperature and pressure..

**Comment by markusfiebig** [comment]
Hi @feggleton ,

the intention behind proposing these terms is precisely to have a version without the STP specification. I proposed the version that includes STP a couple of years ago myself. However, it turns out that being a little less specific can be an advantage for certain use cases, which is the reason for now proposing the version without specifying the temperature and pressure conditions. This goes i bit into the direction of atomizing the CF terms (see [I-ADOPT](https://github.com/i-adopt/supplementary/tree/master/step-by-step) which are very descriptive, but too long for certain uses.

All the best,
Markus

**Comment by feggleton** [comment]
Hi @markusfiebig, ah I see, that makes sense then. Do we still want to propose new terms here then or change the existing terms and create an alias.

I'm happy with these terms being added as new and just dropping the stp phrase. These terms are in the cfeditor (http://cfeditor.ceda.ac.uk/proposals/1) so we can look to get these accepted shortly.

**Comment by markusfiebig** [comment]
Hi Francesca,

I think we should add these terms as new ones. The new ones are definitely not aliases to the existing version with the STP statement. These versions should exist in parallel and serve different use cases. Once Allison progresses to atomising  these terms according to I-ADOPT, the more specific versions will be connected to the less specific ones with skos:broader relations.

Regards,
Markus

**Comment by feggleton** [comment]
That makes sense, thanks for confirming. So if there are no further comments on these terms in the next 7 days then they can be accepted.

**Comment by feggleton** [comment]
Thanks these can now be accepted @japamment

**Comment by feggleton** [comment]
These terms were added to the Standard Name Table Version 80 on the 7th of Feb 2023.
