### ISSUE TITLE
 Standard names: stagnation_temperature_in_air

### ISSUE THREAD

**Issue by damienboulanger** [cf-convention/discuss#132]
Proposer's name: Damien Boulanger
Date: 2021-10-01

Term: stagnation_temperature_in_air
Unit: K
Description: In thermodynamics and fluid mechanics, stagnation temperature is the temperature at a stagnation point in a fluid flow. At a stagnation point the speed of the fluid is zero and all of the kinetic energy has been converted to internal energy and is added to the local static enthalpy. In both compressible and incompressible fluid flow, the stagnation temperature is equal to the total temperature at all points on the streamline leading to the stagnation point.
In aviation, stagnation temperature in air is known as total air temperature and is measured by a temperature probe mounted on the surface of the aircraft. The probe is designed to bring the air to rest relative to the aircraft. As the air is brought to rest, kinetic energy is converted to internal energy. The air is compressed and experiences an adiabatic increase in temperature. Therefore, total air temperature is higher than the static (or ambient) air temperature.
Total air temperature is an essential input to an air data computer in order to enable computation of static air temperature and hence true airspeed.

**Comment by JonathanGregory** [comment]
Dear @damienboulanger 

Thanks for the proposal. It makes sense to me (not being an expert)! I think the standard name should have `_in_air` appended to it.

Best wishes

Jonathan

**Comment by feggleton** [comment]
Hi @damienboulanger, apologies for the delay in getting back to you. I think this term and definition is probably fine. I don't think there are any regularly used phrases which should be used here. I will allow @japamment to comment. If no further comment then these can be accepted in the next 7 days.

**Comment by feggleton** [comment]
These terms were added to the Standard Name Table Version 80 on the 7th of Feb 2023.
