### ISSUE TITLE
New role

### ISSUE THREAD

**Issue by feggleton** [cf-convention/discuss#138]
Hi all,

Just to let you know I have recently moved into a new role at the Met Office. This means I will no longer be helping to manage the Standard Name table in the capacity I have done previously. My new role is within a new data management team at the Met Office and therefore I will still be very involved in metadata standards, NetCDF etc so I would like to stay as involved as possible with the CF community. 

Thanks,

Fran

**Comment by JonathanGregory** [comment]
Dear Fran

Thanks for letting us know, and many thanks for your hard and useful work on the standard name table.

Best wishes

Jonathan
