### ISSUE TITLE
 Standard names: current velocity towards direction other than E or N

### ISSUE THREAD

**Issue by matthiaslankhorst** [cf-convention/discuss#141]
Hi,
I am looking to express ocean current velocity towards a specific direction, which is not East or North, in a CF-compliant file. Is there a standard_name for this? I know that there are names for eastward and northward components, and that there are speed/direction ones as well. Neither quite captures my situation - I only know the velocity component in that one direction, and there may be an (unknown, non-zero) component perpendicular to this, which imho prohibits use of speed/direction. The situation is similar to the existing standard_name "ocean_volume_transport_across_line", except I have individual point data of velocity in units of m/s.
Thanks for any leads, Matthias

**Comment by JonathanGregory** [comment]
Dear Matthias

There are also names `sea_water_x_velocity` and `sea_water_y_velocity` for components relative to the horizontal grid, but that's not what you want either, I think.  I can't think of an existing standard name for this purpose. Do you mean something like `direction_of_sea_water_velocity_component` and `component_of_sea_water_velocity_in_direction`?

Cheers

Jonathan

**Comment by taylor13** [comment]
Alternatively, for the second name you might consider ``vector_component_of_sea_water_velocity`` (or with ``horizontal`` as a prefix of the same).  

Also, if the direction is the same everywhere, I guess ``direction_of_sea_water_velocity_component`` would be a scalar coordinate.

I'm curious, what kind of instrument measures a single component of the velocity (when the other component is non-zero)?  
thanks,
Karl

**Comment by matthiaslankhorst** [comment]
Thanks Karl & Jonathan, all of your suggestions would work for me.

The data I am supposed to represent are from an EOF analysis of multiple moorings, where only the currents along a channel are reported. Data points are along a section across the channel, and the velocities are perpendicular to said section, i.e. along the channel. The EOF analysis does not report the across-channel component. Unlike the underlying observations, this data product is on a neat, regular grid.

The raw data (which are reported elsewhere) contain U and V, and are reported as such with the existing standard_name options. I.e. my problem refers to the derived, neatly gridded, data product.

**Comment by feggleton** [comment]
@matthiaslankhorst Hopefully you've found the appropriate existing names for your work, I can't see a request in here so I will close. Please reopen if I am mistaken.
