### ISSUE TITLE
The 2022 CF meeting - save the date

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#143]
Dear CF community,

We are pleased to announce the dates and locations for this year's CF meeting:

----

### Dates:  **Tuesday-Thursday 13-15 September 2022**

----

### Locations: **Santander, Spain** and **online**

----

The meeting is being planned as a hybrid event for in-person attendees in Spain, and also making it as easy as possible for those who cannot travel to Spain to attend and interact virtually.

If an in-person event turns out to not be possible due to COVID, then we will fall back to the same wholly virtual format of the previous two years' meetings, on the same dates.

#### Training

This year's meeting will feature a CF training session. This wholly online session will be run twice at different times during the week before the main meeting, so as to be convenient to a wider range of time zones. Further details on this to follow in due course ...

#### Get involved

Finally, if you would like to get involved by joining the meeting organising committee, you would be most welcome!

All the best,
The current organising committee:

Aleksandar Jelenak
Alison Pamment
Antonio Cofiño
Charlie Zender
Daniel Lee
David Hassell
Ethan Davis
Fernando Carvalho Pacheco
Guilherme Castelao
Kevin O'Brien

**Comment by squaregoldfish** [comment]
In case anyone else is watching this issue for updated information, check #165

**Comment by davidhassell** [comment]
A call for talks at the 2022 meeting has been announced at #167.
