### ISSUE TITLE
Take Conformance repo offline?

### ISSUE THREAD

**Issue by erget** [cf-convention/discuss#15]
Dear CF enthusiasts,

I hope you've all had a good holiday season thus far. As you may have noticed there's been discussion over the last month over importing the conformance document into the main CF Conventions repository](see cf-convention/cf-conventions#221). This has now been done, and the history of the Conformance document has been imported as well.

In order to avoid confusion in the future I've added a note to users in the old Conformance repository's README that they should go to the Conventions repository to submit changes. However I think that we should think about taking the old repository offline, as that would help prevent confusion in the future. 

The impact of archiving a repository is that it's still visible, but it becomes read-only so that no new issues or changes can be committed to it. 

Who's got an opinion on this?

Best regards,
Daniel

**Comment by dblodgett-usgs** [comment]
I support archiving with clear direction to the new home.

**Comment by davidhassell** [comment]
Archiving to read-only looks like a good option to me, too.

**Comment by erget** [comment]
Seems very uncontroversial and a bit of time has passed since this was brought up. Who has privileges to archive the repo? @davidhassell ?

**Comment by davidhassell** [comment]
@erget - I probably do have the right permissions! perhaps you could send me instructions (offline, if required) on what to do? Many thanks.

**Comment by DocOtak** [comment]
@davidhassell I think it's this https://help.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories

**Comment by dblodgett-usgs** [comment]
https://github.com/cf-convention/Conformance has been archived.
