### ISSUE TITLE
 Standard names: Nansen Legacy Project 01

### ISSUE THREAD

**Issue by lhmarsden** [cf-convention/discuss#150]
Before submitting an issue be sure you have read and understood the rules for vocabulary changes: http://cfconventions.org/standard_name_rules.html

Please note that it is fine to group together a number of proposals in a single GitHub issue (i.e. it is not necessary to open a separate issue for each vocabulary term). Change proposals should include the following information as applicable.

**Proposer's name** This information will be used to add entries to the vocabulary editor: http://cfeditor.ceda.ac.uk/proposals/1. If you prefer not to add your name, your github id will be used instead.
**Date** Also used in the vocabulary editor.
For each term please try to give the following:
**- Term** Proposed term to appear in the vocabulary
**- Description** A brief description to explain the meaning of the term
**- Units** (If applicable).

--------------------------

I have read and understood the above.

I work as a data manager on a large multidisciplinary marine research research project, the Nansen Legacy project (https://arvenetternansen.com/). We investigate the role that climate change is having on the Northern Barents Sea, one of the fastest warmest regions on the planet.

We investigate wide range of parameters. I have asked researchers in the project to look through the existing CF standard names and see if any additions are required for their work. Collectively, we would like to propose the CF standard names linked below:
https://docs.google.com/spreadsheets/d/13GTGCkXjFcFYBe_jhqkKJfIT1Ja95cAd/edit?usp=sharing&ouid=109954185656296467293&rtpof=true&sd=true

The email address of the researcher who proposed each term is included, but please include me in any communication too (lukem@unis.no).

I have gone through and checked each list. I have removed terms that I believe are already covered by the existing standard names, and made some changes to the wording to be more infitting with the general style used for existing standard names.

Please let me know if you require any further information or clarifications. It is likely that I will propose more on behalf of the project at a later date, so please let me know if the way I am doing this is okay for you.

Thanks for the important work that you do!

Kind regards,

Luke

**Comment by roy-lowry** [comment]
Dear Luke,

I appreciate that you have a long list of parameters, but could you please include the text in GitHub rather than an external document. I found the way HOTS presented their requests such as #135 made the review process manageable. It would also be helpful if you could check the pending Standard Names in the editor https://cfeditor.ceda.ac.uk/proposals/1?status=active&namefilter=&proposerfilter=&descfilter=&filter+and+display=filter to make sure that none of the names in your list are currently under discussion. 

I have eyeballed your spreadsheet and most look straightforward. One thing I noticed is that you have used the spelling 'sulphur' but this should be 'sulfur' for CF.

Cheers, Roy.

**Comment by lhmarsden** [comment]
**Proposer's names:** 
- Luke Marsden (lukem@unis.no)
- Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
- Gunnar Bratbak (Gunnar.Bratbak@uib.no)
- Katrine Husum (Katrine.husum@npolar.no)
- Ilker Fer (ilker.fer@uib.no)

**Reviewer's and contributor's names:**
- Luke Marsden (lukem@unis.no)
- Øystein Godøy (o.godoy@met.no)

**Date: 2022-04-04**

**Notes:** I work as a data manager on a large multidisciplinary marine research research project, the Nansen Legacy project (https://arvenetternansen.com/). We investigate the role that climate change is having on the Northern Barents Sea, one of the fastest warmest regions on the planet.

We investigate wide range of parameters. I have asked researchers in the project to look through the existing CF standard names and see if any additions are required for their work. Collectively, we would like to propose the CF standard names listed below. I have checked through the existing set of standard names and the currently proposed listed, and, to the best of my knowledge, there are no conflicts.

### Proposed names

**(1)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_phosphorus_in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(2)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_calcium_in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(3)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_iron_in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(4)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_magnesium_in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(5)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_sodium_in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(6)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_potassium_in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(7)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_zinc_in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(8)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_sulfur_in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(9)**
**Term:** `mole_concentration_of_particulate_matter_expressed_as_manganese _in_sea_water`
**Proposed by:** Tatiana Margo Tsagaraki (tatiana.tsagaraki@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called"molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.
**Unit:** [mol m-3]

**(10)**
**Term:** `mole_concentration_of_prokaryotes expressed_as_carbon_in_sea_water`
**Proposed by:** Gunnar Bratbak (Gunnar.Bratbak@uib.no)
**Description:** Mole concentration means number of moles per unit volume, also called "molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. "Prokaryotes” are all Bacteria and Archaea excluding photosynthetic cyanobacteria such as Synechococcus and Prochlorococcus or other separately named components of the procaryotic population.
**Unit:** [mol m-3]

**(11)**
**Term:** `mole_productivity_of_biomass_expressed_as_carbon_by_prokaryotes`
**Proposed by:** Gunnar Bratbak (Gunnar.Bratbak@uib.no)
**Description:** "Production of carbon" means the production of biomass expressed as the number of mols of carbon which it contains. "Productivity" means production per unit volume. The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. "Prokaryotes” are all Bacteria and Archaea excluding photosynthetic cyanobacteria such as Synechococcus and Prochlorococcus or other separately named components of the procaryotic population.
**Unit:** [mol m-3 s-1]

**(12)**
**Term:** `mass_productivity_of_biomass_expressed_as_carbon_by_prokaryotes`
**Proposed by:** Gunnar Bratbak (Gunnar.Bratbak@uib.no)
**Description:** "Production of carbon" means the production of biomass expressed as the mass of carbon which it contains. "Productivity" means production per unit volume. The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. "Prokaryotes” are all Bacteria and Archaea excluding photosynthetic cyanobacteria such as Synechococcus and Prochlorococcus or other separately named components of the procaryotic population.
**Unit:** [kg m-3 s-1]

**(13)**
**Term:** `mass_concentration_of_prokaryotes_expressed_as_carbon_in_sea_water`
**Proposed by:** Gunnar Bratbak (Gunnar.Bratbak@uib.no)
**Description:** "Mass concentration" means mass per unit volume and is used in the construction "mass_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. "Prokaryotes” are all Bacteria and Archaea excluding photosynthetic cyanobacteria such as Synechococcus and Prochlorococcus or other separately named components of the procaryotic population.
**Unit:** [kg m-3]

**(14)**
**Term:** `age_of_sea_floor_sediment_before_present`
**Proposed by:** Katrine Husum (katrine.husum@npolar.no)
**Description:** "Age of sediment" means the length of time elapsed since the sediment was deposited. "Present" is defined as 1950 AD. Sea floor sediment is sediment deposited at the sea bed. 
**Unit:** [year]

**(15)**
**Term:** `sea_water_speed_shear`
**Proposed by:** Ilker Fer (ilker.fer@uib.no)
**Description:** Speed is the magnitude of velocity. Sea water speed shear is the derivative of sea water speed with respect to depth.
**Unit:** [s-1]

**(16)**
**Term:** `mass_concentration_of_chlorophyll_a_in_sea_ice`
**Proposed by:** Luke Marsden (lukem@unis.no)
**Description:** 'Mass concentration' means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. Chlorophylls are the green pigments found in most plants, algae and cyanobacteria; their presence is essential for photosynthesis to take place. There are several different forms of chlorophyll that occur naturally. All contain a chlorin ring (chemical formula C20H16N4) which gives the green pigment and a side chain whose structure varies. The naturally occurring forms of chlorophyll contain between 35 and 55 carbon atoms. Chlorophyll-a is the most commonly occurring form of natural chlorophyll. The chemical formula of chlorophyll-a is C55H72O5N4Mg. "Sea ice" means all ice floating in the sea which has formed from freezing sea water, rather than by other processes such as calving of land ice to form icebergs.
**Unit:** [kg m-3]

**(17)**
**Term:** `mass_concentration_of_phaeopigments_in_sea_water`
**Proposed by:** Luke Marsden (lukem@unis.no)
**Description:** Mass concentration' means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. Phaeopigments are non-photosynthetic pigments that are the degradation product of algal chlorophyll pigments. It is commonly formed during and after marine phytoplankton blooms. 
**Unit:** [kg m-3]

**(18)**
**Term:** mass_concentration_of_phaeopigments_in_sea_ice
**Proposed by:** Luke Marsden (lukem@unis.no)
**Description:** 'Mass concentration' means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'. Phaeopigments are non-photosynthetic pigments that are the degradation product of algal chlorophyll pigments. It is commonly formed during and after marine phytoplankton blooms. "Sea ice" means all ice floating in the sea which has formed from freezing sea water, rather than by other processes such as calving of land ice to form icebergs.
**Unit:** [kg m-3]

**Comment by roy-lowry** [comment]
Many thanks,
That makes life much easier. I will comment on these over the coming week or so.
Cheers, Roy.

**Comment by roy-lowry** [comment]
Items 10 (mole_concentration_of_prokaryotes expressed_as_carbon_in_sea_water) and 13 (mass_concentration_of_prokaryotes expressed_as_carbon_in_sea_water) are simple modifications of existing standard names for non-taxonomic organism groupings such as mole_concentration_of_mesozooplankton_expressed_as_nitrogen_in_sea_water.
I therefore see no problem with their being accepted.

**Comment by JonathanGregory** [comment]
Dear Luke et al.

These proposed names follow existing patterns and therefore look fine to me, but I am not an expert on this subject.

Thanks

Jonathan

**Comment by roy-lowry** [comment]
Dear Jonathan,

Most do, but a couple require a little more thought. Watch this space.

Cheers, Roy.

**Comment by roy-lowry** [comment]
Item 11 mole_productivity_of_biomass_expressed_as_carbon_by_prokaryotes
Item 12 mass_productivity_of_biomass_expressed_as_carbon_by_prokaryotes


Convention in existing Standard Names is 'production' for biomass created per unit per unit volume
 and 'productivity' for biomass created per unit area. It has been assumed that production/productivity is a mass unless quantity of matter is explicitly stated. Production/productivity have been qualified as 'gross' or 'net' to indicate whether or not data have been corrected for carbon loss through respiration. 

Production/productivity have been qualified as 'primary' to indicate biomass creation from inorganic precursors. Could you confirm that these Standard Names are for total production and not the more usual primary production?  Once this is answered I will propose alternative terms and definitions for these items.

**Comment by roy-lowry** [comment]
I have something in my memory about a previous discussion concerning sediment age before present, but can't remember if it was in the domain of CF or NVS. I've tried to find reference to it in the CF GitHub repository but without success. Does anybody else remember it or have better GitHub searching skills than me? If so, please give me a heads up.

**Comment by lhmarsden** [comment]
> Item 11 mole_productivity_of_biomass_expressed_as_carbon_by_prokaryotes Item 12 mass_productivity_of_biomass_expressed_as_carbon_by_prokaryotes
> 
> Convention in existing Standard Names is 'production' for biomass created per unit per unit volume and 'productivity' for biomass created per unit area. It has been assumed that production/productivity is a mass unless quantity of matter is explicitly stated. Production/productivity have been qualified as 'gross' or 'net' to indicate whether or not data have been corrected for carbon loss through respiration.
> 
> Production/productivity have been qualified as 'primary' to indicate biomass creation from inorganic precursors. Could you confirm that these Standard Names are for total production and not the more usual primary production? Once this is answered I will propose alternative terms and definitions for these items.

I will contact Gunnar about these terms.

**Comment by bratbak** [comment]
Yes I confirm that these Standard Names are for total production and not primary production as the biomass creation is based on (dissolved) organic material and not inorganic precursors.

**Comment by roy-lowry** [comment]
Here is my modified version of items 11 and 12:

Term: gross_mole_production_of_biomass_expressed_as_carbon_by_prokaryotes_in_sea_water

Description: "gross_mole_production" means the rate of creation of biomass per unit volume with no correction for respiration loss in terms of quantity of matter (moles). The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A, in this case carbon. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. "Prokaryotes” are all Bacteria and Archaea excluding photosynthetic cyanobacteria such as Synechococcus and Prochlorococcus or other separately named components of the procaryotic population.

Unit: [mol m-3 s-1]

Term: gross_production_of_biomass_expressed_as_carbon_by_prokaryotes_in_sea_water

Description: "gross_production" means the rate of creation of biomass per unit volume with no correction for respiration. The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A, in this case carbon. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. "Prokaryotes” are all Bacteria and Archaea excluding photosynthetic cyanobacteria such as Synechococcus and Prochlorococcus or other separately named components of the procaryotic population.

Unit: [kg m-3 s-1]

@bratbak and @lhmarsden Do you have any issues with these? Anybody else have ant comments?

**Comment by bratbak** [comment]
I am fine with these
Best
gunnar

**Comment by lhmarsden** [comment]
If they're fine with Gunnar they're fine with me.

**Comment by roy-lowry** [comment]
Item 17 (mass_concentration_of_phaeopigments_in_sea_water) now exists. Created on 18th March 2022.

Items 16 and 18:
mass_concentration_of_phaeopigments_in_sea_ice
mass_concentration_of_chlorophyll_a_in_sea_ice
 
These look fine to me. Although there is a precedent of sea_ice_mass_content_of_salt I think the parallel with names like mass_concentration_of_phaeopigments_in_sea_water is a much stronger phraseology precedent.

**Comment by ngalbraith** [comment]
> I have something in my memory about a previous discussion concerning sediment age before present, but can't remember if it was in the domain of CF or NVS. I've tried to find reference to it in the CF GitHub repository but without success. Does anybody else remember it or have better GitHub searching skills than me? If so, please give me a heads up.

I don't think my GitHub search skills are much good, but the term  'age before present' doesn't appear in any existing CF term, as far as I can see. Can this be rephrased somehow? Is it especially common to define 'Present' as 1950 AD ? Shouldn't that be done with a reference date instead, and maybe use time as a coordinate (or independent) variable?

**Comment by roy-lowry** [comment]
Hi Nan,

'before present'  (BP) referencing 1950 AD may be new to CF, but it is a well-known gold standard convention in geochronology and archaeology. It has its origins in radiocarbon dating but has been adopted for all dating techniques. I feel this is a case where CF has to respect domain conventions.

**Comment by roy-lowry** [comment]
Item 15 (sea_water_speed_shear) follows the same phraseology structure as many precedents, such as sea_water_x_velocity and so looks a valid Standard Name. The only caveat is that speed shear, defined as the derivative of fluid speed with respect to depth is  a new concept to me. My maths isn't even up to confirming that the canonical unit for the derivative of m s-1 with respect to m is s-1. @JonathanGregory could you let me know if you are happy with this term?

**Comment by lhmarsden** [comment]
> Item 15 (sea_water_speed_shear) follows the same phraseology structure as many precedents, such as sea_water_x_velocity and so looks a valid Standard Name. The only caveat is that speed shear, defined as the derivative of fluid speed with respect to depth is a new concept to me. My maths isn't even up to confirming that the canonical unit for the derivative of m s-1 with respect to m is s-1. Googling 'speed shear' leads to sites on the competitive removal of fleeces from sheep or 'shear velocity', which I think is different and so couldn't help me. @JonathanGregory could you let me know if you are happy with this term?

This proposed standard name is very similar to the existing standard name, wind_speed_shear, and has been worded similarly.

**Comment by roy-lowry** [comment]
Many thanks Luke. I had missed that perfectly analogous precedent. So I am now perfectly happy with the proposal for sea_water_speed_shear.

**Comment by lhmarsden** [comment]
It looks like we have discussed all 18 now. Do you need anything more from me? Perhaps for 14?

**Comment by roy-lowry** [comment]
Item 14 age_of_sea_floor_sediment_before_present. I would suggest changing the phrasing to sea_floor_sediment_age_before_present to follow the precedent sea_floor_sediment_grain_size. 

Note that the canonical units should be seconds, not years. The canonical units describe the dimension of the measurement, in this case time. The scaled units - in this case years - go into the parameter attribute in the data file.

**Comment by JonathanGregory** [comment]
I agree with @roy-lowry that "before present" is standard terminology which means "before 1950", and it would be OK to use it in the standard name since it's explained in the definition. Still, following Nan @ngalbraith's comment, since this is a standard name and not everyone is aware of this term, would it be better instead to have `_before_1950` in the standard name, and explain in the definition that "before 1950" is what people mean by "before present"?

I agree that the wind speed shear term is OK.

**Comment by roy-lowry** [comment]
During the geological phase of my career 'before present' was a part of my everyday language. However, I understand the desire to make Standard Names understandable across as many domains as possible. Consequently, I would - a little reluctantly - accept something like:
sea_floor_sediment_age_before_1950
"sediment_age" means the length of time elapsed since the sediment was deposited. "before_1950" is a transparent representation of the phrase "before_present" used in the geological and archaeological domains to refer to time elapsed between an event and 1950 AD. "sea_floor_sediment" is sediment deposited at the sea bed.

@lhmarsden What do you and your colleagues think?

**Comment by lhmarsden** [comment]
As an ex-geoscientist myself, I share your reluctance, @roy-lowry, but also understand. I am happy with your suggestion. I guess someone searching for which standard name to use would search by 'sediment age' rather than 'before present' or 'before 1950' anyway...

**Comment by roy-lowry** [comment]
Thanks Luke. Some vocabulary search engines also scan the definition/description, which I phrased with being a search target in mind.

**Comment by ngalbraith** [comment]
I'm very happy with @roy-lowry's rephrasing of the descriptions on 11 and 12; I was concerned that the original descriptions included a phrase ("Production of carbon" ) that didn't exist in the proposed standard names  themselves. This all looks much better to me now, thanks.

**Comment by feggleton** [comment]
Some really good discussion has taken place here so would be good to move this forward for agreement. We will need to summarise all the terms reflecting the changes in the discussion and then change that in the cfeditor. @japamment raising so we can both work through this one.

**Comment by bratbak** [comment]
Hi
What is the status of these items?
Do not seem to be included in the CF Standard Name Table (Version 81, 25 April 2023)
Gunnar

**Comment by tts041** [comment]
Hi @feggleton, there is an oversight in the copying of the names, the proposed name reads:
Term: mole_concentration_of_particulate_matter_expressed_as_manganese 
whereas it should be: 
Term: mole_concentration_of_particulate_matter_expressed_as_manganese _in_sea_water (see number 9 above)
Tanya

**Comment by feggleton** [comment]
Great spot @tts041 Thank you for that!

**Comment by japamment** [comment]
Hi @bratbak @lhmarsden @feggleton 

All the names in this issue will be included in V82 of the standard name table, currently in preparation.

Best wishes

Alison

**Comment by japamment** [comment]
I am closing this issue as the names have been published in V82 of the standard name table.
