### ISSUE TITLE
Standard names: Nansen Legacy Project 02

### ISSUE THREAD

**Issue by lhmarsden** [cf-convention/discuss#153]
Proposer's name:

    Heather Anne Cannaby (heather.anne.cannaby@hi.no)

Reviewer's and contributor's name:

    Luke Marsden (lukem@unis.no)

Date: 2022-04-04

Notes: I work as a data manager on a large multidisciplinary marine research research project, the Nansen Legacy project (https://arvenetternansen.com/). We investigate the role that climate change is having on the Northern Barents Sea, one of the fastest warmest regions on the planet.

We investigate a wide range of parameters. I have asked researchers in the project to look through the existing CF standard names and see if any additions are required for their work. Please see below a few suggested by Heather Cannaby.

Proposed names

(1)
Term: acoustic_target_strength
Description: The amount of acoustic energy reflected from a target in the water column in active sonar. “Acoustic target” means the object in the water column that the acoustic signal reflects off, e.g. fish, planktonic scatter or internal waves. Defined as 10 times the logarithm of the reflected intensity at one metre from a target, divided by the incident intensity.
Unit: [dB re 1 m-1]

(2)
Term: volume_back_scattering_strength
Description: Proportional to the biomass density per unit volume as obtained from a biological echosounder.  Defined as the ratio of backscattered intensity per unit volume at 1 m from the volume, to the intensity of the incident wave.  
Unit: [dB re 1 m-1]

**Comment by roy-lowry** [comment]
Hi Luke,

First query

The definitions of both names state that they are ratios, in which case I would expect them to have canonical units of dimensionless like the existing name signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water. 

Do you and Heather agree?

**Comment by roy-lowry** [comment]
Thinking about it a little more. Both these parameters are normalised per unit length which I think would make the canonical units m-1? A little out of my comfort zone here so opinions welcome.

**Comment by ngalbraith** [comment]
I'm also outside my comfort zone with these terms, and wonder if they are so different from terms defined for use with data from ADCPs and other acoustic current meters.  

In the description of volume_back_scattering_strength, the terms 'biomass density' and 'biological echosounder' seem to limit the use of this term more than necessary. A quick google search on 'Acoustic Backscattering Intensity' turns up quite a few items that don't strictly relate to biomass.  If the proposed term is only to be used for biological studies, shouldn't that limitation be part of the standard name itself? 

For both terms, is the 1 meter distance hard-wired, or could this be different for different applications, and therefore be a coordinate variable?

**Comment by roy-lowry** [comment]
Hi Nan,

Totally agree with you. I'm working on a suggested redrafting for both of these terms to propose to Heather and Luke.

Looking at computation formulae I'm pretty sure the per metre is a hard-wired part of the parameter specification. Very similar to the derivation of optical attenuance, which also has units of per metre. 

Cheers, Roy.

**Comment by lhmarsden** [comment]
Hi Roy and Nan,

I will get some feedback from Heather and her colleagues. They will be a more reliable source of information on this than myself.

Cheers

Luke

**Comment by roy-lowry** [comment]
Looking at the second term, I have three comments other than my uncertainty about the units.

1) As Nan said, the first sentence describes one purpose (measuring biomass per unit volume) for which that parameter may be used, rather than specifying what the parameter is.
2) The term/definition don't clarify whether it is sound or light that are being scattered
3) The term/definition don't clarify whether the sound/light are in the water column or the atmosphere

I would there propose an alternative:

acoustic_volume_back_scattering_intensity_in_sea_water

The ratio of the backscattered acoustic energy intensity per unit volume at 1 m from that volume, to the intensity of the incident acoustic energy. It is a processed parameter produced by biological echosounders that is proportional to the biomass density per unit volume, but may also be derived by other acoustic instruments for other purposes.

I'm still researching the difference between the first term and the similar - but I think significantly different - ADCP signal strength standard name.

**Comment by hcannaby** [comment]
Hi All,
To give you a reference point, I have tried to define variable names following the advice in this paper: David N. MacLennan, Paul G. Fernandes, and John Dalen ICES Journal of Marine Science, 59: 365–369. 2002 doi:10.1006/jmsc.2001.1158. A consistent approach to definitions and symbols in fisheries acoustics.  
However, I'm also not an acoustics expert, I'll try to find someone from the acoustics department here at IMR to weigh in.

**Comment by roy-lowry** [comment]
Thanks Hannah,

That paper is extremely useful. First answer it provides concerns the canonical unit - there's a column for dimension on page 367 - which shows that both of the parameters you wish to cover with standard names (TS and Sv) are dimensionless, so the canonical unit should be dimensionless. The entries from the units column are what you should put in the parameter attribute in the data file.

The primary subject of the paper is to create a standard terminology for fisheries acoustics and the fact that it is being referenced 20 years after publication tells me that what it says should be respected. The paper proposes the term 'strength' as the term for log10 of a coefficient (scaled by a factor of 10). Initially, I felt that 'strength' shouldn't be a part of the standard name, but my opinion has changed after looking at the paper. I also note that there is a CF precedent for backscatter rather than back_scatter (histogram_of_backscattering_ratio_in_air_over_height_above_reference_ellipsoid)

So, my proposal of yesterday changes to:

acoustic_volume_backscattering_strength_in_sea_water

Acoustic volume backscattering strength is log10 of the volume backscattering coefficient multiplied by 10. Volume backscattering coefficient is the integral of the backscattering cross-section divided by the volume sampled. Backscattering cross-section is a parameter computed from the intensity of the backscattered sound wave relative to the intensity of the incident sound wave. The parameter is computed to provide a measurement that is proportional to biomass density per unit volume in the field of fisheries acoustics. For further details see MacLennan et. al (2002) doi:10.1006/jmsc.2001.1158.

dimensionless

Am I heading down the right track? If so, I'll have a go at drafting for target strength.

**Comment by JonathanGregory** [comment]
Dear Roy, Hannah and others

Thank you for working on this. I had similar concerns to those expressed about the units and the lack of explanatory words in the first version of the proposed standard names. Roy's proposal is clearer. If there is a standard reference value, this can be stated in the definition too.

Roy is correct that there are two existing names containing `backscattering` and none with `back_scattering`, but I see there are five containing `backwards_scattering`, so perhaps it would be best to use that phrase (and modify the two `backscattering` ones for consistency).

I agree that `acoustic` should be included but I note that, by contrast, the standard names for scattering of (electromagnetic) radiation do not all specify `radiation`, though some of them do. We ought to make these consistent too, perhaps, but that's another issue.

Cheers

Jonathan

**Comment by roy-lowry** [comment]
A quick Google search turns up 'backscatter'  and 'backward scatter' in the context of optics and acoustics. Usage of 'backward scatter' is usually accompanied by 'forward scatter'. 'Back scatter' turned up once, referring to a type of shotgun. I can't find 'backwards scatter'. By far the most common term is 'backscatter'.

I'm guessing 'backwards scatter' was the result of a previous standard name discussion on a proposal for 'backscatter' to broaden understanding. If we're going to standardise my preference would be for 'backscatter', but would be interested in other opinions.

**Comment by JonathanGregory** [comment]
Dear Roy

Thanks. I don't have a preference myself for the choice, except that I think we should adopt one of the phrases which normally occurs in terminology, and that we should be consistent.

Best wishes

Jonathan

**Comment by gavinmacaulay** [comment]
Acoustic volume backscattering strength and target strength apply to underwater acoustics in general - a more inclusive suffix for the proposed names would be `_in_water`, instead of `_in_sea_water`.

The proposed description for `acoustic_volume_backscattering_strength_in_sea_water` probably needs to mention the reference value - something like this:

`Acoustic volume backscattering strength is 10 times the log10 of the ratio of the volume backscattering coefficient to the reference value, 1 m-1.`

Since the MacLennan paper there has been an ISO standard on acoustic terminology (ISO 18405:2017) and I used their way of writing dB definitions in the above suggestion.

**Comment by roy-lowry** [comment]
Thanks to all the excellent reference material provided I now have a much better understanding of underwater acoustics and this standard name proposal.  Here is my suggested redrafting of the first term based on this information.

acoustic_target_strength_in_sea_water

Target strength is 10 times the log10 of the ratio of backscattering cross-section to the reference value, 1 m-1. Backscattering cross-section is a parameter computed from the intensity of the backscattered sound wave relative to the intensity of the incident sound wave. For further details see MacLennan et. al (2002) doi:10.1006/jmsc.2001.1158.

dimensionless

Heather, are you happy with my efforts?

**Comment by gavinmacaulay** [comment]
The definition of acoustic_target_strength_in_sea_water looks good, but the unit for the reference value for target strength should be m2, not m-1.

**Comment by roy-lowry** [comment]
Many thanks. Off to buy new glasses!

**Comment by roy-lowry** [comment]
To clarify that make the redraft:

acoustic_target_strength_in_sea_water

Target strength is 10 times the log10 of the ratio of backscattering cross-section to the reference value, 1 m2. Backscattering cross-section is a parameter computed from the intensity of the backscattered sound wave relative to the intensity of the incident sound wave. For further details see MacLennan et. al (2002) doi:10.1006/jmsc.2001.1158.

dimensionless

acoustic_volume_backscattering_strength_in_sea_water

Acoustic volume backscattering strength is 10 times the log10 of the ratio of the volume backscattering coefficient to the reference value, 1 m-1. Volume backscattering coefficient is the integral of the backscattering cross-section divided by the volume sampled. Backscattering cross-section is a parameter computed from the intensity of the backscattered sound wave relative to the intensity of the incident sound wave. The parameter is computed to provide a measurement that is proportional to biomass density per unit volume in the field of fisheries acoustics. For further details see MacLennan et. al (2002) doi:10.1006/jmsc.2001.1158.

dimensionless

**Comment by hcannaby** [comment]
To me at least, this looks good.  Many thanks Roy, Gavin and all for your help.  
(I've been asked to publish project data in a consistent NetCDF-CF format and it will hopefully now be easier to do this...)

**Comment by gavinmacaulay** [comment]
@hcannaby - I wonder if you have, or will have, the need for storing Sa (area backscattering strength) data also? If so, now might be the time to ask for that:) That would then cover the three main quantities used in fisheries acoustics.

**Comment by hcannaby** [comment]
@gavinmacaulay I don't have plans to publish Sa data myself but I assume with increasing pressure to publish data this will be needed by the community..

**Comment by JonathanGregory** [comment]
Thank you, Roy. They look nice. You have clear insight without new glasses.

**Comment by gavinmacaulay** [comment]
@hcannaby - I then propose an entry for area backscattering strength:

acoustic_area_backscattering_strength_in_sea_water

Acoustic area backscattering strength is 10 times the log10 of the ratio of the area backscattering coefficient to the reference value, 1 (m2 m-2). Area backscattering coefficient is the integral of the volume backscattering coefficient over a defined distance. Volume backscattering coefficient is the linear form of acoustic_volume_backscattering_strength_in_sea_water. For further details see MacLennan et. al (2002) doi:10.1006/jmsc.2001.1158.

dimensionless

**Comment by gavinmacaulay** [comment]
To follow up on a comment by @nilsolav - target strength, volume backscattering strength, and area backscattering strength are all just decibel forms of the corresponding linear parameters and I ask (@roy-lowry?) whether there is any preference/precedence in CF for linear or decibel versions of parameters? 

The decibel versions were originally there just to make the numbers more easily understood by people. Pretty much all processing operations are done on the linear forms and the dynamic range of these parameters is well within the range of a single-precision floating point number.

**Comment by JonathanGregory** [comment]
I agree with this:

> CF has no preference for linear or decibel versions.

I would add that both linear and decibel versions could be included in the standard name table, but they would need different standard names. If that is likely to be a need, or if it could be a source of confusion anyway, maybe the decibel names should start with logarithm_of.

Cheers

Jonathan

**Comment by roy-lowry** [comment]
@JonathanGregory The linear parameters have a different terminology to the decibel names clearly set out in the terminology papers/standards I've been reading for this proposal. Consequently, should additional standard names be required in the future for the linear parameters then there would be no risk of confusion. The inclusion of 'strength' in these standard names is a clear statement that they are coefficient logarithms, with no need for an explicit 'logarithm_of'.

**Comment by JonathanGregory** [comment]
OK, fine. Thanks for clarifying, Roy.

**Comment by gavinmacaulay** [comment]
I suggest then that the dB forms are used and as @roy-lowry indicates, the linear forms can be added later if the community wants/needs them.

**Comment by JonathanGregory** [comment]
As far as I can tell, this discussion concluded with three agreed proposals, in the contributions of [11 May 2022 by @roy-lowry](https://github.com/cf-convention/discuss/issues/153#issuecomment-1123485456):

> acoustic_target_strength_in_sea_water (dimensionless)
> 
> Target strength is 10 times the log10 of the ratio of backscattering cross-section to the reference value, 1 m2. Backscattering cross-section is a parameter computed from the intensity of the backscattered sound wave relative to the intensity of the incident sound wave. For further details see MacLennan et. al (2002) doi:10.1006/jmsc.2001.1158.
>
> acoustic_volume_backscattering_strength_in_sea_water (dimensionless)
> 
> Acoustic volume backscattering strength is 10 times the log10 of the ratio of the volume backscattering coefficient to the reference value, 1 m-1. Volume backscattering coefficient is the integral of the backscattering cross-section divided by the volume sampled. Backscattering cross-section is a parameter computed from the intensity of the backscattered sound wave relative to the intensity of the incident sound wave. The parameter is computed to provide a measurement that is proportional to biomass density per unit volume in the field of fisheries acoustics. For further details see MacLennan et. al (2002) doi:10.1006/jmsc.2001.1158.

and [the same day by @gavinmacaulay](https://github.com/cf-convention/discuss/issues/153#issuecomment-1124344872):

> acoustic_area_backscattering_strength_in_sea_water (dimensionless)
> 
> Acoustic area backscattering strength is 10 times the log10 of the ratio of the area backscattering coefficient to the reference value, 1 (m2 m-2). Area backscattering coefficient is the integral of the volume backscattering coefficient over a defined distance. Volume backscattering coefficient is the linear form of acoustic_volume_backscattering_strength_in_sea_water. For further details see MacLennan et. al (2002) doi:10.1006/jmsc.2001.1158.

There weren't any outstanding concerns expressed. There is discussion about different ways of saying "backscattering" in standard names, but that should be handled as a different issue. Please could the moderators have a look at this @feggleton @japamment?

**Comment by hcannaby** [comment]
Yes, I’m also happy with the Roy’s suggestions

**Comment by feggleton** [comment]
Thank you for this proposal and discussion.

I have put these into the cfeditor.

The following standard phrases exist for the terms in acoustic_volume_backscattering_strength_in_sea_water:

Scattering of radiation is its deflection from its incident path without loss of energy. Backwards scattering refers to the sum of scattering into all backward angles i.e. scattering_angle exceeds pi/2 radians. A scattering_angle should not be specified with this quantity. "X_volume" means the volume occupied by X within the grid cell.

And for acoustic_area_backscattering_strength_in_sea_water:

Scattering of radiation is its deflection from its incident path without loss of energy. Backwards scattering refers to the sum of scattering into all backward angles i.e. scattering_angle exceeds pi/2 radians. A scattering_angle should not be specified with this quantity. "X_area" means the horizontal area occupied by X within the grid cell. The extent of an individual grid cell is defined by the horizontal coordinates and any associated coordinate bounds or by a string valued auxiliary coordinate variable with a standard name of "region".

@hcannaby @lhmarsden Do these need to be included?

**Comment by gavinmacaulay** [comment]
@feggleton - I suggest no. They don't make much sense (and some are incorrect) when applied to the three proposed names.

**Comment by lhmarsden** [comment]
> @feggleton - I suggest no. They don't make much sense (and some are incorrect) when applied to the three proposed names.

I am a bit puzzled by this. We have spent some time discussing how to phrase these terms, and there seemed to be agreement on them. So now they should not be included? Did something change? Or have I misunderstood something?

**Comment by gavinmacaulay** [comment]
My comments were in response to the most recent comment by @feggleton (https://github.com/cf-convention/discuss/issues/153#issuecomment-1518002056).

**Comment by feggleton** [comment]
@japamment @JonathanGregory separate to these terms which have been agreed (3), there seems to be discussion around 'backscattering' and 'backwards_scattering' which needs to be raised and discussed in a separate ticket as this effects 9 names and might link to a list of proposed names in #130 but should not delay the names in this ticket. Thanks

**Comment by JonathanGregory** [comment]
Yes, I agree. What's a convenient way to make a note of that, so we can return to it (with aliases if necessary) when the presently proposed changes have been made in the standard name table?

**Comment by japamment** [comment]
I am closing this ticket as the names were added in V81 of the standard name table. I have made a note that we need to resolve the backscattering versus backwards_scattering question. I'll open that in a separate issue shortly.
