### ISSUE TITLE
 Standard names: urban_thermal_climate_index, physiological_equivalent_temperature  and perceived_temperature 

### ISSUE THREAD

**Issue by VossV** [cf-convention/discuss#156]
**Proposer's name**  AtMoDat Project - Vivien Voss
**Date** 2022-05-17.

**- Term** universal_thermal_climate_index
**- Description** Universal Thermal Climate Index (UTCI) is an equivalent temperature of the actual thermal condition. It is the air temperature of a reference condition causing the same dynamic physiological response in a human body considering its energy budget, physiology and clothing adaptation [utci.org].
**- Units** Degree_C

**- Term** physiological_equivalent_temperature
**- Description** Physical equivalent temperature (PET) is an equivalent air temperature of the acutal thermal condition. It is the air temperature of a reference condition without wind and solar radiation at which the heat budget of the human body is balanced with the same core and skin temperature.
**- Units** Degree_C

**- Term** perceived_temperature
**- Description** Perceived temperature (PT) is an equivalent air temperature of the actual thermal condition. It is the air temperature of a reference condition causing the same thermal perception in a human body considering air temperature, windspeed, humidity, solar and thermal radiation as well as clothing and activity level.
**- Units** Degree_C

Relevance: UTCI, PET and PT are established in human-biometeorology, but there are no CF standard names to write out model output in a standardised manner.

Some references for the defintion of the proposed standard_names can be found here:
UTCI: utci.org
PET: Höppe (1999): The physiological equivalent temperature – a universal index for the biometeorological assessment of the thermal environment, https://doi.org/10.1007/s004840050118
PT: Staiger et al. 2012: The perceived temperature – a versatile index for the assessment of the human thermal environment. Part A: scientific basics, https://doi.org/10.1007/s00484-011-0409-6.

**Comment by larsbarring** [comment]
Hi,
A couple of thoughts:
1:
I was initially slightly confused by the title "...urban thermal comfort index..." and the definition. But in your response I found the explanation. I agree that UTCI as in Universal Thermal Climate Index is well established, but I did not know (at least well enough) about the alternative interpretation of the acronym (Urban Thermal Comfort Index) -- they are in fact the same, right?
If so it might be useful to mention this in the explanation. Something like:

- **Term universal_thermal_climate_index**
- **Description** Universal Thermal Climate Index (UTCI) is an equivalent temperature of the actual thermal condition. It is the air temperature of a reference condition causing the same dynamic physiological response in a human body considering its energy budget, physiology and clothing adaptation [utci.org]. Sometimes this index is also known as "Urban Thermal Comfort Index".
- **Units** Degree_C

While the established unit for UTCI is ``degree_C`` we usually use the canonical unit in the standard name table, but then you are of course free to use any convertible unit (as degree_C). I am not sure which is mot appropriate here; keep canonical units or accept the established unit (@JonathanGregory: any thoughts?)

2: 
Regarding ``physiological_equivalent_temperature`` I understand that "PET" is a well-known acronym within the biometeorological community, but with respect to CF there is another well-established community where "PET" is *potential evapo[transpi]ration". I wonder whether it might be better not to include the acronym "PET" here, what do you think?

**Comment by VossV** [comment]
Dear Lars, dear Jonathan

thank you for your feedback! and sorry for the late response.

We agree that universal_thermal_comfort_index seems a good compromise.

We propose to use the standard name 'physiological_equivalent_temperature' and to mention the abbreviation PET only in the term description. We think this should avoid any confusion as the difference of the two unrelated variables is clear.

Kind regards,
Vivien

**Comment by JonathanGregory** [comment]
Dear Vivien

> We agree that universal_thermal_comfort_index seems a good compromise.

Would it be OK to call it `universal_thermal_comfort_index_temperature`, because it _is_ a temperature. An "index" sounds like an arbitrary dimensionless quantity.

> We propose to use the standard name 'physiological_equivalent_temperature' and to mention the abbreviation PET only in the term description. We think this should avoid any confusion as the difference of the two unrelated variables is clear.

That seems sensible. You could even remark in the definition that "PET" should not be confused with potential evapotranspiration.

Cheers

Jonathan

**Comment by VossV** [comment]
Dear Jonathan,

thank you for your suggestions.

UTCI being an index with unit K indeed seems counter-intuitive. However, we believe this is more consistent for two reasons. There are some precedents in the current list of standard names where an index variable is associated with a unit, e.g. atmosphere_stability_k_index, lightning_potential_index and others. In this context it would seem more consistent to remain with UTCI as universal_thermal_comfort_index. This is also the established terminology in the field.

We have added the suggested note to the definition of PET.

Kind regards,
Vivien

####  Updated Version:

Term: universal_thermal_comfort_index
- Description: Universal Thermal Comfort Index (UTCI) is an equivalent temperature of the actual thermal condition. It is the air temperature of a reference condition causing the same dynamic physiological response in a human body considering its energy budget, physiology and clothing adaptation [utci.org].
- Units: Degree_C

Term: physiological_equivalent_temperature
- Description: Physiological equivalent temperature (PET) is an equivalent air temperature of the acutal thermal condition. It is the air temperature of a reference condition without wind and solar radiation at which the heat budget of the human body is balanced with the same core and skin temperature. **Note that PET here is not potential evapotranspiration.**
- Units: Degree_C

Term: perceived_temperature
- Description: Perceived temperature (PT) is an equivalent air temperature of the actual thermal condition. It is the air temperature of a reference condition causing the same thermal perception in a human body considering air temperature, windspeed, humidity, solar and thermal radiation as well as clothing and activity level. **It is not the perceived air temperature, that either derives from wind chill and heat index, which has the standard_name apparent_air_temperature.**
- Units: Degree_C

**Comment by JonathanGregory** [comment]
Dear Vivien

OK, that's fine. Thanks! I assume Alison @japamment will consider this proposal for the standard name table soon.

Best wishes

Jonathan

**Comment by feggleton** [comment]
Thanks for your proposal and to @JonathanGregory I think you have covered all the considerations here. I don't think including the note on potential evapotranspiration is really necessary here but others may think otherwise which is perfectly fine. @japamment could you have a look at these terms to confirm before acceptance. Thanks all

**Comment by JonathanGregory** [comment]
I see `physiological_equivalent_temperature` and `perceived_temperature` in version 81, but not `universal_thermal_comfort_index`. Do you know what's happened to this, @feggleton @japamment?

**Comment by feggleton** [comment]
@JonathanGregory Thanks for flagging. I see what has happened here. The table contains this term:

universal_thermal_climate_index

Universal Thermal Comfort Index (UTCI) is an equivalent temperature of the actual thermal condition. Reference: utci.org. It is the air temperature of a reference condition causing the same dynamic physiological response in a human body considering its energy budget, physiology and clothing adaptation.

The term name is wrong and should be universal_thermal_comfort_index. I will put an alias in to correct this for the next update. Apologies for this.

**Comment by feggleton** [comment]
Added to the editor: https://cfeditor.ceda.ac.uk/proposals/1

**Comment by japamment** [comment]
Closing this issue as the names were published in V81 of the standard name table.

**Comment by japamment** [comment]
This issue is already closed but I am recording that the alias
universal_thermal_climate_index -> universal_thermal_comfort_index
was published in V82 of the standard name table.
