### ISSUE TITLE
New standard_name for Direct Normal Irradiance

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#16]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2019/08/20
Basing on surface_direct_downwelling_shortwave_flux_in_air we want to apply for the new standard name surface_direct_along_beam_shortwave_flux_in_air for use in renewable energy tasks. 
It is the direct solar radiation on a plane at the surface, oriented perpendicular to the incoming beam.

**- Term** surface_direct_along_beam_shortwave_flux_in_air
**- Definition**  "surface" means the lower boundary of the atmosphere. "direct" radiation is radiation that has followed a direct path from the sun. “along_beam” refers to direct radiation on a plane perpendicular to the direction of the sun. This is in contrast to quantities like direct_downwelling_shortwave_flux_in_air, where the radiation falls on a horizontal plane at the earth surface. The term "shortwave" means shortwave radiation. In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics.' Regarding solar energy, applications the given quantity is often called Direct Normal Irradiance (DNI).
**- Units** W m-2

This proposal belongs to http://cfeditor.ceda.ac.uk/proposal/4295 which was discussed earlier via the mailing list and lead to the standard_name given above.

**Comment by japamment** [comment]
Dear Beate and Ronny,

Many thanks for transferring this issue to GitHub, along with your other proposals. As you say, this name has already been the subject of discussion on the mailing list.

The phrase 'along_beam' was suggested by Jonathan as a way of describing the relative orientation of the beam and the surface it is incident upon. I am happy with the proposed name and definition and I think it is useful to include the statement about DNI. I'd like to suggest some (cosmetic) changes to the definition to make it more consistent with existing names:
'The surface called "surface" means the lower boundary of the atmosphere. "Direct" (also known as "beam") radiation is radiation that has followed a direct path from the sun and is alternatively known as "direct insolation". The phrase “along_beam” refers to direct radiation on a plane perpendicular to the direction of the sun. This is in contrast to standard names such as direct_downwelling_shortwave_flux_in_air, where the radiation falls on a horizontal plane at the earth surface. The term "shortwave" means shortwave radiation. In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The quantity with standard name surface_direct_along_beam_shortwave_flux_in_air is also called Direct Normal Irradiance (DNI) in the solar energy industry.'

If you are happy with these changes then I think this name can be accepted for publication.

Best wishes,
Alison

**Comment by GeyerB** [comment]
>If you are happy
Yes, we are!!
Thanks, for the work!!

**Comment by japamment** [comment]
Dear Beate,

Many thanks. This name is now accepted for publication in the standard name table and will be added in this week's update.

Best wishes,
Alison

**Comment by feggleton** [comment]
These changes have been published in version 71 of the standard name table.
