### ISSUE TITLE
New standard names for Methane related variables, Paleo-climate modelling

### ISSUE THREAD

**Issue by SwatiGehlot** [cf-convention/discuss#162]
The below proposed variables are a part of MPI-ESM model development within the German paleo-climate initiative, **Project PalMod** (www.palmod.de)
**Proposer's name** Swati Gehlot, DKRZ, Hamburg
**Date** 2022-07-05

**1. Methane Emissions from Termites**
**Term** surface_upward_mass_flux_of_methane_due_to_emission_from_termites

**Description** 
The surface called "surface" means the lower boundary of the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The chemical formula for methane is CH4. The mass is the total mass of the molecules. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Emission" means emission from a primary source located anywhere within the atmosphere, including at the lower boundary (i.e. the surface of the earth). "Emission" is a process entirely distinct from "re-emission" which is used in some standard names. Termites belong to any of a group of cellulose-eating insects, the social system of which shows remarkable parallels with those of ants and bees, although it has evolved independently. The precise conditions under which termites produce and consume methane can vary between models.

**Units** kg m-2 s-1
**CMOR name** termiteCH4
**Related standard names:** surface_upward_mass_flux_of_methane_due_to_emission_from_wetland_biological_production

**2. Methane Emissions from Herbivorous Mammals**
**Term** surface_upward_mass_flux_of_methane_due_to_emission_from_herbivorous_mammals

**Description** 
The surface called "surface" means the lower boundary of the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The chemical formula for methane is CH4. The mass is the total mass of the molecules. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Emission" means emission from a primary source located anywhere within the atmosphere, including at the lower boundary (i.e. the surface of the earth). "Emission" is a process entirely distinct from "re-emission" which is used in some standard names. Herbivores are animals that feed on vegetation. Mammals are any vertebrates within the class Mammalia. Examples of large herbivorous mammals include cows, elks, and buffalos. These animals eat grass, tree bark, aquatic vegetation, and shrubby growth. Herbivores can also be medium-sized animals such as sheep and goats, which eat shrubby vegetation and grasses. Small herbivores include rabbits, chipmunks, squirrels, and mice. The precise conditions under which herbivorous mammals produce and consume methane can vary between models.

**Units** kg m-2 s-1
**CMOR name** herbivoreCH4
**Related standard names:** surface_upward_mass_flux_of_methane_due_to_emission_from_wetland_biological_production

**3.  Methane Emissions from Fires**
**Term** surface_upward_mass_flux_of_methane_due_to_emission_from_fires

**Description** Methane emitted from the surface, generated by biomass burning (fires). Positive direction upwards.
The surface called "surface" means the lower boundary of the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The chemical formula for methane is CH4. The mass is the total mass of the molecules. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Emission" means emission from a primary source located anywhere within the atmosphere, including at the lower boundary (i.e. the surface of the earth). "Emission" is a process entirely distinct from "re-emission" which is used in some standard names. The term "fires" means all biomass fires, whether naturally occurring or ignited by humans. The precise conditions under which fires produce and consume methane can vary between models.

**Units** kg m-2 s-1
**CMOR name** firesCH4
**Related standard names:** surface_upward_mass_flux_of_nitrogen_compounds_expressed_as_nitrogen_due_to_emission_from_fires

**4.  Methane Uptake by Non-Wetland Soils**
**Term** surface_downward_mass_flux_of_methane_due_to_non_wetland_soil_biological_consumption  

**Description** 
The surface called "surface" means the lower boundary of the atmosphere. "Downward" indicates a vector component which is positive when directed downward (negative upward). In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. The chemical formula for methane is CH4. The mass is the total mass of the molecules. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. Non-wetland soils are all soils except for wetlands. Wetlands are areas where water covers the soil, or is present either at or near the surface of the soil all year or for varying periods of time during the year, including during the growing season. The precise conditions under which non-wetland soils produce and consume methane can vary between models.

**Units** kg m-2 s-1
**CMOR name** fsoilCH4
**Related standard names:** surface_downward_mass_flux_of_methane_due_to_wetland_biological_consumption

Edited by @JonathanGregory to replace "herbivore" by "herbivorous" in a few places. 5 Sep 2022.

**Comment by JonathanGregory** [comment]
Dear @SwatiGehlot

Thanks for these proposals, which follow existing patterns and vocabulary as far as I can tell. One small point: wouldn't `herbivorous_mammals` be better? "Herbivore" is a noun.

Best wishes

Jonathan

**Comment by SwatiGehlot** [comment]
Thanks @JonathanGregory for your feedback. The change is acceptable by me.

Best,
Swati

**Comment by JonathanGregory** [comment]
Thanks, @SwatiGehlot. Since you're OK with `herbivorous` I have edited your initial proposal accordingly. I expect that Alison @japamment, the manager of standard names, will consider these names in due course.

**Comment by feggleton** [comment]
Wow! This is an interesting set of names! I had not considered the methane emissions from termites before and has lead to some interesting googling.

Thanks for a great proposal which highlights similar names and follows conventions well. I am happy that these names can be accepted. Thanks
