### ISSUE TITLE
New  Standard name: *Dissolved Organic Carbon-13 Concentration*

### ISSUE THREAD

**Issue by SwatiGehlot** [cf-convention/discuss#163]
The below proposed variables are a part of MPI-ESM model development within the German paleo-climate initiative, Project PalMod ([www.palmod.de](http://www.palmod.de/))

Proposer's name Swati Gehlot, DKRZ, Hamburg

Date 2022-07-07

**Dissolved Organic Carbon-13 Concentration**

**Term** mole_concentration_of_dissolved_organic_13C_in_sea_water

**Description** Sum of dissolved organic carbon-13 component concentrations. Mole concentration means number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Organic carbon" describes a family of chemical species and is the term used in standard names for all species belonging to the family that are represented within a given model. The list of individual species that are included in a quantity having a group chemical standard name can vary between models. Where possible, the data variable should be accompanied by a complete description of the species represented, for example, by using a comment attribute. "C" means the element carbon and "13C" is the stable isotope "carbon-13", having six protons and seven neutrons.

**Units** mol m-3

**CMOR name** disso13c

**Related standard name** mole_concentration_of_dissolved_inorganic_13C_in_sea_water

**Comment by lqjiang** [comment]
This is a very interesting term. Based on my very limited understanding of isotopes, they are commonly reported as a delta ratio of themselves against its naturally occurring stable isotopes (https://gml.noaa.gov/outreach/isotopes/deltavalues.html), and their units are often things like "parts per thousand (/mille)", or "percent (%). I haven't seen such a thing as "mole concentration" of an isotope previously and wonder if the proposer or someone else in this group could provide some examples of the distribution of mole concentration of carbon-13 reported in the unit of mol/m3? 

Thanks

**Comment by roy-lowry** [comment]
The different expression is because this is an output parameter from a model rather than a measurement. Consequently, I see no problem with the Standard Name proposal because it clearly describes the parameter, making it clear that it is very different entity to measurements as described by @lqjiang, which have Standard Names containing the component 'enrichment' such as enrichment_of_14C_in_carbon_dioxide_in_air_expressed_as_uppercase_delta_14C. There is also a very clear precedent for this Standard Name given in the proposal (mole_concentration_of_dissolved_inorganic_13C_in_sea_water),

**Comment by JonathanGregory** [comment]
Dear @SwatiGehlot

Thanks for this proposal, which looks fine to me.

Jonathan

**Comment by SwatiGehlot** [comment]
Thanks @lqjiang @roy-lowry @JonathanGregory for the feedback.

I am looking forward to get this term accepted.

Swati

**Comment by feggleton** [comment]
I was going to make the same comment about enrichment_of_14C_in_carbon_dioxide_in_air_expressed_as_uppercase_delta_14C so I'm glad this has already been explained.

I then realised we already have:

mole_concentration_of_dissolved_inorganic_13C_in_sea_water
alias: mole_concentration_of_dissolved_inorganic_carbon13_in_sea_water
Mole concentration means number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Dissolved inorganic carbon" describes a family of chemical species in solution, including carbon dioxide, carbonic acid and the carbonate and bicarbonate anions. "Dissolved inorganic carbon" is the term used in standard names for all species belonging to the family that are represented within a given model. The list of individual species that are included in a quantity having a group chemical standard name can vary between models. Where possible, the data variable should be accompanied by a complete description of the species represented, for example, by using a comment attribute. "C" means the element carbon and "13C" is the stable isotope "carbon-13", having six protons and seven neutrons.

So this term and it's definition are in line with the other terms we have and can most likely be accepted. Thank you!
