### ISSUE TITLE
New Standard Names: Wildland Fire Indexes

### ISSUE THREAD

**Issue by akessenich** [cf-convention/discuss#166]
This is a group of terms describing wildland fire conditions. They are compiled from a variety of sources in North America and are not new terms, but have not been assigned CF names. This work is related to the NA-CORDEX archive and supported by NSF Growing Convergence Research.

**Proposer's Name:** Lee Kessenich, National Center for Atmospheric Research

**Date:** July 19, 2022

**- Term:** keetch_byram_drought_index
**- Description:** The Keetch Byram Drought Index (KBDI) is a numerical drought index ranging from 0 to 800 that estimates the cumulative moisture deficiency in soil. It is a cumulative index. It is a function of maximum temperature and precipitation over the previous 24 hours.  
**- Units:** unitless

**- Term:** modified_fosberg_fire_weather_index
**- Description:** The modified Fosberg Fire Weather Index (mFFWI) is a measure of the potential effect of weather conditions on wildland fire. The Fosberg Fire Weather Index is a function of temperature, wind, and humidity. It is modified with a fuel availability factor based on the Keetch Byram Drought Index. 
**- Units:** unitless

**- Term:** canadian_fire_weather_index
**- Description:** The Canadian Fire Weather Index (CFWI) is a numerical rating of potential frontal fire intensity from the Canadian Forest Fire Index System. It indicates fire intensity by combining the rate of spread with the amount of fuel being consumed and is also used for general public information about fire danger conditions. It is a function of wind speed, temperature, relative humidity, and precipitation. The calculation accounts for multiple layers of flammable material on the ground as well as fine fuels above the surface, combined with the expected rate of spread of fire. The index is open ended.
**- Units:** unitless

**- Term:** 100_hour_fuel_moisture_content
**- Description:** 100 hour fuel moisture (FM100) represents the modeled moisture content of dead fuels in the 1 to 3 inch diameter class. It can also be used as a very rough estimate of the average moisture content of the forest floor from three-fourths inch to 4 inches below the surface. The 100-hour timelag fuel moisture is a function of length of day (as influenced by latitude and calendar date), maximum and minimum temperature and relative humidity, and precipitation duration in the previous 24 hours. It is a component in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** %

**- Term:** 1000_hour_fuel_moisture_content
**- Description:** 1000 hour fuel moisture (FM1000) represents the modeled moisture content in the dead fuels in the 3 to 8 inch diameter class and the layer of the forest floor about 4 inches below the surface. The value is based on a running 7-day average. The 1000-hour timelag fuel moisture is a function of length of day (as influenced by latitude and calendar date), daily temperature and relative humidity extremes (maximum and minimum values) and the 24-hour precipitation duration values for a 7-day period. It is a component in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** %

**- Term:** energy_release_component
**- Description:** The Energy Release Component (ERC) is a number related to the available energy (BTU) per unit area (square foot) within the flaming front at the head of a fire. Daily variations in ERC are due to changes in moisture content of the various fuels present, both live and dead. It may also be considered a composite fuel moisture value as it reflects the contribution that all live and dead fuels have to potential fire intensity. Energy Release Component is a cumulative index. The scale is open-ended and relative. Energy Release Component values depend on the fuel model input into the calculations and interpretation of precise values varies with ecology and region.  It is an index in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** unitless [while it is related to BTU/ft^2, the scale of ERC is relative to location and fuel model in ways that do not translate directly, especially in the field]

**- Term:** burning_index
**- Description:** The Burning Index (BI) is a number related to the contribution of fire behavior to the effort of containing a fire. The BI is derived from a combination of Spread and Energy Release Components. The Spread Component is a rating of the forward rate of spread of a headfire and wind is a key input. Burning Index is expressed as a numeric value closely related to the flame length in feet multiplied by 10. The scale is open ended which allows the range of numbers to adequately define fire problems, even in time of low to moderate fire danger. Computed BI values represent the near upper limit to be expected on the rating area. In other words, if a fire occurs in the worst fuel, weather and topography conditions of the rating area, these numbers indicate its expected fireline intensities and flame length. It is an index in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** unitless [while this is "closely related to" the flame length in feet, it is not exact and is not treated as such in the field]

**- Term:** severe_fire_danger_index
**- Description:** Severe Fire Danger Index (SFDI) is the normalized product of normalized Energy Release Component (ERC) and normalized Burning Index (BI) from the National Fire Danger Rating System (NFDRS).  It is commonly categorized into five classes based on percentile: low (0-60), moderate (60-80), high (80-90), very high (90-97), and extreme (97-100).  It can be extended to future conditions by introducing an unprecedented category for values above the historical 100th percentile.  As it is locally normalized, its interpretation remains the same across space.
**- Units:** unitless [though technically a percentile, when applied to future models, this breaks down when "unprecedented" conditions are assigned values higher than 100 percent.]

**Comment by akessenich** [comment]
Dear Jonathan @JonathanGregory 

KBDI, mFFWI, CFWI, and SFDI have fixed definitions. The NFDRS indexes involve modeling of fuels and vegetation, and the recommendations about how to do that can change (and in fact they recently underwent a major update), but the *meaning* of the indexes is fixed. The end results are measures of fuel dryness (FM100 & FM1000), fire intensity (ERC), and flame length (BI).

We can add the prefix `NFDRS_` to all the relevant standard names. 
That's a good idea, thanks.

Agreed also that we should remove `_content` from the names for FM100 and FM1000.

With regard to adding an `_index` suffix to ERC, these names are generally treated as proper names in the literature, and I would argue for referring to them similarly here. "NFDRS energy release component" is immediately recognizable to domain specialists, whereas "energy release component index" might be confusing to someone used to the former.

It appears that the meaning of Burning Index as a measure of flame length is getting lost in the text, so we can move that to the front of the definition. (Flame length is highly relevant to fire management because it affects the safety of firefighters and aerial support.  It is a function of fire intensity and speed of spread. Would it be helpful to add that information to the definition?)

The Severe Fire Danger Index is not officially a part of the NFDRS but is intended as a supplement to it.

Here are updated versions of the definitions:

**- Term:** keetch_byram_drought_index (unchanged from original post)
**- Description:** The Keetch Byram Drought Index (KBDI) is a numerical drought index ranging from 0 to 800 that estimates the cumulative moisture deficiency in soil. It is a cumulative index. It is a function of maximum temperature and precipitation over the previous 24 hours.  
**- Units:** unitless

**- Term:** modified_fosberg_fire_weather_index (unchanged from original post)
**- Description:** The modified Fosberg Fire Weather Index (mFFWI) is a measure of the potential effect of weather conditions on wildland fire. The Fosberg Fire Weather Index is a function of temperature, wind, and humidity. It is modified with a fuel availability factor based on the Keetch Byram Drought Index. 
**- Units:** unitless

**- Term:** canadian_fire_weather_index (unchanged from original post)
**- Description:** The Canadian Fire Weather Index (CFWI) is a numerical rating of potential frontal fire intensity from the Canadian Forest Fire Index System. It indicates fire intensity by combining the rate of spread with the amount of fuel being consumed and is also used for general public information about fire danger conditions. It is a function of wind speed, temperature, relative humidity, and precipitation. The calculation accounts for multiple layers of flammable material on the ground as well as fine fuels above the surface, combined with the expected rate of spread of fire. The index is open ended.
**- Units:** unitless

**- Term:** NFDRS_100_hour_fuel_moisture
**- Description:** 100 hour fuel moisture (FM100) represents the modeled moisture content of dead fuels in the 1 to 3 inch diameter class. It can also be used as a very rough estimate of the average moisture content of the forest floor from three-fourths inch to 4 inches below the surface. The 100-hour timelag fuel moisture is a function of length of day (as influenced by latitude and calendar date), maximum and minimum temperature and relative humidity, and precipitation duration in the previous 24 hours. It is a component in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** %

**- Term:** NFDRS_1000_hour_fuel_moisture
**- Description:** 1000 hour fuel moisture (FM1000) represents the modeled moisture content in the dead fuels in the 3 to 8 inch diameter class and the layer of the forest floor about 4 inches below the surface. The value is based on a running 7-day average. The 1000-hour timelag fuel moisture is a function of length of day (as influenced by latitude and calendar date), daily temperature and relative humidity extremes (maximum and minimum values) and the 24-hour precipitation duration values for a 7-day period. It is a component in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** %

**- Term:** NFDRS_energy_release_component
**- Description:** The Energy Release Component (ERC) is a number related to the available energy (BTU) per unit area (square foot) within the flaming front at the head of a fire. Daily variations in ERC are due to changes in moisture content of the various fuels present, both live and dead. It may also be considered a composite fuel moisture value as it reflects the contribution that all live and dead fuels have to potential fire intensity. Energy Release Component is a cumulative index. The scale is open-ended and relative. Energy Release Component values depend on the fuel model input into the calculations and interpretation of precise values varies with ecology and region.  It is an index in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** unitless [while it is related to BTU/ft^2, the scale of ERC is relative to location and fuel model in ways that do not translate directly, especially in the field]

**- Term:** NFDRS_burning_index
**- Description:** The Burning Index (BI) is a numeric value closely related to the flame length in feet multiplied by 10, which is related to the contribution of fire behavior to the effort of containing a fire. The BI is a function of fire spread and fire intensity and is derived from a combination of Spread and Energy Release Components. The Spread Component is a rating of the forward rate of spread of a headfire and wind is a key input. The scale is open ended which allows the range of numbers to adequately define fire problems, even in time of low to moderate fire danger. Computed BI values represent the near upper limit to be expected on the rating area. In other words, if a fire occurs in the worst fuel, weather and topography conditions of the rating area, these numbers indicate its expected fireline intensities and flame length. It is an index in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** unitless [while this is "closely related to" the flame length in feet, it is not exact and is not treated as such in the field]

**- Term:** severe_fire_danger_index (unchanged from original post)
**- Description:** Severe Fire Danger Index (SFDI) is the normalized product of normalized Energy Release Component (ERC) and normalized Burning Index (BI) from the National Fire Danger Rating System (NFDRS).  It is commonly categorized into five classes based on percentile: low (0-60), moderate (60-80), high (80-90), very high (90-97), and extreme (97-100).  It can be extended to future conditions by introducing an unprecedented category for values above the historical 100th percentile.  As it is locally normalized, its interpretation remains the same across space.
**- Units:** unitless [though technically a percentile, when applied to future models, this breaks down when "unprecedented" conditions are assigned values higher than 100 percent.]

**Comment by JonathanGregory** [comment]
Dear Lee

Thanks for these changes. Standard names don't contain upper case so the prefix should be `nfdrs_`. That looks a bit odd, but no worse than `canadian_`! Yes, I follow the definition of burning index now, and with the prefix it's obvious that you can't expect to understand it in detail without looking it up.

The severe fire danger index is not from NFDRS but it would still be good to add a prefix, since it otherwise sounds generic. Maybe we could prefix `us_`?

Best wishes

Jonathan

**Comment by akessenich** [comment]
Thank you for your feedback again, Jonathan. 
Despite SFDI not being an official part of the NFDRS system, it is closely related enough to be identifiable by associating the two, so I have specified it as unofficial in the description and added `nfdrs_` as a prefix, if that works.

Here are updated versions of the definitions:

**- Term:** keetch_byram_drought_index (unchanged from original post)
**- Description:** The Keetch Byram Drought Index (KBDI) is a numerical drought index ranging from 0 to 800 that estimates the cumulative moisture deficiency in soil. It is a cumulative index. It is a function of maximum temperature and precipitation over the previous 24 hours.  
**- Units:** unitless

**- Term:** modified_fosberg_fire_weather_index (unchanged from original post)
**- Description:** The modified Fosberg Fire Weather Index (mFFWI) is a measure of the potential effect of weather conditions on wildland fire. The Fosberg Fire Weather Index is a function of temperature, wind, and humidity. It is modified with a fuel availability factor based on the Keetch Byram Drought Index. 
**- Units:** unitless

**- Term:** canadian_fire_weather_index (unchanged from original post)
**- Description:** The Canadian Fire Weather Index (CFWI) is a numerical rating of potential frontal fire intensity from the Canadian Forest Fire Index System. It indicates fire intensity by combining the rate of spread with the amount of fuel being consumed and is also used for general public information about fire danger conditions. It is a function of wind speed, temperature, relative humidity, and precipitation. The calculation accounts for multiple layers of flammable material on the ground as well as fine fuels above the surface, combined with the expected rate of spread of fire. The index is open ended.
**- Units:** unitless

**- Term:** nfdrs_100_hour_fuel_moisture
**- Description:** 100 hour fuel moisture (FM100) represents the modeled moisture content of dead fuels in the 1 to 3 inch diameter class. It can also be used as a very rough estimate of the average moisture content of the forest floor from three-fourths inch to 4 inches below the surface. The 100-hour timelag fuel moisture is a function of length of day (as influenced by latitude and calendar date), maximum and minimum temperature and relative humidity, and precipitation duration in the previous 24 hours. It is a component in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** %

**- Term:** nfdrs_1000_hour_fuel_moisture
**- Description:** 1000 hour fuel moisture (FM1000) represents the modeled moisture content in the dead fuels in the 3 to 8 inch diameter class and the layer of the forest floor about 4 inches below the surface. The value is based on a running 7-day average. The 1000-hour timelag fuel moisture is a function of length of day (as influenced by latitude and calendar date), daily temperature and relative humidity extremes (maximum and minimum values) and the 24-hour precipitation duration values for a 7-day period. It is a component in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** %

**- Term:** nfdrs_energy_release_component
**- Description:** The Energy Release Component (ERC) is a number related to the available energy (BTU) per unit area (square foot) within the flaming front at the head of a fire. Daily variations in ERC are due to changes in moisture content of the various fuels present, both live and dead. It may also be considered a composite fuel moisture value as it reflects the contribution that all live and dead fuels have to potential fire intensity. Energy Release Component is a cumulative index. The scale is open-ended and relative. Energy Release Component values depend on the fuel model input into the calculations and interpretation of precise values varies with ecology and region.  It is an index in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** unitless [while it is related to BTU/ft^2, the scale of ERC is relative to location and fuel model in ways that do not translate directly, especially in the field]

**- Term:** nfdrs_burning_index
**- Description:** The Burning Index (BI) is a numeric value closely related to the flame length in feet multiplied by 10, which is related to the contribution of fire behavior to the effort of containing a fire. The BI is a function of fire spread and fire intensity and is derived from a combination of Spread and Energy Release Components. The Spread Component is a rating of the forward rate of spread of a headfire and wind is a key input. The scale is open ended which allows the range of numbers to adequately define fire problems, even in time of low to moderate fire danger. Computed BI values represent the near upper limit to be expected on the rating area. In other words, if a fire occurs in the worst fuel, weather and topography conditions of the rating area, these numbers indicate its expected fireline intensities and flame length. It is an index in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** unitless [while this is "closely related to" the flame length in feet, it is not exact and is not treated as such in the field]

**- Term:** nfdrs_severe_fire_danger_index (unchanged from original post)
**- Description:** Severe Fire Danger Index (SFDI) is the normalized product of normalized Energy Release Component (ERC) and normalized Burning Index (BI) from the United States National Fire Danger Rating System (NFDRS). While SFDI is not officially part of the National Fire Danger Rating System, it is related to and intended to supplement NFDRS.  It is commonly categorized into five classes based on percentile: low (0-60), moderate (60-80), high (80-90), very high (90-97), and extreme (97-100).  It can be extended to future conditions by introducing an unprecedented category for values above the historical 100th percentile.  As it is locally normalized, its interpretation remains the same across space.
**- Units:** unitless [though technically a percentile, when applied to future models, this breaks down when "unprecedented" conditions are assigned values higher than 100 percent.]

**Comment by JonathanGregory** [comment]
Thanks very much, Lee @akessenich. It looks fine to me now. I expect Alison @japamment will comment in due course on adding these names to the table.

**Comment by sebvi** [comment]
Just wanted to mention that some of these variables are also defined in WMO GRIB2 (see table below). I only see a  difference with the units of "Energy Release Component", "unitless" vs "J/m2", otherwise it seems relatively coherent.

Code table 4.2
Product discipline 2 – Land surface products, parameter category 4: fire weather products

| Number | Parameter | Units| 
|--|--|--|
|0| Fire outlook |Code table 4.224|
|1| Fire outlook due to dry thunderstorm | Code table 4.224|
|2| Haines index |Numeric|
|3| Fire burned area |%|
|4| Fosberg index (see Note) |Numeric|
|5| Forest Fire Weather Index (Canadian Forest Service) |Numeric|
|6| Fine Fuel Moisture Code (Canadian Forest Service) |Numeric|
|7| Duff Moisture Code (Canadian Forest Service) |Numeric|
|8| Drought Code (Canadian Forest Service) |Numeric|
|9| Initial Fire Spread Index (Canadian Forest Service) |Numeric|
|10| Fire Buildup Index (Canadian Forest Service) |Numeric|
|11| Fire Daily Severity Rating (Canadian Forest Service) |Numeric|
|12| Keetch-Byram drought index |Numeric|
|13| Drought factor (as defined by the Australian Forest Service)|Numeric|
|14| Rate of spread (as defined by the Australian Forest Service) |m/s|
|15| Fire danger index (as defined by the Australian Forest Service) |Numeric|
|16| Spread component (as defined by the US Forest Service National Fire Danger Rating System) |Numeric|
|17| Burning index (as defined by the US Forest Service National Fire Danger Rating System) |Numeric|
|18| Ignition component (as defined by the US Forest Service National Fire Danger Rating System) |%|
|19| Energy release component (as defined by the US Forest Service National Fire Danger Rating System) |J/m2|

**Comment by akessenich** [comment]
@sebvi 
Thanks for providing the list, it is helpful to cross-reference. As noted next to the units for Energy Release Component, technically it has units of BTU/ft^2, which could be converted to J/m2. However, this does not seem to line up with how it is used or intended to be used. In NFDRS documentation, it is noted that the index is "related to the available energy per unit area within the flaming front at the head of a fire." For a CF standard name, what would be the appropriate way to approach units that are technically accurate but does not align with usage?

**Comment by JonathanGregory** [comment]
Dear Lee @akessenich and Sebastien @sebvi 

If the energy release component is really not dimensionless, but actually in `BTU ft-2`, the canonical unit for CF should be `J m-2`, because that's the SI unit. You can write in the definition that it's usually given in `BTU ft-2`. According to UDUNITS

``` 
1 BTU ft-2 = 11356.5 (J m-2)
```
Cheers

Jonathan

**Comment by akessenich** [comment]
Thank you Jonathan for clarifying. 
Here is the updated ERC definition:

**- Term:** nfdrs_energy_release_component
**- Description:** The Energy Release Component (ERC) is a number related to the available energy per unit area within the flaming front at the head of a fire. It is usually given in BTU ft-2. Daily variations in ERC are due to changes in moisture content of the various fuels present, both live and dead. It may also be considered a composite fuel moisture value as it reflects the contribution that all live and dead fuels have to potential fire intensity. Energy Release Component is a cumulative index. The scale is open-ended and relative. Energy Release Component values depend on the fuel model input into the calculations and interpretation of precise values varies with ecology and region.  It is an index in the US National Fire Danger Rating System. The US National Fire Danger Rating System comprises several numeric indexes that rate the potential over a large area for wildland fires to ignite, spread, and require action to suppress or manage.  It was designed for use in the continental United States, and all its components are relative, not absolute. 
**- Units:** J m-2

**Comment by sethmcg** [comment]
Hi!  There's been no further discussion of these names for considerably more than 7 days.  Can they be accepted and added to the standard name table?

**Comment by JonathanGregory** [comment]
As @sethmcg says, I think these are fine. Please could Alison @japamment or Fran @feggleton take a look? Thanks.

**Comment by feggleton** [comment]
Hi all, thanks for the prompt. Just looking at the terms, I don't know much about this topic but reading about the Canadian Fire Weather Index, I wonder whether it should be just Fire Weather Index. After reading: The Fire Weather Index is a component of the Canadian Forest Fire Weather Index (FWI) System.

For nfdrs_100_hour_fuel_moisture please ensure NFDRS is in brackets next to the words in the definition.

I think the only fire phrases we have in the CF SN table are fire_area which doesn't apply to any of these terms so that's fine.

@japamment please confirm you're happy with the definitions here and I think these can be accepted.

**Comment by sethmcg** [comment]
Hi Francesca,
We discussed that point about CFWI, and concluded that just calling it "Fire Weather Index" would be confusingly generic, since all of these terms refer to fire weather indexes.  It is also commonly referred to as the "Canadian Fire Weather Index" in the literature.

**Comment by feggleton** [comment]
Yes that is a fair point. Thanks. 

@japamment If there are no further comments from your side in the next 5 days we can accept this (as i added the label 2 days ago)

**Comment by sethmcg** [comment]
@feggleton @japamment - These standard_names were all accepted back in November, but they still haven't shown up in the Standard Name table, which was last updated a week ago.  What do we need to do to move this issue forward?

**Comment by feggleton** [comment]
Apologies for the delay on these terms @sethmcg. I have now added all of these into the cfeditor and they will be in the next update on Monday.

**Comment by sethmcg** [comment]
Great to hear!  Thanks very much!

**Comment by JonathanGregory** [comment]
These terms are in version 81 of the table, @akessenich. Thanks, @feggleton @japamment.
