### ISSUE TITLE
atmospheric tendencies due to surface fluxes

### ISSUE THREAD

**Issue by taylor13** [cf-convention/discuss#168]
Does anyone know why names like
minus_tendency_of_atmosphere_mass_content_of_ozone_due_to_dry_deposition
are used rather than, say,
surface_downward_mass_flux_of_ozone_due_to_dry_deposition ?

Similarly, 
tendency_of_atmosphere_mass_content_of_carbon_dioxide_expressed_as_carbon_due_to_anthropogenic_emission 
is defined rather than, say,
surface_upward_mass_flux_of_carbon_dioxide_expressed_as_carbon_due_to_anthropogenic_emission 

If the alternative standard names were defined, would they mean the same things as the current one?

**Comment by Armin-RS** [comment]
Hi @taylor13 ,
I can easily think of reasons why the change is not coming from the surface.

Ozone could be deposited on dry sand or dust particles or meteoric smoke particles in the atmosphere itself.

Carbon dioxide could be emitted by human activity in the atmosphere itself, think of aircrafts and rockets.
Or precursor substances like methane or carbon monoxide could be emitted by humans (on the ground or in the atmosphere) and then be oxidized to CO2 in the atmosphere itself. So the CO2 is not coming from below but is formed in the atmosphere itself.

So from my understanding of atmospheric chemistry, these tendencies do not necessarily have to be related to the surface. And no, for me the alternative standard names would or at least could mean something different.
