### ISSUE TITLE
CF-1.10 - schedule for release

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#169]
Hello,

The CF Conventions committee has set out a timeline for the release of the next version of conventions, CF-1.10.

CF-1.10 will be released **during the week starting on Monday 29 August 2022**.

The new version will include all of the enhancement proposals that have already been merged since CF-1.9, plus any existing or new proposals that are concluded and merged before 29 August 2022.

The key dates to note for getting a new or not-yet-concluded enhancement into CF-1.10 are

   * _07 August 2022_
     The last date by which the proposal must be agreed, initiating the three week gestation period.

   * _28 August 2022_
     The last date by which the proposal's gestation period must be completed.

Note that if any substantive questions arise during the gestation period, then the three weeks starts again when the questions are resolved. Non-substantive items arising in this period (such as identification of a trivial formatting issue or spelling mistake) would not cause the clock to reset.

Many thanks,
David,
On behalf of the Conventions Committee and Standard Names Committee

**Comment by davidhassell** [comment]
Hello,

If all goes to plan, I shall be trying out the new release procedure (https://github.com/cf-convention/cf-conventions/issues/371) and releasing CF-1.10 on Wednesday 31st August 2022.

I hope to be back here then to close this issue :)

**Comment by davidhassell** [comment]
Hello,

CF-1.10 has now been released at http://cfconventions.org.

If anyone would like to take a look around the web-site to check that everything is in order, that would be much appreciated (I had to do more of the release manually than I had expected, so the chance human error is increased!)

Thanks, David

**Comment by JonathanGregory** [comment]
In [issue #190 of the website repo](https://github.com/cf-convention/cf-convention.github.io/issues/190), Angelika @atmodatcode reported some broken links to the NUG in CF 1.9. Some of them have been fixed in 1.10, but some remain. Are you still able to fix bugs in 1.10, @davidhassell, in view of your announcement above?

If not, should this be reposted as a defect in the conventions repo for attention next year in 1.11? In either case, once they're fixed, Angelika should be added to the [list of contributors to the conventions](http://cfconventions.org/conventions_contributors.html).

> [Angelika] discovered broken hyperlinks to the NUG reference. They point to https://www.unidata.ucar.edu/software/netcdf/docs/user_guide.html while the correct link is now https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/
> 
> Here are the [remaining] places where [Angelika] discovered broken links: 1.2. Terminology CDL syntax --> see NUG section on CDL syntax
> 
> 
> Bibliography References --> [NUG] The NetCDF User’s Guide

**Comment by JonathanGregory** [comment]
In [issue #250 of the website repo](https://github.com/cf-convention/cf-convention.github.io/issues/250), @larsbarring reported

> In the HTML version of the Conventions document the "keywords" are shown as expected in the reference list, but not in the PDF version. See this example:
> 
> HTML:
> 
> > black_small_square [NetCDF][ NetCDF Software Package](http://www.unidata.ucar.edu/netcdf/index.html) . UNIDATA Program Center of the University Corporation for Atmospheric Research
> 
> PDF:
> 
> > black_small_square [] [NetCDF Software Package](http://www.unidata.ucar.edu/netcdf/index.html) . UNIDATA Program Center of the University Corporation for Atmospheric Research .

Can this still be fixed in the new release?

**Comment by larsbarring** [comment]
Another small thing that I just came across: The link in the [Snyder] reference item should be updated to read
"https://pubs.er.usgs.gov/publication/pp1395" (or is this a separate issue + PR?)

**Comment by davidhassell** [comment]
Hello - A new issue has been opened for fixing the reference problems with the document: https://github.com/cf-convention/cf-conventions/issues/391, so I think we can close this now. Thanks!
