### ISSUE TITLE
How do I register for the online training workshop in September 2022?

### ISSUE THREAD

**Issue by mo-benjaminevans** [cf-convention/discuss#171]
I would like to register for the online training workshop in September 2022 mentioned at http://cfconventions.org/Training/ How do I register?

**Comment by davidhassell** [comment]
Hi @mo-benjaminevans  - sorry we didn't make that clear ... For convenience, we only have one registration form for both the training and the meeting during the following week, so go to the [registration form](https://forms.gle/RB9BYZuLULcVKBsF6) for the meeting (also linked from http://cfconventions.org/Meetings/2022-Workshop.html), which has a question about whether or not you want to attend the training. (Don't worry if you can't also attend the meeting, in-person or on-line  - there are no fees and no obligations!)

I'll get this information up at http://cfconventions.org/Training/ as well.
