### ISSUE TITLE
CF meeting 2022 - Agenda

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#172]
Hello,

The agenda for the CF meeting (13-15 September 2022, Santander and on-line) is now ready and can found at the meeting home page: https://cfconventions.org/Meetings/2022-Workshop.html. 

Thank you to everyone who has volunteered to give talks and host hackathon sessions - I'm sure that it will be a good meeting!

A few reminders:

* Please register by 30th August.
* The on-line only CF training session is on Thursday 8th September - details of which will be announced soon at http://cfconventions.org/Training/2022-Training-Workshop.html.
* There is plenty of space for posters, should you wish to bring one.

All the best,
David, on behalf of the organising committee

**Comment by erget** [comment]
We are taking a group photo tomorrow at lunch, so come dressed to your nines. If you're attending remotely, I invite you to send us a picture representing you so we can print you out and include you in the picture as well. Please get in touch with me or @cofinoa or upload it to this issue if you'd like your picture in the group photo.

Non-exhaustive people who I know have been taking part from afar:
@DocOtak @zklaus @JonathanGregory

**Comment by JonathanGregory** [comment]
![image](https://user-images.githubusercontent.com/8126248/189972154-e5912ea8-0a99-48d3-9293-eaf7136b59d3.png)
 :smile:

**Comment by taylor13** [comment]
A face revealed.  No anonymity anymore.  Cheers.  Will try to get up early tomorrow so I might qualify.

**Comment by DocOtak** [comment]
If you don't want to use the screen shot from yesterday... here is one of me on the Healy.... looking at ice.
![user_photo](https://user-images.githubusercontent.com/868027/190036897-bb038dbd-c67b-479f-a895-d679b9e6075a.jpeg)

**Comment by erget** [comment]
@taylor13 in case we don't hear from you this morning we can use this one, I hope that's fine for you :)

![image](https://user-images.githubusercontent.com/1914151/190105689-cd9bb147-0454-401d-b540-e74f94b58180.png)

**Comment by taylor13** [comment]
Not my happiest face, but what can you expect at 6 a.m. local time.  I did manage to tune in for part of the compression break-out this morning.  Wish I could have attended in person.  Looks like some good progress is being made.

**Comment by cofinoa** [comment]
Thanks to @jesusff who has composed this picture, with local participants and "wall of fame" online participants:

![Participants-Picture](https://user-images.githubusercontent.com/5098603/190988909-f3ba6c55-e959-4245-8da2-206e915bf585.jpg)

I will upload to the 2022 CF Workshop meeting page.

**Comment by rsignell-usgs** [comment]
Just curious: is there a blog post or summary of how the meeting went?

**Comment by davidhassell** [comment]
Hi Rich,
> is there a blog post or summary of how the meeting went?

... not yet, but we're going to be putting one together soon, based on the google doc that recorded (hopefully) all of the comments, questions, actions, etc.
