### ISSUE TITLE
new area type proposed for stratiform cloud

### ISSUE THREAD

**Issue by taylor13** [cf-convention/discuss#176]
**Proposer's name**  Karl Taylor
**Date** 14 September 2022

This is a proposed addition to the **"area types" table**.

**- Term**: stratiform_cloud
**- Description**: This area type complements the existing "convective_cloud" area type, which is the other major category of cloud.   The existing "cloud" area type is the more general term available and includes both convective_cloud and stratiform_cloud types.
**- Units**:  "area types" do not have associated units.

**Justification**: For CMIP, we would like to reference "stratiform_cloud" in the cell_methods. For example, the cell_methods associated with a variable like "effective_radius_of_stratiform_cloud_liquid_water_particles" should limit consideration to the portion of the grid cell occupied by stratiform cloud.  If an area type of "stratiform_cloud" were defined, we could do this, for example, with "cell_methods="area: mean where stratiform_cloud".

**Comment by JonathanGregory** [comment]
Since we already have the area type of `convective_cloud`, as you say, and the phrase `stratiform_cloud` is used in standard names, this proposal is consistent and logical.

**Comment by taylor13** [comment]
Dear @japamment et al.,

I think there is no objection to and there is support for adding the area type "stratiform_cloud" to the list.

thanks,
Karl

**Comment by feggleton** [comment]
This seems logical and makes sense to me. If there are no further comments in the next 7 days we can accept this and include an update of the Area Type table when we update the Standard Names table next. Thanks

**Comment by japamment** [comment]
@taylor13 @feggleton 

I agree this proposal looks fine and there have been no objections. I am currently preparing an update of the standard name table and will also update the area type table this week.

This term will be added to the area type table.

Best wishes

Alison

**Comment by efisher008** [comment]
This issue has now been closed, as the term was added to the area type table in v11 (6th July 2023).
