### ISSUE TITLE
difference between area types "ice_sheet" and "land_ice"

### ISSUE THREAD

**Issue by taylor13** [cf-convention/discuss#182]
I must be missing something obvious, but the [area types table](http://cfconventions.org/Data/area-type-table/current/build/area-type-table.html) includes:

`land_ice`:  "Land ice" means glaciers, ice-caps, grounded ice sheets resting on bedrock and floating ice-shelves.
and
`ice_sheet`: An area type of "ice sheet" indicates where ice sheets are present. It includes both grounded ice sheets resting over bedrock and ice shelves flowing over the ocean, but excludes ice-caps and glaciers (in contrast to land_ice, which includes all components).

I would have thought if we needed both of these, the two descriptions would have been reversed (i.e., `land_ice`, not `ice_sheet` would exclude ice-caps and glaciers.

Can someone explain why the terminology is appropriate?

**Comment by JonathanGregory** [comment]
The area type table is consistent with the use of these words in IPCC and Earth system modelling, I would say. "Land ice" is the general term for ice which is made from snowfall on land (including on land ice), distinguishing it from "sea ice", which is made of frozen seawater and snowfall on sea ice. The distinction between the types of land ice body (ice sheet, icecap and glacier) is a bit vague and is essentially to do with size. A glacier is comparatively small and mostly confined by bedrock topography, whose form strongly affects its surface topography. An ice sheet is so large that it buries the bedrock topography, and its surface topography is mostly determined by surface mass balance and ice dynamics. An icecap is something intermediate in size. There are only two ice sheets in the modern world viz on Greenland and on Antarctica (where East and West are sometimes regarded as distinct) but there are at least 200e3 glaciers.

**Comment by JonathanGregory** [comment]
Ah, I see. Yes, "ice cap" is sometimes used to mean polar sea ice, isn't it. "Ice sheet" includes both grounded ice and ice shelves, as the current text correctly says. People often write phrases like "grounded ice sheet" when they want to clarify that ice shelves should be excluded.

**Comment by taylor13** [comment]
Yes, I know Ice_sheet includes both grounded ice and ice shelves, but it doesn't say it only includes the ice shelves connected to the ice sheet.  I misinterpreted the description as including both ice shelves attached to the ice_sheet and also ice shelves attached to any other land ice (e.g., attached to glaciers).  I think the ice shelves attached to glaciers should be explicitly excluded.  The current description is:

`ice_sheet`: An area type of "ice sheet" indicates where ice sheets are present. It includes both grounded ice sheets resting over bedrock and ice shelves flowing over the ocean, but excludes ice-caps and glaciers (in contrast to land_ice, which includes all components).

Could we revise this to:

`ice_sheet`: An area type of "ice sheet" indicates where ice sheets are present. It includes both grounded ice sheets resting over bedrock and any ice shelves flowing over the ocean that are attached to it, but it excludes ice-caps and glaciers (in contrast to land_ice, which includes all components).

I suppose most would not have misinterpreted what we currently have, but I, for one, did.

**Comment by JonathanGregory** [comment]
Dear Karl

Ah, thanks, I see what you mean now. Yes, I agree, that would be useful to clarify. Maybe to be even more explicit we could say "but it excludes ice-caps and glaciers and any floating ice shelves and ice tongues attached to them".

Best wishes

Jonathan

**Comment by taylor13** [comment]
I would be happy with that.  Thanks.

**Comment by JonathanGregory** [comment]
Dear Alison @japamment et al.

As discussed in this issue, Karl and I propose that the definition for the `ice_sheet` area type should be clarified, to read

> An area type of "ice sheet" indicates where ice sheets are present. It includes both grounded ice sheets resting over bedrock and any ice shelves flowing over the ocean that are attached to grounded ice sheets. The `ice_sheet` area excludes ice-caps and glaciers and any floating ice shelves and ice tongues attached to them, but the `land_ice` area includes those as well the `ice_sheet` area.

Here, I've rephrased the last part, hoping to make it even clearer.

Best wishes

Jonathan

**Comment by taylor13** [comment]
Seems clear to me now.  Thanks, Jonathan and Alison.

**Comment by JonathanGregory** [comment]
Thanks for raising the issue, Karl.

**Comment by feggleton** [comment]
That clarification seems sensible. Thanks.

**Comment by japamment** [comment]
@taylor13 @JonathanGregory

Thanks for clarifying the ice_sheet area type definition - anything we can do to make meanings clear and unambiguous is always an improvement!

I will make this change in the area type table update this week.

Best wishes

Alison
