### ISSUE TITLE
Mercator projection: rotated vs. transverse

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/discuss#189]
In Appendix F: Grid Mapping on [Oblique Mercator](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_oblique_mercator) the *Notes* states that 

> The Rotated Mercator projection is an Oblique Mercator projection with azimuth = +90.

However, I think that the generally established name for a Mercator projection with azimuth = +90 is `Transverse Mercator`.  At least this is what is used by [Wikipedia](https://en.wikipedia.org/wiki/Mercator_projection), in the [proj  software](https://proj.org/), and in [Snyder](https://pubs.er.usgs.gov/publication/pp1395). Also searching the [epsg database](https://epsg.io) did not return anything for "rotated mercator", but several items were returned both for "mercator" and for "transverse mercator".

When searching the web for "rotated mercator" one of the few (the only) relevant results leads to the [Arpege/Aladin/Arome doumentation](https://www.umr-cnrm.fr/gmapdoc/spip.php?article53), referring a pdf document, which (if I understand correctly) equates the "Rotated/Tilted Mercator" to the oblique Mercator projection.

**Comment by zklaus** [comment]
One place where this surfaced for us was in CORDEX data, where some models put `rotated_mercator` as grid mapping name. Cf SciTools/iris#4830.

**Comment by larsbarring** [comment]
ping @gnikulin

**Comment by larsbarring** [comment]
After having mulled a bit more over this, and looked at the issue that @zklaus links to, and also looked at what WMO does for GriB:

The data dataset used as example in [SciTools/iris/issues/4830](https://github.com/SciTools/iris/issues/4830) includes the following
> crs:grid_mapping_name = "rotated_mercator" ;
   crs:latitude_of_projection_origin = -22. ;
   crs:longitude_of_projection_origin = -59. ;

where the first line specifies a grid mapping name that is not recognised as such by CF. And from the next two lines we can conclude that is in fact an oblique Mercator projection. 

The [WMO Manual on Codes 2019 (2019 edition, updated in 2022)](https://library.wmo.int/?lvl=notice_display&id=10684#.Y1_rXkjMJZI) includes both "Grid definition template 3.10 – Mercator" and "Grid definition template 3.12 – transverse Mercator". And it seems (not sure though) that the former actually includes the possibility to cater for the oblique Mercator version by specifying the "Orientation of the grid, angle between i direction on the map and the Equator". 

Thus I conclude that sentence cited in the first comment is misleading and should be deleted. As deleting this sentence does not change the Conventions I relabel this as a defect.

**Comment by JonathanGregory** [comment]
Fine, thanks @larsbarring

**Comment by zklaus** [comment]
For the benefit of those that refer to their own grid as a rotated Mercator, I suggest instead replacing that sentence with something along the lines of:
> Rotated Mercator is not recognized as an independent grid mapping. In its place, use the oblique Mercator grid mapping with appropriate parameters, usually `azimuth_of_central_line = 90`.

**Comment by larsbarring** [comment]
This issue has now been open for 115 days, and generated very little discussion. Could it now be closed in favour for the suggested change in PR #189?

**Comment by JonathanGregory** [comment]
Yes, I agree, this change should be made, to rectify the defect. If we wish to insert suggestions of alternatives, as mentioned by @zklaus, that could be done as a separate enhancement.

Even correction of defects should be mentioned in `history.adoc`. Please could include this in your [PR](https://github.com/cf-convention/cf-conventions/pull/408), @larsbarring? I'll merge it once that's done. Many thanks.

**Comment by larsbarring** [comment]
Dear Jonathan,

The history.adoc is now updated. Thank you for offering to do this. As a github newbie (and especially in relation to the CF repo) I would not want to do this myself.

**Comment by JonathanGregory** [comment]
Thanks, Lars. I have merged it. I think it's good practice for someone else to merge one's PR anyway, so that another person has looked at it. I'm closing the issue.
