### ISSUE TITLE
How to include a palette (color table) with mapped data?

### ISSUE THREAD

**Issue by gfireman** [cf-convention/discuss#191]
[We](https://oceancolor.gsfc.nasa.gov/) like to provide a suggested color table for use with mapped data, as a simple RGB byte array.  We've traditionally provided it without attributes (as below), which causes compliance checkers to report an error.  Is there a CF-compliant way to  specify a color table?

```
dimensions:
        lat = 2160 ;
        lon = 4320 ;
        rgb = 3 ;
        eightbitcolor = 256 ;
variables:
        short aot_869(lat, lon) ;
                aot_869:long_name = "Aerosol optical thickness at 869 nm" ;
                aot_869:scale_factor = 0.0001f ;
                aot_869:add_offset = 0.f ;
                aot_869:standard_name = "atmosphere_optical_thickness_due_to_ambient_aerosol" ;
                aot_869:_FillValue = -32767s ;
                aot_869:valid_min = 0s ;
                aot_869:valid_max = 30000s ;
                aot_869:display_scale = "linear" ;
                aot_869:display_min = 0.f ;
                aot_869:display_max = 0.25f ;
        float lat(lat) ;
                lat:long_name = "Latitude" ;
                lat:units = "degrees_north" ;
                lat:standard_name = "latitude" ;
                lat:_FillValue = -999.f ;
                lat:valid_min = -90.f ;
                lat:valid_max = 90.f ;
        float lon(lon) ;
                lon:long_name = "Longitude" ;
                lon:units = "degrees_east" ;
                lon:standard_name = "longitude" ;
                lon:_FillValue = -999.f ;
                lon:valid_min = -180.f ;
                lon:valid_max = 180.f ;
        ubyte palette(rgb, eightbitcolor) ;

// global attributes:
                :product_name = "AQUA_MODIS.20221110.L3m.DAY.RRS.aot_869.9km.NRT.nc" ;
```
etc.

**Comment by gfireman** [comment]
Thanks for the suggestion.  Providing long_name helps!
```
	ubyte palette(rgb, eightbitcolor) ;
		palette:long_name = "Recommended color table: viridian" ;
		palette:units = "1" ;
                palette:valid_min = 0UB ;
                palette:valid_max = 255UB ;
```
Checking against with [IOOS Compliance Checker](https://compliance.ioos.us/index.html) reported missing units as an error.  Also reports as an error:
§2.2 Data Types	The variable palette failed because the datatype is uint8
It seems to want char or string?

Adding valid_min and valid_max makes no difference, but seems to be a good idea.

[cf-checker](https://github.com/cedadev/cf-checker) does not complain about ubyte, and reports missing units as an info item only.

The latest available standard for both compliance checkers is CF-1.8.
_Neither_ seems to check variables inside a group.
Oh, how I wish the cf-conventions team would provide a checker, updated for each version!

**Comment by JonathanGregory** [comment]
Dear @gfireman

The cf-checker is correct: `units` is optional for dimensionless quantities in CF, and `unsigned byte` is OK for data variables (listed in CF section 2.2).

I'm sure that work is being done on a version of the cf-checker for versions after 1.8. The intention is to provide it for every version, just as you would like! When things are slow in CF development, it's because CF is mostly a community project. The "team" is mostly "spare time"; no-one is employed to work on it full-time.

Best wishes

Jonathan

**Comment by gfireman** [comment]
Thank you all for the hard work!
