### ISSUE TITLE
New area type proposed: "air"

### ISSUE THREAD

**Issue by taylor13** [cf-convention/discuss#193]
Proposer's name Karl Taylor
Date 21 November 2022

This is a proposed addition to the "area types" table.

- Term: air
- Description: This area type distinguishes the atmospheric portion of a domain from the land portion (or any other non-air portion).  It is needed when a variable like wind speed is reported, for example, on a surface at mean sea level pressure.  At most locations over land, this surface would be underground and would need to be excluded from consideration, which could be indicated by specifying in a cell_methods "where air".   
- Units: "area types" do not have associated units.

Justification: The justification is provided by the example given in the description.  There are times when atmospheric variables are reported on standard pressure surface extending from sea level to high levels in the atmosphere.  Some of those pressure levels are underground and it important to indicate that the variable has not been extrapolated underground but only reported "where air".  This requires definition of an area type named "air" or something equivalent.  It should be viewed as comparable to "sea", which can be used in reporting ocean properties.

**Comment by davidhassell** [comment]
Thanks, Karl - sounds very reasonable to me.

**Comment by JonathanGregory** [comment]
I agree too, Karl.

**Comment by feggleton** [comment]
Looks like there is a need for this and agreement. Happy for this area type to be approved and added to the next update of the Area Type Table.

**Comment by japamment** [comment]
@taylor13 @JonathanGregory @feggleton

I agree this proposal looks fine and there have been no objections. I am currently preparing an update of the standard name table and will also update the area type table this week.

This term will be added to the area type table.

Best wishes
Alison

**Comment by japamment** [comment]
I am closing this issue as the proposed change has been published in V11 of the area type table.
