### ISSUE TITLE
Standard names: Third Batch - 16 variables from the Hawaii Ocean Time-series (HOT) + CLIVAR and Carbon Hydrographic Data Office (CCHDO)

### ISSUE THREAD

**Issue by fcarvalhopacheco** [cf-convention/discuss#197]
**Proposer's name:**
- Fernando Carvalho Pacheco (fernando.pacheco@hawaii.edu)
- Fernando Santiago-Mandujano (santiago@hawaii.edu)
- Karin Bjorkman (bjorkman@hawaii.edu) 
- Andrew Barna (abarna@ucsd.edu; @DocOtak )

**Possible Reviewers & Contributors:** 
- Roy K. Lowry (rkl@bodc.ac.uk; @roy-lowry)
- @JonathanGregory 
- @ngalbraith 

**Date: 2022-12-15**

**Notes:** The following are 16 proposed names and descriptions of some of the biogeochemical variables reported by the [Hawaii Ocean Time-Series (HOT)](https://hahana.soest.hawaii.edu/hot/) and the [CLIVAR and Carbon Hydrographic Data Office (CCHDO)](https://cchdo.ucsd.edu/). We include generic terminology for similar CF names and a description corresponding to the specific HOT variable, constructed based on definitions from HOT documentation or other sources (e.g., [Natural Environment Research Council Vocabulary Server (NERC)](http://vocab.nerc.ac.uk/search_nvs/). The corresponding reference is also included for each term whenever possible. The current variable names and units used by the HOT program, [Biological and Chemical Oceanography Data Management Office (BCO-DMO / HOT Niskin and Water Bottle Dataset)](https://www.bco-dmo.org/dataset/3773), and CCHDO  can be seen on the following links:

HOT Niskin bottle samples parameters: 
https://hahana.soest.hawaii.edu/FTP/hot/water/Readme.water.jgofs 

HOT Particle Flux parameters:
https://datadocs.bco-dmo.org/docs/302/HOT/data_docs/737393/1/Readme.flux 

BCO-DMO / HOT - Niskin and Water Bottle Dataset:
 https://erddap.bco-dmo.org/erddap/info/bcodmo_dataset_3773/index.html 

BCO-DMO / HOT - Particle Flux information:
https://www.bco-dmo.org/dataset/737393 

CCHDO:
https://exchange-format.readthedocs.io/en/latest/parameters.html#

----------------------------------------------------------------------------------------------------------
## See the other proposals 

-  #124 
-  #135 

----------------------------------------------------------------------------------------------------------
(1)Term: `moles_of_dissolved_organic_phosphorus_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen”. "Organic phosphorus" means phosphorus in carbon compounds. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at http://vocab.nerc.ac.uk/collection/P01/current/ORGPMSZZ/4/.

Units: [mol kg-1]
 
NERC P01 (per unit volume): http://vocab.nerc.ac.uk/collection/P01/current/ORGPDSZZ/4/

----------------------------------------------------------------------------------------------------------

(2)Term: `moles_of_dissolved_organic_nitrogen_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Organic nitrogen" means nitrogen in carbon compounds. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at http://vocab.nerc.ac.uk/collection/P01/current/MDMAP008/3/. 

Units: [mol kg-1]

NERC P01 (per unit volume): http://vocab.nerc.ac.uk/collection/P01/current/MDMAP009/3/

----------------------------------------------------------------------------------------------------------
(3)Term: `moles_of_dissolved_organic_carbon_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". “Organic carbon” means carbon not in carbonate or bicarbonate molecules. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at http://vocab.nerc.ac.uk/collection/P01/current/CORGZZKG/1/.

Units: [mol kg-1]

NERC P01 (per unit volume): http://vocab.nerc.ac.uk/collection/P01/current/CORGZZZX/6/ 

----------------------------------------------------------------------------------------------------------
(4)Term: `moles_of_dissolved_phosphorus_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". “Phosphorus” means phosphorus in all chemical forms, commonly referred to as "total phosphorus". The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at
http://vocab.nerc.ac.uk/collection/P01/current/TPHSDSZZ/6/.

Units: [mol kg-1]
Similar NERC P01: http://vocab.nerc.ac.uk/collection/P01/current/TPHSMSPT/5/

----------------------------------------------------------------------------------------------------------
(5)Term: `moles_of_dissolved_nitrogen_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Nitrogen" means the sum of all nitrogen in solution: inorganic nitrogen (nitrite, nitrate, and ammonium) plus nitrogen in carbon compounds.

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(6)Term: `moles_of_particulate_matter_expressed_as_carbon_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at http://vocab.nerc.ac.uk/collection/P01/current/MDMAP011/4/.

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(7)Term: `moles_of_particulate_matter_expressed_as_nitrogen_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at  
http://vocab.nerc.ac.uk/collection/P01/current/MDMAP013/4/

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(8)Term: `moles_of_particulate_matter_expressed_as_phosphorus_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at http://vocab.nerc.ac.uk/collection/P01/current/TPHSVLPT/5/.

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(9)Term: `moles_of_particulate_organic_matter_expressed_as_carbon_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.

Units: [mol kg-1]
NERC P01 (per unit volume): http://vocab.nerc.ac.uk/collection/P01/current/MDMAP010/5/

----------------------------------------------------------------------------------------------------------
(10)Term: `moles_of_particulate_organic_matter_expressed_as_nitrogen_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. 

Units: [mol kg-1]

Similar NERC P01: http://vocab.nerc.ac.uk/collection/P01/current/MDMAP008/3/ 
                              : http://vocab.nerc.ac.uk/collection/P01/current/MDMAP010/5/

----------------------------------------------------------------------------------------------------------
(11)Term: `moles_of_particulate_organic_matter_expressed_as_phosphorus_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at  http://vocab.nerc.ac.uk/collection/P01/current/OPHSVLPT/6/.

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(12)Term: `moles_of_adenosine_triphosphate_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at http://vocab.nerc.ac.uk/collection/P01/current/ATPXZZDZ/2/.

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(13)Term: `moles_of_guanosine_triphosphate_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula of guanosine triphosphate is C10H16N5O14P3. 

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(14)Term: `moles_of_sulfur_hexafluoride_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula of sulfur hexafluoride is SF6.

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(15)Term: `moles_of_ammonium_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula of ammonium is NH4. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at
http://vocab.nerc.ac.uk/collection/P01/current/MDMAP004/3/

Units: [mol kg-1]

----------------------------------------------------------------------------------------------------------
(16) Term: `moles_of_alkalinity_per_unit_mass_in_sea_water`

Description: The construction "moles_of_X_per_unit_mass_in_Y" is also called "molality" of X in Y, where X is a material constituent of Y. A chemical species or biological group denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at
http://vocab.nerc.ac.uk/collection/P01/current/MDMAP014/1/

Units: [mol kg-1]

OBS: HOT reports this as microeq/kilogram (ueq/kg). So I believe we can’t use `sea_water_alkalinity_expressed_as_mole_equivalent` (mol m^-3) as a `standard_name`

----------------------------------------------------------------------------------------------------------

**Comment by roy-lowry** [comment]
I have now had a look at this batch of proposals.

Proposals (1)-(6), (10)-(12) and (14)-(15) are simple adaptations of 'mole_concentration' Standard Names in the published list.

Proposal (13) is a simple adaptation of mole_concentration_of_guanosine_triphosphate_in_sea_water. Whilst this isn't in the published Standard Name list it is included in #135 which was flagged 'accepted' on 2/11/2022.

Proposals (7-9) do not have a 'mole_concentration'  equivalent that I have been able to find as yet, although I have forgotten/lost the link to the pending Standing Names (@feggleton @japamment can you refresh my memory?), but they are simple adaptations of other moles_of_X_per_unit_mass_in_sea_water proposals that do have equivalents for other substances.

Consequently, I recommend that proposals (1) to (15) be accepted. I will post my comments on (16) separately.

**Comment by roy-lowry** [comment]
Now for (16)....

Alkalinity is a property of sea water (it's capacity to neutralise acids) rather than a substance whose concentration is the property. Consequently 'moles_of_alkalinity' makes as much sense as 'moles_of_salinity' or 'moles_of_temperature'.

As @fcarvalhopacheco says, the existing Standard Name is a fudge around the problem of alkalinity having units of 'equivalents per quantity of matrix', but it is only valid for equivalents per unit volume, not equivalents per unit mass. So what is needed is a New Standard Name adapted from sea_water_alkalinity_expressed_as_mole_equivalent so that it is appropriate for equivalents per unit mass.

My suggestion would be:

sea_water_alkalinity_per_unit_mass_expressed_as_mole_equivalent

Is the acceptable to all?

**Comment by DocOtak** [comment]
Attn @squaregoldfish for input on Roy's suggestion for alkalinity

**Comment by ngalbraith** [comment]
This is a little outside my area, having less experience with data from water samples than with the process of collecting them. Roy's points seem perfectly clear, though, so I'll gladly defer to him.

**Comment by squaregoldfish** [comment]
Somehow I missed the notification first time round. I'll consult with Siv Lauvset (head of GLODAP) on this. Unfortunately I'm travelling this week, but I'll try to get it done via email.

**Comment by squaregoldfish** [comment]
Siv agrees with with Roy's suggestion, although she acknowledges that she's not specifically an alkalinity expert. She also notes that GLODAP records alkalinity in umol/kg, in case that has any effect on the chosen canonical unit.

(More communication from the wider ocean observation community, i.e. SOCAT/GLODAP/SDG14.3 will be coming in the early part of this year.)

**Comment by roy-lowry** [comment]
Units of umol/kg are totally compatible with the proposed canonical units of mol kg-1 (canonical units describe dimensionality but not scaling).

**Comment by fcarvalhopacheco** [comment]
Updating this issue: 

- [x] terms 1 to 15 seem to be approved. 

- Next: What would be a good description for our new term (16)? here is my first attempt:


(16) Term: `sea_water_alkalinity_per_unit_mass_expressed_as_mole_equivalent`

Description: 'sea_water_alkalinity_per_unit_mass_expressed_as_mole_equivalent' is the total alkalinity equivalent concentration (including carbonate, nitrogen, silicate, and borate components), expressed as the number of moles of alkalinity per unit mass of seawater. The equivalent term in the NERC P01 Parameter Usage Vocabulary may be found at
http://vocab.nerc.ac.uk/collection/P01/current/MDMAP014/1/

Units: [mol kg-1]

**Comment by feggleton** [comment]
Hi @fcarvalhopacheco, thank you for your proposal and thanks to all for discussing. 

I have now added the first 15 terms into the cfeditor and marked as accepted, as there has been discussion and a long period of time without comment. I have added a couple of common phrases to some of the terms so they match other similar terms, where it is relevant. These can be viewed here: https://cfeditor.ceda.ac.uk/proposals/1

I have also added term number 16 to the editor as under discussion. @roy-lowry if you have a chance to review this again, please do. We will keep this issue open until the last term has been accepted and added to the standard name table.

**Comment by roy-lowry** [comment]
I gave Fernando's proposal for term 16 on March 21the 'thumbs up'. I'm still happy with it and there's been no subsequent discussion so I think it can go ahead.

**Comment by japamment** [comment]
Hi @roy-lowry thanks for reviewing proposal 16. I will add that one to the accepted list.

@fcarvalhopacheco I am preparing an update to the standard name table - all the terms in this issue will be included in the next version.

**Comment by japamment** [comment]
I am closing this issue now as all the proposed names have been published in V83 of the standard name table.
