### ISSUE TITLE
New description for equivalent_potential_temperature

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#20]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2019/08/20

The description of equivalent_potential_temperature is misleading because the term "equivalent" is not explained at all. The quantity does not exist for sea water.

**- Term** equivalent_potential_temperature
**- New Definition** "equivalent potential temperature" refers to a thermodynamic quantity, with its natural logarithm proportional to the entropy of moist air, that is conserved in a reversible moist adiabatic process. (AMS-glossary)
**- Units** K

**Comment by japamment** [comment]
Dear Beate and Ronny,

Thank you for raising this issue. I agree that the current definition is unsatisfactory and indeed the quantity does not make sense for sea water, also it is good to reference the AMS glossary. I suggest adding a further explanatory sentence as follows:

'The "equivalent potential temperature" is a thermodynamic quantity, with its natural logarithm proportional to the entropy of moist air, that is conserved in a reversible moist adiabatic process. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Equivalent_potential_temperature.
It is the potential temperature of a parcel of air if all the moisture contained in it were first condensed, releasing latent heat, before moving the parcel dry adiabatically to sea level pressure.'

Is that okay?

Best wishes,
Alison

**Comment by roy-lowry** [comment]
@japamment There is also a Standard Name pseudo_equivalent_potential_temperature with an equally inadequate description. 

Although it is obvious that these parameters are totally inappropriate for water should the Standard Names be 'air_equivalent_potential_temperature' and 'air_pseudo_equivalent_potential_temperature'?

**Comment by GeyerB** [comment]
@japamment We agree to your proposal with a tiny modification, as
```
The equivalent potential temperature is a thermodynamic quantity, with its natural logarithm proportional to the entropy of moist air, that is conserved in a reversible moist adiabatic process. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Equivalent_potential_temperature.
It is the potential temperature of a parcel of air if all the moisture contained in it were first condensed, releasing latent heat, before moving the parcel dry adiabatically to standard pressure (typically mean sea level pressure or 1000 hPa).
To specify the standard pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure. 
```
@roy-lowry We agree to adapt the description for the other variables and opened new issues for them:

**Comment by japamment** [comment]
@GeyerB @roy-lowry many thanks for your comments. I agree with Roy's suggestion to add air_ to clarify the name itself, so I think we are all happy with creating the alias equivalent_potential_temperature -> air_equivalent_potential_temperature.

I agree also with Beate's modification to the definition. Having reread the AMS glossary definition I realised that, as with air_potential_temperature, this quantity should allow for a coordinate variable containing the reference pressure to which the parcel is moved. Hence the definition of the name should be:
'The "equivalent potential temperature" is a thermodynamic quantity, with its natural logarithm proportional to the entropy of moist air, that is conserved in a reversible moist adiabatic process. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Equivalent_potential_temperature. It is the temperature of a parcel of air if all the moisture contained in it were first condensed, releasing latent heat, before moving the parcel dry adiabatically to a standard pressure, typically representative of mean sea level pressure. To specify the standard pressure to which the quantity applies, provide a scalar coordinate variable with standard name reference_pressure.'

If you are happy with this then I think the name is ready to be accepted for publication.

Best wishes,
Alison

**Comment by GeyerB** [comment]
This is fine with us, thanks for the work,
Beate

**Comment by japamment** [comment]
@GeyerB many thanks. This name is accepted for publication in the standard name table and will be added in the 9th March update.

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table.
