### ISSUE TITLE
Why not pack data into unsigned int types?

### ISSUE THREAD

**Issue by gfireman** [cf-convention/discuss#202]
[Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#packed-data) say:

> ...the variable containing the packed data must be of type byte , short or int .

Why not ubyte, ushort, or uint?

We typically pack data into unsigned int types.
To be CF compliant we'd have to change types - and then adjust scale_factor and add_offset to recover the range lost to a sign bit.

**Comment by cofinoa** [comment]
When the CF convention was written, the netCDF format only supported signed types. This restriction on data model support, it's named netCDF `classic model` in the current netCDF data model:
https://docs.unidata.ucar.edu/netcdf-c/current/netcdf_data_model.html#classic_model

Probably, support for new types could be proposed as an enhancement. 

P.S.: This out of scope for the CF Convention, but if you are using writing packed data to encode new data, you can apply netCDF4 chunking feature, apply shaving to non-significant bits on the float number, and add the deflate filter, honouring *classic data model* and CF, without the use of CF packed data feature and using float/double original type.

**Comment by gfireman** [comment]
The CF convention _does_ allow for unsigned integer types, just not for packing data into.
Interesting suggestion on using compression instead of scaling.  We'll run some tests and see how that works for us.
Thanks!

**Comment by cofinoa** [comment]
yes, you are right!! The restriction on classic data model was removed on CF-1.9, allowing, among others, some data types from the enhanced data model. The Packed Data sections wasn't updated following that.

**Comment by JonathanGregory** [comment]
Yes, I think this question is now answered.

**Comment by JonathanGregory** [comment]
Dear Gwyn @gfireman 

I'm closing this issue now, because it's been addressed by a recent update to the working version of the convention (that will be released in a month or so). Please see the [updated section 8.1](http://cfconventions.org/cf-conventions/cf-conventions.html#packed-data). Thanks for asking the question. If it's not completely answered, please feel free to reopen this issue.

Cheers

Jonathan
