### ISSUE TITLE
 Standard names: land_ice_mass_not_displacing_sea_water

### ISSUE THREAD

**Issue by taylor13** [cf-convention/discuss#208]
I'm not sure the description is correct for land_ice_mass_not_displacing_sea_water.  It says ""Land ice not displacing sea water" means land ice that would not alter sea level if the ice were converted to water and added to the ocean."  From the rest of the description, I think the "not" should be removed so that the description reads ""Land ice not displacing sea water" means land ice that would alter sea level if the ice were converted to water and added to the ocean."

**Comment by efisher008** [comment]
Hi @taylor13,

This is not particularly my area of expertise, but I wonder if 
Aurore Biardeau @abiardeau (from Copernicus Marine Service/Mercator Ocean) might like to contribute to this discussion, as it seems she has previously proposed standard names relating to sea ice which could be of relevance at the terrestrial-marine boundary. Any other comments from @JonathanGregory or @davidhassell would also be welcome.

Best regards,
Ellie

**Comment by efisher008** [comment]
Dear @JonathanGregory and @taylor13,

That's great, thank you for clarifying. I will change the description to ""Land ice not displacing sea water" means land ice that would not alter sea level if the ice were converted to water and added to the ocean. "Land ice not displacing sea water" is sometimes referred to as "ice above flotation" or "ice above floatation"."

Best regards,
Ellie

**Comment by efisher008** [comment]
This issue has been closed as the above names were published in version 84 of the standard names table (visible [here](https://cfconventions.org/Data/cf-standard-names/84/build/cf-standard-name-table.html)).
