### ISSUE TITLE
Standard names: specific_enthalpy_of_air

### ISSUE THREAD

**Issue by oceannetworkscanada2** [cf-convention/discuss#210]
Ocean Networks Canada deploys Lufft SF501 weather stations at many locations on the west coast of British Columbia. One of the outputs from these types of instruments is specific enthalpy described as in the manual: 

Parameter of state of the humid air, composed of the specific enthalpies (heat capacity) of
the components of the mixture and related to the mass fraction of the dry air (at 0°C).

Would like to request a term for specific_enthalpy. Is there a need for this term? Is it possible to get it added to the CF Standard Name vocabulary?

**Comment by feggleton** [comment]
@ChantelRidsdale I have actually just transferred this to the correct repo for you so we don't lose the history, I hope this is useful.

**Comment by ChantelRidsdale** [comment]
@feggleton thank you for transferring, much appreciated. I'm wondering if the suggestion above from @taylor13 for the term to read specific_enthalpy_of_air might be considered? It doesn't seem that I can edit the title. 

So to be clear, we are suggesting:

Term: specific_enthalpy_of_air

Description: the enthalpy of air per unit mass, which can be computed for an air sample as the sum of the enthalpy of the dry air and the enthalpy of the water water vapor in that air, divided by the mass of dry air.

Units: kJ/kg

**Comment by feggleton** [comment]
Thanks @ChantelRidsdale I have now added this to the cfeditor and added the most recent definition https://cfeditor.ceda.ac.uk/proposal/4849. If there are no further comments in the next 7 days then this can be accepted.

**Comment by japamment** [comment]
@ChantelRidsdale @feggleton 

The name in this issue issue will be included in V82 of the standard name table, currently in preparation.

Best wishes

Alison

**Comment by japamment** [comment]
I am closing this issue as the name has been published in V82 of the standard name table.

**Comment by ChantelRidsdale** [comment]
Thank you for helping me push this to the finish line!
