### ISSUE TITLE
 Standard names: *Turbulent kinetic energy (atmosphere)*

### ISSUE THREAD

**Issue by sol1105** [cf-convention/discuss#214]
TKE (turbulent kinetic energy) is part of the [COSMO model](http://www.cosmo-model.org/) output, and yet lacking a specific standard name.

**Proposer's name**: Martin Schupfner

**Date**: March 08, 2023

**- Term**: ~~specific_turbulent_kinetic_energy_of_atmosphere_layer~~ `specific_turbulent_kinetic_energy_of_air`

**- Description**:
Specific means per unit mass. "Turbulent kinetic energy" is the kinetic energy of chaotic fluctuations of the fluid flow. ~~"Layer" means any layer with upper and lower boundaries that have constant values in some vertical coordinate. There must be a vertical coordinate variable indicating the extent of the layer(s). If the layers are model layers, the vertical coordinate can be model_level_number, but it is recommended to specify a physical coordinate (in a scalar or auxiliary coordinate variable) as well.~~

**- Units**: m2 s-2

**- Comment**: I used the expression “chaotic fluctuations of the fluid flow” from the sea water example below. If "fluid flow" is too general, maybe one could substitute it by “air flow”.

**- Related terms**:

**atmosphere_kinetic_energy_content**  [J m-2]
Content indicates a quantity per unit area. The "atmosphere content" of a quantity refers to the vertical integral from the surface to the top of the atmosphere. For the content between specified levels in the atmosphere, standard names including content_of_atmosphere_layer are used.

**specific_turbulent_kinetic_energy_of_sea_water** [m2 s-2]
Specific means per unit mass. "Turbulent kinetic energy" is the kinetic energy of chaotic fluctuations of the fluid flow.

**kinetic_energy_content_of_atmosphere_layer** [J m-2]
Content indicates a quantity per unit area. "Layer" means any layer with upper and lower boundaries that have constant values in some vertical coordinate. There must be a vertical coordinate variable indicating the extent of the layer(s). If the layers are model layers, the vertical coordinate can be model_level_number, but it is recommended to specify a physical coordinate (in a scalar or auxiliary coordinate variable) as well.

**specific_kinetic_energy_of_air** [m2 s-2]
"specific" means per unit mass.

**Comment by jeremygibbs** [comment]
I politely and pedantically suggest that "turbulence kinetic energy" is the more appropriate term. I believe "turbulent kinetic energy" seemingly denotes some kinetic energy that is itself turbulent, while "turbulence kinetic energy" makes it clear that one is describing the kinetic energy associated with turbulence.

While both have been used interchangeably in the literature, I think "turbulence kinetic energy" should be the preferred standard name. Many canonical authors / sources in the atmospheric sciences use this version. See, e.g., 

- American Meteorological Society's ["Glossary of Meteorology"](https://glossary.ametsoc.org/wiki/Turbulence_kinetic_energy).
- Stull, R.B. (1988). Some Mathematical & Conceptual Tools: Part 1. Statistics. In: Stull, R.B. (eds) An Introduction to Boundary Layer Meteorology (p. 45). Atmospheric Sciences Library, vol 13. Springer, Dordrecht. [https://doi.org/10.1007/978-94-009-3027-8_2](https://doi.org/10.1007/978-94-009-3027-8_2)
- Wyngaard, J. (2010). Conservation equations for covariances. In _Turbulence in the Atmosphere_ (p. 101). Cambridge: Cambridge University Press. [doi:10.1017/CBO9780511840524.006](https://doi.org/10.1017/CBO9780511840524.006)
- Deardorff, J. (1970). A numerical study of three-dimensional turbulent channel flow at large Reynolds numbers. Journal of Fluid Mechanics, 41(2), 453-480. [doi:10.1017/S0022112070000691](https://doi.org/10.1017/S0022112070000691)
- Golitsyn, G.S. (1998). Convection in Viscous and Rotating Fluids from the Viewpoint of the Forced Flow Theory. In: Plate, E.J., Fedorovich, E.E., Viegas, D.X., Wyngaard, J.C. (eds) Buoyant Convection in Geophysical Flows. NATO ASI Series, vol 513. Springer, Dordrecht. [https://doi.org/10.1007/978-94-011-5058-3_6](https://doi.org/10.1007/978-94-011-5058-3_6)
- It is also defined this way on [Wikipedia](https://en.wikipedia.org/wiki/Turbulence_kinetic_energy) and [CFD Online](https://www.cfd-online.com/Wiki/Introduction_to_turbulence/Turbulence_kinetic_energy).

**Comment by JonathanGregory** [comment]
Dear Martin @sol1105 

Thanks for your proposal. I think there are two possible quantities you might want to name - both of them sensible - and I am not sure which you intend. Do you mean `turbulent_kinetic_energy_content_of_atmosphere_layer` in J m-2 = kg s-2, which depends on the vertical extent of the layer, or is it `specific_turbulent_kinetic_energy_of_air` in J kg-1 = m2 s-2, which is an intensive property?

Dear @jeremygibbs 

If `turbulence` is agreed for the new standard name, for consistency it would require changing the existing names `specific_turbulent_kinetic_energy_dissipation_in_sea_water` and `specific_turbulent_kinetic_energy_of_sea_water`, and perhaps `turbulent_mixing_length_of_sea_water`. This could be done, with aliases, if we agree it is useful to make that change.  Thanks for raising this point.

Best wishes

Jonathan

**Comment by sol1105** [comment]
@JonathanGregory Thank you for your reply. The model variable is provided on model layers and in units [m2 s-2] . `specific_turbulent_kinetic_energy_of_air` would also be fine if something speaks against `specific_turbulent_kinetic_energy_of_atmosphere_layer`.

@jeremygibbs Thank you for commenting. I do not oppose the change to `specific_turbulence_kinetic_energy_of_atmosphere_layer/of_air`, but I cannot take part in the discussion whether it is useful to change existing standard_names or not.

**Comment by JonathanGregory** [comment]
Dear Martin @sol1105 

If it's in m2 s-2 = J kg-1 then `specific_turbulent_kinetic_energy_of_air` would be right. The model layers have boundaries in some coordinate, presumably, and this is an intensive property which is representative of the air in the layer - right? It's the same kind of property as `air_temperature`, for instance. In a model, `air_temperature` is likewise provided on model layers, but that isn't relevant to the definition of the quantity itself.

If you multiply `specific_turbulent_kinetic_energy_of_air` by `air_density` you get a quantity in m2 s-2 kg m-3 = J m-3. This quantity doesn't have a standard name at present. It would be the concentration of turbulent KE. If you calculate the vertical integral of that within the model layer, you get something in J m-2. That would be probably be given the standard name `turbulent_kinetic_energy_content_of_atmosphere_layer`. We already have a similar quantity in the standard name table without `turbulent_`.

Best wishes

Jonathan

**Comment by sol1105** [comment]
@JonathanGregory Thank you, I adjusted the term and description:

**- Term**: `specific_turbulent_kinetic_energy_of_air`

**- Description**:
Specific means per unit mass. "Turbulent kinetic energy" is the kinetic energy of chaotic fluctuations of the fluid flow.

**- Units**: m2 s-2

**Comment by JonathanGregory** [comment]
Thanks, @sol1105. This looks fine to me - clear and simple, following previous patterns. If no-one expresses concerns in the next week or two it should be accepted for inclusion in the standard name table. @jeremygibbs, I suggest that question of whether "turbulent" should be "turbulence", which doesn't affect only this name, should be regarded as a different issue; please raise one if you would like. Thanks,  both.

**Comment by feggleton** [comment]
Thanks for this proposal and discussion. I have added this to the editor, apologies for the delay. 

The standard phrase for Turbulent kinetic energy is '"Turbulent kinetic energy" is the kinetic energy of all eddy-induced motion that is not resolved on the grid scale of the model.' @sol1105 Are you ok if I change this in the description?

**Comment by sol1105** [comment]
@feggleton Thank you for your reply. After the initial comments, the standard_name term is an adjustment of **specific_turbulent_kinetic_energy_of_sea_water**. And the description is that of said term (`Specific means per unit mass. "Turbulent kinetic energy" is the kinetic energy of chaotic fluctuations of the fluid flow.`). I consulted the modelers if they agree with `'"Turbulent kinetic energy" is the kinetic energy of all eddy-induced motion that is not resolved on the grid scale of the model` and will get back to you with their reply.

**Comment by sol1105** [comment]
@feggleton I received the feedback from the modelers, the new description fits perfectly, thank you.

**Comment by japamment** [comment]
@sol1105 @feggleton 

The name proposed and agreed in this issue will be included in V82 of the standard name table, currently in preparation.

Best wishes

Alison

**Comment by sol1105** [comment]
@japamment That's great news, thank you :+1:

**Comment by japamment** [comment]
I am closing this issue as the name has been published in V82 of the standard name table.
