### ISSUE TITLE
 Standard names: *Gust winds due to turbulence / convection*

### ISSUE THREAD

**Issue by sol1105** [cf-convention/discuss#215]
V_GUST_DYN and V_GUST_CON (gust winds due to turbulence and convection) are part of the [COSMO model](http://www.cosmo-model.org/) output, and yet lacking specific standard names.

**Proposer's name**: Martin Schupfner

**Date**: March 08, 2023

------

**- Term**: wind_speed_of_gust_due_to_turbulence

**- Description**:
Speed is the magnitude of velocity. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) The wind speed is the magnitude of the wind velocity. A gust is a sudden brief period of high wind speed. In an observed timeseries of wind speed, the gust wind speed can be indicated by a cell_methods of maximum for the time-interval. In an atmospheric model which has a parametrised calculation of gustiness, the gust wind speed may be separately diagnosed from the wind speed. The specification of a physical process by the phrase due_to_process means that the quantity named is a single term in a list of terms, the maximum of which composes the general quantity named by omitting the phrase.

**- Units**: m s-1

------

**- Term**: wind_speed_of_gust_due_to_convection

**- Description**:
Speed is the magnitude of velocity. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) The wind speed is the magnitude of the wind velocity. A gust is a sudden brief period of high wind speed. In an observed timeseries of wind speed, the gust wind speed can be indicated by a cell_methods of maximum for the time-interval. In an atmospheric model which has a parametrised calculation of gustiness, the gust wind speed may be separately diagnosed from the wind speed. The specification of a physical process by the phrase due_to_process means that the quantity named is a single term in a list of terms, the maximum of which composes the general quantity named by omitting the phrase.

**- Units**: m s-1

------

**- Comment**: I extended the description of the already registered standard_name "wind_speed_of_gust" (see below) by an alteration of the common "due_to_process" phrase. The problem is, that the gust winds are associated with a maximum for a time-interval. So in this case, not the sum of both terms but the maximum of both terms composes the general quantity "wind_speed_of_gust". Hence the alteration of the "due_to"-phrase. 

**- Related terms**:

**wind_speed_of_gust**
Speed is the magnitude of velocity. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) The wind speed is the magnitude of the wind velocity. A gust is a sudden brief period of high wind speed. In an observed timeseries of wind speed, the gust wind speed can be indicated by a cell_methods of maximum for the time-interval. In an atmospheric model which has a parametrised calculation of gustiness, the gust wind speed may be separately diagnosed from the wind speed.

**tendency_of_air_temperature_due_to_convection**
Air temperature is the bulk temperature of the air, not the surface (skin) temperature. The specification of a physical process by the phrase due_to_process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "tendency_of_X" means derivative of X with respect to time.

**tendency_of_air_temperature_due_to_turbulence**
The specification of a physical process by the phrase due_to_process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "tendency_of_X" means derivative of X with respect to time. Air temperature is the bulk temperature of the air, not the surface (skin) temperature.

**Comment by JonathanGregory** [comment]
Dear Martin @sol1105 

These proposals look good to me.

Thanks

Jonathan

**Comment by feggleton** [comment]
Thank you for these terms. I have now added these to the cfeditor (https://cfeditor.ceda.ac.uk/proposals/1). They follow the correct phrases in the description so thanks for taking the time to construct them. These look good to me. We can allow 7 days for others comment, otherwise these can be accepted.

**Comment by japamment** [comment]
@sol1105 @feggleton

The names proposed and agreed in this issue will be included in V82 of the standard name table, currently in preparation.

Best wishes

Alison

**Comment by sol1105** [comment]
@japamment That's great news, thank you :+1:
