### ISSUE TITLE
Adding the CF Attributes to the NVS

### ISSUE THREAD

**Issue by feggleton** [cf-convention/discuss#217]
Hi everyone, I spoke to a couple of people at the last CF annual workshop about adding the CF Attribute Names to the NERC Vocab Server and I had good support to do so.

A new NVS collection has been created here: http://vocab.nerc.ac.uk/collection/P31/current/

I will initially be adding the 52 attribute terms from the CF Conventions document, Appendix A, table of Attributes. This controlled vocabulary is set up very similar to the standard names collection. I will maintain this collection should new attributes be added. Any comments or questions, please add below.

Thanks, Fran

**Comment by larsbarring** [comment]
Would it be relevant to provide this link in Appendix A.

**Comment by feggleton** [comment]
Possibly.. do we link to the NERC Vocab Server when we discuss Standard Names in the conventions document?

**Comment by larsbarring** [comment]
I had the same thought as you; if we add this link to Appendix A, we should do the same for standard names which would be http://vocab.nerc.ac.uk/collection/P07/current/. And I think the right place to do this would be in the standard name table (which is what actually is in NVS) as well as in Section 3.3. 

Or, we do not add links in the Conventions document, but in the web site [Vocabularies](https://cfconventions.org/vocabularies.html) page, where a new section would then be needed for the Attributes.

**Comment by larsbarring** [comment]
.... or maybe we should not given the discussion in #51 (which I just rigth now came across) ....

**Comment by davidhassell** [comment]
Hi, I think that making these connections on the website is better, and a good connection to make. The fact that these attributes are duplicated elsewhere doesn't really feel like part of the actual conventions themselves.
