### ISSUE TITLE
Trialling GitHub Actions

### ISSUE THREAD

**Issue by feggleton** [cf-convention/discuss#219]
I have done some work to add a bit of automation into the standard name process using GitHub Actions. I have currently added the following actions:

-When a new issue is added with the label 'standard name', a comment will be added to explain a little bit about the next steps and link to the cfeditor where name requests are added. 
-When an issue with the label 'standard name' has not been commented on or seen activity for 30 days , a label will be added of 'moderator attention' and a comment will be added to encourage discussion whilst notifying standard name managers so they can also comment.

This will be a bit of a trial to see how this goes and if it works for the community. Hopefully it should be useful in maintaining the standard name table and we can look to add more later if necessary.

**Comment by JonathanGregory** [comment]
Dear Fran @feggleton 

Thanks for designing and implementing this. I expect it will indeed help.

Best wishes

Jonathan
