### ISSUE TITLE
2023 CF Workshop (virtual) - forming an organizing committee

### ISSUE THREAD

**Issue by ethanrd** [cf-convention/discuss#220]
Hi all,

It is time to start planning for the 2023 CF Workshop, a virtual event this year. The first task is to put together an organizing committee. If you are interested in helping plan and organize the 2023 CF Workshop, please reach out to me by email (edavis at ucar . edu). We will hold an initial meeting of the committee in the next few weeks to kick off our planning efforts.

The work of the committee will likely be conducted mainly during hour long virtual meetings every 2-3 weeks with a few wrap up meetings after the workshop.

Cheers,

Ethan

**Comment by JonathanGregory** [comment]
closed as implemented
