### ISSUE TITLE
Values for variable sector

### ISSUE THREAD

**Issue by MargaridaS** [cf-convention/discuss#227]
Dear CF Team,
I contact you to ask about the values of the variable "sector". I have some files with the values:
"Global Ocean - Marginal Seas",  "Atlantic Ocean + Mediterranean Sea + Labrador Sea + GIN Sea + Arctic Ocean + Hudson Bay" 

Are these values equivalent to "global_ocean", "atlantic_arctic_ocean"? If not, what values should we assign?

Thank you very much in advance.
Best regards,
MargaridaS

**Comment by JonathanGregory** [comment]
Dear @MargaridaS 

CF doesn't standardise the names of netCDF variables, and `sector` isn't a CF standard name. Does your variable have an attribute `standard_name="region"`? The strings `global_ocean` and `atlantic_arctic_ocean` are permissible names of regions. As far as I can see, we don't have region names for the ones you mention. The first one could be called `global_ocean_excluding_marginal_seas`, but we would need to list the marginal seas, to be clear. Which marginal seas are excluded in your case? I don't know how to describe your second one. What is the defining characteristic of that set of sea areas?

Best wishes

Jonathan

**Comment by MargaridaS** [comment]
Dear @JonathanGregory 

Thank you very much for your prompt reply. Yes, the variable sector has the standard_name attribute region:
```
ncdump -h msftmz_Omon_CESM1-CAM5-SE-HR_hist-1950_r1i1p1f1_gn_199209.nc
netcdf msftmz_Omon_CESM1-CAM5-SE-HR_hist-1950_r1i1p1f1_gn_199209 {
dimensions:
	time = UNLIMITED ; // (1 currently)
	basin = 2 ;
	lev = 63 ;
	lat = 395 ;
	strlen = 256 ;
variables:
	float msftmz(time, basin, lev, lat) ;
		msftmz:_FillValue = 9.96921e+36f ;
		msftmz:long_name = "Meridional Overturning Circulation" ;
		msftmz:units = "kg s-1" ;
		msftmz:cell_methods = "time: mean" ;
		msftmz:coordinates = "sector" ;
	float lev(lev) ;
		lev:positive = "down" ;
		lev:units = "m" ;
		lev:long_name = "ocean depth coordinate" ;
		lev:standard_name = "depth" ;
		lev:axis = "Z" ;
	float lat(lat) ;
		lat:long_name = "latitude grid for transport diagnostics" ;
		lat:units = "degrees_north" ;
		lat:valid_min = -79.48815f ;
		lat:valid_max = 90.f ;
	double time(time) ;
		time:long_name = "time" ;
		time:units = "days since 0000-01-01 00:00:00" ;
		time:bounds = "time_bound" ;
		time:calendar = "365_day" ;
	char sector(basin, strlen) ;
		sector:long_name = "ocean basin" ;
		sector:standard_name = "region" ;
```
If strings `global_ocean` and `atlantic_arctic_ocean` are permissible names of regions, then I guess they are the right names for sector, so I'll assign these ones. Thank you very much for the clarification!
Best regards,
Margarida
