### ISSUE TITLE
error in canonical `units` for `lightning_potential_index`

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/discuss#230]
The `units` for `lightning_potential_index` are given in the table as `J Kg-1`, which is not valid. It should probably be `J kg-1`; `J K g-1` is a valid alternative unit, but seems unlikely (and wouldn't be preferred since it's not MKS).

**Comment by japamment** [comment]
@JonathanGregory

I can confirm that the correct units for lightning potential index (LPI) are J kg-1 and the current entry in the standard name table is a typo.  (See, for example, https://asr.copernicus.org/articles/19/29/2022/ and https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1002/2016JD026115).

I am therefore accepting this change and it will be included in V82 of the standard name table, currently in preparation.

Best wishes

Alison

**Comment by japamment** [comment]
I am closing this issue as the units have been corrected in V82 of the standard name table.
