### ISSUE TITLE
The 2023 CF workshop : Choosing a date

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#232]
Dear CF community,

Planning has started for the 2023 CF workshop, which this year will be an **online-only event**.

We'd like to hold the meeting _some time during the three weeks spanning Monday 18th September to Friday 6th October_, but before settling on any exact dates it would be very useful to know of any other meetings in our wider community that are happening in that window, so that we can try to avoid those days and prevent people having to choose between meetings. 

Fixing the dates for the meeting is clearly a priority, so please let us know very soon (by commenting on this issue) if you know of any possible clashes. In any event, we'll settle on some dates in a few weeks, and certainly before the end of the month. 

Many thanks for your help,
The organising committee

**Comment by MathewBiddle** [comment]
The week of September 25th, IOOS is planning to host the annual IOOS DMAC Meeting https://ioos.noaa.gov/project/dmac/. We don't have specific dates yet, but that week is lining up for us. There are a few of our community members who participate in the CF workshops, for whom it would be beneficial to avoid overlap.

**Comment by larsbarring** [comment]
The same week, 25-29 September, the ICRC-CORDEX 2023 (https://icrc-cordex2023.cordex.org/) is scheduled.

**Comment by larsbarring** [comment]
Can the timeframe for the workshop already now be narrowed down to something more precise than "Monday 18th September to Friday 6th October"?

Many thanks,
Lars

**Comment by JonathanGregory** [comment]
Closed as completed.
