### ISSUE TITLE
The 2023 CF workshop: Call for Breakout session proposals

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#233]
Dear CF Community,

Even though the dates aren't yet finalised, we are excited to solicit "Breakout" proposals for the upcoming 2023 CF Conventions Workshop to be held online (virtual) over a [3-day period TBD in late September or early October, 2023](https://github.com/cf-convention/discuss/issues/232).

We envision devoting some portion of each day to focus attention on high priority CF issues/opportunities. Breakout sessions may be organized around new or existing topics. Suggestions will nominate a discussion leader for the Breakout, preferably someone interested in participating (remotely) in the workshop. Self-nominations are welcome!

We hope that the outcome of each Breakout will be:
* Progress on some new, neglected, or stymied issue or opportunity of importance to CF
* Recommendation on whether to pursue any CF proposals relevant to the Breakout
* More future contributors to CF

Breakout proposals can be short and informal. One or two paragraphs will suffice. Please attach your proposal to this announcement prior to 30th May, 2023 so the Workshop Organizing Committee can rank the proposals at its next meeting.

Inspiration might be found at the [CF meetings home page](http://cfconventions.org/Meetings/), where you can see what the Breakout sessions at previous meeting were.

Sincerely,
The CF Workshop Organizing Committee.

**Comment by larsbarring** [comment]
Here is an idea from the top of my head: 
1. Have a breakout group looking through all open CF github discussion issues to see if
    * some can be either closed as outdated or answered (is the answer relevant to move to the FAQ?)
    * some can be closed as "WONTFIX" or "No Agreement"
    * some maybe resolved with little/modest extra effort, maybe as an activity during the workshop
    * some are important enough to resolve, but need a more dedicated effort either by resurrecting the discussion in the issue or perhaps by a separate group working offline

Of course the "categories" are just suggestions. Or maybe even a group could start this triage before the workshop and report back, thus allowing some more focus on point 3, to resolve some outstanding issues, as well as point 4 to actually discuss the more complex issues and possibly form an offline group.

2. I think that the Hackaton last year was very successful in cleaning up a number of issues related to the web pages and document language and formatting, etc. But there were some leftovers and a few new have surfaced. So, having a similar activity also this year could be useful, even though it would be all virtual this time.

**Comment by turnbullerin** [comment]
I would definitely be interested in participating in and possibly leading a breakout session on enhancing the CF conventions to include a convention for localizing NetCDF metadata. The goal would be to work on a consistent pattern for localized metadata so that locale-aware applications can select the correct metadata when displaying it.
