### ISSUE TITLE
error in canonical units of `mole_concentration_of_dissolved_organic_nitrogen_in_sea_water`

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/discuss#234]
The canonical unit of `mole_concentration_of_dissolved_organic_nitrogen_in_sea_water` is given as `mol/m3`. It's the only standard name with this `units` string, whereas there are 161 with `mol m-3`, so I think it should be changed to conform. Thanks.

**Comment by japamment** [comment]
@JonathanGregory 

I agree that the current units string for this name is a typo. There have been no objections to this proposal, therefore I am accepting it and the change will be included in V82 of the standard name table, currently in preparation.

Best wishes

Alison

**Comment by japamment** [comment]
I am closing this issue as the units were corrected in V82 of the standard name table.
