### ISSUE TITLE
error in canonical `units` of `atmosphere_convective`* quantities

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/discuss#235]
The three quantities `atmosphere_convective_available_potential_energy_wrt_surface`, `atmosphere_convective_inhibition` and `atmosphere_convective_inhibition_wrt_surface` have canonical units written as `J kg -1`, with a space between `kg` and `-1`. The string given is a legal unit, which is dimensionally equivalent to `J kg`, but I think the space is a typo and the unit should be `J kg-1`. Thanks.

**Comment by feggleton** [comment]
Hi Jonathan, thanks for spotting. I agree and so i have added these to the editor and accepted as only a typo. Thanks

**Comment by japamment** [comment]
@JonathanGregory @feggleton 

The units corrections in this issue will all be published in V82 of the standard name table, currently in preparation.

Best wishes

Alison

**Comment by japamment** [comment]
I am closing this issue as the units were corrected in V82 of the standard name table.
