### ISSUE TITLE
Precipitation-related variables (X-day multiday totals)

### ISSUE THREAD

**Issue by mps01060** [cf-convention/discuss#240]
I am working on formatting data like the GHCN-daily (https://www.ncei.noaa.gov/products/land-based-station/global-historical-climatology-network-daily), specifically precipitation-related data. There are three elements I will be working with:

PRCP = Precipitation (inches or mm). This is true 1-day timestep precipitation
MDPR = Multiday precipitation total (mm or inches as per user preference; use with DAPR and DWPR, if available)
DAPR = Number of days included in the multiday precipitation total (MDPR)

I am pretty sure what to do with PRCP to follow the CF-conventions (eg. standard_name 'precipitation_amount', units, etc.). I am having trouble with the MDPR and DAPR variables. The MDPR/DAPR pairs are used to construct a multiday precipitation total (eg. the observer missed an observation and knows the precipitation occurred over a multiday period / not a true 1-day value). For this example, we can look at station id "USC00371874" for the month of 2021-09. For reproducibility, the raw data can be downloaded from:

https://www.ncei.noaa.gov/data/global-historical-climatology-network-daily/access/USC00371874.csv

If we just look at these specific variables for this month, the raw data looks something like this:

USC00371874,20210901,PRCP,0,,,7,0700
USC00371874,20210902,PRCP,1016,,,7,0700
USC00371874,20210903,PRCP,0,,,7,0700
USC00371874,20210904,PRCP,0,,,7,0700
USC00371874,20210905,PRCP,0,,,7,0700
USC00371874,20210908,PRCP,0,,,7,0700
USC00371874,20210909,PRCP,15,,,7,0700
USC00371874,20210910,PRCP,142,,,7,0700
USC00371874,20210911,PRCP,0,,,7,0700
USC00371874,20210912,PRCP,0,,,7,0700
USC00371874,20210913,PRCP,0,,,7,0700
USC00371874,20210914,PRCP,0,,,7,0700
USC00371874,20210915,PRCP,0,,,7,0700
USC00371874,20210918,PRCP,0,,,7,0700
USC00371874,20210919,PRCP,0,,,7,0700
USC00371874,20210920,PRCP,0,,,7,0700
USC00371874,20210921,PRCP,0,,,7,0700
USC00371874,20210922,PRCP,0,,,7,0700
USC00371874,20210923,PRCP,15,,,7,0700
USC00371874,20210924,PRCP,5,,,7,0700
USC00371874,20210928,PRCP,0,,,7,0700
USC00371874,20210929,PRCP,30,,,7,0700
USC00371874,20210930,PRCP,8,,,7,0700

USC00371874,20210907,DAPR,2,,,7,
USC00371874,20210917,DAPR,2,,,7,
USC00371874,20210927,DAPR,3,,,7,

USC00371874,20210907,MDPR,18,,,7,
USC00371874,20210917,MDPR,28,,,7,
USC00371874,20210927,MDPR,97,,,7,

and a more readable format (the raw units from the archive are mm*10 for PRCP and MDPR, and number of days for DAPR):

|YYYYMMDD|PRCP|MDPR|DAPR|
|--------|----|----|----|
|20210901|0|||
|20210902|1016|||
|20210903|0|||
|20210904|0|||
|20210905|0|||
|20210906||||
|20210907||18|2|
|20210908|0|||
|20210909|15|||
|20210910|142|||
|20210911|0|||
|20210912|0|||
|20210913|0|||
|20210914|0|||
|20210915|0|||
|20210916||||
|20210917||28|2|
|20210918|0|||
|20210919|0|||
|20210920|0|||
|20210921|0|||
|20210922|0|||
|20210923|15|||
|20210924|5|||
|20210925||||
|20210926||||
|20210927||97|3|
|20210928|0|||
|20210929|30|||
|20210930|8|||

The MDPR/DAPR pairs are used to get a multiday total, for example 2021-09-07 MDPR is 18 (1.8 mm) and DAPR is 2, which means 1.8mm fell in 2 days, ending on 2021-09-07.

One way to handle this would be to change the MDPR=18 DAPR=2 to two PRCP values, like:
|YYYYMMDD|PRCP|
|--------|----|
|20210906|9|
|20210907|9|

This is not ideal, because it does not retain the raw measurement (which is needed for further QA/QC downstream), though other quality/measurement flags could be added. Additionally, both PRCP and MDPR/DAPR sometimes have values populated for the same dates, which would cause overwriting. Ideally, we would keep the MDPR and DAPR elements, though, I am not sure how to make these follow the CF-conventions.

Lastly, there are other datasets with other timesteps (eg. hourly) that have this same "multi-observational total" that we need to generalize to. Currently, we keep the MDPR and DAPR, and give attributes such as "number of days included in the multiday precipitation" for the DAPR variable, and link MDPR to DAPR with the "ancillary_variables" information. It is currently not following CF-conventions.

For example, the MDPR and DAPR as xarray DataArrays in python:
```
<xarray.DataArray 'MDPR' (dset: 1, sid: 12224, time: 67206)>
dask.array<open_dataset-MDPR, shape=(1, 12224, 67206), dtype=float32, chunksize=(1, 100, 3660), chunktype=numpy.ndarray>
Coordinates:
  * dset     (dset) object 'ghcndaily'
  * sid      (sid) object 'CA006130409' 'CA006130411' ... 'USW00094868'
  * time     (time) datetime64[ns] 1840-01-01 1840-01-02 ... 2024-01-01
Attributes:
    ancillary_variables:  DAPR PRCP_MFLAG PRCP_QFLAG PRCP_SFLAG PRCP_QFLAG_ag...
    description:          multiday precip amount
    long_name:            precipitation accumulated
    standard_name:        precipitation amount
    timestep:             {'unit': 'D', 'value': 1}
    units:                inches
```

```
<xarray.DataArray 'DAPR' (dset: 1, sid: 12224, time: 67206)>
dask.array<open_dataset-DAPR, shape=(1, 12224, 67206), dtype=float32, chunksize=(1, 100, 3660), chunktype=numpy.ndarray>
Coordinates:
  * dset     (dset) object 'ghcndaily'
  * sid      (sid) object 'CA006130409' 'CA006130411' ... 'USW00094868'
  * time     (time) datetime64[ns] 1840-01-01 1840-01-02 ... 2024-01-01
Attributes:
    ancillary_variables:  MDPR PRCP_MFLAG PRCP_QFLAG PRCP_SFLAG PRCP_QFLAG_ag...
    description:          number of days included in the multiday precipitation
    long_name:            number of days included in the multiday precipitation
    standard_name:        number of days included in the multiday precipitation
    timestep:             {'unit': 'D', 'value': 1}
    units:                days accumulated
```

Thank you for any suggestions/help.

**Comment by larsbarring** [comment]
I am not sure that I understand all aspects (e.g. whether DWPR that is mentioned in connection with DAPR is relevant), but here is one possible approach: Think of the precipitation record as just one series of precipitation measurements. Most are accumulations over one day (24h), but a few are accumulations over some other period (typically several days). This can easily be accommodated in one time series, where the time coordinate (variable) has bounds attached, cf. section [7.1 Cell boundaries](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#cell-boundaries). Another approach is to go the other ways around and consider all data as (MDPR, DAPR) pairs where DAPR in most cases would be 1.

Hope this helps.
/Lars

**Comment by DanHollis** [comment]
I don't have anything to add to Lars' suggestions - either option would be a good solution.

One other comment - the canonical units for 'precipitation_amount' are kg m-2. For precipitation depth (in mm or inches) I think the correct standard name would be 'lwe_thickness_of_precipitation_amount' with canonical units of metres. At least, this is what we use!

**Comment by mps01060** [comment]
Thank you all for your help and patience. I'll try to expand a bit more. I think I can use the "time_bounds" method to do most of this, like you said.

I will need to keep PRCP And MDPR separate, as there are times in the dataset where conflicting PRCP and MDPR exist for the same overlapping times (we want to keep the original data true to the archive).

A second version of this .zarr dataset, it would make sense for us to have a single PRCP variable, where after QC/QA is performed and overlapping PRCP and MDPR are rectified.

My main confusion for the use of time_bounds is with a multi-dimensional PRCP / MDPR variable (multiple stations). I end up with 'time' and 'time_bnds' used for my 'PRCP' data, since it is all 1-day duration for every observation for every station.

For the MDPR variable, I end up with a separate 'time_MDPR' and 'time_bnds_MDPR'. The 'time_bnds_MDPR' ends up being 3-dimensions (time_MDPR, station, nbnd) because the time bounds are different for each station. I don't see a 3-dimensional "time_bounds" example on the CF-conventions, so I am not sure if this is allowed? If this is allowed, then I think I (mostly) know what to do.

For my 'time' coordinate, it gets attribute 'bounds' = 'time_bnds'
For 'time_MDPR', it gets attribute 'bounds' = 'time_bnds_MDPR'

Here is a summary of the variables/coordinates/dimensions for an example where we have 2 stations with data that looks like. The goal is a sliceable Zarr:

|Station|YYYY-MM-DD|PRCP|MDPR|DAPR|
|-------|----------|----|----|----|
|a|2000-01-01|0|||
|a|2000-01-02|10|||
|a|2000-01-03|0|||
|a|2000-01-04||||
|a|2000-01-05||200|2|
|b|2000-01-01||||
|b|2000-01-02||||
|b|2000-01-03||100|3|
|b|2000-01-04|0|||
|b|2000-01-05|0|||


![image](https://github.com/cf-convention/discuss/assets/6819509/76a659b5-4200-40a2-bef2-5db38ca6bee2)



Long version to reproduce summary above in python:

```python
import numpy as np
import pandas as pd
import xarray as xr

# Create two stations (we have many)
stations = ['a', 'b']

# Create a few days of data
times = pd.date_range(pd.Timestamp(2000,1,1),pd.Timestamp(2000,1,5),freq='1D')

# Create some data
PRCP = np.array(
    [[0      , np.nan],
     [10     , np.nan],
     [0      , np.nan],
     [np.nan , 0],
     [np.nan , 0]],
    dtype=np.float32
)
MDPR = np.array(
    [[np.nan , np.nan],
     [np.nan , np.nan],
     [np.nan , 100],
     [np.nan , np.nan],
     [200    , np.nan]],
    dtype=np.float32
)
DAPR = np.array(
    [[np.nan , np.nan],
     [np.nan , np.nan],
     [np.nan , 3],
     [np.nan , np.nan],
     [2      , np.nan]],
    dtype=np.float32
)

# Scale from mm*10 to mm
PRCP = PRCP/10.
MDPR = MDPR/10.

# NaN DAPR can be effectively treated as "1"s for our purposes
DAPR[np.isnan(DAPR)] = 1

# Create time_bnds for regular daily precipitation
# This is 2-d
time_bnds = np.column_stack((times - np.timedelta64(1,'D'), times))

# Create a 3-dimensional time_bnds
# dims (time, station, nbnd)
# Start with the "time" array to tile the data
# reshape the original array to shape (5,1,1)
time_bnds_MDPR = np.array(times).reshape(5, 1, 1)
time_bnds_MDPR = np.tile(time_bnds_MDPR, (1,len(stations), 2))

# Populate MDPR time bounds with the DAPR values
# Loop over stations dim
for station_idx in range(time_bnds_MDPR.shape[1]):
    time_bnds_MDPR[:,station_idx,0] =  np.array(time_bnds_MDPR[:,station_idx,-1] - pd.to_timedelta(DAPR[...,station_idx], unit='day'))

# Create the dataset
ds = xr.Dataset(
    data_vars={
        'PRCP' : (['time', 'station_id'], PRCP),
        'MDPR' : (['time_MDPR', 'station_id'], MDPR),
    },
    coords={
        'station_id' : stations,
        'time' : times,
        'time_MDPR' : times,
        'time_bnds' : (['time','nbnd'], time_bnds),
        'time_bnds_MDPR' : (['time_MDPR','station_id','nbnd'], time_bnds_MDPR),
        'nbnd' : np.arange(2),
    },
    attrs={
        'description' : 'example attr'
    },
)
ds['time'].attrs['bounds'] = 'time_bnds'
ds['time_MDPR'].attrs['bounds'] = 'time_bnds_MDPR'
```


```python
print(ds)
```

    <xarray.Dataset>
    Dimensions:         (time: 5, station_id: 2, time_MDPR: 5, nbnd: 2)
    Coordinates:
      * station_id      (station_id) <U1 'a' 'b'
      * time            (time) datetime64[ns] 2000-01-01 2000-01-02 ... 2000-01-05
      * time_MDPR       (time_MDPR) datetime64[ns] 2000-01-01 ... 2000-01-05
        time_bnds       (time, nbnd) datetime64[ns] 1999-12-31 ... 2000-01-05
        time_bnds_MDPR  (time_MDPR, station_id, nbnd) datetime64[ns] 1999-12-31 ....
      * nbnd            (nbnd) int64 0 1
    Data variables:
        PRCP            (time, station_id) float32 0.0 nan 10.0 nan ... 0.0 nan 0.0
        MDPR            (time_MDPR, station_id) float32 nan nan nan ... 200.0 nan
    Attributes:
        description:  example attr



```python
# Print first station's MDPR
print(ds.sel({'station_id':'a'})['MDPR'])
print('---------------------------------')
print('---------------------------------')
print(ds.sel({'station_id':'a'})['time_bnds_MDPR'])
```

    <xarray.DataArray 'MDPR' (time_MDPR: 5)>
    array([ nan,  nan,  nan,  nan, 200.], dtype=float32)
    Coordinates:
        station_id  <U1 'a'
      * time_MDPR   (time_MDPR) datetime64[ns] 2000-01-01 2000-01-02 ... 2000-01-05
    ---------------------------------
    ---------------------------------
    <xarray.DataArray 'time_bnds_MDPR' (time_MDPR: 5, nbnd: 2)>
    array([['1999-12-31T00:00:00.000000000', '2000-01-01T00:00:00.000000000'],
           ['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000'],
           ['2000-01-02T00:00:00.000000000', '2000-01-03T00:00:00.000000000'],
           ['2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
           ['2000-01-03T00:00:00.000000000', '2000-01-05T00:00:00.000000000']],
          dtype='datetime64[ns]')
    Coordinates:
        station_id      <U1 'a'
      * time_MDPR       (time_MDPR) datetime64[ns] 2000-01-01 ... 2000-01-05
        time_bnds_MDPR  (time_MDPR, nbnd) datetime64[ns] 1999-12-31 ... 2000-01-05
      * nbnd            (nbnd) int64 0 1



```python
# Save to example netcdf-4
encoding = {
    'PRCP' : {
        'dtype' : np.int16,
        'scale_factor' : np.float32(0.1),
        'add_offset' : np.float32(0),
        '_FillValue' : np.iinfo('int16').min,
        'zlib' : True
    },
    'MDPR' : {
        'dtype' : np.int16,
        'scale_factor' : np.float32(0.1),
        'add_offset' : np.float32(0),
        '_FillValue' : np.iinfo('int16').min,
        'zlib' : True
    },
    'time' : {
        'dtype' : np.int32,
        '_FillValue' : np.iinfo('int32').min,
        'units' : 'days since 1800-01-01 00:00:00',
        'calendar' : 'gregorian',
        'zlib' : True
    },
    'time_MDPR' : {
        'dtype' : np.int32,
        '_FillValue' : np.iinfo('int32').min,
        'units' : 'days since 1800-01-01 00:00:00',
        'calendar' : 'gregorian',
        'zlib' : True
    },
    'time_bnds' : {
        'dtype' : np.int32,
        '_FillValue' : np.iinfo('int32').min,
        'units' : 'days since 1800-01-01 00:00:00',
        'calendar' : 'gregorian',
        'zlib' : True
    },
    'time_bnds_MDPR' : {
        'dtype' : np.int32,
        '_FillValue' : np.iinfo('int32').min,
        'units' : 'days since 1800-01-01 00:00:00',
        'calendar' : 'gregorian',
        'zlib' : True
    },
}
ds.to_netcdf('test.nc', engine='netcdf4', encoding=encoding)
```


```python
# Read back in and print some information
ds_in = xr.open_dataset('test.nc', engine='netcdf4', decode_coords='all')
print(ds_in)
```

    <xarray.Dataset>
    Dimensions:         (time: 5, station_id: 2, time_MDPR: 5, nbnd: 2)
    Coordinates:
      * station_id      (station_id) object 'a' 'b'
      * time            (time) datetime64[ns] 2000-01-01 2000-01-02 ... 2000-01-05
      * time_MDPR       (time_MDPR) datetime64[ns] 2000-01-01 ... 2000-01-05
        time_bnds       (time, nbnd) datetime64[ns] ...
        time_bnds_MDPR  (time_MDPR, station_id, nbnd) datetime64[ns] ...
      * nbnd            (nbnd) int64 0 1
    Data variables:
        PRCP            (time, station_id) float32 ...
        MDPR            (time_MDPR, station_id) float32 ...
    Attributes:
        description:  example attr



```python

```

**Comment by JonathanGregory** [comment]
Dear @mps01060 

1. The time coordinates have to be unique and monotonic, but the cells can overlap - that is not disallowed in the CF convention. Therefore I don't think you need to put the single-day and multi-day precipitation accumulations in different variables.
2. If the accumulation intervals, and hence the time coordinates and bounds, are different for each station, you can't use a common set of time coordinates for them. This kind of situation can be treated in CF as a `timeseries` feature, using one of the array representations described in sections 9.3.2-4 (incomplete multidimensional, contiguous ragged and indexed ragged).

Best wishes

Jonathan
