### ISSUE TITLE
The 2023 CF workshop: 3-5 October 2023

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#243]
Dear CF community,

Thank you for the [feedback](https://github.com/cf-convention/discuss/issues/232) about possible dates for this year's workshop. We're happy to announce that the 2023 CF workshop will take place over _three consecutive half days_ on 

#### **Tuesday 3rd, Wednesday 4th, and Thursday 5th October 2023**

The format will be broadly similar to that of the previous online workshops of [2020](http://cfconventions.org/Meetings/2020-Workshop.html) and [2021](http://cfconventions.org/Meetings/2021-Workshop.html), but we've deliberately not yet specified a start time on each day so that we have the flexibility to choose one that is best for the most participants. Registration will open soon, so there'll be some data to support the choice.

We look forward to seeing you there, all the best,
The organising committee

**Comment by ethanrd** [comment]
Dear Participants,

We are excited to welcome everyone to the upcoming 2023 CF Conventions (virtual) Workshop scheduled for 3-5 October from 15:00-18:00 UTC each day on Zoom.

Following the formal workshop each day will be social time, also on Zoom.

The workshop agenda, and the form for registration (free!), is at

https://cfconventions.org/Meetings/2023-Workshop.html

Sincerely,
The CF Workshop Organizing Committee.
