### ISSUE TITLE
New standard_name: mass_concentration_of_zooplankton_expressed_as_carbon_in_sea_water

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#25]
**Proposer's name** Ute Daewel / Beate Geyer
**Date** Wed Jul 19 06:43:37 MDT 2017

**- Term** mass_concentration_of_zooplankton_expressed_as_carbon_in_sea_water
**- Definition** 'Mass concentration' means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'.The phrase 'expressed_as' is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A.  'Zooplankton' means the total zooplankton population, with components such as mesozooplankton, microzooplankton and miscellaneous zooplankton.
**- Units kg m-3**

The proposal was sent to the mailling list in 2017.
mole_concentration_of_zooplankton_expressed_as_carbon_in_sea_water already exists, but we want to use the mass_concentration as it exists for other species (e.g., diatoms and flagellates).

**Comment by japamment** [comment]
Dear Ute and Beate,

Thank you for this proposal and apologies again for missing the original mailing list posting: [http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2017/009409.html](http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2017/009409.html).

The name and units as proposed look fine and closely match existing zooplankton names. Following  my comments regarding the diazotroph proposal in issue #24[](https://github.com/cf-convention/discuss/issues/24) I checked the WoRMS taxonomy and it seems that "zooplankton" is not a taxonomic classification, hence there is no problem with adding this one as a separate name.

This name is accepted for publication in the standard name table and will be added in the next update on 3rd February.

Best wishes,
Alison

**Comment by feggleton** [comment]
These changes have been published in version 71 of the standard name table.
