### ISSUE TITLE
Call for abstracts - CF and netCDF session at 2023 AGU Fall Meeting

### ISSUE THREAD

**Issue by ethanrd** [cf-convention/discuss#253]
Hi all,

The [2023 AGU Fall Meeting](https://www.agu.org/Fall-Meeting) will be held 11-15 December 2023 in San Francisco, CA and online. Please consider submitting an abstract to session IN017 "CF and NetCDF: 30 Years of Wide Open Science". Share how you are using CF and netCDF, your experiences, and any new developments. The deadline for submissions is 2 August 2023.

To submit: https://agu.confex.com/agu/fm23/prelim.cgi/Session/192249

Session Description:

> The CF (Climate and Forecast) Conventions are a community-developed standard for describing Earth system science data in the netCDF data format. The CF Conventions can encode information that describes the coordinate systems, data structure, and geophysical meaning and units of each variable, and how the data were collected. It is widely used by weather and climate scientists and remote-sensing researchers and is gaining traction in new communities, such as biogeochemistry and operational weather prediction. It has a mature ecosystem of FOSS and commercial software tools that can explore, analyze, and visualize data that is encoded using the CF Conventions.
> 
> This session will focus on efforts to extend the existing CF Conventions; recent advances in the CF and netCDF software ecosystem; the experience of projects in domains and features new to CF and netCDF (e.g., new standard names, compression, aggregation, Zarr); optimization of data formats; and engagement with the community.

We hope to see you there.

Session Organizers
Ethan Davis, UCAR Unidata
Kevin O'Brien, University of Washington/CICOES
Charlie Zender, University of California Irvine
David Hassell, University of Reading

**Comment by JonathanGregory** [comment]
I am closing this because the deadline has passed.
