### ISSUE TITLE
Adopting BCP 14 (RFC 2119, RFC 8174) requirement levels in CF

### ISSUE THREAD

**Issue by DocOtak** [cf-convention/discuss#258]
In the discussion of #256, the idea of formally adopting RFC 2119 requirement level key words was raised by myself and, perhaps foolishly :wink:, I offered to start the effort if desired. This received immediate support from @larsbarring and @JonathanGregory. So this new issue where I will describe what this is, what changes would need to be adopted, and what I think the steps might be to getting this implemented. Adopting this will likely touch every section of the CF document and impact new and existing proposed changes to CF.

## What is BCP 14?
[RFC 2119](https://www.rfc-editor.org/rfc/rfc2119.txt) defines a set of key words that are used to indicate requirement levels of a specification. Requirement levels range from absolute requirements (i.e. not following this recommendation means this file is NOT CF) to things that are truly optional (e.g. the use of standard names in on data variables). RFC 2119 was updated by [RFC 8174](https://www.rfc-editor.org/rfc/rfc8174.txt) to clarify that only when a key word appears in all upper case type does it mean it is a requirement level key word. e.g. "the attribute standard_name may exist on a variable" has no requirement level where "the attribute standard_name MAY exist on a variable" does. Collectively, these two standards are combined into [BCP 14](https://www.rfc-editor.org/bcp/bcp14.txt) (best common practice).

## Changes to the CF document
There are two changes that would need to be made to the CF document:
1. Include the following text near the start of the document as per BCP 14:
     > The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here. 
2. Update all the instances of the instances of the above key words to be in their all capital form when they are intended to be interpreted as a requirement level.

Point 2 is where the real effort lays. Here is a breakdown of how many times these words currently appear in CF 1.10:

| Key Word | Frequency|
| --- | --: |
|MUST|161|
|MUST NOT|8|
|REQUIRED|69|
|SHALL|14|
|SHALL NOT|3|
|SHOULD|119|
|SHOULD NOT|13|
|RECOMMENDED|43|
|NOT RECOMMENDED|3|
|MAY|236|
|OPTIONAL|93|

Not all these occurrences actually indicate the intent to make a requirement and not all the usages of the above words indicate the intent as defined by BCP 14. The conformance document/section will come in quite handy as the various sections are updated with these key words.

## Implementation
Naturally following the [Rules for CF Conventions Changes](http://cfconventions.org/rules.html), implementation starts with this discussion. There should be feedback here (this very issue as per rules) but I also feel this is such a large change that discussion should be had at the 2023 CF Workshop (#243) in early October before any "final" decisions are made. 

Practically, if we do decide that we will adopt BCP 14, because the key words specifically need to appear in all capital letters we can adopt it immediately with the text in point 1 above (perhaps with a caveat that it is a work in progress) and the CF conventions would be unchanged in meaning. Then a gradual update the text of the document in small pieces to have the all capitol keywords. This would alleviate the need for a single very large change set to be prepared and could be done in multiple separate pull requests.

**Comment by larsbarring** [comment]
@DocOtak, Andrew, again thank you, for this this excellent summary and outline of the work need! I agree that this is a undertaking that first should (perhaps even MUST ;-) be be discussed at the CF2023 workshop.  

And I agree with @erget that it is important to keep the work on updating the text separate enough to not confuse readers of the "official" Working Draft. Not knowing much about github I still imagine that this could be handled by having a totally separate working branch/fork/repo (or whatever it might be called) and then when we are reasonably close to finished the changes can be systematically moved to the main Working Draft?

**Comment by sadielbartholomew** [comment]
I agree it would be best to discuss this at the forthcoming workshop, but to add, I think it is a really good idea overall due to the significant reduction of ambiguity it will lead to, and so I am happy to register my support (and possibly, offer to help implement if extra help is needed and if I can find time). :100:

**Comment by JonathanGregory** [comment]
Dear @DocOtak 

I would say your offer was generous and valiant, rather than foolish. Thanks again. This is very helpful.

It sounds like BCP 14 has more levels than CF does. The conformance document will clarify which are requirements and recommendations. I suppose these can be equated with two of the BCP levels. We will have to discuss whether other optional things that aren't explicitly recommended, just allowed, and consequently not mentioned in the conformance document, are all in the same level. Also, as I mentioned before, there may be requirements and recommendations on the same levels as those in the conformance document, but they're not in that document because they cannot be checked automatically.

Like Daniel @erget, I would prefer the all-at-once update, but I agree it will take time to prepare. Following Lars's idea, could it be done in a branch of the public repo? I presume people can make pull requests to a branch (other than main) of the public repo from branches in their own repos - right? It would be necessary to pull updates from main to the branch periodically and some of them would conflict, but not most, I guess.

Best wishes

Jonathan

**Comment by erget** [comment]
[like]  Daniel Lee reacted to your message:
________________________________

**Comment by erget** [comment]
I think we can figure out the details of the update itself clarified once we have the substantive discussion out of the way, but in a nutshell I do think that we can do an update as you @JonathanGregory propose - public branch where we're working on the BCP 14 updates, against which pull requests could be submitted. Should we decide to ask people to continue submitting PRs against the already-published or already-agreed draft, we could still integrate at the end - in the end we just need to decide how we want to approach that particular release. In all cases, I think it makes sense to work in open view.

**Comment by DocOtak** [comment]
Things can absolutely take place in a publicly in a branch. I don't think merging in changes from the main branch would be too difficult, there are several options: rebase, merge commits, etc... and I don't think making this change incrementally vs one large changeset change the effort involved for those of us who would be making the actual modifications. Considerations about how external readers might be affected should take precedence in the decisions in my opinion.

**Comment by JonathanGregory** [comment]
Dear Andrew @DocOtak 

It occurs to me that DEPRECATED should also appear in the list of words to be changed. We have used this word to mean the same as "not recommended". By both "deprecated" and "not recommended" we mean "recommended against".

Cheers

Jonathan

**Comment by larsbarring** [comment]
I did a little bit of playing around with some ideas and put together some python code that paints the selected keywords. Basically it takes the .adoc files located in the parent directory (which is where they are as usual) and adds some asciidoc coloring tags and saves the results in the same directory as the python code. And if you have asciidoctor installed it creates html in a subdirectory. All is available in [my fork under branch BCP14](https://github.com/larsbarring/cf-conventions/tree/my_bcp-14), in particular in the subdirectory BCP-14.

Perhaps this could be a starting point to build on, but I have rather limited experience of github and do not know how to set up a branch that will efficient for collaboration.

Another thing that I thought of is what words/phrases to work on. BCP14 has a clearly defined list. I think that @DocOtak wanted to restrict the work to only these. I like this because this is a rather extensive undertaking anyway. On the other hand, if we are going to do all this work, I think that it might at least be useful to be aware of closely related words/phrases so we don't miss some important context. In the python code I have these preliminary lists (which have to be checked/updated !!):

```python
BCP14 = [
    "MUST NOT", "SHALL NOT", "SHOULD NOT",
    "MUST", "REQUIRED", "SHALL", "SHOULD",
    "RECOMMENDED", "MAY", "OPTIONAL"
]
EXTENDED_BCP14 = [
    "NOT RECOMMENDED", "RECOMMENDS* NOT","RECOMMENDS*",
    "CAN NOT", "COULD NOT", "CAN", "COULD", 
    "DEPRECATED", "HAVE TO"
]
```

Here is a screen-clip of how it looks like:

--------------------------------------
![image](https://github.com/cf-convention/discuss/assets/15440426/7ba927e4-f072-4080-9d1f-fd77ce6a13c1)

**Comment by JonathanGregory** [comment]
Dear @larsbarring 

Thanks for doing this. I agree with you, and I'd nominate _permitted_ and _required_ as two more words we should consider. Your screenshot is a good example of the need for context. The word _recommended_ clarifies that those two statements are both recommendations, not requirements. The first of them appears as a recommendation in the conformance document (Sect 2.3). We are _not_ saying that "names MUST NOT be distinguishable only by case" or that "names MUST be obviously meaningful". The word _should_ by itself has various meanings. E.g. in "The `crs_wkt` attribute should comprise a text string that conforms to the WKT syntax" (Sect 5.6.1.), the word _should_ means _MUST_. This statement is given as a requirement in the conformance document (Sect 5.6).

Best wishes

Jonathan

**Comment by erget** [comment]
This initiative has gained fresh wind at the 2024 workshop. We made a plan [at Friday's hackathon.](https://docs.google.com/document/d/1VknWozJM3vkUeoJKQHXlmroXPwZtd2EO8_jgGIID-kw/edit)

I will make an issue as a starting point for us to collaborate on getting this done and flag those who have expressed explicit interest. Target implementation for CF-1.13 in 2025.

**Comment by erget** [comment]
We've found a good way forward at the annual meeting so I'm closing this one as the work will take place in the Conventions repo, referenced previous to this comment. Reopen if you disagree and thank you all for contributing there and for your future contributions in the new issue ;)

**Comment by sadielbartholomew** [comment]
Hi all, to update:

> We've found a good way forward at the annual meeting so I'm closing this one as the work will take place in the Conventions repo, referenced previous to this comment.

Unfortunately I think despite good intentions people didn't have the bandwidth to progress this forward after the 2024 workshop, however we'd like to revive it for the 2026 workshop! Hence I am re-opening this.

Our aim would be to start converting to fully adopt BCP 14 the CF document and ideally also the standard name definitions after the release of CF 1.14 later this year to have the converted content ready in time for the CF 1.15 release, due late in 2027 by our release schedule. Which gives a good year to do the work together to make that happen.

**To prepare for this, we on the organising committee are looking for a volunteer to lead, or to help lead,  a hackathon on BCP 14 at the [CF Workshop 2026](https://climate.copernicus.eu/cf-conventions-community-workshop-2026), where we can summarise where we are at with this and how we can go forward to get the document converted ready for CF 1.15 release.**

Ideally this would be someone who attended the 2024 hackathon session on BCP 14, so if that was you please consider volunteering! You don't have to be attending the CF Workshop in Bonn in person, but need to be attending online. If it helps, I am happy to chair and/or coordinate as someone who will be there in-person to facilitate the hybrid session.

*If you wish to take on this role, please comment here in the first case, including to note whether you are attending the workshop in-person or remotely, and whether you'd like me to assist with anything.*

**Comment by larsbarring** [comment]
The python script mentioned [above](https://github.com/cf-convention/discuss/issues/258#issuecomment-1984488844) is now updated to work with the current repo. To produce a rendered html pages the [`asciidoctor`](https://asciidoctor.org/) software package has to be installed, otherwise only the tagged asciidoc (`.adoc`) files are produced. 

Here is the help text (the colors are changed in a postprocessing script to better support CVD): 
```bash
$ python paint_text.py -h

usage: paint_text [-h] [-f FILE_NAME] [-v VOCABULARY] [-c COLOR_CODE]

Paint words related to BCP-14 in .adoc files, which must reside in the parent directory ('../'). If no filename is given then all .adoc files will be processed.

options:
  -h, --help            show this help message and exit
  -f FILE_NAME, --file_name FILE_NAME
  -v VOCABULARY, --vocabulary VOCABULARY
                        Either 'BCP14' (default), 'EXT[ENDED]', or 'BOTH'
  -c COLOR_CODE, --color_code COLOR_CODE
                        BCP14=black/aqua [BCP14], Extended BCP14=black/lime [Extended BCP14] (Extended keywords have black letters)
```

And here are some stats for the current draft version of the Conventions text  (as of writing this comment), which may help to select where to start:

```bash
$ python paint_text.py 


Keywords:
BCP14:    ['MUST NOT', 'SHALL NOT', 'SHOULD NOT', 'MUST', 'REQUIRED', 'SHALL', 'SHOULD', 'RECOMMENDED', 'MAY', 'OPTIONAL']
IN: ../ch01.adoc                 OUT: ./ch01.adoc                count: 37
IN: ../ch02.adoc                 OUT: ./ch02.adoc                count: 83
IN: ../ch03.adoc                 OUT: ./ch03.adoc                count: 59
IN: ../ch04.adoc                 OUT: ./ch04.adoc                count: 92
IN: ../ch05.adoc                 OUT: ./ch05.adoc                count: 71
IN: ../ch06.adoc                 OUT: ./ch06.adoc                count: 15
IN: ../ch07.adoc                 OUT: ./ch07.adoc                count: 173
IN: ../ch08.adoc                 OUT: ./ch08.adoc                count: 81
IN: ../ch09.adoc                 OUT: ./ch09.adoc                count: 40
IN: ../appa.adoc                 OUT: ./appa.adoc                count: 4
IN: ../appb.adoc                 OUT: ./appb.adoc                count: 4
IN: ../appc.adoc                 OUT: ./appc.adoc                count: 5
IN: ../appd.adoc                 OUT: ./appd.adoc                count: 24
IN: ../appe.adoc                 OUT: ./appe.adoc                count: 2
IN: ../appf.adoc                 OUT: ./appf.adoc                count: 78
IN: ../appg.adoc                 OUT: ./appg.adoc                count: 0
IN: ../apph.adoc                 OUT: ./apph.adoc                count: 82
IN: ../appi.adoc                 OUT: ./appi.adoc                count: 64
IN: ../appj.adoc                 OUT: ./appj.adoc                count: 29
IN: ../appk.adoc                 OUT: ./appk.adoc                count: 3
IN: ../appl.adoc                 OUT: ./appl.adoc                count: 0
IN: ../appm.adoc                 OUT: ./appm.adoc                count: 6
IN: ../about-authors.adoc        OUT: ./about-authors.adoc       count: 0
IN: ../authors.adoc              OUT: ./authors.adoc             count: 0
IN: ../bibliography.adoc         OUT: ./bibliography.adoc        count: 0
IN: ../cf-conventions.adoc       OUT: ./cf-conventions.adoc      count: 0
IN: ../conformance.adoc          OUT: ./conformance.adoc         count: 278
IN: ../history.adoc              OUT: ./history.adoc             count: 6
IN: ../toc-extra.adoc            OUT: ./toc-extra.adoc           count: 0
IN: ../version.adoc              OUT: ./version.adoc             count: 0

[a001257@c22558 BCP-14]$ python paint_text.py -v BOTH


Keywords:
BCP14:    ['MUST NOT', 'SHALL NOT', 'SHOULD NOT', 'MUST', 'REQUIRED', 'SHALL', 'SHOULD', 'RECOMMENDED', 'MAY', 'OPTIONAL']
Extended: ['NOT RECOMMENDED', 'RECOMMENDS* NOT', 'RECOMMENDS*', 'NOT PERMITTED', 'PERMITTED', 'PERMITS*', 'NOT REQUIRED', 'NOT REQUIRES*', 'REQUIRES*', 'CAN NOT', 'COULD NOT', 'CAN', 'COULD', 'MIGHT', 'NOT SUGGESTED', 'SUGGESTED', 'SUGGESTS*', 'NOT ALLOWED', 'ALLOWED', 'ALLOWS*', 'FORBIDDEN', 'FORBIDS*', 'PROHIBITED', 'PROHIBITS*DEPRECATED', 'HAVE TO']
IN: ../ch01.adoc                 OUT: ./ch01.adoc                count: 67
IN: ../ch02.adoc                 OUT: ./ch02.adoc                count: 127
IN: ../ch03.adoc                 OUT: ./ch03.adoc                count: 82
IN: ../ch04.adoc                 OUT: ./ch04.adoc                count: 125
IN: ../ch05.adoc                 OUT: ./ch05.adoc                count: 94
IN: ../ch06.adoc                 OUT: ./ch06.adoc                count: 22
IN: ../ch07.adoc                 OUT: ./ch07.adoc                count: 254
IN: ../ch08.adoc                 OUT: ./ch08.adoc                count: 115
IN: ../ch09.adoc                 OUT: ./ch09.adoc                count: 61
IN: ../appa.adoc                 OUT: ./appa.adoc                count: 9
IN: ../appb.adoc                 OUT: ./appb.adoc                count: 5
IN: ../appc.adoc                 OUT: ./appc.adoc                count: 5
IN: ../appd.adoc                 OUT: ./appd.adoc                count: 26
IN: ../appe.adoc                 OUT: ./appe.adoc                count: 2
IN: ../appf.adoc                 OUT: ./appf.adoc                count: 103
IN: ../appg.adoc                 OUT: ./appg.adoc                count: 0
IN: ../apph.adoc                 OUT: ./apph.adoc                count: 129
IN: ../appi.adoc                 OUT: ./appi.adoc                count: 94
IN: ../appj.adoc                 OUT: ./appj.adoc                count: 36
IN: ../appk.adoc                 OUT: ./appk.adoc                count: 3
IN: ../appl.adoc                 OUT: ./appl.adoc                count: 0
IN: ../appm.adoc                 OUT: ./appm.adoc                count: 7
IN: ../about-authors.adoc        OUT: ./about-authors.adoc       count: 0
IN: ../authors.adoc              OUT: ./authors.adoc             count: 0
IN: ../bibliography.adoc         OUT: ./bibliography.adoc        count: 0
IN: ../cf-conventions.adoc       OUT: ./cf-conventions.adoc      count: 0
IN: ../conformance.adoc          OUT: ./conformance.adoc         count: 293
IN: ../history.adoc              OUT: ./history.adoc             count: 12
IN: ../toc-extra.adoc            OUT: ./toc-extra.adoc           count: 0
IN: ../version.adoc              OUT: ./version.adoc             count: 0

```
