### ISSUE TITLE
OGC GeoZarr working group: Comments sought

### ISSUE THREAD

**Issue by erget** [cf-convention/discuss#259]
Dear CF enthusiasts,

OGC has issued [a call for public comments on a potential GeoZarr Standards Working Group](https://mailchi.mp/ogc.org/geozarr-swg-charter-rfc?e=0dfce398ca). The document is very brief and is focused on the mandate of the working group. As Zarr, GeoZarr, and OGC are all relevant friends of CF, please be aware of this call in case you're interested in submitting comments! :)

Daniel

**Comment by taylor13** [comment]
Hi all,
In the draft description, it appears that there are intentions to try to adopt some aspects at least of CF.  It would be good if one or more individuals might engage with this effort to ensure as much compatibility as is sensible.  I recognize one of the working group organizers has been a contributor to CF, but perhaps others of us should become involved.  
Karl

**Comment by dblodgett-usgs** [comment]
Hi All - Ethan and I have been involved thus far. Others would be more than welcome - I think the activity will be run in an open github, so it should be quite accessible.

From: taylor13 ***@***.***>
Sent: Friday, August 25, 2023 10:18 AM
To: cf-convention/discuss ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [cf-convention/discuss] OGC GeoZarr working group: Comments sought (Issue #259)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi all,
In the draft description, it appears that there are intentions to try to adopt some aspects at least of CF. It would be good if one or more individuals might engage with this effort to ensure as much compatibility as is sensible. I recognize one of the working group organizers has been a contributor to CF, but perhaps others of us should become involved.
Karl

-

**Comment by ngalbraith** [comment]
Just for background info, this is from the call for public comments (for those, like me, who have never heard of Zarr).

 _OGC is looking to form a GeoZarr Standards Working Group (SWG) that will develop a Zarr encoding for geospatial gridded data in the form of Zarr conventions. Public comment is requested on the SWG’s charter. Comments are due by September 13, 2023.

In the geospatial world, new cloud-native data formats are emerging. Zarr is a generic data format for n-dimensional arrays that enables access to data in compressed chunks of the original array. Zarr has become increasingly popular to use for geospatial purposes. Zarr facilitates portability and interoperability on both object stores and hard disks._

**Comment by feggleton** [comment]
@dblodgett-usgs @ethanrd Any updates on how the working group is progressing or a link to the GitHub, I haven't seen anything from OGC. The UK Met Office is very interested in this at the moment.

**Comment by dblodgett-usgs** [comment]
This went out a while ago. https://www.ogc.org/requests/ogc-to-form-geozarr-standards-working-group-public-comment-sought-on-draft-charter/ and the SWG is underway. https://www.ogc.org/press-release/ogc-forms-new-geozarr-standards-working-group-to-establish-a-zarr-encoding-for-geospatial-data/
