### ISSUE TITLE
Release of CF-1.8

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#26]
Dear CF community,

I am very happy to announce that CF-1.8 will be formally released in early February 2020. It will contain all enhancements and defects raised since 1.7 that have _already_ been agreed and merged into the master conventions source text.

It has been over two years since CF-1.7 was released, even though it was agreed that more frequent releases should occur - 1 or 2 per year. I am confident that new versions can be created more often from now on, given that the GitHub workflow that we are now using has bedded in.

All the best,
David

**Comment by davidhassell** [comment]
The list of merged pull requests that will define CF-1.8 may be seen at https://github.com/cf-convention/cf-conventions/pulls?utf8=%E2%9C%93&q=+milestone%3A1.8+ (identified by having milestone 1.8 set on them).

This selection does not include pull requests that do not change the text of the main conventions document (such as changes to the CONTRIBUTING.md file).

Please let me know if I've missed any. This list is independent of the 1.8 release, but may be useful for seeing at a glance what has changed, and will certainly be useful when any upgrading software to CF-1.8. 

Thanks,
Daivd

**Comment by marqh** [comment]
Hello @davidhassell 

There is a nearly completed Pull Request altering the interpretation of the enhanced `grid_mapping` attribute syntax:
https://github.com/cf-convention/cf-conventions/pull/224
https://github.com/cf-convention/cf-conventions/issues/223

which is agreed in principle and ticking down it's 'any further objection' clock
https://github.com/cf-convention/cf-conventions/issues/223#issuecomment-577669154

Please may I request that this change be considered for inclusion in the CF 1.8 publication? 
As the timescales look like they're going to align and the change is interpretation of current syntax with no new conformance requirements, I think this could be delivered without harming the 1.8 delivery.

what do you think?

thank you
mark

**Comment by davidhassell** [comment]
I think that this is OK, as the new content is more than 3 weeks old and is now all agreed (see https://github.com/cf-convention/cf-conventions/issues/223 for details)

CF-1.8 will contain anything merged by the 31st January 2020.

The build is scheduled for some time during the following week (3-7 February), so no merges should be made from 1st February until the announcement that the release has been completed.

Many thanks,
David

**Comment by davidhassell** [comment]
Hello,

I am happy to announce, as many will already already seen, that version 1.8 of the CF conventions has been released and is available on the web site (http://cfconventions.org/latest.html).

A great thank you to Jeff Painter who made it all happen.

The master branch in https://github.com/cf-convention/cf-conventions now holds the draft for version 1.9, and we can start merging pull requests again.

The list of merged pull requests that defines CF-1.8 may be seen at https://github.com/cf-convention/cf-conventions/pulls?utf8=%E2%9C%93&q=+milestone%3A1.8+ (identified by having milestone 1.8 set on them).

All the best,
David

**Comment by JonathanGregory** [comment]
Thank you, David, Jeff, and all others who contributed to this version and the process of publishing it.
