### ISSUE TITLE
 Standard names: mole_fraction_of_cfc13_in_air

### ISSUE THREAD

**Issue by joe-pitt** [cf-convention/discuss#260]
**Proposer's name** Joe Pitt

**Date** 2023-08-25

**- Term** mole_fraction_of_cfc13_in_air

**- Description** "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula for CFC13 is CF3Cl. The IUPAC name for CFC13 is chloro(trifluoro)methane.

**- Units** 1

There are already entries for cfc11 and cfc12, but unless I somehow missed it I think cfc13 is not yet in the table. I have replicated the format of the entry for cfc12 mole fraction in air, and made the necessary modifications.

**Comment by JonathanGregory** [comment]
Dear @joe-pitt 

I agree, CFC13 is not currently in the standard name table. Thanks for this proposal to fill the gap! It looks fine to me.

Cheers

Jonathan

**Comment by joe-pitt** [comment]
Thanks Jonathan! I also just noticed that hcfc132b and hcfc133a are missing too - should I create separate issues for these?

**Comment by JonathanGregory** [comment]
You could add hcfc132b and hcfc133a to this issue if you like. It's common for several standard names to be proposed in one issue. Jonathan

**Comment by joe-pitt** [comment]
OK great thanks - here are my suggestions...

**Proposer's name** Joe Pitt

**Date** 2023-08-25

**- Term** mole_fraction_of_hcfc132b_in_air

**- Description** "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula for HCFC132b is CH2ClCClF2. The IUPAC name for HCFC132b is 1,2-dichloro-1,1-difluoroethane

**- Units** 1

**Comment by joe-pitt** [comment]
**Proposer's name** Joe Pitt

**Date** 2023-08-25

**- Term** mole_fraction_of_hcfc133a_in_air

**- Description** "Mole fraction" is used in the construction "mole_fraction_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The chemical formula for HCFC133a is CH2ClCF3. The IUPAC name for HCFC133a is 2-chloro-1,1,1-trifluoroethane

**- Units** 1

**Comment by efisher008** [comment]
Hello @joe-pitt,

The time period mentioned above has now passed and so these names have been accepted. Thanks again for the proposal!

Best regards,
Ellie

**Comment by efisher008** [comment]
This issue has been closed as the above names were published in version 84 of the standard names table (visible [here](https://cfconventions.org/Data/cf-standard-names/84/build/cf-standard-name-table.html)).
