### ISSUE TITLE
Release of CF-1.11

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#264]
Hello,

At the [2023 CF meeting](https://cfconventions.org/Meetings/2023-Workshop.html), it was agreed to shift the the schedule of releasing new CF versions from just before the meeting, to just after it; with the exact timing decided on during the meeting.

- **The release of CF-1.11 will take place during the week starting 4th December 2023**

- **For a change to make it into this release, it's pull request must be finalised by 12th November 2023**, to guarantee that the 3 week cooling-off period is completed before the public release is created.

Many thanks,
Daivd

**Comment by davidhassell** [comment]
The list changes that are already going in to CF-1.11: https://github.com/cf-convention/cf-conventions/milestone/6?closed=1 (the contents of this page will get updated when more changes are accepted).

**Comment by DocOtak** [comment]
@davidhassell If most/all of the changes went in via a pull request, maybe try the auto generated release notes feature (https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by davidhassell** [comment]
Hello,

Just a reminder that for a change to make it into CF-1.11, its pull request must be finalised by **12th November 2023**, allowing a full three weeks cooling-off period prior to the release (remember typographical and editorial changes are still allowed during this period).

Many thanks,
David

**Comment by JonathanGregory** [comment]
Thank you very much, @davidhassell, for coordinating and producing the release of CF-1.11.

**Comment by ChrisBarker-NOAA** [comment]
Yes -- thanks! Great work.
