### ISSUE TITLE
 Standard names: soil water: liquid water content

### ISSUE THREAD

**Issue by taylor13** [cf-convention/discuss#267]
Karl E. Taylor
14 November 2023

Currently for soil water we have for column integrated amounts:

mass_content_of_water_in_soil
soil_frozen_water_content

For soil layer content we have:

mass_content_of_water_of_soil_layer
frozen_water_content_of_soil_layer
liquid_water_content_of_soil_layer

For CMIP we need the missing column total amount of liquid water, so I propose:

soil_liquid_water_content.

**Comment by JonathanGregory** [comment]
I agree that this proposal is consistent with the existing standard names. Thanks, @taylor13

**Comment by efisher008** [comment]
Hello @taylor13,

Thank you for the proposal, and thanks @JonathanGregory for the comment. I have added the name to the editor, and given that it is consistent with existing standard names as Jonathan says, the name will be accepted in the next 7 days unless there are any further comments on the issue.

For reference, the suggested phrases which I have added to the definition are the following:
"_Content" indicates a quantity per unit area. The "soil content" of a quantity refers to the vertical integral from the surface down to the bottom of the soil model. For the content between specified levels in the soil, standard names including "content_of_soil_layer" are used._" 
If there are any issues with this content please let me know. I've also given the units as kg m-2 (in keeping with the units of the existing standard name examples you gave), which I hope is correct.

Best regards,
Ellie

**Comment by taylor13** [comment]
Thanks.  Looks all good.

**Comment by efisher008** [comment]
This issue has been closed as the above names were published in version 84 of the standard names table (visible [here](https://cfconventions.org/Data/cf-standard-names/84/build/cf-standard-name-table.html)).
