### ISSUE TITLE
Modify description of `atmosphere_stability_k_index`

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/discuss#271]
The description of `atmosphere_stability_k_index` currently says _The index is derived from the difference in air temperature between 850 and 500 hPa, the dew point temperature at 850 hPa, and the difference between the air temperature and the dew point temperature at 700 hPa._ I propose that this sentence should be changed to _The index is the sum of three quantities: the difference in air temperature between 850 and 500 hPa, the dew point temperature at 850 hPa, and the difference between the air temperature and the dew point temperature at 700 hPa._ That would be more informative. Its definition is given by https://en.wikipedia.org/wiki/K-index_(meteorology). (Thanks to @larsbarring for this reference.) Jonathan

**Comment by efisher008** [comment]
Hello @JonathanGregory and @taylor13,

Looking at the article you provided a link to, is it definitely correct to say the index is the **sum** of these three quantities? According to the equation: 

![image](https://github.com/cf-convention/discuss/assets/108138256/4dc6b8b7-8286-4281-a93e-fc77fd23ee4a)
Where:
![image](https://github.com/cf-convention/discuss/assets/108138256/7525e8c8-d808-4072-bdb3-3ca0e4ae5256) = Dew point at 850 hPa
![image](https://github.com/cf-convention/discuss/assets/108138256/bb82e6ac-3122-430c-91d9-9b3d47c128d2) = Temperature at 850 hPa
![image](https://github.com/cf-convention/discuss/assets/108138256/5905aa0e-a22b-43a6-a913-760ae3a2b7aa) = Dew point at 700 hPa
![image](https://github.com/cf-convention/discuss/assets/108138256/97a2d5b7-fd97-451b-99d5-38d9838692be) = Temperature at 700 hPa
![image](https://github.com/cf-convention/discuss/assets/108138256/f8a478fa-e840-45a0-91b2-590f9c5557ed) = Temperature at 500 hPa

It seems to me as though the first two terms are summed i.e. added together, but the third (i.e. the difference between the air temperature and the dew point temperature at 700 hPa, the dewpoint depression at this pressure level) is subtracted from the total. Would using the phrase _'sum of'_ not imply that all terms are added together and so potentially lead to a misunderstanding of the calculation of K? 

Best regards,
Ellie

**Comment by JonathanGregory** [comment]
Dear Ellie @efisher008 

Yes, quite right, sorry, and thanks for checking. Evidently I read that too quickly. It arose because @larsbarring and I were discussing whether this quantity is `temperature: in-situ` or `temperature: difference`, and that's not possible to tell from the existing description. With your correction, we could write it (mostly) in words as "The index is calculated as _A_ + _B_ - _C_, where _A_ is the difference in air temperature between 850 and 500 hPa, _B_ is the dew point temperature at 850 hPa, and _C_ is the dew point depression at 700 hPa." Is that correct and clear? From this you can tell that the index is a `temperature: in-situ` quantity, because _A_ and _C_ are defined as differences, but _B_ is an in-situ temperature. Therefore the numerical value of the index will be different in `degC` and `K`. Without _B_, it would be a `temperature: difference` quantity, which is the same in `degC` and `K`.

Best wishes

Jonathan

**Comment by larsbarring** [comment]
@JonathanGregory: Just to clarify, what do you mean by `temperature: in -situ` ?

 If you are referring to the possible values of the new `units_metadata` attribute the possible values to go with a unit involving temperature are `temperature: difference`, `temperature: on_scale` and `temperature: unknown`, where the last alternative should only be used as a last resort if a data _reader_ cannot ascertain which of the other two alternatives it is. A data _writer_ should always select one of the other depending on the type of the data that is produced.

**Comment by JonathanGregory** [comment]
Sorry again! I mean `on_scale`, but wrote the wrong thing. Evidently I'm trying to do things too fast, or too may things, and consequently making stupider and more numerous mistakes than usual.

**Comment by taylor13** [comment]
@JonathanGregory and all,

I think I'd include the definition of "dew point depression" in the description since to some the sign of a "depression" might be confusing.  The end of the description could then read: "... and C is the dew point depression (i.e. the differences between actual temperature and dew point temperature) at 700 hPa."

**Comment by JonathanGregory** [comment]
Karl @taylor13, Yes, you're right (as always), and I agree that would be even more informative. Jonathan

**Comment by efisher008** [comment]
Dear @JonathanGregory, @taylor13 and @jwrotny74,

I thought it would be appropriate to link Jonathan @jwrotny74 into this conversation as he is listed as the proposer for the name we are discussing. I have proposed a change to the description of the existing name in the table. 

You can view the proposal [here](https://cfeditor.ceda.ac.uk/proposal/5130/edit), the description now reads:
_The atmosphere_stability_k_index is an index that indicates the potential of severe convection and is often referred to a simply the k index. The index is calculated as A + B - C, where A is the difference in air temperature between 850 and 500 hPa, B is the dew point temperature at 850 hPa, and C is the dew point depression (i.e. the differences between actual temperature and dew point temperature) at 700 hPa._

I wonder if it might be useful to insert the definition of dew point and/or dew point depression from the CF phrasebank into the description as well? These are:
_" Dew point temperature is the temperature at which a parcel of air reaches saturation upon being cooled at constant pressure and specific humidity."_
_" Dew point depression is also called dew point deficit. It is the amount by which the air temperature exceeds its dew point temperature."_

Please let me know your thoughts.

Best regards,
Ellie

**Comment by JonathanGregory** [comment]
Those are actually the descriptions of the standard names `dew_point_temperature` and `dew_point_depression`, aren't they? Given they are defined as standard names, the parenthetical "(i.e. the differences between actual temperature and dew point temperature) " doesn't seem necessary after all, especially if you insert those extra phrases. Is it usual to copy descriptions of standard names into the descriptions of other standard names?

**Comment by taylor13** [comment]
agree that no need to include parenthetical description if the additional descriptions are included.

**Comment by efisher008** [comment]
Hello @JonathanGregory and @taylor13,

You are right that those are the descriptions of those two standard names. I think they have been added to the phrasebank in the case that the terms are used as part of a longer name in future. Since `atmospheric_stability_k_index` doesn't contain either of these phrases, I think perhaps it is unnecessary to add the definitions of `dew_point_temperature` and `dew_point_depression` when they don't form part of the standard name itself? Another equally useful option would be what you suggest, i.e. adding both descriptions and removing the parenthetical description suggested by @taylor13. What would be your preference?

Best wishes,
Ellie

**Comment by taylor13** [comment]
I think there is no need to define "dew point temperature".  Anyone interested in ``atmospheric_stability_k_index`` will surely already know what dew point temperature is.  Fewer folks will know what sign ``dew_point_depression`` has, so I think the more concise phrasing in https://github.com/cf-convention/discuss/issues/271#issuecomment-1898638065 is preferable (but after correcting the typo by replacing "a simply" with "as simply").

**Comment by efisher008** [comment]
Hello @JonathanGregory and @taylor13,

It sounds like you've come to a conclusion about the description. Does this text look alright to both of you?

_"The atmosphere_stability_k_index is an index that indicates the potential of severe convection and is often referred to as simply the k index. The index is calculated as A + B - C, where A is the difference in air temperature between 850 and 500 hPa, B is the dew point temperature at 850 hPa, and C is the dew point depression (i.e. the amount by which the air temperature exceeds its dew point temperature) at 700 hPa."_

If you agree with this change and there are no further comments in the next 7 days, this term change can be accepted. 

Best wishes,
Ellie

**Comment by JonathanGregory** [comment]
Yes, that's fine. Thanks, Ellie.

**Comment by efisher008** [comment]
Hi all, 

Just to make you aware that this name has been included in the list of standard names in issue #270 who need text adding for the value of the `units_metadata` attribute. I've changed the status of the name from 'accepted' to 'under discussion' in the CF editor while this and the rest of the names from that issue are dealt with, which will mean expanding the description slightly. 

Best wishes,
Ellie

**Comment by efisher008** [comment]
Hi all, 

This name has been accepted along with the other names in issue #270 with additional text to clarify the use of the `units_metadata` attribute due to its use of temperature units. The next standard names table release (v85) is planned for the first half of April 2024. 

Best,
Ellie

**Comment by efisher008** [comment]
Closing this issue as this name has been accepted in version 85 of the CF standard names table, published on 21 May 2024 [(https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html)](https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html).
