### ISSUE TITLE
 Standard names: New Ocean BGC tracer variables (MPI-ESM)

### ISSUE THREAD

**Issue by SwatiGehlot** [cf-convention/discuss#274]
The below proposed are 5 new standard names for bio-geo-chemical tracer variables as a part of MPI-ESM model development within the German paleo-climate initiative, Project PalMod ([www.palmod.de](http://www.palmod.de/))

**Proposer's name:** Swati Gehlot, DKRZ, Hamburg
 (technical description via Bo Liu - bo.liu@mpimet.mpg.de)

**Date** 2024-01-17

**1. Preformed Phosphate Concentration**
**Term** mole_concentration_of_preformed_dissolved_inorganic_phosphorus_in_sea_water
**Description** The fraction of the dissolved inorganic phosphorus which is subducted from the sea surface and transported into the ocean interior.
**Units** mol m-3
**CMOR name** preformed_po4

**2. Preformed Oxygen Concentration**
**Term** mole_concentration_of_preformed_dissolved_molecular_oxygen_in_sea_water
**Description** The fraction of the dissolved oxygen which is subducted from the sea surface and transported into the ocean interior.
**Units** mol m-3
**CMOR** name preformed_o2

**3. Preformed Dissolved Inorganic Carbon Concentration**
**Term** mole_concentration_of_preformed_dissolved_inorganic_carbon_in_sea_water
**Description** The fraction of the dissolved inorganic carbon which is subducted from the sea surface and transported into the ocean interior. 
**Units** mol m-3
**CMOR** name preformed_dissic

**4. Preformed Dissolved Inorganic Carbon-13 Concentration**
**Term** mole_concentration_of_preformed_dissolved_inorganic_13C_in_sea_water
**Description** The fraction of the dissolved inorganic 13C which is subducted from the sea surface and transported into the ocean interior.
**Units** mol m-3
**CMOR** name preformed_dissic13

**5. Preformed Alkalinity Concentration**
**Term** sea_water_preformed_alkalinity_expressed_as_mole_equivalent
**Description** The fraction of alkalinity which is subducted from the sea surface and transported into the ocean interior.
**Units** mol m-3
**CMOR** name preformed_talk

**Comment by JonathanGregory** [comment]
Dear @SwatiGehlot

Thanks for your proposals. I have a few comments, as a non-expert:

* In the first one, do you mean phosphorus (as in the proposed standard name and description) or phosphate (as in the title and the CMOR name)?

* What does `preformed` mean? It would be useful to have an explanation of this word in the description. What is the difference between `mole_concentration_of_preformed_`_X_`_in_sea_water` and `mole_concentration_of_`_X_`_in_sea_water`? There are also a couple of standard names for `preformed_salinity` and I must confess I don't understand what it means there either.

* Existing `mole_concentration` standard names contain the following explanation in their description: _Mole concentration means number of moles per unit volume, also called "molarity", and is used in the construction mole_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical species denoted by X may be described by a single term such as 'nitrogen' or a phrase such as 'nox_expressed_as_nitrogen'._

Best wishes

Jonathan

**Comment by efisher008** [comment]
Dear @SwatiGehlot,

I have now added your proposed names into the CF editor. You can view them here.
1) `mole_concentration_of_preformed_dissolved_inorganic_phosphorus_in_sea_water`
link: [https://cfeditor.ceda.ac.uk/proposal/5133/edit](url)
2) `mole_concentration_of_preformed_dissolved_molecular_oxygen_in_sea_water`
link: [https://cfeditor.ceda.ac.uk/proposal/5134/edit](url)
3) `mole_concentration_of_preformed_dissolved_inorganic_carbon_in_sea_water`
link: [https://cfeditor.ceda.ac.uk/proposal/5135/edit](url)
4) `mole_concentration_of_preformed_dissolved_inorganic_13C_in_sea_water`
link: [https://cfeditor.ceda.ac.uk/proposal/5136/edit](url)
5) `sea_water_preformed_alkalinity_expressed_as_mole_equivalent`
link: [https://cfeditor.ceda.ac.uk/proposal/5137/edit](url)

I would agree with @JonathanGregory's questions. I think '_preformed_' might need its own definition in the description. If this is related to its origin from subducted material, this needs to be specifically stated i.e. _'"preformed" refers to a quantity which has been subducted from a pre-existing form at the sea surface'_ or something similar as you'd prefer. The standard name `sea_water_preformed_salinity` that Jonathan mentioned is described as _'Absolute Salinity ... minus all contributions to sea water composition from biogeochemical processes.'_ To me this also seems somewhat confusing in overlap with your usage so I'd be grateful if you could clarify this!

I would also second Jonathan's recommendation to add the `mole_concentration` definition to the description for each standard name. This is a standard and commonly used phrase for all mole_concentration names.

From a quick search, it would seem that @SwatiGehlot might be referring to phosphate ions in seawater (PO43−), which are 
"a dominant form of inorganic phosphorus in natural waters" ([doi:10.1016/C2009-0-01718-8](https://doi.org/10.1016/C2009-0-01718-8)). I think this could be referred to as DIP, unless this is a differently-defined quantity? But would appreciate any explanation you can give here.

Thanks and best regards,
Ellie

**Comment by BoLiu-MPIM** [comment]
Dear @JonathanGregory, dear @efisher008,

Thank you for the valuable input! @SwatiGehlot kindly submitted the new variables from my model data. In the following, I will address your questions. 

In the first term, “phosphorus” is meant for “dissolved inorganic phosphorus”, the sum of all inorganic phosphorus in solution (including phosphate, hydrogen phosphate, dihydrogen phosphate, and phosphoric acid), following the description of the existing standard name “po4”( https://clipc-services.ceda.ac.uk/dreq/u/ba9e25a4-e5dd-11e5-8482-ac72891c3257.html). 

I agree with both of you about adding the mole_concentration definition to the description for each standard name. 

Indeed, the definition of “preformed” should be elaborated. I adopt the definition by Redfield (1942), which is similar to what @efisher008 wrote: The subduction and subsequent transport of surface water carry into the interior ocean considerable quantities of nutrients, which are entirely independent of biological activity (such as organic decomposition and oxidation) after the water leaves the sea surface. Such nutrients are termed “preformed” nutrients. 

Redfield, A. C., The processes determining the concentration of oxygen, phosphate and other organic derivatives within the depths. Papers in Physical Oceanography and Meteorology, Massachusetts Institute of Technology and Woods Hole Oceanographic Institution, Vol. 9, No. 2, 1942.

Considering the above suggestions, I have updated the descriptions of the new variables; see below. I'd be happy to hear your further comments/suggestions! 

Cheers,
Bo


Preformed Dissolved Inorganic Phosphorus Concentration
Term: mole_concentration_of_preformed_dissolved_inorganic_phosphorus_in_sea_water
Description: "Mole concentration" means the number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Dissolved inorganic phosphorus" means the sum of all inorganic phosphorus in solution (including phosphate, hydrogen phosphate, dihydrogen phosphate, and phosphoric acid). The subduction and subsequent transport of surface water carry into the interior ocean considerable quantities of nutrients, which are entirely independent of biological activity (such as organic decomposition and oxidation) after the water leaves the sea surface. Such nutrients are termed “preformed” nutrients. 
Units: mol m-3
CMOR name: preformed_po4


Preformed Dissolved Oxygen Concentration
Term: mole_concentration_of_preformed_dissolved_molecular_oxygen_in_sea_water
Description: "Mole concentration" means the number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The subduction and subsequent transport of surface water carry into the interior ocean considerable quantities of dissolved oxygen, which are entirely independent of biological activity (such as organic decomposition and oxidation) after the water leaves the sea surface. Such dissolved oxygen is termed “preformed” dissolved oxygen. 
Units: mol m-3
CMOR name: preformed_o2

Preformed Dissolved Inorganic Carbon Concentration
Term: mole_concentration_of_preformed_dissolved_inorganic_carbon_in_sea_water
Description: "Mole concentration" means the number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Dissolved inorganic carbon" is the sum of CO3, HCO3 and H2CO3. The subduction and subsequent transport of surface water carry into the interior ocean considerable quantities of dissolved inorganic carbon, which is entirely independent of biological activity (such as organic decomposition and oxidation) after the water leaves the sea surface. Such dissolved inorganic carbon is termed “preformed” dissolved inorganic carbon.
Units: mol m-3
CMOR name: preformed_dissic


Preformed Dissolved Inorganic Carbon-13 Concentration
Term: mole_concentration_of_preformed_dissolved_inorganic_13C_in_sea_water
Description: "Mole concentration" means the number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Dissolved inorganic carbon-13" is the sum of CO3_13C, HCO3_13C and H2CO3_13C. The subduction and subsequent transport of surface water carry into the interior ocean considerable quantities of dissolved inorganic carbon-13, which is entirely independent of biological activity (such as organic decomposition and oxidation) after the water leaves the sea surface. Such dissolved inorganic carbon-13 is termed “preformed” dissolved inorganic carbon-13.
Units: mol m-3
CMOR name: preformed_dissic13


Preformed Alkalinity Concentration
Term: sea_water_preformed_alkalinity_expressed_as_mole_equivalent
Description: "Mole concentration" means the number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "Alkalinity" refers to total alkalinity equivalent concentration, including carbonate, borate, phosphorus, silicon, and nitrogen components. The subduction and subsequent transport of surface water carry into the interior ocean considerable quantities of alkalinity, which is entirely independent of biological activity (such as organic decomposition and oxidation) after the water leaves the sea surface. Such alkalinity is termed “preformed” alkalinity.
Units: mol m-3
CMOR name: preformed_talk

**Comment by BoLiu-MPIM** [comment]
Hi @efisher008,

Yes, I fully agree with you to add the citation "(Redfield, 1942)" in the text!

Bests,
Bo

**Comment by efisher008** [comment]
Hi Bo,

I'm glad you agree! I will add this to the end of the description for each of the 5 proposed names. If there are no further comments after 7 days, these names will be accepted and published in the next standard names table release. Thanks again for the proposal and enjoy your weekend.

Best wishes,
Ellie

**Comment by BoLiu-MPIM** [comment]
Thank you, @efisher008, for the prompt response! 
You too have a lovely weekend!
-Bo

**Comment by efisher008** [comment]
Hi Bo,

Apologies for the late reply. I've accepted these names now, and they will be added to the next release of the standard names table, which is planned for the first half of April. Thanks again for the proposal!
 
Best regards,
Ellie

**Comment by efisher008** [comment]
Closing this issue as these names have been accepted in version 85 of the CF standard names table, published on 21 May 2024 [(https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html)](https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html).
