### ISSUE TITLE
CF meeting: 17-20 September 2024

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#279]
Dear CF community,

Following on from the [announcement](https://github.com/cf-convention/discuss/issues/276) that this year's CF workshop will be held at SMHI, Norrköping, Sweden (and online) in September, we'd like to announce the formal dates for the meeting:

### **Tuesday 17th - Friday 20th September 2024**

Many thanks to all those who helped to select these times.

As previously announced, the meeting will be divided into two parts, and participants may choose to attend the first two days of the programme, the last two days, or the whole meeting, according to their own interests and availability:

  - **Part 1 (17-18 September 2024)**: Engaging the cross-domain CF community to gather user needs and develop a high-level CF roadmap.
  - **Part 2 (19-20 September 2024)**: Detailed CF development including hackathon sessions.

* The plan for **Part 1** of the workshop is to invite speakers from a broad range of CF users and potential users, for example, representatives of data producers and data archives in the earth system sciences, the health and biological research communities.
  * The aim is to maximise the usefulness of CF to a wide range of communities, encourage others to join and contribute to the CF community effort, and enhance interoperability with other widely used standards. 
  * The desired outcome is a publication of the proceedings, including a roadmap for development of the CF conventions and vocabularies over the next 1 to 5 years.

* **Part 2** will follow the familiar format of our usual annual meeting.

If you are interested in helping to set the meeting agenda, please comment on this issue, or even join the organising committee (there's still room for more help!)

Many thanks,
Lars Bärring, Ethan Davis, David Hassell, Alison Pamment, Ellie Fisher

**Comment by davidhassell** [comment]
Hello,

As you may have seen on other forums, [registration for the 2024 CF meeting is now open](https://www.smhi.se/en/research/research-departments/climate-research-at-the-rossby-centre/cf-community-workshop-2024-1.207332).

You can register for both Parts I and II, or just one of those. 

Many thanks,
Lars Bärring, Ethan Davis, David Hassell, Alison Pamment, Ellie Fisher, Kevin O'Brien

**Comment by japamment** [comment]
Dear CF community,

The program for the upcoming CF 2024 meeting is taking shape!

**Where:** In-person, SMHI, Norrköping, Sweden and online
**When:** Part 1 17-18 September 2024.  Part 2 19-20 September 2024.

Please take a look at the current program on the [SMHI website](https://www.smhi.se/en/research/research-departments/climate-research-at-the-rossby-centre/cf-community-workshop-2024-1.207332) where you can also **register to attend**.

Program development is continuing and we are still adding more speakers.

Information about the meeting is also available on the [Meetings section](http://cfconventions.org/Meetings/2024-Workshop.html) of the CF website.

Best wishes,
Alison
