### ISSUE TITLE
Standard names: Update definitions of all cloud_liquid_water names

### ISSUE THREAD

**Issue by japamment** [cf-convention/discuss#28]
Proposer: Alison Pamment
Date: 3 February 2020

The descriptions of all 45 existing cloud_liquid_water standard names need to be updated to add the following text:
' "Cloud liquid water" refers to the liquid phase of cloud water. A diameter of 0.2 mm has been suggested as an upper limit to the size of drops that shall be regarded as cloud drops; larger drops fall rapidly enough so that only very strong updrafts can sustain them. Any such division is somewhat arbitrary, and active cumulus clouds sometimes contain cloud drops much larger than this. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Cloud_drop.'

This text was agreed in [issue #19](https://github.com/cf-convention/discuss/issues/19). The changes will be added in the March standard names update.

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table.
