### ISSUE TITLE
CF Convention for Covariance Matrices

### ISSUE THREAD

**Issue by Bruce-T-T-Calvert** [cf-convention/discuss#283]
Hi,

I have a netcdf file that failed the [CF-checker tool](https://cfchecker.ncas.ac.uk/) for CF-1.8 because it has repeated dimensions, in this case latitude dimensions. Covariance matrices are supposed to have repeated dimensions by design. I don't see guidelines on covariance matrices within the [CF convention guidelines](https://cfconventions.org/cf-conventions/cf-conventions.html), including if it says repeated dimensions are not allowed.

Is it possible to have covariance matrices consistent with CF conventions? Are repeat dimensions acceptable and is there just a mistake with the CF checker tool? Should I have separate variable names for the repeated dimensions? Should I find some workaround such as converting the covariance matrix into a single vector (which would make things less intuitive and user friendly).

The covariance matrices of [HadSST4](https://www.metoffice.gov.uk/hadobs/hadsst4/data/download.html) claim to be compatible with CF-1.7 and use separate variable names for repeat latitude and longitude dimensions. In this case, HadSST4 uses "latitude_vector_1", "longitude_vector_1", "location_index_1", "latitude_vector_2", "longitude_vector_2", and "location_index_2" as its coordinates or dimensions. Is this the approach that I should take for covariance matrices?

Best regards,
Bruce Calvert

**Comment by Bruce-T-T-Calvert** [comment]
Thank you Jonathan,

Your quick and helpful reply is greatly appreciated! I feel a bit silly for overlooking the relevant text in section 2.4.

Best regards,
Bruce

**Comment by JonathanGregory** [comment]
Dear @Bruce-T-T-Calvert 

There's no need to be embarrassed! CF is a very large document to keep in mind, and the CF checker has occasionally been wrong.

Best wishes

Jonathan
