### ISSUE TITLE
 Standard names: area_cover_lccs -- outdated advice in help text.

### ISSUE THREAD

**Issue by martinjuckes** [cf-convention/discuss#29]
**Proposer's name** Martin Juckes
**Date** 4th Feb, 2020
**Term**  `land_cover_lccs` and  `land_cover_lcml`

The `land_cover_lccs` standard name, which refers to the UN Land Cover Classification System. The reference given in the help text is a web page from 2000 explaining the system and motivation behind the terms, but getting at the terms requires running the database on a computer with windows 95/98 or NT, apparently. It appears that LCCS has evolved to become a software tool and the terms the community is now using are in the Land Cover Meta Language (LCML), which is an ISO standard (ISO 19144-2:2012). This suggests, I think, we need to be cautious about how external references are introduced. 

One option would be to introduce `area_cover_lcml` and make `area_cover_lccs` an alias. 

The current text says that the value assigned to the land cover should be "combinations of classifiers". The classifiers in question (for the current LCML standard) are of the form `LC_WoodyGrowthForm`, `LC_BroadLeaf`, `LC_Evergreen`. There needs to be some guidance on how these are to be combined: e.g. as a space separated list.

**Comment by feggleton** [comment]
Hi Martin,

Thanks for this proposal, I will have a further look into the LCML and think about this change. I have added this to the cfeditor as a change to the existing name (and therefore an alias). This will need to be a change in the name and definition if it were to go ahead. We will need to think about this. The definition is below (the obvious change would be the reference part etc but the first part needs discussion):

A variable with the standard name of land_cover_sccs contains strings which indicate the nature of the surface, e.g. cropland_..., tree_... . These strings are standardised. Values must be combinations of classifiers from the Land Cover Classification System (LCCS; Di Gregorio A., 2005, UN Land Cover Classification System (LCCS) - Classification concepts and user manual for Software version 2; available at www.fao.org/DOCREP/003/X0596E/X0596e00.htm).

**Comment by martinjuckes** [comment]
Hi Fran,

The `land_cover_lccs` term is used by the ESA Land Cover CCI held at [CEDA](https://catalogue.ceda.ac.uk/uuid/4761751d7c844e228ec2f5fe11b2e3b0). They include a specific list of terms constructed using the LCCS methodology in their dataset documentation. 

Since the term is in current use, perhaps it is better to adjust the description, rather than create a new term. Strings such as "cropland" are not explicitly mentioned in LCCS, so it is misleading to say that the strings themselves are standardised. LCCS works on the basis of codes such as `A.1.2.1` which have a description): the way it is used by ESA CCI is to construct a label based on the LCCS classification system using a pragmatic combination terms to represent the LCCS classes, e.g. `Tree cover, mixed leaf type (broadleaved and needleleaved)`. 

E.g.
> A variable with the standard name of land_cover_sccs contains strings which indicate the nature of the surface, e.g. cropland_..., tree_... . Each string should represent a land cover class constructed using the Land Cover Classification System (LCCS; Di Gregorio A., 2005, UN Land Cover Classification System (LCCS) - Classification concepts and user manual for Software version 2; available at www.fao.org/DOCREP/003/X0596E/X0596e00.htm). String values should represent the classifiers used to define each class.

**Comment by feggleton** [comment]
Hi Martin,

Thanks for bringing that to attention, good to know. If it still being actively used lets do what you suggest and change the definition slightly to be clearer. Just to check, am I right in thinking there is also a typo in this definition 'land_cover_sccs'? or is that intentional? So, in addition to that wording change do we also want to create a new term for land_cover_lcml or mention it in the lccs definition maybe? It would be good to see if any others have thoughts on the use of this term or how to go forward. 

I have updated creditor with this definition update for now and we'll see if any further changes need to be made.

**Comment by martinjuckes** [comment]
Yes, I think `sccs` is a straight typo for `lccs`. A new term for `land_cover_lcml` would have some advantages, but I don't think we should introduce it without a clear request from users.

**Comment by feggleton** [comment]
Ok thanks Martin. So definition change is as below for clafirication:

Term: land_cover_lccs
A variable with the standard name of land_cover_lccs contains strings which indicate the nature of the surface, e.g. cropland_..., tree_... . Each string should represent a land cover class constructed using the Land Cover Classification System (LCCS; Di Gregorio A., 2005, UN Land Cover Classification System (LCCS) - Classification concepts and user manual for Software version 2; available at www.fao.org/DOCREP/003/X0596E/X0596e00.htm). String values should represent the classifiers used to define each class.

If there is no further comments or discussion in the next week or so this simple clarification can be accepted.

**Comment by feggleton** [comment]
There have been no further comments on this simple change in the definition to give clarity, so this will be accepted into the next update (23rd June). Thanks, Fran
