### ISSUE TITLE
 Standard names: Propose new additions to the standard names table

### ISSUE THREAD

**Issue by fmoconnor** [cf-convention/discuss#299]
On behalf of the Tropospheric Ozone Assessment Report working group on ozone radiative forcing, I would like to propose standard names for the radiative fluxes from a diagnostic call to a model's radiation scheme using a reference ozone field. These flux diagnostics are analogous to those from an aerosol-free diagnostic call to a model's radiation scheme (e.g., rsdcsaf; downwelling_shortwave_flux_in_air_assuming_clear_sky_and_no_aerosol), but in this case, the diagnostics refer to a call to the radiation scheme using a reference field for ozone. 

The proposed names for the 3D radiative flux diagnostics are:

1. rsdo3ref       downwelling_shortwave_flux_in_air_assuming_referenceo3                              W/m2
Downwelling radiation is radiation from above. It does not mean "net downward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "shortwave" means shortwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase "assuming_condition" indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

2. rsdcso3ref    downwelling_shortwave_flux_in_air_assuming_clear_sky_and_referenceo3       W/m2
Downwelling radiation is radiation from above. It does not mean "net downward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "shortwave" means shortwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase "assuming_condition" indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds.

3. rsuo3ref       upwelling_shortwave_flux_in_air_assuming_referenceo3                                   W/m2
Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "shortwave" means shortwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase "assuming_condition" indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

4. rsucso3ref    upwelling_shortwave_flux_in_air_assuming_clear_sky_and_referenceo3           W/m2
Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "shortwave" means shortwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase "assuming_condition" indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds.

5. rldo3ref       downwelling_longwave_flux_in_air_assuming_referenceo3                                W/m2
Downwelling radiation is radiation from above. It does not mean "net downward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "longwave" means longwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

6. rluo3ref       upwelling_longwave_flux_in_air_assuming_referenceo3                                     W/m2
The term "longwave" means longwave radiation. Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

7. rldcso3ref   downwelling_longwave_flux_in_air_assuming_clear_sky_and_referenceo3          W/m2
Downwelling radiation is radiation from above. It does not mean "net downward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "longwave" means longwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds.

8. rlucso3ref   upwelling_longwave_flux_in_air_assuming_clear_sky_and_referenceo3               W/m2
The term "longwave" means longwave radiation. Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds.

The proposed names for the corresponding top-of-atmosphere (TOA) diagnostics are:

1.  rsuto3ref      toa_outgoing_shortwave_flux_assuming_referenceo3                                       W/m2
The abbreviation "toa" means top of atmosphere. The term "shortwave" means shortwave radiation. The TOA outgoing shortwave flux is the reflected and scattered solar radiative flux i.e. the "upwelling" TOA shortwave flux, sometimes called the "outgoing shortwave radiation" or "OSR". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase "assuming_condition" indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

2. rsutcso3ref   toa_outgoing_shortwave_flux_assuming_clear_sky_and_referenceo3                 W/m2
The abbreviation "toa" means top of atmosphere. The term "shortwave" means shortwave radiation. The TOA outgoing shortwave flux is the reflected and scattered solar radiative flux i.e. the "upwelling" TOA shortwave flux, sometimes called the "outgoing shortwave radiation" or "OSR". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase "assuming_condition" indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds.

3. rluto3ref       toa_outgoing_longwave_flux_assuming_referenceo3                                         W/m2
A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "longwave" means longwave radiation. "toa" means top of atmosphere. The TOA outgoing longwave flux is the upwelling thermal radiative flux, often called the "outgoing longwave radiation" or "OLR". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics.

4. rlutcso3ref   toa_outgoing_longwave_flux_assuming_clear_sky_and_referenceo3                   W/m2
A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "longwave" means longwave radiation. "toa" means top of atmosphere. The TOA outgoing longwave flux is the upwelling thermal radiative flux, often called the "outgoing longwave radiation" or "OLR". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. "Clear sky" means in the absence of clouds.

The proposed name for the reference ozone field used in the diagnostic call to the radiation scheme is:
o3ref               mole_fraction_of_reference_ozone_in_air                                                             mol/mol
This ozone field acts as a reference ozone field in a diagnostic call to the radiation scheme. Mole fraction is used in the construction mole_fraction_of_X_in_Y, where X is a material constituent of Y.

Proposer's name: Fiona O'Connor
Date: 19 March 2024

**Comment by fmoconnor** [comment]
There are an additional set of proposed radiative flux diagnostics for the surface that are linked with the 3D and top-of-atmosphere proposed diagnostics above. These are listed as follows:

1. rsdso3ref        surface_downwelling_shortwave_flux_in_air_assuming_referenceo3                             W/m2
The surface called "surface" means the lower boundary of the atmosphere. Downwelling radiation is radiation from above. It does not mean "net downward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "longwave" means longwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

2. rsdscso3ref     surface_downwelling_shortwave_flux_in_air_assuming_clear_sky_and_referenceo3     W/m2
The surface called "surface" means the lower boundary of the atmosphere. Downwelling radiation is radiation from above. It does not mean "net downward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "longwave" means longwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds.

Proposer's name: Fiona O'Connor
Date: 19 March 2024

3. rsuso3ref        surface_upwelling_shortwave_flux_in_air_assuming_referenceo3                                  W/m2
The surface called "surface" means the lower boundary of the atmosphere. Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "shortwave" means shortwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase "assuming_condition" indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

4. rsuscso3ref    surface_upwelling_shortwave_flux_in_air_assuming_clear_sky_and_referenceo3            W/m2
The surface called "surface" means the lower boundary of the atmosphere. Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "shortwave" means shortwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase "assuming_condition" indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds.

5. rldso3ref        surface_downwelling_longwave_flux_in_air_assuming_referenceo3                               W/m2
The surface called "surface" means the lower boundary of the atmosphere. Downwelling radiation is radiation from above. It does not mean "net downward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "longwave" means longwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

6. rluso3ref        surface_upwelling_longwave_flux_in_air_assuming_referenceo3                                    W/m2
The surface called "surface" means the lower boundary of the atmosphere. Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "longwave" means longwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. 

7. rldscso3ref    surface_downwelling_longwave_flux_in_air_assuming_clear_sky_and_referenceo3         W/m2
The surface called "surface" means the lower boundary of the atmosphere. Upwelling radiation is radiation from below. It does not mean "net upward". The sign convention is that "upwelling" is positive upwards and "downwelling" is positive downwards. The term "longwave" means longwave radiation. When thought of as being incident on a surface, a radiative flux is sometimes called "irradiance". In addition, it is identical with the quantity measured by a cosine-collector light-meter and sometimes called "vector irradiance". In accordance with common usage in geophysical disciplines, "flux" implies per unit area, called "flux density" in physics. A phrase assuming_condition indicates that the named quantity is the value which would obtain if all aspects of the system were unaltered except for the assumption of the circumstances specified by the condition. "Clear sky" means in the absence of clouds.

**Comment by larsbarring** [comment]
Thank you Fiona @fmoconnor for these detailed and carefully crafted proposals.

I am neither an expert in this particular science area, nor in the construction of standard names, but I will venture a couple of comments anyway:
* The proposed `mole_fraction_of_reference_ozone` is similar to `mole_fraction_of_ozone`, which is good. But I guess that it the ""mole_fraction" that is the reference. Hence I think that `reference_mole_fraction_of_ozone` might be more descriptive.
* In many (all?) proposals you use the phrase `..._referenceo3`, but "o3" was replaced by "ozone" in early days of the standard name table. Hence, I suggest to use `..._reference_ozone`, or perhaps even the longer but more unambiguous `..._reference_ozone_mole_fraction` if there ever is a chance that someone might come up with another way to quantify "reference ozone".

**Comment by JonathanGregory** [comment]
Dear Fiona @fmoconnor 

Thanks for your proposals. I agree with your approach of adding an `assuming` condition. I agree with @larsbarring that the condition should indicate how the reference field is specified i.e. as `mole_fraction` (as Lars writes), `mole_concentration`, `mass_concentration`, etc. There are a few possibilities in the standard name table. The phrase `assuming_clear_sky_and_reference_`_Q_`_of_ozone_` would follow the pattern of existing standard names for ozone in air, where _Q_ is `mole_fraction` or whatever.  Also, it would be good to add a sentence or two to the description of the standard names about this reference ozone field.

Best wishes

Jonathan

**Comment by fmoconnor** [comment]
Dear Lars and Jonathan @larsbarring  @JonathanGregory 

Thanks both for taking the time to review and comment on my proposed variable names. I agree with the proposed change from `o3` to `..._ozone`. I also agree with the suggestion to expand the text following `assuming` to incorporate more information on the ozone reference. 

I also agree with adding a few more sentences in the description of the reference ozone field. How about the following: 

`This 3D ozone field acts as a reference ozone field in a diagnostic call to the model's radiation scheme. It is expressed in terms of mole fraction of ozone in air. It may be observation-based or model-derived. It may be from any time period. By using the same ozone reference in the diagnostic radiation call in two model simulations and calculating differences between the radiative flux diagnostics from the prognostic call to the radiation scheme and the diagnostic call to the radiation scheme with the ozone reference, an instantaneous radiative forcing for ozone can be calculated`?

What I'm unclear about (and this is my first time proposing names, so please excuse my lack of relevant knowledge) is the rationale for using `reference_mole_fraction_of_ozone` rather than `mole_fraction_of_reference_ozone`. Can you explain the rationale? Would `mole_fraction_of_ozone_reference_in_air` be a possibility?

Thanks,
Fiona

**Comment by larsbarring** [comment]
Regarding the part following `assuming_` I think Jonathan's suggestion `assuming_clear_sky_and_reference_Q_of_ozone` is better than mine (as always :-). And regarding the additional sentences for describing the reference ozone field, I wonder how much of this is specific to you application, and what is actually required to describe the *standard name* as such, even when it might be used in a different context than your particular project. Typically we try to find a precise enough description of the *physical quantity* rather than how this quantity is used in any particular situation. Admittedly there is a balance here, so this is really a question. Finally, regarding where to put the phrase `reference`, my thinking was that ozone is what it is, there is nothing like "reference ozone" as opposed to some other type of ozone.  For "mole fraction" the situation is the opposite, it can be a fixed reference value (or field), it can be time-evolving in a model or from observations, it can be parameterised, and so on. But maybe my limited language skills are playing games here.

**Comment by JonathanGregory** [comment]
Dear Fiona @fmoconnor 

Thanks for considering this. I think your extra text is good. Is there also a need to record some metadata (in some other attributes) about reference ozone field? - its dates and source, for instance. This would matter for comparing datasets from different sources, I suppose, since your words suggest it is not a universal convention.

As for the `assuming` phrase, I would say there are _no "rules"_ for this situation. As in other cases, we are trying to construct something that has the general style of standard names, in the hope that consistency makes it easier for users to digest them. I tend to think it's better, where possible, to use existing standard names verbatim when there's a need to include them in a new standard name. For that reason I'd prefer not to insert `reference` in the midst of `mole_fraction_of_ozone_in_air`, which is an existing standard name. I would prefer `reference_mole_fraction_of_ozone_in_air` to `mole_fraction_of_reference_ozone_in_air` or `mole_fraction_of_ozone_reference_in_air`. Besides that, I agree with Lars that it's really the "mole fraction" which is standardised as the reference, rather than the ozone. But perhaps you see some reason why it wouldn't be so good to put `reference` first?

Best wishes

Jonathan

**Comment by efisher008** [comment]
Dear Fiona,

I have added the proposed names to the editor (I counted 20 terms in total, including the standalone `mole_fraction_of_reference_ozone_in_air`) and updated the names and descriptions by changing `o3` to `_ozone` and adding the [extra text for the description of the reference ozone field](https://github.com/cf-convention/discuss/issues/299#issuecomment-2010498281). I assumed this was intended to be added to all names with `assuming_reference_ozone` in the name - would that be correct?

Thanks and best regards,
Ellie

**Comment by JonathanGregory** [comment]
Dear Ellie @efisher008 and Fiona @fmoconnor 

If Fiona is OK with it, I think `assuming_clear_sky_and_reference_mole_fraction_of_ozone_in_air`  would be best, as the most explicit, and consistent with the existing standard name of `mole_fraction_of_ozone_in_air`.

Best wishes

Jonathan

**Comment by fmoconnor** [comment]
Thank you @efisher008 I'm happy with what @JonathanGregory has proposed above for the text after `assuming`. 

Also, if I interpret the comments from @JonathanGregory and @larsbarring correctly, I think we were also proposing that the standalone ozone variable name should be `reference_mole_fraction_of_ozone_in_air` - this makes it consistent with what will be added after `assuming`.

**Comment by JonathanGregory** [comment]
Yes, I agree that reference_mole_fraction_of_ozone_in_air would be sensible as a stdname in its own right. J

**Comment by efisher008** [comment]
Hi all,

I've made the changes mentioned [here](https://github.com/cf-convention/discuss/issues/299#issuecomment-2020351995) and [here](https://github.com/cf-convention/discuss/issues/299#issuecomment-2020421269). Looking forward to more discussion.

Best,
Ellie

**Comment by efisher008** [comment]
Hi,

Are there any further comments on the format of these standard names? 

Best regards,
Ellie

**Comment by larsbarring** [comment]
With the recent updated from Fiona and Jonathan I am all good /L

**Comment by efisher008** [comment]
Hi Fiona, 

As all changes appear to be agreed, your proposed standard names can be accepted after 7 days have passed, if there are no further comments or suggestions. I'll update you when that happens. They will then be published in the next release of the standard names table (v85), which is currently planned for mid-May. 

Best wishes,
Ellie

**Comment by taylor13** [comment]
Just a couple of things I noticed.  The original proposed description of the new standard names included a variable name (e.g.., rsdo3ref , rsdcso3ref, ...).  I trust these will not appear in the standard name table.

I note that in CMIP6, the following somewhat-related standard names can be found:
```
toa_instantaneous_longwave_forcing 
toa_instantaneous_shortwave_forcing
toa_longwave_dust_ambient_aerosol_particles_direct_radiative_effect_assuming_clear_sky
toa_instantaneous_shortwave_forcing_due_to_dust_ambient_aerosols_assuming_clear_sky
toa_outgoing_longwave_flux_due_to_volcanic_ambient_aerosol_particles_assuming_clear_sky
surface_downwelling_longwave_flux_in_air_due_to_volcanic_ambient_aerosol_particles
surface_downwelling_longwave_flux_in_air_due_to_volcanic_ambient_aerosol_particles
surface_net_downward_longwave_dust_ambient_aerosol_particles_direct_radiative_effect_assuming_clear_sky
surface_net_downward_shortwave_dust_ambient_aerosol_particles_direct_radiative_effect
```

Standard names were also needed for recording radiative fluxes in the presence of 4XCO2, but instead non-specific existing standard names were used.  Just wanted to point out that ozone is not the only species where standard names like these are needed.  We should try to make sure the names are consistent.

**Comment by fmoconnor** [comment]
Agree with above comment by @taylor13 - in fact, if (or should I say when?!) these names are accepted into the standard, my intention was to follow up with a corresponding set of names for a methane double radiation call. But as rightly pointed out, the suggested names could be expanded out further to include diagnostics from all potential diagnostic radiation calls for the different greenhouse gases (e.g., nitrous oxide, carbon dioxide). May get complicated for halogenated greenhouse gases as the names will depend on the level of speciation handled by different models' radiation schemes.

**Comment by efisher008** [comment]
Hi @taylor13,

The variable names (rsdo3ref , rsdcso3ref etc.), which I understood as clarifying parts of the diagnostic call to the model, are not part of the entries in the CF editor. If these are necessary to include somehow, I would suggest making reference to them in the name descriptions.

@fmoconnor are there any changes you would like to make to the proposed names for reference ozone in light of the existing non-specific standard names @taylor13 has mentioned? 

Best,
Ellie

**Comment by taylor13** [comment]
To be clear, I think the standard names proposed here for radiative fluxes with a reference ozone mole fraction imposed do not need further modification.  I would say these new names are more specific and therefore better than "ambient", which is used for aerosols.  In the case of aerosols, of course, we would not only need concentration but also their optical properties to define a "reference", so maybe the existing standard names for aerosol radiative fluxes is as good as we can do.

**Comment by efisher008** [comment]
I see - thank you for clarifying @taylor13, I think I misunderstood the meaning of your earlier comment. If @fmoconnor you are happy with these names, then they can be accepted early next week and you can then proceed with proposed names for diagnostics from radiation scheme calls for other greenhouse gases, as far as you are comfortable to expand this.

**Comment by fmoconnor** [comment]
@efisher008 @taylor13 Apologies for the misunderstanding about the inclusion of the short names, e.g., "rsdo3ref" - I was proposing these as the corresponding output variable name to be associated with the proposed standard variable name. I now realise that output variable names are not part of the CF standard. On that basis, they should not be included in the proposed CF standard names. 

P.S. Some guidance on how these proposed output variable names can be accepted as "standard" so that they could potentially be proposed for a CMIP data request would be useful although I recognise this ask is outside the scope of this issue!

**Comment by taylor13** [comment]
The variable names in CMIP are constructed following historical precedent (starting with AMIP ca. 1990).  We are working on guidelines for adding names to the list.  One rule is clear (but a few exceptions exist in CMIP): the same variable name cannot apply to more than one standard_name.  The converse is not true: in about 10% of the more than 2000 variables defined for CMIP6, more than one variable name is associated with the same standard_name.  

Once the guidelines are finalized, you should be able to propose a variable name, which would be vetted before being accepted as part of CMIP.

**Comment by fmoconnor** [comment]
Thank you @taylor13 for your response - that's really helpful and I'll await the guidelines!

**Comment by efisher008** [comment]
Dear Fiona @fmoconnor,

Thank you again for your proposal. The 19 total proposed names in this issue have now been accepted in the CF editor, and will be published in the next release of the standard names table (v85), which is expected in mid-May 2024 (there will be an announcement on the CF Conventions GitHub when this happens). Please let me know if I can help with anything else!

Best regards,
Ellie

**Comment by fmoconnor** [comment]
Thanks @efisher008 

I've looked at the CF editor (http://cfeditor.ceda.ac.uk/proposals/1) and *think* there may be an error in the entries!

For example, for the 3D downwelling shortwave flux with the reference ozone field, there should be two standard names: 
1. downwelling_shortwave_flux_in_air_assuming_clear_sky_and_reference_mole_fraction_of_ozone_in_air
2. downwelling_shortwave_flux_in_air_assuming_reference_mole_fraction_of_ozone_in_air
with the second one referring to "all sky". However, in the CF editor, I think the first entry above is repeated twice. 

This repetition also appears to occur for the other variables, e.g., upwelling_shortwave, downwelling longwave, etc.

Can you please take a look and correct them?

Thanks,
Fiona

**Comment by efisher008** [comment]
Hi Fiona, 

Thank you very much for catching that and I apologise for the mix-up! It looks like I made the distinction between "clear sky" and "all sky" (i.e. `assuming_reference_mole_fraction_of_ozone_in_air`) for the 3D radiative flux diagnostics names in your first post, but not for the other sets. I've been through and corrected these. These were also changed for the surface and TOA variables e.g. `surface_upwelling_shortwave_flux,`, `toa_outgoing_longwave_flux`. I hope this is now as you'd intended, and please let me know if everything seems in order. 

I've noticed there is only one entry for `surface_upwelling_longwave_flux` (no "clear sky" version), is this intentional? Your [second set](https://github.com/cf-convention/discuss/issues/299#issuecomment-2007757730) of proposed names only includes one name with this format, whereas the other surface names have both "clear sky" and "all sky" versions.

Best wishes,
Ellie

**Comment by fmoconnor** [comment]
@efisher008 Apologies for the delay in replying. In response to your query on <surface_upwelling_longwave_flux>, we only expect a single diagnostic/name. Thanks for all your help, and sorry again for the delay on my part.
