### ISSUE TITLE
Depth to Bedrock ?

### ISSUE THREAD

**Issue by gnikulin** [cf-convention/discuss#303]
In CORDEX we have a request for a variable which we call Depth to Bedrock (lower boundary of land surface models). In the CF Standard Name Table I only found `bedrock_altitude` (also discussions here  https://github.com/cf-convention/discuss/issues/2). Should we request a new standard name (e.g. `bedrock_depth`) or may be there is something similar that can be used ?

**Comment by JonathanGregory** [comment]
Dear Grigory @gnikulin 

Thanks for the question. Following the usual meanings in standard names, `bedrock_depth` would mean the vertical distance of the top of the bedrock below the solid surface (the bottom of the atmosphere). Is that what you mean by it? An alternative, which might mean the same thing in practice and might be clearer, would be to call it `soil_thickness`. What do you (and others) think?

Cheers

Jonathan

**Comment by gnikulin** [comment]
Thanks  Jonathan !!!!

Yes, a better alternative to `bedrock_depth` is indeed something like `soil_thickness` (e.g. the thickness of the permeable soil layer above bedrock). I see that soil depth is also used sometimes with the same meaning (e.g. the distance from the soil surface to the underlying bedrock). I'll check with experts whether `soil_thickness` fits or not.

**Comment by JonathanGregory** [comment]
Thanks, Grigory. In CF standard names, we use the word `thickness` for the vertical extent of a layer. As you say, the word "depth" is sometimes used to mean "thickness", but in CF standard names `depth` means the vertical distance below the Earth's surface (solid or sea level, bottom of the atmosphere).

**Comment by gnikulin** [comment]
It took a bit of time to discuss this issue with several groups working with land surface models. It was noted that  in a geological sense`soil_thickness` is not always equal to `depth_to_bedrock`. Soil is the product of pedogenesis, but between soil and bedrock, much sediment, mineral material might be deposited still. Fore example [this dataset](https://daac.ornl.gov/SOILS/guides/Global_Soil_Regolith_Sediment.html) provides "the thickness of the permeable layers above bedrock (soil, regolith, and sedimentary deposits)" Of course, it depends on the definition of soil and in climate modelling, I think,  we always  assume that the soil layer is a permeable layer between the surface and bedrock. Perhaps `depth_to_bedrock` helps to avoid any ambiguity  ?

**Comment by taylor13** [comment]
I think  ``depth_to_bedrock`` would be correctly interpreted by most folks, but ``bedrock_depth`` might be misinterpreted by some as the thickness of bedrock.  (But I could be wrong about that.)

**Comment by JonathanGregory** [comment]
I suggest `bedrock_depth_below_ground_level`, on the pattern of the existing name `sea_floor_depth_below_sea_surface`. Would that be clear?

**Comment by taylor13** [comment]
that's even clearer to me.  Grisha (@gnikulin), what do you think?

**Comment by efisher008** [comment]
Dear Grigory @gnikulin,

As it looks like the format of the prospective standard name has been agreed, would you now like to make the official proposal for the name? This should include the standard name, units, description, and proposer name and date. This can be done in this issue or you can open a new one if you'd prefer.

Best regards,
Ellie

**Comment by gnikulin** [comment]
Thanks Ellie !!! I can propose the name in this issue.

New standard name:  `bedrock_depth_below_ground_level`
Units: `m`
Description: `The bedrock_depth_below_ground_level is the vertical distance between the ground and the bedrock`
Proposer name: Grigory Nikulin
Date: 2023-04-03

I'm not sure if the proposed description is enough or we need more details ?

Best regards,

Grisha.

**Comment by taylor13** [comment]
Some may think otherwise, but I think the description is sufficient (once a period is added to the end of the sentence).

**Comment by efisher008** [comment]
Thank you @gnikulin, I have added the name to the editor. There was a typo in the date; the year was changed to 2024, and I've updated your message with this.

**Comment by efisher008** [comment]
Hi @gnikulin,

I've been looking at the CF phrasebank and think it might also be useful to include the definitions for "bedrock" and "ground_level" after your proposed text. These are below:

-  _"Bedrock" is the solid Earth surface beneath land ice or ocean water._
- _"ground_level" means the land surface (including beneath snow, ice and surface water, if any)._

What do you think of this?

Best wishes,
Ellie

**Comment by taylor13** [comment]
If we include these definitions, then:

I think "bedrock" more generally refers to the  solid rock that is typically buried beneath soil and other broken or unconsolidated material.  In our usage above, of course it may lie under land ice or ocean water too.

I think our description of "ground_level" should specify whether surface vegetation is assumed to be above or below the "ground_level".  On the other hand, we may want to leave that point vague.

**Comment by JonathanGregory** [comment]
In existing standard names, "ground level" is used to indicate the interface between snow and soil. I think therefore it is beneath the above-ground vegetation, but the roots are below ground level! J

**Comment by gnikulin** [comment]
I see that _"Bedrock" is the solid Earth surface beneath land ice, ocean water or soil._ is included in description of  3 standard names where `bedrock` appears -  `bedrock_altitude`, `bedrock_altitude_change_due_to_isostatic_adjustment` and   `tendency_of_bedrock_altitude`. Seems "_or soil_" was simply missing. Using the same definition "Bedrock" is the solid Earth surface beneath land ice, ocean water or soil._  sound fine for me since in our case we assume `where land`. 

Regarding "_ground_level_"  I'm not sure that we need to mention vegetation here, I didn't get this point. The definition of `ground_level`that appears in several standard names:

- _"ground_level" means the land surface (including beneath snow, ice and surface water, if any)_ in `upward_geothermal_heat_flux_at_ground_level_in_land_ice`
- _ground_level means the land surface (beneath the snow and surface water, if any)_ in `upward_heat_flux_at_ground_level_in_snow`
- _ground_level means the land surface (beneath the snow and surface water, if any)_ in `upward_heat_flux_at_ground_level_in_soil`

_ground_level" means the land surface (beneath snow, ice and surface water, if any)_ sounds better for me

**Comment by gnikulin** [comment]
Although _"Bedrock" is the solid Earth surface beneath land ice, ocean water or soil._ says nothing about surface fresh water, lakes etc.

**Comment by taylor13** [comment]
The existing definition of "bedrock" quoted above could be amended to read:
"Bedrock" is the solid Earth surface beneath any land ice, surface waters (including ocean), soil, and other broken or unconsolidated surface material. 

Regarding ground level, I note that for ``upward_geothermal_heat_flux_at_ground_level_in_land_ice`` the description states this "is the upward heat flux at the interface between the ice and bedrock". Is this correct?  Doesn't scree-like material often underlie a glacier?  If so, shouldn't this say "heat flux at the interface between the ice and underlying ground"? 

For other standard names that reference "ground_level", I think most folks with interpret this as did @JonathanGregory: "it is beneath the above-ground vegetation, but the roots are below ground level".  If this is so, then there probably is no need to revise the description.

**Comment by JonathanGregory** [comment]
We could define `ground_level` as the level of the solid land surface (beneath any snow, land ice, surface water and permanent inland water). That means the bed or a lake or river would be "ground". Does that make sense? `ground_level` is not defined in sea areas. On Karl's point, I think that for `upward_geothermal_heat_flux_at_ground_level_in_land_ice` we could say "at the interface between the ice and the underlying sediment or bedrock."

I agree that `bedrock` is the solid Earth surface beneath any land ice, surface waters (including ocean), soil, loose rock, and unconsolidated sediment. Is it helpful to say "beneath the regolith"? Does bedrock include consolidated sediment i.e. sedimentary rock?

**Comment by gnikulin** [comment]
`bedrock` exists everywhere beneath any surface.  May be `regolith` is a right word to describe "_soil, and other broken or unconsolidated surface material_" suggested by Karl. Britannica defines the regolith as "_a region of loose unconsolidated rock and dust that sits atop a layer of bedrock. On Earth, regolith also includes soil, which is a biologically active medium and a key component in growth._" something like that  - `"Bedrock" is the solid Earth surface beneath any land ice, surface waters (including ocean) and regolith.`

**Comment by gnikulin** [comment]
> We could define `ground_level` as the level of the solid land surface (beneath any snow, land ice, surface water and permanent inland water). That means the bed or a lake or river would be "ground". Does that make sense? `ground_level` is not defined in sea areas. On Karl's point, I think that for `upward_geothermal_heat_flux_at_ground_level_in_land_ice` we could say "at the interface between the ice and the underlying sediment or bedrock."
> 
In our application (land surface modeling) `ground_level` can be defined only over land. I wouldn't call lake or river bed  `ground_level`, although it has been already defined for heat fluxes.

**Comment by gnikulin** [comment]
I agree that meaning of the regolith can be simply unknown to many of even most users of the CF conventions. I didn't know what it actually means until  yesterday :-). I think that  _"bedrock" refers to the surface of the consolidated rock, beneath any unconsolidated rock, sediment, soil, water or land ice_  is clear enough. 

 _The level of the solid surface in land areas without permanent inland water, beneath any snow, ice or surface water._ should work as well.

**Comment by efisher008** [comment]
Hi all,

I've just finished following the discussion of `bedrock` and `ground_level` through your comments. I have updated the text for the proposed name `bedrock_depth_below_ground_level` to the following: 
_"The bedrock_depth_below_ground_level is the vertical distance between the ground and the bedrock. "Bedrock" refers to the surface of the consolidated rock, beneath any unconsolidated rock, sediment, soil, water or land ice. "Ground level" means the level of the solid surface in land areas without permanent inland water, beneath any snow, ice or surface water."_

Are you proposing to change the definition of `bedrock` and `ground_level` in the CF phrasebank to these new sentences, or just in the description for the new proposed name? I think it should be a consistent usage between what's in the term description and the phrasebank so it would be good to have a conclusion either way. I would also suggest we could create a phrasebank entry for `regolith`: "_soil, and other broken or unconsolidated surface material_". What are your thoughts on this?

Best regards,
Ellie

**Comment by JonathanGregory** [comment]
Dear Ellie

I believe our new definitions of `bedrock` and `ground_level` are fine for the existing standard names containing these phrases viz.

`bedrock_altitude`
`bedrock_altitude_change_due_to_isostatic_adjustment`
`tendency_of_bedrock_altitude`
`downward_heat_flux_at_ground_level_in_snow`
`downward_heat_flux_at_ground_level_in_soil`
`ground_level_altitude`
`upward_geothermal_heat_flux_at_ground_level_in_land_ice`
`upward_heat_flux_at_ground_level_in_snow`
`upward_heat_flux_at_ground_level_in_soil`.

Therefore we can amend them in the phrasebank.

We could define `regolith` but we aren't using that word at the moment, are we? Do we have other phrases defined that aren't used in standard names?

Best wishes

Jonathan

**Comment by efisher008** [comment]
Hi Jonathan, 

I have changed the definitions of the terms `bedrock` and `ground_level` in the phrasebank to our agreed text (as seen in the name description [here](https://github.com/cf-convention/discuss/issues/303#issuecomment-2063852291)). I think it could still be useful to define `regolith` following this discussion, in the event that it is (presumably) required in a name in future, and the above discussion does not need to be repeated (possibly yielding a different outcome). 

> We could define regolith but we aren't using that word at the moment, are we? Do we have other phrases defined that aren't used in standard names?

I think the answer to this is "possibly not", however there would be no quick way to check the whole phrasebank against the current standard names table for unused phrases. This could be a useful exercise in the future though.

I am not familiar with the standard approach to this in CF, is it usually the case that phrases are/should only be added when they are actively used in a standard name?

Best wishes,
Ellie

**Comment by JonathanGregory** [comment]
Dear Ellie

Thanks for you attention to this. You ask

> I am not familiar with the standard approach to this in CF, is it usually the case that phrases are/should only be added when they are actively used in a standard name?

I don't recall this being explicitly discussed (Alison @japamment or Fran @feggleton might comment) but I would expect that we have only included phrases in the phrasebank that are actually in use, because that would accord with the usual CF practice (number 2 of the [CF principles](https://cfconventions.org/cf-conventions/cf-conventions.html#design)) that we don't add things unless there's a definite use-case). 

Best wishes

Jonathan

**Comment by efisher008** [comment]
Dear Grigory @gnikulin,

Your proposed name `bedrock_depth_below_ground_level` has now been accepted in the CF editor. This will be published in the next update to the standard names table (v85), which is scheduled for mid-May 2024. Thank you very much for your proposal!

Best wishes,
Ellie

**Comment by JonathanGregory** [comment]
Yes, I agree, Ellie. J

**Comment by gnikulin** [comment]
Many thanks to all who helped with the new standard name !!!!

**Comment by efisher008** [comment]
Closing this issue as this name has been accepted in version 85 of the CF standard names table, published on 21 May 2024 [(https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html)](https://cfconventions.org/Data/cf-standard-names/85/build/cf-standard-name-table.html).
