### ISSUE TITLE
 Standard names: Boundary_layer_mixing names

### ISSUE THREAD

**Issue by feggleton** [cf-convention/discuss#34]
Proposer's name: Francesca Eggleton
Date: 21/02/2020

The term 'boundary_layer_mixing' has an associated phrase:

"Boundary layer mixing" means turbulent motions that transport heat, water, momentum and chemical constituents within the atmospheric boundary layer and affect exchanges between the surface and the atmosphere. The atmospheric boundary layer is typically characterised by a well-mixed sub-cloud layer of order 500 metres, and by a more extended conditionally unstable layer with boundary-layer clouds up to 2 km. (Reference: IPCC Third Assessment Report, Working Group 1: The Scientific Basis, 7.2.2.3, https://www.ipcc.ch/ipccreports/tar/wg1/273.htm).

The IPCC link in this phrase no longer works, it has a new location in their archive pages. Therefore any existing names which contain this phrase will be updated to have the new link:

https://archive.ipcc.ch/ipccreports/tar/wg1/273.htm

These names can be seen in the cf editor if there are any objections to this please comment below.

Thanks

**Comment by japamment** [comment]
Dear Francesca,

Thanks for noticing this problem. I fully support this proposal and agree that the definitions need to be updated.

Best wishes,
Alison

**Comment by feggleton** [comment]
These changes have been published in version 72 of the standard name table.
