### ISSUE TITLE
 Standard names: new atmosphere_x_relative_vorticity & atmosphere_y_relative_vorticity

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#39]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2020/03/11

**- Term** atmosphere_x_relative_vorticity
**- New Definition** The vorticity is a vector quantity. "x" indicates a vector component along the grid x-axis, positive with increasing x. Atmosphere x relative vorticity is the x-component of the 3D air vorticity vector. “Relative” means only the vorticity of air and does not consider the Earth’s rotation.
**- Units** s-1

**- Term** atmosphere_y_relative_vorticity
**- New Definition** The vorticity is a vector quantity. "y" indicates a vector component along the grid y-axis, positive with increasing y. Atmosphere y relative vorticity is the y-component of the 3D air vorticity vector. “Relative” means only the vorticity of air and does not consider the Earth’s rotation.
**- Units** s-1

**Comment by feggleton** [comment]
Hi Beate and Ronny,

Thank you for this proposal. These look to be in line with other iterations of x and y components we have done. In terms of the definition, the first two lines are fine and already in use. The second two sentences would be new in place of 'Relative vorticity is the upward component of the vorticity vector i.e. the component which arises from horizontal velocity' which would no longer be appropriate (from atmosphere_relative_vorticity).  Some discussion and agreement from others on these two sentences would be appreciated. 

In issue #38 1 new phrase and 1 amended phrase was introduced which has been included in these terms. If the phrases are agreed upon then this should be reflected here.

_This would be amending the phrase 'Relative vorticity is the upward component of the vorticity vector i.e. the component which arises from horizontal velocity.' to ' Atmosphere upward relative vorticity is the vertical component of the 3D air vorticity vector. The vertical component arises from horizontal velocity only.'_

[obviously here this phrase above has been amended to be for the relevant component]

_And then adding the new phrase for 'relative' as '“Relative” means only the vorticity of air and does not consider the Earth’s rotation. In contrast, the “atmosphere_upward_absolute_vorticity” considers the Earth’s rotation.'_

[when mentioned in issue 38, this phrase had a second sentence, should this be added to these terms?]

These terms are now in the cf editor. 

Thanks

Fran

**Comment by taylor13** [comment]
I think the definition of "relative" could be tweaked.  Both relative vorticity and absolute vorticity characterize the vorticity of the air (only).  How about:

'"Relative" in this context means the vorticity of the air relative to the rotating solid earth reference frame.  In contast, the "atmosphere_upward_absolute_vorticity" includes the Earth's rotational contribution to the air's vorticity. '  

Maybe someone can improve on the phrasing.

**Comment by japamment** [comment]
Dear Beate, Ronny, Karl, Francesca, @GeyerB @taylor13 @feggleton 

I agree the names and units are fine and also that the definitions should be similar to the one in [#38](https://github.com/cf-convention/discuss/issues/38) for atmosphere_upward_relative_vorticity. I like Karl's wording for the definition of "relative" and think we should also indicate the positive direction of rotation as suggested by @JonathanGregory in #38. Putting together the various suggestions for the definition text, I think we would have:
**atmosphere_x_relative_vorticity** (Canonical units: s-1)
'Atmosphere x relative vorticity is the x component of the 3D air vorticity vector. "Relative" in this context means the vorticity of the air relative to the rotating solid earth reference frame, i.e. excluding the Earth's own rotation. "x" indicates a vector component along the grid x-axis, positive with increasing x. A positive value of atmosphere_x_relative_vorticity indicates anticlockwise rotation when viewed by an observer looking along the axis in the direction of decreasing x, i.e. consistent with the "right hand screw" rule.'

Similarly:
**atmosphere_y_relative_vorticity** (Canonical units: s-1)
'Atmosphere y relative vorticity is the y component of the 3D air vorticity vector. "Relative" in this context means the vorticity of the air relative to the rotating solid earth reference frame, i.e. excluding the Earth's own rotation. "y" indicates a vector component along the grid y-axis, positive with increasing y. A positive value of atmosphere_y_relative_vorticity indicates anticlockwise rotation when viewed by an observer looking along the axis in the direction of decreasing y, i.e. consistent with the "right hand screw" rule.'

The description of positive direction of rotation is maybe a bit clumsy. I was trying to find wording similar to the definition of the upward component and have something that the reader can visualise, but would be happy if anyone can improve on these.

Best wishes,
Alison

**Comment by feggleton** [comment]
There have been no further comments on these terms so they have now been accepted into the next standard name table update.

**Comment by feggleton** [comment]
These terms have been added to the v76 update of the standard name table.
