### ISSUE TITLE
New description for ertel_potential_vorticity 

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#41]
**Proposer's name** Beate Geyer / Ronny Petrik
**Date** 2020/03/11

**- Term** ertel_potential_vorticity 
**- New Definition** The Ertels potential vorticity is the scalar product of the atmospheric absolute vorticity vector and the gradient of potential temperature. It is a conserved quantity in the absence of friction and heat sources [AMS Glossary, http://glossary.ametsoc.org/wiki/Ertel_potential_vorticity]. 
A frequently used simplification of the general Ertel potential vorticity considers the Earth rotation vector to have only a vertical component. Then, only the vertical contribution of the scalar product is calculated.
**- Units** K m2 kg-1 s-1

**Comment by graybeal** [comment]
ertel (in name) or Ertels (in description)?

**Comment by GeyerB** [comment]
In the name and description. The pure potential_vorticity is needed as well later on (see issue #42).

**Comment by taylor13** [comment]
I've never seen it written Ertel's potential vorticity; only Ertel potential vorticity.  (There is, however, Ertel's theorem.)

**Comment by neumannd** [comment]
The description file of the `ertel_potential_vorticity` standard name seems to be empty. Seems to be necessary to add a description.

**Comment by feggleton** [comment]
Hi all,

Thank you Beate and Ronny for your suggestion to add a description to this existing name. Thanks all for your contribution to the discussion. I think this description is spot on from AMS and I am happy to support this. The second half of the description I know less about and have not read this anywhere but if everyone supports this I am happy for this to go forward. 

This name is now in the creditor. If there are no further objections to this change in the next couple of weeks I am happy for this term to be accepted. 

Thanks for this!

Fran

**Comment by feggleton** [comment]
Hi all,

As there have been no further comments on this term, this will be accepted into the next standard name table update (tbc). I will update the cfeditor.

Thanks!

**Comment by awill-btu** [comment]
Dear Colleagues,
I support the new definition of Ertel Potential Vorticity (EPV). It is the correct one. However, the new definition means not only a new description but also a new computation of EPV. I wonder, what happens with the EPV data already available which are computed following the old definition ave(zeta)/( p(z_2) -p(z_1) ). I suggest to define an attribute indicating that the new EPV is numerically different from the old EPV. Otherwise, it's confusing. Unfortunately I cannot make a suggestion in that respect.
