### ISSUE TITLE
Description of potential_vorticity_of_atmosphere_layer 

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#42]
The given description lets unclear which definition of potential_vorticity was used when the standard_name was introduced. That should be clarified.

**Comment by neumannd** [comment]
The current definition for reference:

> "Layer" means any layer with upper and lower boundaries that have constant values in some vertical coordinate. There must be a vertical coordinate variable indicating the extent of the layer(s). If the layers are model layers, the vertical coordinate can be model_level_number, but it is recommended to specify a physical coordinate (in a scalar or auxiliary coordinate variable) as well. Atmosphere potential vorticity is the vertically averaged absolute vorticity of a layer of the atmosphere divided by the pressure difference from the bottom to the top of the layer.

**Comment by feggleton** [comment]
Thank you Beate for your suggestion and thank you Daniel for posting the original definition for reference. I have added this proposed change to the editor (http://cfeditor.ceda.ac.uk/proposals/1), but currently, there has been no proposed additions or changes to the definition so any comments on this change would be welcomed.
