### ISSUE TITLE
New standard name: mole_concentration_of_dissolved_organic_nitrogen_in_sea_water

### ISSUE THREAD

**Issue by neumannd** [cf-convention/discuss#44]
**Proposer's name** Daniel Neumann
**Date** 2020-03-27

**- Term**: mole_concentration_of_dissolved_organic_nitrogen_in_sea_water
**- Description**: Mole concentration means number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "dissolved organic nitrogen" describes a family of chemical species, in an ocean model, which originate directly from plankton (excretion or released on death) or indirectly from soil via the atmosphere (blown by wind) and rivers (washout by rain). "dissolved organic nitrogen" is the term used in standard names for all species belonging to the family that are represented within a given model. The list of individual species that are included in a quantity having a group chemical standard name can vary between models. Where possible, the data variable should be accompanied by a complete description of the species represented, for example, by using a comment attribute.
**- unit**: mol/m3

The description is a modified version of the description of the standard name `mole_concentration_of_dissolved_inorganic_nitrogen_in_sea_water`.

**Comment by roy-lowry** [comment]
The DON definition has been based on the DIN definition, but I don't think that works. DIN has a small number of components and these are always known both for measurements and models. DON, especially for measurements, can have a huge and possibly unknown number of components. How many different dissolved amino acids are there in a water sample? 

How about:

"dissolved organic nitrogen" describes the nitrogen held in carbon compounds in solution. These are mostly generated by plankton excretion and decay.

**Comment by neumannd** [comment]
> "dissolved organic nitrogen" describes the nitrogen held in carbon compounds in solution. These are mostly generated by plankton excretion and decay.

@roy-lowry : Sounds good.

The new description reads:

*Mole concentration means number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". **"dissolved organic nitrogen" describes the nitrogen held in carbon compounds in solution. These are mostly generated by plankton excretion and decay.** "dissolved organic nitrogen" is the term used in standard names for all species belonging to the family that are represented within a given model. The list of individual species that are included in a quantity having a group chemical standard name can vary between models. Where possible, the data variable should be accompanied by a complete description of the species represented, for example, by using a comment attribute.*

**Comment by roy-lowry** [comment]
I must admit I was thinking of losing

 "dissolved organic nitrogen" is the term used in standard names for all species belonging to the family that are represented within a given model. The list of individual species that are included in a quantity having a group chemical standard name can vary between models. Where possible, the data variable should be accompanied by a complete description of the species represented, for example, by using a comment attribute.

from the definition altogether. My experience of biogeochemical modelling is about 20 years out of date, but I would be very surprised if DON were partitioned.  Certainly with measurements there is no partitioning. The method I knew determined TDN with an elemental analyser followed by subtraction of the separate DIN measurements, although I have seen references to methods that chemically eliminate the DIN components prior to elemental analysis..

So, unless you (or anybody else following the thread) has knowledge of DON partitioning in models  (having things like urea, proteins and amino acids as separate variables in the model that are combined to produce DON) then I would recommend leaving the definition at 

_Mole concentration means number of moles per unit volume, also called "molarity", and is used in the construction "mole_concentration_of_X_in_Y", where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". "dissolved organic nitrogen" describes the nitrogen held in carbon compounds in solution. These are mostly generated by plankton excretion and decay._

**Comment by neumannd** [comment]
@roy-lowry  I am fine with that definition. Thanks for the feedback.

**Comment by feggleton** [comment]
Hi all,

Thank you Daniel for your request and to Roy for your contributions to the definition. This is looking good. I have added this term to the cfeditor and updated the definition with the changes discussed above. This discussion looks like it has come to a natural end so if there are no further comments in the next week or so I am happy for this term to be accepted in the next standard name table update (tbc).

Thanks,

Fran

**Comment by feggleton** [comment]
Hi all, 

As there have been no further comments on this term, this will be accepted into the next standard name table update (tbc). I will update the cfeditor.

Thanks!

**Comment by neumannd** [comment]
Thanks, @feggleton !
