### ISSUE TITLE
Question on the usage on `cell_methods` in the context of standard name `surface_temperature`

### ISSUE THREAD

**Issue by neumannd** [cf-convention/discuss#46]
# Problem description

The description of the standard name `surface_temperature` reads:

> The surface called "surface" means the lower boundary of the atmosphere. The surface temperature is the temperature at the interface, not the bulk temperature of the medium above or below. Unless indicated in the cell_methods attribute, a quantity is assumed to apply to the whole area of each horizontal grid box. Previously, the qualifier where_type was used to specify that the quantity applies only to the part of the grid box of the named type. Names containing the where_type qualifier are deprecated and newly created data should use the cell_methods attribute to indicate the horizontal area to which the quantity applies.

Thus, the type of surface should be indicated by the value of `cell_methods`. I did not find any examples that clarifies this use case of `cell_methods`. I think that chapter [7.3.4. Cell methods when there are no coordinates](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#cell-methods-no-coordinates) describes this use case but I don't fully understand it. I guessed what it meant and wrote down an example below.

# Possible usage example: `surface_temperature_where_land`

Assuming that I wanted to rewrite `surface_temperature_where_land` to `surface_temperature`+`cell_methods` then it might be:

```
float surface_temperature(time, lat, lon) ;
   surface_temperature:cell_methods = "land: point lat: lon: mean" ;
```

For this example I assume that we have a horizontal mean temperature. It would be `land: point` if it was the temperature at the land-atmosphere interface (vertical direction). If we had the temperature within the lowest model level of the atmosphere above ground, we would have `land: mean` (because it is a vertical mean). Is that assumption correct?

Does `land` need to be an individual variable in the file so that `land: point` could be automatically evaluted?

# How to deal with temperature at building surfaces?

Assuming that my understanding of the usage of `cell_methods` in this context is correct:

I would like to use the `surface_temperature` in the context of air temperature close to the surfaces of buildings (walls, windows, roots, doors, ...). The building surfaces are not necessarily orientated orthogonal to one spatial dimension. Nevertheless, is it possible to use `building` in `cell_methods`?

```
float surface_temperature(time, lat, lon) ;
   surface_temperature:cell_methods = "building: point" ;
```

**Comment by neumannd** [comment]
Also `surface_temperature` is ambiguous in the meaning. It might be (a) the temperature of the surface material or (b) the air temperature above the surface. The corresponding pressure variable is unambiguous in this context: `surface_air_pressure`.

**Comment by JimBiardCics** [comment]
@neumannd **`surface_temperature`** is the temperature of the surface. It's not **`air_temperature`**.

**Comment by JimBiardCics** [comment]
@neumannd Example 7.7 in [Section 7.3.3](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#statistics-applying-portions) shows how the "where land" construct is used in a **`cell_methods`** attribute.

**Comment by neumannd** [comment]
@JimBiardCics Thanks for the clarification. I mis-read the second sentence of the description. ... and should habe looked for "where land" in the CF Conventions. Thanks for looking it up. Excuse me that I did not look it up in detail.
