### ISSUE TITLE
 Standard names: new proposals in the context of the ESA Permafrost CCI Project

### ISSUE THREAD

**Issue by awi-gamma** [cf-convention/discuss#48]
**Proposer's Name:** ESA Permafrost CCI Project - Andreas Wiesmann 
**Date:** 2020-05-05 
**Term:** ground_temperature
**Definition:** Ground temperature is the bulk temperature of the ground below the surface, not the surface (skin) temperature, independent from presence of soil.
**Units:** K - Kelvin

**Proposer's Name:** ESA Permafrost CCI Project - Andreas Wiesmann
**Date:** 2020-05-05 
**Term:** permafrost_active_layer_thickness
**Definition:** Active Layer Thickness is the thickness of the layer of the ground that is subject to annual thawing and freezing in areas underlain by permafrost. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years
**Units:** m - Meter

**Proposer's Name:** ESA Permafrost CCI Project - Andreas Wiesmann
**Date:** 2020-05-05 
**Term:** permafrost_area_fraction
**Definition:** fraction of permafrost-underlain area within a grid cell's horizontal are. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years
**Units:** % - Percent

**Comment by taylor13** [comment]
If permafrost_area_fraction is acceptable, then we should probably also add "permafrost" to the CF Area Type Table (http://cfconventions.org/Data/area-type-table/current/build/area-type-table.html).

Further clarification is needed concerning "ground_temperature".  Does the "bulk" invariably extend from the surface to some depth (presumably defined by a vertical scalar coordinate)?  Or can it represent the bulk temperature of any sub-surface layer, either at the surface or below.  

If it is limited to the surface, this perhaps suggests a need for a more general standard_name for subsurface temperature.  Apparently, we currently have only "soil_temperature" defined, but soil normally is the near-surface layer where plants sink their roots.  What should be used to represent temperatures below that layer (or is "soil" used loosely to apply to any depth)?  

One suggestion is to call it "subsurface_temperature" (and there might be no need for "ground_temperature") in this case.  It would apply to any depth below the surface (or a layer  of any thickness at or below the surface).  Again, a vertical scalar coordinate and a cell_methods can be defined for this variable that indicates whether it applies at a particular depth or for some layer.

**Comment by awi-gamma** [comment]
CF Area Type Table – yes, ‘permafrost’ should probably be added

Ground_temperature represents the bulk temperature of any sub-surface layer, either at the surface or below. For the dataset that we are creating we e.g. provide 0m, 1m, 2m and 5 m depth. If we would use "subsurface_temperature", then the 0m product would need to be labelled with a different name.

Our understanding of soil is as you describe (‘where plants sink their roots’), therefor our suggestion to use ‘ground’

**Comment by taylor13** [comment]
thanks for the clarification.  
I would say that a layer extending from say 0m to 1/2 m is almost entirely subsurface except for the infinitesimally thin layer that interfaces with the atmosphere above, so I think subsurface would do for all the layers with some thickness.  

If the 0m temperature is actually the temperature of the surface itself (with no significant depth), it should probably be given the existing name "surface_temperature".

**Comment by awi-gamma** [comment]
We can agree on using 'surface_temperature' for 0 m and 'subsurface_temperature' for the other depths.

**Comment by feggleton** [comment]
Hi all,

Thank you for your proposal and for the comments to clarify. I have added those three terms to the cfeditor but will now remove the ground_temperature and add subsurface_temperature as discussed above, is that correct? If you could also provide a definition for subsurface_temperature I will add that in. 

For permafrost_active_layer_thickness the only thing I would add is the existing phrase to explain thickness (as you have done for permafrost) if you think this is ok to add? The definition would then be:

Active Layer Thickness is the thickness of the layer of the ground that is subject to annual thawing and freezing in areas underlain by permafrost. "Thickness" means the vertical extent of a layer. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years.

For permafrost_area_fraction definition, I'm assuming there was a little typo at the end of the first sentence and should be (let me know if not):

Fraction of permafrost-underlain area within a grid cell's horizontal area. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years.

There is also some associated phrases with 'area fraction' which I'm not sure are needed here or not? I will put them below and let me know if any of the wording needs adding to that definition (I'm assuming probably not the first sentence):

"Area fraction" is the fraction of a grid cell's horizontal area that has some characteristic of interest. It is evaluated as the area of interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction.

**Comment by taylor13** [comment]
As a definition of subsurface_temperature, I suggest:
```
"subsurface_temperature is the temperature at any depth (or in a layer) of the "solid"
earth, excluding surficial snow and ice (but not permafrost).  For surface snow and ice, 
the more specific standard names, "temperature_in_surface_snow" and 
"land_ice_temperature", should be used rather than "subsurface_temperature".  
```

I hope all will carefully review and say whether this is clear and correct.

I would note that standard names have yet to be defined for the temperature of lakes, ponds, rivers, and the like, but I don't think subsurface_temperature should apply to these.  If names are needed, we can add them later.

**Comment by awi-gamma** [comment]
We agree with the definitions given by @feggleton and @taylor13 above

**Comment by ngalbraith** [comment]
I am a little concerned that the term subsurface_temperature, if it's meant to be used only for solid earth,  should include that in the name itself. I can imagine people doing a quick search on temperature and finding this term, without noticing that it should not be used for, e.g. water temperature.

**Comment by graybeal** [comment]
I agree with Nan. The ocean community uses that phrase for underwater temperatures a lot, that was my first association on seeing it.

John

________________________________

**Comment by taylor13** [comment]
Let's brainstorm some possible alternatives to subsurface_temperature then....

underground_temperature  (would this apply underneath the seas?)
subsurface_solid_earth_temperature
solid_earth_temperature
temperature_within_the_earth_crust

others???

**Comment by roy-lowry** [comment]
How about solid_earth_subsurface_temperature? It's an explicit description and having the subdivision of the medium of measure following the name of that medium reads better to me.

**Comment by awi-gamma** [comment]
> How about solid_earth_subsurface_temperature? It's an explicit description and having the subdivision of the medium of measure following the name of that medium reads better to me.

That is fine with us. 
We would appreciate if we could close the discussion soon so that we can publish the data.

Thanks

**Comment by taylor13** [comment]
I'm also fine with solid_earth_subsurface_temperature.

**Comment by feggleton** [comment]
Hi all, 

Thanks for the great discussion and contributions. It looks like the following has been confirmed, let me know if I have got this wrong:

Term: solid_earth_subsurface_temperature
definition: The "solid_earth_subsurface_temperature" is the temperature at any depth (or in a layer) of the "solid" earth, excluding surficial snow and ice (but not permafrost). For surface snow and ice, the more specific standard names, "temperature_in_surface_snow" and 
"land_ice_temperature", should be used rather than "solid_earth_subsurface_temperature".


Term: permafrost_area_fraction
definition: Fraction of permafrost-underlain area within a grid cell's horizontal area. It is evaluated as the area of interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years.

I have added two sentences in the above which are existing phrases relating to area_fraction, let me know if these are ok or not.  ( It is evaluated as the area of interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. ) - I have also asked Alison to look at this term just to make sure I have added those correctly.

Term: permafrost_active_layer_thickness
definition: Active Layer Thickness is the thickness of the layer of the ground that is subject to annual thawing and freezing in areas underlain by permafrost. "Thickness" means the vertical extent of a layer. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years.

If there are no more comments on these terms by the end of the week and everyone is happy then we can accept them into the next update (23rd June).

Thanks, Fran

**Comment by taylor13** [comment]
These look good to me.  Perhaps Alison will check the definitions for style consistency with other definitions.  Not sure whether the second one should have capitalized "Active Layer Thickness", and maybe it should include the word permafrost up front: "Permafrost active layer thickness is the thickness of the permafrost layer that is subject to annual thawing and freezing.  "Thickness" means the vertical .... "

**Comment by feggleton** [comment]
Yes I have asked her to take a look. Yes perhaps it should be "permafrost_active_layer_thickness" is the thickness.... to be consistent with other names. Thanks for the spot.

**Comment by japamment** [comment]
Dear All,

Apologies for getting to this discussion late in the day. I've read through the issue and all is looking in pretty good shape.

Fran and Karl have asked me to check over some style points in the definitions, which I have now done (see below).

I also noted Andreas and Karl's comments about the difference between the solid_earth temperature name being proposed and our existing soil_temperature name. I think it is important to  have something in the definition of both names to differentiate between the two. The proposed definition is clear that surface lying snow and ice are definitely not included in solid_earth_subsurface. My understanding from the discussion is that "subsurface" can apply in both soil where it is present or, for example, in rock where it underlies soil or where there is no surface soil. Is that correct? If so, I would write the subsurface_temperature definition as follows:
Term: **solid_earth_subsurface_temperature** (K)
Definition: The quantity with standard name solid_earth_subsurface_temperature is the temperature at any depth (or in a layer) of the "solid" earth, excluding surficial snow and ice (but not permafrost or soil). For temperatures in surface lying snow and ice, the more specific standard names temperature_in_surface_snow and land_ice_temperature should be used. For temperatures measured or modelled specifically in the soil layer (the near-surface layer where plants sink their roots) the standard name soil_temperature should be used.

I think writing the definition this way also helps to distinguish between "solid earth" and "bedrock". The latter has been discussed and agreed in [Issue #2](https://github.com/cf-convention/discuss/issues/2) where bedrock has been defined as "Bedrock is the solid Earth surface beneath land ice, ocean water or soil" and therefore clearly excludes soil.

Assuming all of the above is correct, then we should also clarify the definition of soil_temperature. I suggest we modify the definition as follows:
"Soil temperature is the bulk temperature of the soil, not the surface (skin) temperature. "Soil" means the near-surface layer where plants sink their roots. For subsurface temperatures that extend beneath the soil layer or in areas where there is no surface soil layer the standard name solid_earth_subsurface_temperature should be used".

Do others agree with these suggestions?

Fran asked me to check the definition of permafrost_area_fraction. I'd reorganise it slightly:
Term: **permafrost_area_fraction** (1)
' "Area fraction" is the fraction of a grid cell's horizontal area that has some characteristic of interest. It is evaluated as the area of interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years.'
This is constructed in the same way as the definition for burned_area_fraction, for example, and allows us to use our usual text for all the components of the name.

Note that the canonical unit in the standard name table should just be '1' as it is a dimensionless quantity. This is consistent with other X_area_fraction standard names. It is fine to then specify the unit as "percent" or "%" in the data files as the UDunits software recognizes these as dimensionless numbers between zero and 100.

Term: **permafrost_active_layer_thickness**
definition: Active Layer Thickness is the thickness of the layer of the ground that is subject to annual thawing and freezing in areas underlain by permafrost. "Thickness" means the vertical extent of a layer. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years.

I agree with Karl about the capitalization and also that the definition should refer clearly to "permafrost active layer". I did a quick search on "active layer" and found that, although it does most commonly seemed to be used in relation to permafrost, there are also mentions of semi-conductor active layers, solar cell active layers and even the "active layer" in Photoshop, so it's important to be very clear in our own usage. I'd write this definition as:
'The quantity with standard name permafrost_active_layer_thickness is the thickness of the layer of the ground that is subject to annual thawing and freezing in areas underlain by permafrost. "Thickness" means the vertical extent of a layer. Permafrost is soil or rock that has remained at a temperature at or below zero degrees Celsius throughout the seasonal cycle for two or more years.'

I hope these suggestions are all okay. We are planning a standard name table update for next week and if we can agree on these last few details then I agree with Fran that these names can be included.

Best wishes,
Alison

**Comment by awi-gamma** [comment]
All fine for us. Thanks.
