### ISSUE TITLE
 Standard names: Current meter echo intensity

### ISSUE THREAD

**Issue by hhourston** [cf-convention/discuss#65]
**Hana Hourston and Di Wan**
**August 6, 2020**

We would like to propose the following standard name for current meter echo intensity data, which borrows from the standard name for ADCP echo intensity proposed in Issue #56 :

**- Term:** signal_intensity_from_multibeam_current_meter_velocity_sensor_in_sea_water
**- Description:** The magnitude of an acoustic signal transmitted then received.
**- Units:** 1

**Comment by JonathanGregory** [comment]
Dear Hana

You're proposing
> signal_intensity_from_multibeam_current_meter_velocity_sensor_in_sea_water
on the pattern of
> signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water
which looks logical from the point of view of syntax, but I think for the non-expert (like me) some more clarity is needed in the names or the definitions of the difference between these. What is the difference between a multibeam acoustic Doppler velocity sensor and a multibeam (presumably also acoustic) current meter velocity sensor?

Best wishes

Jonathan

**Comment by ngalbraith** [comment]
The originally proposed variable name explicitly referred to profilers, but was generalized to apply to 'velocity sensors' - that's a really good thing.  More than one of the 'engineering variables' output by acoustic doppler current profilers are also output by single point acoustic current meters. 

For that reason, unless I'm missing some detail about these instruments, I don't think this new name is needed. 

Gory detail - 
proposed: echo_intensity_in_sea_water_by_adcp 
accepted: signal_intensity_from_multibeam_acoustic_doppler_velocity_sensor_in_sea_water

**Comment by hhourston** [comment]
Hi @JonathanGregory and @ngalbraith,
For clarification on instrument differences, the multibeam Acoustic Doppler current profilers measure currents at different distances (bins) from the instrument, whereas the multibeam current meters measure currents at one point in the water column. Given that both instruments use the Doppler effect, I agree with Nan that the accepted code from #56 can be used here, and will close the issue. Thanks!
