### ISSUE TITLE
Taking a new position

### ISSUE THREAD

**Issue by JimBiardCics** [cf-convention/discuss#66]
Hi.

I'm taking a new position with Vexcel Corporation. My new duties won't bring me into much contact with the CF world (if any), so I believe it's best for me to resign from my duties with CF.

I have loved working with all of you. You are a great bunch of humans, and you are doing great work. I'm excited about my new job, but I'm going to miss you all quite a lot.

If you would like to contact me, feel free to email me at j.biard@computer.org or jimbiard@gmail.com.

Grace and peace,

Jim

**Comment by taylor13** [comment]
Say it ain't so, Jim.  We'll miss your thoughtful input into CF's evolution and considerable contributions to improving/expanding it.  Thanks for all you've done. 
 
Best wishes in your new position, and take care.  We'll miss you too.
Karl

**Comment by JonathanGregory** [comment]
Dear Jim

Congratulations to you. I hope you enjoy your new position. Thank you very much for your large number of very useful and clear-minded contributions to CF. We will miss them and you. I'll write to you if we manage to agree a convention about the leap seconds. :-)

Best wishes

Jonathan
