### ISSUE TITLE
Request for creation of "Standard names" label

### ISSUE THREAD

**Issue by japamment** [cf-convention/discuss#7]
Dear All,

I'd like to request the creation of a "Standard names" label that can be added to all GitHub issues related to CF standard names. This would be helpful to @feggleton and myself so that we can easily spot which issues we need to be watching closely and might be useful to others who prefer to view the list of issues via GitHub. I think the label would have to be created by someone who is an owner of the cf-convention organization.

It would be useful if the label could be visible in both the discuss and cf-convention repositories. Occasionally people send standard name requests to the latter and some conventions issues turn out to also have implications for standard names, so it would be helpful if we could identify them easily.

This request is also related to my comments in issue [#1.](https://github.com/cf-convention/discuss/issues/1)

Best wishes

Alison

**Comment by davidhassell** [comment]
I have just done this! It can, of course be undone/changed with no difficulty or consequence if there are any problems. I shall put the labal (with the same colour) on the "cf-conventions" repository, too.

**Comment by japamment** [comment]
@davidhassell 

Thank you very much!
