### ISSUE TITLE
 Standard names: snow density

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#71]
**Proposer's names** Beate Geyer and Burkhardt Rockel
**Date** 2020/08/21

_There is no definition for the existing quantity 'snow_density'._

-**Term** snow_density
-**New Definition** Snow density is the mean density of the entire snow cover at the surface.
-**Units** kg m-3

_In earth system models multi layer snow models are used. Therefore, the variability of snow quantities should be taken into account._

-**Term** snow_density_of_snow_layer
-**Definition** Snow density is the density of the snow cover at the surface. "Layer" means any layer with upper and lower boundaries that have constant values in some vertical coordinate. There must be a vertical coordinate variable indicating the extent of the layer(s). If the layers are model layers, the vertical coordinate can be model_level_number, but it is recommended to specify a physical coordinate (in a scalar or auxiliary coordinate variable) as well.
-**Units** kg m-3

**Comment by BrienenS** [comment]
This looks good to me. I agree on the suggested new definition for snow_density and the new term snow_density_of_snow_layer.

**Comment by feggleton** [comment]
Thanks for the proposal and for the supporting comment. My only suggestion for snow_density would be to add the phrase about density in, however, I know there have been discussions in the past about layers at the surface so any comments on that are welcome but seems fine to me (not my expertise):

-**Term** snow_density
-**New Definition** Snow density is the mean density of the entire snow cover at the surface. The density of a substance is its mass per unit volume.
-**Units** kg m-3

-**Term** snow_density_of_snow_layer
-**Definition** Snow density is the density of the snow cover at the surface. The density of a substance is its mass per unit volume. "Layer" means any layer with upper and lower boundaries that have constant values in some vertical coordinate. There must be a vertical coordinate variable indicating the extent of the layer(s). If the layers are model layers, the vertical coordinate can be model_level_number, but it is recommended to specify a physical coordinate (in a scalar or auxiliary coordinate variable) as well.
-**Units** kg m-3

**Comment by JonathanGregory** [comment]
In existing names, the phrase `surface_snow` is consistently used to describe the layer of snow which lies on the ground (to distinguish it from snow in the air and on the canopy, for instance). If that's what you mean in this case, I think the same phrase should be used. Jonathan

**Comment by GeyerB** [comment]
@JonathanGregory thanks for keeping an overview!!
Yes, `surface_snow_density` is the term we need (and `surface_snow_density_of_snow_layer`).
Should we add than the explanatory comment 'Surface amount refers to the amount on the ground, excluding that on the plant or vegetation canopy.' to the definitions?

**Comment by JonathanGregory** [comment]
`surface_snow_density` would fit the existing standard names very well, and apply to the entire snow cover, I suppose. Since density is an intensive variable, I don't think you need a different standard name to describe its dependence on snow layer; you just need to add a coordinate variable to specify the levels or layers. Standard names containing `of_`**X**`_layer` refer to extensive quantities, involving some vertical integral.

**Comment by taylor13** [comment]
I agree with Jonathan regarding the need for only one of the names.
The phrase "Surface snow refers to the snow on the ground, and excludes, for example, falling snowflakes and and snow on plants"  might need tweaking since some might think it also excludes snow on glaciers, ice sheets and sea ice, which I think it doesn't.  Perhaps the following would be better:  "Surface snow refers to the snow on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and and snow on plants."

**Comment by feggleton** [comment]
Hi all, 

It looks like we are agreed to drop the term snow_density_of_snow_layer.

For 'snow_density' remember this is not a new name, it is existing without a definition so this will be changing the name (alias) to surface_snow_density.

I have amended the definition slightly to include phrases commonly used with these words. Let me know if you would like to add the other line @taylor13 recommends 'Surface snow refers to the snow on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and and snow on plants.' - I think that seems sensible but please confirm.

Term: surface_snow_density
Definition: Snow density is the mean density of the snow cover at the surface. The phrase "surface_snow" means snow lying on the surface. The surface called "surface" means the lower boundary of the atmosphere. The density of a substance is its mass per unit volume.

Thanks,

Fran

**Comment by GeyerB** [comment]
Should we delete the 'mean' from 'mean density' to allow for several layers?
Beate

**Comment by GeyerB** [comment]
As nobody has any reservations about deleting 'mean' we can close the issue with the definition-update, can't we?

**Term** snow_density
**Definition** Snow density is the density of the snow cover at the surface. The phrase "surface_snow" means snow lying on the surface. The surface called "surface" means the lower boundary of the atmosphere. The density of a substance is its mass per unit volume.
**Units** kg m-3

**Comment by GeyerB** [comment]
Yes, we want to add in the @taylor13 suggestion!
I would say instead of the 'old' sentence. We should even omit the sentence _The surface called "surface" means the lower boundary of the atmosphere._ as the plants might be the lower boundary of the atmosphere which would contradict our sentence from taylor13.

**Term**: surface_snow_density
**Definition**: Snow density is the density of the snow cover. Surface snow refers to the snow on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and and snow on plants. The density of a substance is its mass per unit volume.

**Comment by GeyerB** [comment]
Can we add surface_snow_density to the table and close the issue?

**Comment by japamment** [comment]
Hi Beate and Francesca @GeyerB @feggleton @taylor13 

I agree with creating the alias snow_density -> surface_snow_density and also with Karl's comment that surface_snow includes snow lying on ice surfaces.

In existing surface_snow names we seem to have used a variety of wording in the definitions! As Francesca says, many of them  just say 'The phrase "surface_snow" means snow lying on the surface' while the amount names say 'Surface amount refers to the amount on the ground, excluding that on the plant or vegetation canopy'. There are also a few existing names that don't contain any explanation of surface_snow.

Karl's suggested wording is clear so I think it would be good to standardize on that. Beate's suggestion to remove 'The surface called "surface" means the lower boundary of the atmosphere' also makes sense for this name. Hence I agree with
> **Term**: surface_snow_density
> **Definition**: Snow density is the density of the snow cover. Surface snow refers to the snow on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and and snow on plants. The density of a substance is its mass per unit volume.

I think we should also use this opportunity to bring all the definitions of existing surface_snow names into line with this one.

Best wishes,
Alison

**Comment by feggleton** [comment]
Hi all, 

Thank you Alison for your comments. 

If there are no further comments about surface_snow_density in the next 7 days we can accept this into the next update.

I will also identify the other surface_snow names and bring them in line with this definition. There are quite a few but this should not stall the acceptance of the term in this discussion.

**Comment by GeyerB** [comment]
Fine with me, except the double 'and and'...

**Comment by feggleton** [comment]
As there have been no further comments, this term can now be accepted into the next update. Thanks all.

**Comment by feggleton** [comment]
I have now also added 31 terms containing surface_snow in the cfeditor (http://cfeditor.ceda.ac.uk/proposals/1) to bring them all in line with this term, to contain the phrase:

surface_snow:  Surface snow refers to the snow on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and snow on plants.

or 

surface_snow_amount:  Surface snow amount refers to the amount on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and snow on plants.

**Comment by japamment** [comment]
Dear Fran

Thank you for working on the surface_snow[_amount] definitions. I've had a look at them in the CEDA editor and they all look fine. There haven't been any other comments, so I think it's okay to go ahead and accept these in time for the update.

Best wishes
Alison

**Comment by feggleton** [comment]
These terms have now been added to the standard name table v77.
