### ISSUE TITLE
 Standard names: lifted_index and lightning_potential_index

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#72]
**Proposer's names** Beate Geyer and Burkhardt Rockel
**Date** 2020/08/21

_We want to propose following names:_

-**Term** lifted_index
-**Definition** The lifted index, usually abbreviated to LI, is the temperature difference between the environment and an air parcel lifted adiabatically Tp(p) at a given pressure height in the troposphere, usually 500 hPa. When the value is positive, the atmosphere (at the respective height) is stable and when the value is negative, the atmosphere is unstable. 
-**Units** K

_and_

-**Term** lightning_potential_index
-**Definition** 'lightning_potential_index', usually abbreviated to LPI, is an index calculated for improvement of the lightning forecast from atmosphere_convective_available_potential_energy, air temperature at 850 hPa, atmosphere_mass_content_of_cloud_liquid_water, relative_humidity at -10°C, air_equivalent_potential _temperature lapse rates and lifted index.
-**Units** J kg-1

**Comment by doblerone** [comment]
Good to add.
Can you check the units? For LI, I think it should be K or °C (since it is a temperature difference).
For LPI, I think the unit is J kg−1.

**Comment by GeyerB** [comment]
Yes, K is the right unit for `lifted_index`.

For `lightning_potential_index` I got from the COSMO consortium following statement: The LPI is a vertically integrated diagnostic to quantify favorable physical conditions for charge separation and lightning in a convection allowing model within explicitly simulated/resolved convective cells. It is derived from the updraft speed and the explicitly simulated hydrometeor contents of supercooled water, graupel and other ice hydrometeors (cloud ice, snow). It needs a sufficiently detailed cloud microphysics scheme with a graupel category besides other non-rimed hydrometeors. 

@feggleton could you help to rephrase this (or parts) to cf-style definition? 

I updated the unit to J kg-1, thanks for correction.

**Comment by feggleton** [comment]
I've had a further look at these.

For lifted_index, it looks like we already have this term:

Term: temperature_difference_between_ambient_air_and_air_lifted_adiabatically
Definition: This quantity is defined as the temperature difference between a parcel of air lifted adiabatically from a starting air pressure to a finishing air pressure in the troposphere and the ambient air temperature at the finishing air pressure in the troposphere. It is often called the lifted index (LI) and provides a measure of the instability of the atmosphere. The air parcel is "lifted" by moving the air parcel from the starting air pressure to the Lifting Condensation Level (dry adiabatically) and then from the Lifting Condensation Level to the finishing air pressure (wet adiabatically). Air temperature is the bulk temperature of the air. Coordinate variables of original_air_pressure_of_lifted_parcel and final_air_pressure_of_lifted_parcel should be specified to indicate the specific air pressures at which the parcel lifting starts (starting air pressure) and the temperature difference is calculated at (finishing air pressure), respectively.

Might need a bit of help on lightning_potential_index

**Comment by emilye12** [comment]
@feggleton The CAMPS team at MDL also planned to suggest lifted_index as a standard name.  While it does technically exist in the table, it's very very long.  We've noticed the use of aliases recently while looking through the table, but are not completely clear on how to use aliases properly.  Would this be an appropriate place to use an alias?

**Comment by feggleton** [comment]
So I've had a look back into the mailing list archives (where standard name proposals used to be discussed) and found the thread which discusses why this term wasn't called 'lifted_index'. It looks like the longer descriptive name was given for a reason. http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2013/006282.html - you can see the further messages by clicking 'Next message (by thread): [CF-metadata] new standard name: lifted_index' at the bottom. 

There are two names in question here as it appears two values are required (this is what I gather from the thread ie.) so there is 
temperature_difference_between_ambient_air_and_air_lifted_adiabatically and temperature_difference_between_ambient_air_and_air_lifted_adiabatically_from_the_surface

Obviously, the cf conventions do evolve with time as things change in science but it looks like maybe this decision was made based on the purpose of the standard name table itself (in order to make the terms descriptive and understandable by anyone). This can definitely be open to discussion. Hope this helps.

**Comment by GeyerB** [comment]
What about the lightning_potential_index could that go to the next release?

**Comment by feggleton** [comment]
I don't think the definition of lightning_potential_index is quite there yet. It describes what it is used for and how it is derived but not exactly what it is. We need to create a definition from:

COSMO consortium following statement: The LPI is a vertically integrated diagnostic to quantify favourable physical conditions for charge separation and lightning in a convection-allowing model within explicitly simulated/resolved convective cells. It is derived from the updraft speed and the explicitly simulated hydrometeor contents of supercooled water, graupel and other ice hydrometeors (cloud ice, snow). It needs a sufficiently detailed cloud microphysics scheme with a graupel category besides other non-rimed hydrometeors.

Googling also gives a simple definition of 'The Lightning Potential Index (LPI) is a measure of the potential for charge generation and separation that leads to lightning flashes in convective thunderstorms. It is calculated from model simulated updraft and microphysical fields.'

Index definitions tend to follow a structure of 'The ....._index is an index that indicates .......................... The index is derived from ................' from this example:

The atmosphere_stability_k_index is an index that indicates the potential of severe convection and is often referred to a simply the k index. The index is derived from the difference in air temperature between 850 and 500 hPa, the dew point temperature at 850 hPa, and the difference between the air temperature and the dew point temperature at 700 hPa.

so maybe something like - 'The lightning_potential_index is a measure of the potential for charge generation and separation that leads to lightning flashes in convective thunderstorms. The index is derived from the convective available potential energy (CAPE), Lifted Index, Theta-E lapse rates, 850 mb temperature, precipitable water and relative humidity at -10 degrees. '

I will ask Alison for her opinion on this also. Any comments welcome.

**Comment by GeyerB** [comment]
Dear Francesca,
I was trying to get a comment from an expert (Martina Lagasio, see 'Lightning Potential Index performances in multimicrophysicalcloud-resolving simulations...', 2014) on the definition of `lightning_potential_index` and got following answer: 
"The LPI version I used in that paper is the one implemented by Lynn and Yair [2008, 2010] into the WRF model. The LPI is defined as a volume integral of the total mass flux of ice and liquid water within a zone between 0 and -20°C isotherms (charging zone), where the non-inductive mechanism (collisions of ice and graupel particles in the presence of supercooled water) is most effective and it is in J/Kg."
You already cited from the abstract of Lynn and Yair [2010]. In the 'Model description' section one might further read: "It is derived from the model simulated grid-scale updraft velocity and the mass mixing-ratios of liquid water, cloud ice, snow, and graupel." Which is very similar to the statement I got from the COSMO people.

These considerations together might result in the following:
**-Term** lightning_potential_index
**-Definition** The lightning_potential_index is a measure of the potential for charge generation and separation that leads to lightning flashes in convective thunderstorms. It is derived from the model simulated grid-scale updraft velocity and the mass mixing-ratios of liquid water, cloud ice, snow, and graupel.
**-Units**  J kg-1

**Comment by feggleton** [comment]
Great to get advice from an expert! This makes a lot more sense. I can see the definition and derivation from that paper now [https://www.researchgate.net/publication/242759928_Prediction_of_lightning_flash_density_with_the_WRF_model]. I was reading the derivation from a different paper here https://www.weather.gov/media/gjt/Research/FrisbiePHXAMS2009.pdf which I think is a slightly different thing. Hence confusion on my part. That seems fine to me, any comments welcome and I will check back soon to see if we have reached an agreement. Thanks for seeking advice.

**Comment by davidhassell** [comment]
Hello - I was just wondering if

> The lightning_potential_index is a measure of the potential for ...

Would that be better as

"The lightning_potential_index measures the potential for ..."

Does that still mean the correct thing?

David

**Comment by feggleton** [comment]
Thanks David, @GeyerB What do you think about the above?

**Comment by GeyerB** [comment]
Fine with me!!

**Comment by feggleton** [comment]
Ok, the final definition is below:

Term: lightning_potential_index
Definition: The lightning_potential_index measures the potential for charge generation and separation that leads to lightning flashes in convective thunderstorms. It is derived from the model simulated grid-scale updraft velocity and the mass mixing-ratios of liquid water, cloud ice, snow, and graupel.
Units: J Kg-1

Please have a check of this and make sure everyone is happy. If there are no further comments in the next week this can be accepted.

**Comment by feggleton** [comment]
This standard name has now been accepted into the next update.

**Comment by japamment** [comment]
Updates applied in version 78 of the standard name table.
