### ISSUE TITLE
 Standard names: stratiform_graupel_fall_amount

### ISSUE THREAD

**Issue by GeyerB** [cf-convention/discuss#74]
**Proposer's names** Beate Geyer and Burkhardt Rockel
**Date** 2020/08/21

_Coming from stratiform_graupel_flux and graupel_fall_amount we want to apply for stratiform_graupel_amount._

-**Term** stratiform_graupel_fall_amount
-**Definition** "Amount" means mass per unit area. Stratiform precipitation, whether liquid or frozen, is precipitation that formed in stratiform cloud. Graupel consists of heavily rimed snow particles, often called snow pellets; often indistinguishable from very small soft hail except when the size convention that hail must have a diameter greater than 5 mm is adopted. Reference: American Meteorological Society Glossary http://glossary.ametsoc.org/wiki/Graupel. There are also separate standard names for hail. Standard names for "graupel_and_hail" should be used to describe data produced by models that do not distinguish between hail and graupel.
-**Units** kg m-2

**Comment by BrienenS** [comment]
This looks good to me. I agree on the proposed new term 'stratiform_graupel_fall_amount'.

**Comment by GeyerB** [comment]
@feggleton - are there any concerns or can we get this name?
Best 
Beate

**Comment by feggleton** [comment]
I think this definition looks fine. I would have combined the same phrases to get this definition. I might have put the 'amount' phrase at the end but doesn't make much difference. Alison has had a look at the definition and thinks it looks fine. 

We think this can be accepted into the next update. If anyone has any further comments or changes etc please comment below over the next couple of weeks.

Thanks

**Comment by GeyerB** [comment]
Moving the 'amount'-sentence to the end is fine with me! That better follows the general structure of the definitions...
Thanks

**Comment by feggleton** [comment]
No comments have been made in 2 weeks since this was approved so I have now marked this term as accepted in the cfeditor to be published in the next standard name table update.

**Comment by feggleton** [comment]
This term has now been added to the standard name table v77.
