### ISSUE TITLE
 Standard names: roughness lengths

### ISSUE THREAD

**Issue by ngalbraith** [cf-convention/discuss#75]
**Proposer's name**  Nan Galbraith
**Date** Sept 22 2020

**- Term** surface_roughness_length_for_humidity_in_air 
**- Description** The height above the displacement plane at which the mean wind becomes zero when extrapolating the logarithmic wind speed profile downward through the surface layer.  "Surface" means the lower boundary of the atmosphere.
**- Units** m

I'm not sure if this issue should be a request for a new standard name or not, it's a little more complicated than that.

We're implementing the (fairly) new Coare 3.6 algorithm for our surface fluxes, and have several new variables to include. While we're doing this, we thought we'd check for any standard names that might need to be updated or added.

CF currently includes surface_roughness_length_for_momentum_in_air, surface_roughness_length_for_heat_in_air, and surface_roughness_length. There are no definitions, however, they are all simply 'The surface called "surface" means the lower boundary of the atmosphere.' 

Our new surface flux data files include a time series variable, surface_roughness_length_for_humidity_in_air as well as for_heat and for_momentum. We'd like to find a standard name for this variable, unless it's preferable to use the existing surface_roughness_length and indicate the associated data variable (heat, momentum, and, now, humidity) some other way. If that's so, maybe we should instead consider deprecating the two existing names (heat, momentum). In any case we should update the definitions of the existing names.

Thanks for your help on this, and please be patient - surface flux parameters are not in my area of expertise, though I do work with them when  needed.

**Comment by JonathanGregory** [comment]
Thanks, @ngalbraith. I think this proposal makes sense.

**Comment by feggleton** [comment]
Thanks @ngalbraith for your proposal and @JonathanGregory for your support. This definition makes sense to me (someone who knows a bit about roughness lengths). I have put this in the cfeditor here: http://cfeditor.ceda.ac.uk/proposal/4524. I have edited the last sentence to be like the others with that phrase:

Term:surface_roughness_length_for_humidity_in_air
definition: The height above the displacement plane at which the mean wind becomes zero when extrapolating the logarithmic wind speed profile downward through the surface layer. The surface called "surface" means the lower boundary of the atmosphere.

If everyone is happy with this term then I think this can be accepted into the next update. I will check back at the end of the week.

Thanks,

Fran

**Comment by DanHollis** [comment]
Does the estimation of surface roughness length depend in some way on the associated data variable (heat, momentum or humidity)? If so then I would expect to see something in the description that makes that difference clear. If not then I would favour updating the description for surface_roughness_length and deprecating the other two names.

**Comment by feggleton** [comment]
Good point. From what I understand they are all different quantities (depend on the associated variable, heat, momentum or humidity) 

"To calculate the surface turbulent fluxes knowledge of the surface roughness lengths for momentum, heat and moisture is necessary. They are defined as the height at which, respectively, wind speed, temperature and specific humidity assume their surface values. In atmospheric models the roughness lengths for land surfaces are prescribed surface characteristic fields based on empirical results. Owing to the limited amount of measurements, heat and moisture are often set equal to surface roughness lengths for momentum or 0.1x surface roughness lengths for momentum."

Some definitions I have seen:

The roughness length denotes the height where a meteorological variable, such as wind speed, temperature, and humidity, is extrapolated down to a “surface” value using the log-profile relationship of the Monin-Obukhov similarity theory (Brutsaert 1975).

It is well known that the roughness length of momentum (z0m) is dependent on the nature of the land surface. In addition to the nature of the surface, the roughness lengths for heat (z0T) and moisture (z0q) are altered by the nature of atmospheric flow (Brutsaert 1975).

**Comment by DanHollis** [comment]
Thanks - I'm learning something!

Based on this, the proposed description (which matches my understanding of roughness length) seems to be the definition for roughness length for momentum (i.e. wind speed). Exactly how this should be re-formulated for humidity (or temperature) is not clear to me. (Is a log-profile being fitted to the humidity values (in theory if not in practice)? What is the "surface value" of humidity that is being extrapolated to? etc etc)

Hopefully someone else can help.

**Comment by GeyerB** [comment]
The roughness length for humidity is used in the FLAKE model (we have right now open issues for variables coming from there. And I asked Dimitrii Mironov for his definition and he delivered following comment:

"The roughness length with respect to momentum, heat and moisture (or other scalar quantity) is the height above the surface where mean values of wind speed, temperature and humidity (or other scalar quantity) assume their surface values when extrapolated along their logarithmic profiles downward towards the surface."

This is what the roughness lengths are by definition.

The key point here is the extrapolation is along the log profiles, not in any other way. The roughness length for scalar quantities are different (often very different) from the roughness length for momentum, and there are good physical reasons for this difference.  
Some models indeed take all roughness lengths equal to each other, but that is clearly an oversimplification.

**Comment by DanHollis** [comment]
Adapting the definition provided by @GeyerB, I suggest the new _humidity_ roughness length standard name should be something like this:

**Term** surface_roughness_length_for_humidity_in_air
**Description** The height above the surface where the mean value of humidity assumes its surface value when extrapolated along a logarithmic profile downward towards the surface. "Surface" means the lower boundary of the atmosphere.
**Units** m

I discussed this with a colleague who knows more about roughness lengths than I do and he thought this would be suitable.

Additionally, it would make sense to improve the description of the existing _momentum_ roughness length standard name using the text originally provided by @ngalbraith i.e.

**Term** surface_roughness_length_for_momentum_in_air
**Description** The height above the displacement plane at which the mean wind becomes zero when extrapolating the logarithmic wind speed profile downward through the surface layer. "Surface" means the lower boundary of the atmosphere.
**Units** m

**Comment by ngalbraith** [comment]
This looks good, thank you all. @DanHollis, the new definition seems fine. 

Do we also need to update  surface_roughness_length_for_heat_in_air? I actually don't know what that means, and I haven't used it (I guess that's self-evident), so I can't help with that.

**Comment by ngalbraith** [comment]
Can we consider the term surface_roughness_length_for_humidity_in_air to be finalized now? It's been almost 2 weeks.
And there is a proposal to update surface_roughness_length_for_momentum_in_air, with no negative responses.

Term: surface_roughness_length_for_humidity_in_air
Description: The height above the surface where the mean value of humidity assumes its surface value when extrapolated along a logarithmic profile downward towards the surface. "Surface" means the lower boundary of the atmosphere.
Units m

Term: surface_roughness_length_for_momentum_in_air
Description The height above the displacement plane at which the mean wind becomes zero when extrapolating the logarithmic wind speed profile downward through the surface layer. "Surface" means the lower boundary of the atmosphere.
Units m

**Comment by feggleton** [comment]
Hi all,

Thank you for everyone's input on these terms. 

Looks like we have had some useful advice from people who know about the topic and come to a conclusion on the definition of the humidity term. Thank you for also proposing an improved definition for momentum as it definitely needed doing. I have amended both of the definitions to match the phrase we have in other terms for 'surface', only a couple of extra words. We also have the term surface_roughness_length_for_heat_in_air if we would also like to add a similar definition update to this term?? See below, let me know what you think. (just saw your comment about the heat term, woops!)

Term: surface_roughness_length_for_heat_in_air
Definition: The height above the surface where the mean value of heat assumes its surface value when extrapolated along a logarithmic profile downward towards the surface. The surface called "surface" means the lower boundary of the atmosphere.

Term: surface_roughness_length_for_humidity_in_air
Description: The height above the surface where the mean value of humidity assumes its surface value when extrapolated along a logarithmic profile downward towards the surface. The surface called "surface" means the lower boundary of the atmosphere.
Units m

Term: surface_roughness_length_for_momentum_in_air
Description The height above the displacement plane at which the mean wind becomes zero when extrapolating the logarithmic wind speed profile downward through the surface layer. The surface called "surface" means the lower boundary of the atmosphere.
Units m

If no further comments are received in the next seven days, they will be accepted for inclusion in the standard name table and added at the next update.

Fran

**Comment by feggleton** [comment]
There have been no further comments here so I'm assuming everyone is happy with these terms. Therefore these will be accepted into the next standard name table update. Thanks

**Comment by feggleton** [comment]
These terms have now been added to the standard name table v77.
