### ISSUE TITLE
 Standard names: wind relative to surface currents

### ISSUE THREAD

**Issue by ngalbraith** [cf-convention/discuss#78]
**Proposer's name:** Nan Galbraith
**Date:** Oct 9, 2020, mod Oct 29,2020

**-Term:**  difference_between_eastward_wind_and_eastward_sea_water_velocity 
**-Description:**  The eastward wind, relative to near-surface eastward current; eastward_wind - eastward_sea_water_velocity. "Eastward" indicates a vector component which is positive when directed eastward (negative westward). Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Note: was eastward_wind_relative_to_surface_current)
**-Units:**  m s-1

**-Term:**  difference_between_northward_wind_and_northward_sea_water_velocity  
**-Description:**  The northward_wind, relative to the near-surface northward current; northward_wind - northward_sea_water_velocity. "Northward" indicates a vector component which is positive when directed northward (negative southward). Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Note: was northward_wind_relative_to_surface_current)
**-Units:** m s-1

**-Term:**  [anti|counter]clockwise_angle_of_rotation_from_direction_of_sea_water_velocity_to_wind_direction 
**-Description:**  The difference between the direction of the wind  and the near-surface current. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component.   (Note: was wind_to_direction_relative_to_surface_current)
**-Units:** degree

**-Term:**   magnitude_of_difference_between_wind_and_sea_water_velocity 
**- Description:**  The speed of the wind relative to the near-surface current, normally derived from vectors.  Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component.  
**- Units:**  m s-1
**-Note:** was wind_speed_relative_to_surface_current

These terms are needed for reporting surface fluxes. Because they do not represent the actual speed of the wind (relative to earth), it would be useful to have standard names for them.

**Comment by JonathanGregory** [comment]
There are currently no standard names containing "relative to" but there are some with "difference". Although the sign still has to be stipulated in the definition, it might be clearer to use as a standard name what you have put in the definition: `difference_between_eastward_wind_and_eastward_sea_water_velocity` and similarly for "northward" and the direction. For the direction, the sign of the angular difference could perhaps be included in the standard name e.g. `clockwise`.

**Comment by ngalbraith** [comment]
Thanks Jonathan, this is much better.  It does raise a couple of questions, which I ran into as I started to edit the proposal. 

The relative wind calculation ideally uses a surface current, but in observational data sets there are rarely actual surface current measurements. In our data, we just use the currents closest to the surface, call it eastward_sea_water_velocity (and northward_), and include the depth of the measurement as a coordinate.  Presumably some data sets have actual surface currents, would they need a separate standard name?  Or should the new standard name include 'surface_'  and require there be a surface current variable, maybe suggesting a mechanism for documenting the actual depth of the measurement? Should there be some text in the definition specifying that the currents are ideally from the surface, or is that implicit? 

Also, for the speed and direction variables, (which I called wind_to_direction_relative_to_surface_current and wind_speed_relative_to_surface_current), I'm concerned that calling these difference_between_wind_to_direction_and_sea_water_velocity_to_direction
(and difference_between_wind_speed_and_sea_water_speed) could be misleading, since the vectors have to 
be differenced and then converted to speed and direction; subtracting speeds and directions doesn't work.

I looked through the [Guidelines for Construction of CF Standard Names document](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html) to check whether a data variable using 'difference_between' should actually be generated by subtraction, but there's no guidance on this term. 

I also looked at the existing names that use this term, and they a) they don't all appear to be created by direct subtraction of other variables with standard names, and b) they don't necessarily consist of the standard names of the components. 

So, would it be preferable, for the speed and direction, to use something like difference_between_wind_and_current_speed,
and difference_between_wind_and_current_to_direction? My thought is that this implies that this is not a straight subtraction of two data variables, but maybe not ... would that would just confuse things more?

**Comment by JonathanGregory** [comment]
Dear Nan

I would say that your current practice of supplying a depth for the sea water velocity would be exactly the right thing to clarify a variable with a standard name of `difference_between_eastward_wind_and_eastward_sea_water_velocity`. If the surface velocity is used, we would need a different standard name of `difference_between_eastward_wind_and_surface_eastward_sea_water_velocity` and no depth coordinate; `surface_eastward_sea_water_velocity` is already in the table. All this applies to "northward" as well, of course.

Following the example of `angle_of_rotation_from_east_to_x`, would you find [`anti`|`counter`]`clockwise_angle_of_rotation_from_direction_of_sea_water_velocity_to_wind_direction` an acceptable name? It's described like that, I don't think we need to specify "to" or "from" because the angle is unaffected by that choice (provided it's consistent).

I agree about the pitfall of differencing the speeds. Perhaps `magnitude_of_difference_between_wind_and_sea_ice_velocity` would avoid that problem? To me this would imply calculating the scalar magnitude of the vector difference.

Best wishes

Jonathan

**Comment by ngalbraith** [comment]
That seems fine, thanks. I'll edit the original post, but keep the terms originally proposed ... somewhere.

**Comment by japamment** [comment]
Dear Nan and Jonathan

Thank you for these proposals and the discussion so far.

I think the names in the latest version of the proposal look fine. As well as using a depth coordinate to describe the sea water velocity measurement, I think we may also need a height coordinate to describe the wind component. Just as surface, or near surface, currents are being used I assume you are also using surface or near surface wind components. (We have existing names for eastward|northward_wind, but not separate ones for surface winds). We can use the definitions to explain how to supply the coordinate information.

**difference_between_eastward_wind_and_eastward_sea_water_velocity** (Canonical units: m s-1)
'The near-surface eastward wind, relative to near-surface eastward current; calculated as eastward_wind minus eastward_sea_water_velocity. A vertical coordinate variable or scalar coordinate with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component. "Eastward" indicates a vector component which is positive when directed eastward (negative westward). Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name "upward_air_velocity").'

**difference_between_northward_wind_and_northward_sea_water_velocity** (Canonical units: m s-1)
'The near-surface northward_wind, relative to the near-surface northward current; calculated as northward_wind minus northward_sea_water_velocity. A vertical coordinate variable or scalar coordinate variable with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate variable with standard name "height" should be used to indicate the height of the the wind component. "Northward" indicates a vector component which is positive when directed northward (negative southward). Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name "upward_air_velocity").'

**magnitude_of_difference_between_wind_and_sea_water_velocity** (Canonical units: m s-1)
'The speed of the near-surface wind relative to that of the near-surface current, normally derived from vectors. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name "upward_air_velocity"). A vertical coordinate variable or scalar coordinate variable with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component.'

For the direction name, is there a preferred sign convention? The definitions of our existing angle_of_rotation names say 'anticlockwise reckoned positive' so would the same apply to this quantity? In that case it would be:
**anticlockwise_angle_of_rotation_from_direction_of_sea_water_velocity_to_wind_direction** (Canonical units: degree)
'The angle between the direction of the near-surface wind and that of the near-surface current, normally derived from vectors. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. A vertical coordinate variable or scalar coordinate variable with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component.'

Are these okay?

Best wishes

Alison

**Comment by ngalbraith** [comment]
Thank you, Alison. It took me longer than it should have to realize this, but 'difference' and 'rotation' are not the correct way to describe the speed and direction, despite the fact that the vectors are differences. 

The angle and speed are similar to the wind direction and speed, they're just offset by the (usually much slower moving) current. So it's the speed (or direction) of the wind when the wind is measured against the current, instead of being measured over the ground, but neither speed or direction is an offset or a difference.  I'll have to think about this a bit more, unless the definitions seem obvious to anyone else.

wind_e   wind_n   curr_e   curr_n   rel_wind_e   rel_wind_n
-7.41     -0.92      -0.20      -0.04    -7.21        -0.87
-7.04    -0.47      -0.11         0.07    -6.93       -0.54

wind_to_dir    curr_to_dir      rel_wind_to_dir  wind_speed    curr_speed      rel_wind_speed
262.96           257.55            263.11               7.47                 0.21                 7.26 
266.21           302.58            265.55              7.06                 0.13                6.95

I completely agree that the z axis information should be supplied for both wind and currents.

**Comment by japamment** [comment]
Dear Nan,

Okay, so I think we are agreed on the first two names, `difference_between_eastward_wind_and_eastward_sea_water_velocity` and `difference_between_northward_wind_and_northward_sea_water_velocity`. Unless any further comments are received in the next seven days, these names will be accepted for publication in the standard name table.

Looking at the example data you provided, it seems that the speed quantity rel_wind_speed is the magnitude of the vector whose components are rel_wind_e and rel_wind_n. The direction rel_wind_to_dir is the direction of that vector expressed as a compass bearing, clockwise from due north. This is pretty much the text book definition of a relative velocity and is similar to talking about air speed and bearing for an aircraft in flight. We already have a standard name for air speed: platform_speed_wrt_air. Borrowing from this I'd suggest the speed name should be `wind_speed_wrt_sea_water`, and it would then seem logical to use `wind_to_direction_wrt_sea_water`. We need a clear explanation in the definitions and I've had a go at putting something together.

**wind_speed_wrt_sea_water** (Canonical units: m s-1)
'The quantity with standard name wind_speed_wrt_sea_water is the magnitude of the relative velocity vector of wind and sea water. Speed is the magnitude of velocity. The abbreviation "wrt" means with respect to. The components of the relative velocity vector have standard names difference_between_eastward_wind_and_eastward_sea_water_velocity and difference_between_northward_wind_and_northward_sea_water_velocity. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name "upward_air_velocity"). A vertical coordinate variable or scalar coordinate variable with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component.'

**wind_to_direction_wrt_sea_water** (Canonical units: degree)
'The quantity with standard name wind_to_direction_wrt_sea_water is the direction towards which the relative velocity vector of wind and sea water is headed. The phrase "to_direction" is used in the construction X_to_direction and indicates the direction towards which the velocity vector of X is headed. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The abbreviation "wrt" means with respect to. The components of the relative velocity vector have standard names difference_between_eastward_wind_and_eastward_sea_water_velocity and difference_between_northward_wind_and_northward_sea_water_velocity. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name "upward_air_velocity"). A vertical coordinate variable or scalar coordinate variable with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component.'

What do you think?

Best wishes,
Alison

**Comment by ngalbraith** [comment]
This is exactly right, it's clear and concise. Thank you for figuring it out!

**Comment by japamment** [comment]
Hi Nan

Glad we managed to get there in the end! I think all the names in this issue are now agreed. If no further comments are received in the next seven days, they will be accepted for inclusion in the standard name table and added at the next update.

Best wishes
Alison

**Comment by JonathanGregory** [comment]
Dear Alison @japamment and Nan @ngalbraith 

Thanks for this discussion, and sorry to intervene again. I think it's good to use the analogy of platform speed. so I'm happy with `wind_speed_wrt_sea_water `. This seems fairly obvious.

I'm not so happy with `wind_to_direction_wrt_sea_water`, even though it uses the same idea of sea water as a moving frame of reference. To me this phrase suggests that the wind is somehow travelling "towards" the sea water. Apparently I think of the sea water as a "place" rather than a "direction"! To avoid this misapprehension, I think we should mention "direction" for sea water as well.

Also, as I mentioned before, I don't think we need "to" in this case. This quantity is the angle between two vectors, given as a clockwise rotation, since that's the convention we use for `direction`, isn't it? Maybe I'm wrong. Suppose that the wind is towards 45 degrees (NE) and the sea water velocity towards 35 degrees. Then the direction of the wind wrt to the sea water is 10 degrees. The wind from_direction is 225 degrees (SW) and the sea water from_direction is 215 degrees. I think the direction of the wind wrt sea water direction is still 10 degrees. Would you agree?

If that is right, I would propose `wind_direction_wrt_sea_water_direction` for this name.

Best wishes

Jonathan

**Comment by ngalbraith** [comment]
> I'm not so happy with `wind_to_direction_wrt_sea_water`, even though it uses the same idea of sea water as a moving frame of reference. To me this phrase suggests that the wind is somehow travelling "towards" the sea water. Apparently I think of the sea water as a "place" rather than a "direction"! To avoid this misapprehension, I think we should mention "direction" for sea water as well.
> 
> Also, as I mentioned before, I don't think we need "to" in this case. This quantity is the angle between two vectors, given as a clockwise rotation, since that's the convention we use for `direction`, isn't it? Maybe I'm wrong. Suppose that the wind is towards 45 degrees (NE) and the sea water velocity towards 35 degrees. Then the direction of the wind wrt to the sea water is 10 degrees. The wind from_direction is 225 degrees (SW) and the sea water from_direction is 215 degrees. I think the direction of the wind wrt sea water direction is still 10 degrees. Would you agree?

Actually, no, the quantity we're trying to describe is not a rotation; it is the actual direction of the wind, where the wind is the measurement of air flow over a moving water surface.

If the wind is 45 and the current is 35, the direction of the 'relative wind', would not be 10. To find the actual relative wind direction,  I'd need to pop these numbers (45 and 35 degrees), along with some reasonable speeds, into some software to get the vectors (u,v) for both wind and current, and then calculate the wind vectors relative to the current,  and then get the wind-relative-to-current speed and direction.  I'll do that if needed, but the sample data above shows that, for a wind direction of 263 and a current direction of 256, the direction of the wind-relative-to-the-current is 263, not 7.

I'll run some numbers and figure out if we need names for both from and to - I can't wrap my head around that without some tests. We should be able to presume, though, that both the wind and currents are either to or from, not a combination.

**Comment by JonathanGregory** [comment]
Dear Nan

I'm confused about what this quantity is, sorry. Do you mean the direction of
the difference in the velocities? That is, if the wind velocity is (ua,va) and
the sea water velocity is (us,vs), this quantity is the angle of the vector
(ua-us,va-vs). I see now that this quantity is consistent with the other ones
you want, which are the components and the magnitude of the difference of the
velocities. I am confused by calling this the direction of the wind. If the
wind and the sea water velocity are in the same direction, whatever it is, the
angle is zero. That's not really the direction of the wind; if interpreted as
a wind direction, it means due north.

Best wishes

Jonathan

**Comment by DanHollis** [comment]
I think in sailing this would be termed the 'apparent wind'.

https://sailtrain.org.uk/apparent-wind-explained/

Could you use this terminology here? e.g.

`apparent_wind_direction_wrt_sea_water`
`apparent_wind_speed_wrt_sea_water`

Given it's the motion of the water that causes the 'apparent wind' to differ from the 'true wind', I wonder if a phrase other than 'sea_water' is required e.g. sea_water_current?

**Comment by ngalbraith** [comment]
I like the idea of using the term apparent wind, or, as I started with, relative wind.

>  I am confused by calling this the direction of the wind. If the wind and the sea water velocity are in the same direction, whatever it is, the angle is zero. 

If the angle of the wind and the current are the same, the direction of the relative (or apparent) wind is the same as the direction of the wind.  

If wind is the motion of air over a fixed point, we're just untethering that point, and having it move along with the surface current, for use in calculating surface fluxes.

rel_wind_to_east = wnd_to_east - curr_to_east;
rel_wind_to_north = wnd__to_north - curr_to_north;
rel_wind_speed =  sqrt(rel_wind_to_east.^2 + rel_wind_to_north).^2);
rel_wind_to_dir = atan2(rel_wind_to_east, rel_wind_to_north)*180/pi;

**Comment by JonathanGregory** [comment]
Dear Nan

Thanks for your patience and the equations. I've got it last! I was thinking of unit vectors. Sorry to be so slow on the uptake.

> rel_wind_to_east = wnd_to_east - curr_to_east;
> rel_wind_to_north = wnd__to_north - curr_to_north;
> rel_wind_speed =  sqrt(rel_wind_to_east.^2 + rel_wind_to_north).^2);
> rel_wind_to_dir = atan2(rel_wind_to_east, rel_wind_to_north)*180/pi;

Since I think we've agreed to call the first two difference_between_Xward_wind_and_Xward_sea_water_velocity, wouldn't it be logical to call the other two magnitude_of_ and direction_of_difference_between_wind_and_sea_water_velocity?

Best wishes

Jonathan

**Comment by ngalbraith** [comment]
Thank you, Jonathan.

>Since I think we've agreed to call the first two difference_between_Xward_wind_and_Xward_sea_water_velocity, wouldn't it be logical to call the other two magnitude_of_ and direction_of_difference_between_wind_and_sea_water_velocity?

I'm afraid that that might lead people to think these are differences, where they're actually wind speeds and directions, where the wind is measured against the current. 

Maybe we need a term for 'wind relative to a moving point' where the moving point might be in the current or might be a platform. Something like what @DanHollis suggested, although 'apparent' seems less descriptive than 'relative', to me.    Using the precedent of platform_speed_wrt_sea_water, could we go with 'wind_speed_wrt_sea_water' and  'wind_direction_wrt_sea_water' ?  To me, this makes it more clear that these are speeds and directions, though not measured against a fixed point.

**Comment by JonathanGregory** [comment]
Dear Nan

You write

> I'm afraid that that might lead people to think these are differences, where they're actually wind speeds and directions, where the wind is measured against the current.

But they _are_ differences, I would say. If I've got it right now, they're the magnitude and direction of a vector which is the differnence of two vectors. Since this difference vector is _not_ the wind velocity, these quantities aren't the wind speed or direction - or put another way, they would be equally well-described as sea water speed and direction. The to_direction of the wind velocity wrt the sea water velocity equals the from_direction of the sea water velocity wrt the wind velocity, and the speeds are equal.

It's possible that `direction_of_difference` might be misunderstood as `difference_of_direction`, as I did at first, or `speed_of_difference` as `difference_of_speed`, which you were concerned about earlier, I think.

I agree that "relative" is clearer than "apparent", because it's more self-explanatory. I also find "relative" better than "wrt". I think the four terms should be described in similar ways. How about

`magnitude_of_air_velocity_relative_to_sea_water`
`to_direction_of_air_velocity_relative_to_sea_water`
`eastward_air_velocity_relative_to_sea_water`
`northward_air_velocity_relative_to_sea_water`

which is probably like your original proposal, which I don't remember exactly! These use `air_velocity_relative_to_sea_water` to mean "difference between air (or wind) velocity and sea water velocity". We use the phrase "air velocity" in some other standard names, and I feel more comfortable with using it here than "wind" because the difference vector is not the wind velocity. Also, if you wanted the reverse, it would naturally be called `sea_water_velocity_relative_to_air`, since air is a medium.

Best wishes

Jonathan

**Comment by ngalbraith** [comment]
You make some very good points, Jonathan, thank you. The terms you suggest are exactly right, and they perfectly address the problem that prompted me to request these names, which I probably didn't even state. 

I've been looking at surface flux files that used the standard names wind_speed and wind_to_direction for these variables. I knew that was not a great idea, and these additional terms will solve that problem very nicely.

**Comment by ngalbraith** [comment]
Thank you all for your input. I think this issue is ready to be closed with the addition of these terms, as finalized by @JonathanGregory:

-Term: eastward_air_velocity_relative_to_sea_water
-Description: The eastward motion of air, relative to near-surface eastward current; eastward_wind - eastward_sea_water_velocity. "Eastward" indicates a vector component which is positive when directed eastward (negative westward).  (Note: was originally proposed as eastward_wind_relative_to_surface_current)
-Units: m s-1

-Term: northward_air_velocity_relative_to_sea_water
-Description: The northward motion of air, relative to the near-surface northward current; northward_wind - northward_sea_water_velocity. "Northward" indicates a vector component which is positive when directed northward (negative southward).  (Note: was originally proposed as northward_wind_relative_to_surface_current)
-Units: m s-1

-Term: to_direction_of_air_velocity_relative_to_sea_water
-Description: The difference between the direction of motion of the air and the near-surface current. Air velocity is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component.  (Note: was originally proposed as wind_to_direction_relative_to_surface_current)
-Units: degree

-Term: magnitude_of_air_velocity_relative_to_sea_water
- Description: The speed of the motion of the air relative to the near-surface current, normally derived from vectors. Air velocity is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Note:  was originally proposed as wind_speed_relative_to_surface_current)
- Units: m s-1

**Comment by ngalbraith** [comment]
I think this issue is ready to be closed and the names added to the next update. @japamment, can you please confirm that these will be added? Thank you!

**Comment by japamment** [comment]
Dear Nan @ngalbraith 

Thank you to you, @JonathanGregory and @DanHollis for continuing the hard work to agree these names.

We need to flesh out the definitions with the sentences about vertical coordinate variables as previously discussed, so the final form would be as follows:

**eastward_air_velocity_relative_to_sea_water** (m s-1)
'The eastward motion of air, relative to near-surface eastward current; calculated as eastward_wind minus eastward_sea_water_velocity. A vertical coordinate variable or scalar coordinate with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component. A velocity is a vector quantity. "Eastward" indicates a vector component which is positive when directed eastward (negative westward).'

**northward_air_velocity_relative_to_sea_water** (m s-1)
'The northward motion of air, relative to near-surface northward current; calculated as northward_wind minus northward_sea_water_velocity. A vertical coordinate variable or scalar coordinate with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component. A velocity is a vector quantity. "Northward" indicates a vector component which is positive when directed northward (negative southward).'

**to_direction_of_air_velocity_relative_to_sea_water** (degree)
'The quantity with standard name to_direction_of_air_velocity_relative_to_sea_water is the difference between the direction of motion of the air and the near-surface current. The phrase "to_direction" is used in the construction X_to_direction and indicates the direction towards which the velocity vector of X is headed. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The components of the relative velocity vector have standard names eastward_air_velocity_relative_to_sea_water and northward_air_velocity_relative_to_sea_water. A vertical coordinate variable or scalar coordinate variable with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component.'

**magnitude_of_air_velocity_relative_to_sea_water** (m s-1)
'The quantity with standard name magnitude_of_air_velocity_relative_to_sea_water is the speed of the motion of the air relative to the near-surface current, usually derived from vectors. The components of the relative velocity vector have standard names eastward_air_velocity_relative_to_sea_water and northward_air_velocity_relative_to_sea_water. A vertical coordinate variable or scalar coordinate variable with standard name "depth" should be used to indicate the depth of sea water velocity used in the calculation. Similarly, a vertical coordinate variable or scalar coordinate with standard name "height" should be used to indicate the height of the the wind component.'

If you are happy with these then, yes, they can be accepted for publication in the next update.

Best wishes,
Alison

**Comment by ngalbraith** [comment]
Thank you, Alison, yes those are great. My only concern is whether it's truly self-explanitory for a single variable (e.g. northward_air_velocity_relative_to_sea_water) to have both a height and depth coordinate variable. I haven't checked to see whether there are other standard names that implicitly apply multiple z-axis coordinates to the components of a data variable.

And, in the surface flux algorithms, I suspect that the wind and current are somehow adjusted to the surface before computing the relative air velocity. If that's the case, presumably both height and depth coordinates would be 0, although there would not be a wind or current variable at those z positions.

**Comment by japamment** [comment]
Hi Nan,

I can't think of any other standard names where we currently suggest there should be two vertical coordinates, but I imagine it could arise in other quantities associated with air-sea interaction where data values are being used from particular heights/depths/model levels and fed into a calculation. The purpose of including it in these definitions is simply to encourage data providers to add as much metadata as is useful/possible to describe how their variables were produced. I hope that the suggested sentences are sufficiently self-explanatory, but if you'd like to add further text I'd be happy to consider any suggestions.

I'd suggest using a comment attribute on the data variable as a way of documenting if some sort of adjustment has been applied to the current/wind to allow for the fact they were not actually measured at the surface. Alternatively, if there is a standard method for making these adjustments that is published somewhere we could add a reference to it in the definitions.

Please let me know if you would like to modify the definitions in any way - we are currently trying to finalise the list of names that will be added in next week's (18th/19th Jan) update and I was hoping to include these. In issue [#80](https://github.com/cf-convention/discuss/issues/80) there has been support for allowing a comment period between accepting names and publishing them and although we haven't formally written that into the rules yet, I'd like fix what will go into the next update in the next day or so. We can then advertise the contents ahead of time, but that would also mean not officially accepting any more names until after the update is published.

Best wishes,
Alison

**Comment by ngalbraith** [comment]
Thanks Alison - it turns out that it's a great idea to include 2 z-axis variables; members of my group were unaware that our 'relative winds' were not adjusted to the surface.

So, yes, these are perfect in your last iteration. Thanks again!

**Comment by japamment** [comment]
Hi Nan,

That's great! Thanks for confirming. The four new names proposed in this issue are now accepted for publication in the standard name table and will be added in next week's update.

Best wishes,
Alison

**Comment by feggleton** [comment]
These terms have now been added to the standard name table v77.
