### ISSUE TITLE
Standard name request: At sea floor definitions for observations 

### ISSUE THREAD

**Issue by feggleton** [cf-convention/discuss#8]
Hi all,

I have moved this conversation across from the mailing list so I can have a read through, try and come up with some suggestion for an addition to the definition of these sea floor terms and ensure the people involved don't think this has got lost in the migration to github. Will respond to this shortly.

Fran
-----------------------------------------------------------------------------------------------------------
Hi John,

I touched on this issue when the sea floor temperature and practical salinity names were set up.  My understanding is that it does have a meaning which is the portion of the water column influenced by the seabed, sometimes termed the 'benthic boundary layer'. Oceanographers I've worked with certainly of a conceptual understanding of this, but what it means in terms of a quantitative definition varies depending upon whether one is working in shelf sea, deep ocean or other environments.

I think I suggested adding 'benthic boundary layer' to the CF sea_floor Standard Name definitions, but I don't recall any reaction.

Cheers, Roy.

-------------------------------------------------------------------------------------------------------------
I have a question about the definitions of the *_at_sea_floor standard names, which state "… is that adjacent to the ocean bottom, which would be the deepest grid cell in an ocean model."  

I understand what this means for ocean models (but suspect it has quite different implications for models featuring cells of smaller thickness nearer the boundary).  

Does it mean anything for observational data? (In which case, there should be a corresponding definition, yes?) Or by definition, are all of these variables not applicable to observational data?

This question is general and should not affect this particular request, so conceivably it should be a new topic if the answer is not straightforward.

John

**Comment by feggleton** [comment]
Hi all,

Thanks to John Graybeal and Roy for bringing up this discussion. I hope you're both aware of it since moving across to github and changing to a new subject. Looking back at when this was previously discussed it looks appropriate to add to the at_sea_floor definition about what this means for measurements/observation data. For example something like:

"The potential temperature at the sea floor is that adjacent to the ocean bottom, which would be the deepest grid cell in an ocean model and within the benthic boundary layer for measurements."

Let me know what you think about that or whether it needs to be a separate sentence or if the words observation data need to be used instead of measurements, thoughts are welcome, please.

This would affect the following names (definitions of): northward_sea_water_velocity_at_sea_floor (going into next version), sea_water_velocity_to_direction_at_sea_floor (going into next version), eastward_sea_water_velocity_at_sea_floor (going into next version), sea_water_speed_at_sea_floor  (going into next version), sea_water_practical_salinity_at_sea_floor, sea_water_temperature_at_sea_floor, sea_water_salinity_at_sea_floor and sea_water_potential_temperature_at_sea_floor.


Thanks,

Fran

**Comment by roy-lowry** [comment]
Hi Fran,

Your suggestion works for me.

Cheers, Roy.

**Comment by feggleton** [comment]
These changes have been published in version 70 of the standard name table.
