### ISSUE TITLE
 Standard names: Phytoplankton Size Class (PSC)

### ISSUE THREAD

**Issue by cderval** [cf-convention/discuss#87]
**Proposer's name** Corinne Derval
**Date** Nov, 13, 2020

**- Term** mass_concentration_of_nanophytoplankton_expressed_as_chlorophyll_in_sea_water
**- Description** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. Chlorophylls are the green pigments found in most plants, algae and cyanobacteria; their presence is essential for photosynthesis to take place. There are several different forms of chlorophyll that occur naturally. All contain a chlorin ring (chemical formula C20H16N4) which gives the green pigment and a side chain whose structure varies. The naturally occurring forms of chlorophyll contain between 35 and 55 carbon atoms. Nanophytoplankton are phytoplankton between 2 and 20 micrometers in size. Phytoplankton are algae that grow where there is sufficient light to support photosynthesis.
**- Units** mg m-3

**- Term** mass_concentration_of_microphytoplankton_expressed_as_chlorophyll_in_sea_water
**- Description** Mass concentration means mass per unit volume and is used in the construction mass_concentration_of_X_in_Y, where X is a material constituent of Y. A chemical or biological species denoted by X may be described by a single term such as "nitrogen" or a phrase such as "nox_expressed_as_nitrogen". The phrase "expressed_as" is used in the construction A_expressed_as_B, where B is a chemical constituent of A. It means that the quantity indicated by the standard name is calculated solely with respect to the B contained in A, neglecting all other chemical constituents of A. Chlorophylls are the green pigments found in most plants, algae and cyanobacteria; their presence is essential for photosynthesis to take place. There are several different forms of chlorophyll that occur naturally. All contain a chlorin ring (chemical formula C20H16N4) which gives the green pigment and a side chain whose structure varies. The naturally occurring forms of chlorophyll contain between 35 and 55 carbon atoms. Microphytoplankton are phytoplankton between 20 and 200 micrometers in size. Phytoplankton are algae that grow where there is sufficient light to support photosynthesis
**- Units** mg m-3

In addition to the existing standard "name mass_concentration_of_picophytoplankton_expressed_as_chlorophyll_in_sea_water" (less than 2 micrometers), it would be interesting to add these two standard names complete the classification of  phytoplankton by size

**Comment by roy-lowry** [comment]
The question I asked of ticket #86 also applies here. Note that I asked it to ascertain whether now is the time to turn back the tide of new biological entity expressed as Standard Names and am well aware that the alternative requires a significant structural change to data files. So my underlying question is whether adoption of such a structure cause major backward compatability issues.

**Comment by roy-lowry** [comment]
There does not seem to be strong support for change now in CF to start treating trophic/functional/morphological groupings of organisms using an extension to the CF convention set up for taxa. Consequently, as the names in this proposal are straightforward extensions of an existing morphological group Standard Name using widely adopted size class definitions I see no reason why this proposal should not be accepted. 

Canonical units should be kg m-3 (the scaled units of measure (mg m-3) are included in the data files as a parameter attribute).

Note I'll comment further on #86 in the coming days.

**Comment by feggleton** [comment]
Hi all,

Thank you @cderval for your proposal and Roy for your comments. I have added these two terms to the cfeditor (http://cfeditor.ceda.ac.uk/proposals/1) and amended the units. Thanks. If we are not currently changing the way we do these names then I am happy with these two to go forward. They match the existing picophytoplankton name and are a simple extension to micro and nano. If there are no further comments in the next 7 days then I am happy for these to be accepted.

**Comment by cderval** [comment]
Hi all,
thanks a lot

**Comment by feggleton** [comment]
These have now been accepted and will go into the next CF standard name table update.

**Comment by feggleton** [comment]
These terms have now been added to the standard name table v77.
