### ISSUE TITLE
New names for sea surface waves variables

### ISSUE THREAD

**Issue by marceloandrioni** [cf-convention/discuss#9]
Hello, I have some suggestions for new standard_names for waves variables.

In v69 there are some variables that exist for the "full" wave, wind wave and swell partitions (primary, secondary, tertiary) but not for the whole swell. My suggestions would be:
```
sea_surface_swell_wave_period_at_variance_spectral_density_maximum
sea_surface_swell_wave_directional_spread
```
like it curently exist:
```
sea_surface_primary_swell_wave_period_at_variance_spectral_density_maximum
sea_surface_primary_swell_wave_directional_spread
```

Also, taking into account that WAVEWATCH III is one of the most "popular" wave models and v6.07 allow as output "Peak wave direction of partition" (page 420/466 of the [manual](https://github.com/NOAA-EMC/WW3/wiki/files/manual.pdf)) I would also like to ask for the inclusion of:
```
sea_surface_wind_wave_from_direction_at_variance_spectral_density_maximum
sea_surface_swell_wave_from_direction_at_variance_spectral_density_maximum
sea_surface_primary_swell_wave_from_direction_at_variance_spectral_density_maximum
sea_surface_secondary_swell_wave_from_direction_at_variance_spectral_density_maximum
sea_surface_tertiary_swell_wave_from_direction_at_variance_spectral_density_maximum
```
like it curently exist for the "full" wave
```
sea_surface_wave_from_direction_at_variance_spectral_density_maximum
```
Thank you.

**Comment by roy-lowry** [comment]
These are straightforward extensions to the existing Standard Names quoted and have my support. 

@marceloandrioni It would be helpful if you could prepare the new definitions based on the definitions for the existing Names.

**Comment by marceloandrioni** [comment]
Sorry for the delay @roy-lowry, here is the first try:

`sea_surface_swell_wave_period_at_variance_spectral_density_maximum`

> The quantity with standard name sea_surface_swell_wave_period_at_variance_spectral_density_maximum is the period of the most energetic waves within the swell wave component of a sea. Swell waves are waves on the ocean surface and are the low frequency portion of a bimodal wave frequency spectrum. A period is an interval of time, or the time-period of an oscillation. Wave period is the interval of time between repeated features on the waveform such as crests, troughs or upward passes through the mean level. The phrase "wave_period_at_variance_spectral_density_maximum", sometimes called peak wave period, describes the period of the most energetic waves within a given sub-domain of the wave spectrum.

`sea_surface_swell_wave_directional_spread`
> The quantity with standard name sea_surface_swell_wave_directional_spread is the directional width of the swell wave component of a sea. Swell waves are waves on the ocean surface and are the low frequency portion of a bimodal wave frequency spectrum. Directional spread is the (one-sided) directional width within a given sub-domain of the wave directional spectrum, S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. For a given mean wave (beam) direction the quantity approximates half the root mean square width about the beam axis, as derived either directly from circular moments or via the Fourier components of the wave directional spectrum.

`sea_surface_wind_wave_from_direction_at_variance_spectral_density_maximum`
> The quantity with standard name sea_surface_wind_wave_from_direction_at_variance_spectral_density_maximum is the direction from which the most energetic waves are coming in the wind wave component of a sea. Wind waves are waves on the ocean surface and are the high frequency portion of a bimodal wave frequency spectrum. The spectral peak is the most energetic wave in the wave spectrum partition. The phrase "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X is coming. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The wave directional spectrum can be written as a five dimensional function S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density.

`sea_surface_swell_wave_from_direction_at_variance_spectral_density_maximum`
> The quantity with standard name sea_surface_swell_wave_from_direction_at_variance_spectral_density_maximum is the direction from which the most energetic waves are coming in the swell wave component of a sea. Swell waves are waves on the ocean surface and are the low frequency portion of a bimodal wave frequency spectrum. The spectral peak is the most energetic wave in the wave spectrum partition. The phrase "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X is coming. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The wave directional spectrum can be written as a five dimensional function S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density.

`sea_surface_primary_swell_wave_from_direction_at_variance_spectral_density_maximum`
> The quantity with standard name sea_surface_primary_swell_wave_from_direction_at_variance_spectral_density_maximum is the direction from which the most energetic waves are coming in the primary swell wave component of a sea. Swell waves are waves on the ocean surface and are the low frequency portion of a bimodal wave frequency spectrum. The primary swell wave is the most energetic swell wave in the low frequency portion of a bimodal wave frequency spectrum. The spectral peak is the most energetic wave in the wave spectrum partition. The phrase "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X is coming. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The wave directional spectrum can be written as a five dimensional function S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density.

`sea_surface_secondary_swell_wave_from_direction_at_variance_spectral_density_maximum`
> The quantity with standard name sea_surface_secondary_swell_wave_from_direction_at_variance_spectral_density_maximum is the direction from which the most energetic waves are coming in the secondary swell wave component of a sea. Swell waves are waves on the ocean surface and are the low frequency portion of a bimodal wave frequency spectrum. The secondary swell wave is the second most energetic wave in the low frequency portion of a bimodal wave frequency spectrum. The spectral peak is the most energetic wave in the wave spectrum partition. The phrase "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X is coming. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The wave directional spectrum can be written as a five dimensional function S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density.

`sea_surface_tertiary_swell_wave_from_direction_at_variance_spectral_density_maximum`
> The quantity with standard name sea_surface_tertiary_swell_wave_from_direction_at_variance_spectral_density_maximum is the direction from which the most energetic waves are coming in the tertiary swell wave component of a sea. Swell waves are waves on the ocean surface and are the low frequency portion of a bimodal wave frequency spectrum.  The tertiary swell wave is the third most energetic swell wave in the low frequency portion of a bimodal wave frequency spectrum. The spectral peak is the most energetic wave in the wave spectrum partition. The phrase "from_direction" is used in the construction X_from_direction and indicates the direction from which the velocity vector of X is coming. The direction is a bearing in the usual geographical sense, measured positive clockwise from due north. The wave directional spectrum can be written as a five dimensional function S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density.

Thank you.

**Comment by roy-lowry** [comment]
Many thanks. I have checked these against the definitions for the similar Standard Names and they have all been correctly adapted following existing precedents.

**Comment by feggleton** [comment]
Hi @marceloandrioni, thank you for your proposal and for preparing the definitions and to @roy-lowry for his comments. Similar to ticket 8, I agree these terms look like simple additions which are similar extensions to the existing names as long as they are needed. I have put all 7 in the [cfeditor](http://cfeditor.ceda.ac.uk/proposals/1) but just need to double-check the definitions against our phrases before accepting. I have made the units the same as the corresponding existing terms, mostly 'degree' with one (wave period) as 's' which can be seen on the editor. As this has also been open for a while and little other discussion has been posted I would like to propose we give people a few more days but if everyone is in agreement then we can accept these terms for the next publication. I'll check back on Monday.

Fran

**Comment by feggleton** [comment]
Hi all, I have checked over the phrases and these look fine in the definitions of each of these terms. I have left this longer just to check there were no further comments but if everyone is in agreement then I shall accept these terms for the next release.

**Comment by feggleton** [comment]
This name is accepted for publication in the standard name table and will be added in the next update on 3rd February.

**Comment by marceloandrioni** [comment]
Okay, thank you very much @feggleton.

**Comment by feggleton** [comment]
These changes have been published in version 71 of the standard name table.
