### ISSUE TITLE
 Standard names: sea surface wave parameters (wavelength, peak frequency, infragravity SWH)

### ISSUE THREAD

**Issue by ukmo-ansaulter** [cf-convention/discuss#90]
**Proposer's name** Andy Saulter
**Date** 21st December 2020

**- Term** sea_surface_wave_mean_wavelength_from_variance_spectral_density_inverse_wavenumber_moment
**- Description** The wave directional spectrum can be written as a five dimensional function S(t,x,y,k,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), k is wavenumber and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density. Wavenumber is the number of oscillations of a wave per unit distance. Wavenumber moments, M(n) of S1 can then be calculated as follows: M(n) = integral(S1 k^n dk), where k^n is k to the power of n. The inverse wave wavenumber, k(m-1), is calculated as the ratio M(-1)/M(0).
**- Units** m

**- Term** sea_surface_wave_frequency_at_variance_spectral_density_maximum
**- Description** Frequency is the number of oscillations of a wave per unit time. The sea_surface_wave_frequency_at_variance_spectral_density_maximum is the frequency of the most energetic waves in the total wave spectrum at a specific location.
**- Units** s-1

**- Term** sea_surface_infragravity_wave_significant_height
**- Description** Significant wave height is a statistic computed from wave measurements and corresponds to the average height of the highest one third of the waves, where the height is defined as the vertical distance from a wave trough to the following wave crest. Infragravity waves are waves occurring in the frequency range 0.04 to 0.004 s^-1 (wave periods of 25 to 250 seconds).
**- Units** m

**Comment by roy-lowry** [comment]
As far as I can see these are derived correctly from existing Standard Names and so they have my support.

**Comment by feggleton** [comment]
Hi all,

Thank you for your proposal. I have added these terms to the editor. http://cfeditor.ceda.ac.uk/proposals/1

For the term sea_surface_wave_mean_wavelength_from_variance_spectral_density_inverse_wavenumber_moment, there is another phrase which has not been included which we could add:

'The wavelength is the horizontal distance between repeated features on the waveform such as crests, troughs or upward passes through the mean level. '

sea_surface_infragravity_wave_significant_height seems fine.

For sea_surface_wave_frequency_at_variance_spectral_density_maximum there is another phrase that has come up:

The wave directional spectrum can be written as a five dimensional function S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density. 

But not sure if this is relevant here?

**Comment by ukmo-ansaulter** [comment]
Thanks @feggleton 

The suggested additions for both  sea_surface_wave_mean_wavelength_from_variance_spectral_density_inverse_wavenumber_moment and sea_surface_wave_frequency_at_variance_spectral_density_maximum are both relevant and would be good to add.

For sea_surface_wave_frequency_at_variance_spectral_density_maximum I'd developed the description from the existing wording for sea_surface_wave_period_at_variance_spectral_density_maximum, so it might be useful to add the wave directional spectrum descriptive text to this existing parameter also?

**Comment by feggleton** [comment]
Great thanks. We now have:

Term: sea_surface_wave_mean_wavelength_from_variance_spectral_density_inverse_wavenumber_moment
Definition: The wave directional spectrum can be written as a five dimensional function S(t,x,y,k,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), k is wavenumber and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density. Wavenumber is the number of oscillations of a wave per unit distance. Wavenumber moments, M(n) of S1 can then be calculated as follows: M(n) = integral(S1 k^n dk), where k^n is k to the power of n. The inverse wave wavenumber, k(m-1), is calculated as the ratio M(-1)/M(0). The wavelength is the horizontal distance between repeated features on the waveform such as crests, troughs or upward passes through the mean level.

Term: sea_surface_wave_frequency_at_variance_spectral_density_maximum
Definition:Frequency is the number of oscillations of a wave per unit time. The sea_surface_wave_frequency_at_variance_spectral_density_maximum is the frequency of the most energetic waves in the total wave spectrum at a specific location. The wave directional spectrum can be written as a five dimensional function S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density.

Term: sea_surface_infragravity_wave_significant_height
Definition: Significant wave height is a statistic computed from wave measurements and corresponds to the average height of the highest one-third of the waves, where the height is defined as the vertical distance from a wave trough to the following wave crest. Infragravity waves are waves occurring in the frequency range 0.04 to 0.004 s^-1 (wave periods of 25 to 250 seconds).

And then for consistency I have added to the definition of sea_surface_wave_period_at_variance_spectral_density_maximum:

Term: sea_surface_wave_period_at_variance_spectral_density_maximum
Definition: A period is an interval of time, or the time-period of an oscillation. The sea_surface_wave_period_at_variance_spectral_density_maximum, sometimes called peak wave period, is the period of the most energetic waves in the total wave spectrum at a specific location. Wave period is the interval of time between repeated features on the waveform such as crests, troughs or upward passes through the mean level. The wave directional spectrum can be written as a five dimensional function S(t,x,y,f,theta) where t is time, x and y are horizontal coordinates (such as longitude and latitude), f is frequency and theta is direction. S has the standard name sea_surface_wave_directional_variance_spectral_density. S can be integrated over direction to give S1= integral(S dtheta) and this quantity has the standard name sea_surface_wave_variance_spectral_density. The density of a substance is its mass per unit volume. The phrase "wave_period_at_variance_spectral_density_maximum", sometimes called peak wave period, describes the period of the most energetic waves within a given sub-domain of the wave spectrum.

Any comments of discussion welcome. Thanks

**Comment by feggleton** [comment]
Hi all, if everyone is happy with the discussed terms above and there are no further comments in the next 7 days then these can be accepted. @ukmo-ansaulter are you happy with the above?

**Comment by feggleton** [comment]
Thanks these can now be accepted @japamment and will be included in the next update, after which this ticket will be closed.

**Comment by feggleton** [comment]
These terms were added to the Standard Name Table Version 80 on the 7th of Feb 2023.
