### ISSUE TITLE
Issue with wind shear standard names

### ISSUE THREAD

**Issue by emilye12** [cf-convention/discuss#91]
**Question/potential issue with vertical directional wind shear:**
In the last proposal we submitted (_Standard Names: Meteorological Standard Names Proposal for CAMPS #55_), we requested 9 wind shear variables and all were accepted.  After reviewing our own work, as we were preparing our second standard name proposal submission, we realized that there were 2 wind shear variables already present in the standard name table at the time our proposal was accepted.

**Standard names prior to our proposal:**
eastward_wind_shear 
northward_wind_shear

**Definitions:** 
"Eastward (northward)" indicates a vector component which is positive when directed eastward (northward) (negative westward (southward)). Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) Wind shear is the derivative of wind with respect to height.

**Possibly equivalent standard names added by our last proposal:**
upward_derivative_of_northward_wind
upward_derivative_of_eastward_wind

**Definitions:**
The quantity with standard name upward_derivative_of_eastward(northward)_wind is the derivative of the eastward(northward) component of wind with respect to height. The phrase "component_derivative_of_X" means derivative of X with respect to distance in the component direction, which may be "northward", "southward", "eastward", "westward", "upward", "downward", "x" or "y". The last two indicate derivatives along the axes of the grid, in the case where they are not true longitude and latitude. A positive value indicates that X is increasing with distance along the positive direction of the axis. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name "upward_air_velocity").

**A possible 3rd overlap:**
There is also a standard name “wind_speed_shear” which appears to be a more generic way of describing the speed shear in general.  Basically, this is the magnitude of the vector components of speed shear.

**Definition:** 
Speed is the magnitude of velocity. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) The wind speed is the magnitude of the wind velocity. Wind speed shear is the derivative of wind speed with respect to height.

**Solution:**
We can see how the term “wind_speed_shear” could co-exist with the two terms that break that down to the two velocity vectors.  But for the other 4 terms, it seems like these are simply a set of 2 standard names that mean roughly the exact same thing. Given they now all exist, would an **alias** be appropriate for the 2 sets of overlapping standard names?  I’m not sure how we all overlooked this before!  Sorry about that!!

Emily Schlie, Eric Engle and the CAMPS team

**Comment by JonathanGregory** [comment]
Dear @emilye12

Thanks for noticing. I think the newly agreed standard names are better than than existing ones! I'd be happy if the existing ones were made aliases of your new ones.

Best wishes

Jonathan

**Comment by emilye12** [comment]
@JonathanGregory 

Great!  I agree, but I'm biased.  I do think the language of the new ones agree better as a whole than before though.  And are more descriptive.  

We appreciate the response!

**Comment by feggleton** [comment]
@japamment we need to do a bit of sorting here to deprecate the old terms and then create alias'.

**Comment by feggleton** [comment]
@japamment let's discuss this one on Monday.

**Comment by efisher008** [comment]
Hello @emilye12,

As there seems to be a general agreement to make this change, I've marked this for "accept within 7 days" and will hopefully make this change with @japamment by the end of next week.

Best regards,
Ellie

**Comment by efisher008** [comment]
Hello @emilye12,

These changes have been made in the editor and the former names will be kept as aliases. The standalone versions of the new names (proposed on 2020/06/12) will be removed from the standard names table before publication. Thank you again!

Best regards,
Ellie
