### ISSUE TITLE
 Standard names: **

### ISSUE THREAD

**Issue by emilye12** [cf-convention/discuss#92]
Proposer's name:  Emily Schlie, Eric Engle, and the CAMPS team (NOAA MDL)
Date: 12/22/2020

**Standard Name:** altimeter_setting
**Definition:**  The air pressure value, to which an aircraft altimeter scale is set, so that it will indicate the altitude above mean sea level pressure of an aircraft on the ground, at the location for which the value was determined.  Commonly reported as inches of mercury for a METAR observation.
**Units:** Pa
**Source:** https://www.ofcm.gov/publications/fmh/FMH1/FMH1_2017.pdf

**Standard Name:** atmosphere_helicity
**Definition:** One-half the scalar product of the velocity and vorticity vectors, where vorticity refers to the standard name atmosphere_upward_absolute_vorticity.  Helicity is proportional to the strength of the flow, the amount of vertical wind shear, and the amount of turning in the flow. 
**Units:** m^2/s^2
**Source:** 
https://glossary.ametsoc.org/wiki/Helicity
https://forecast.weather.gov/glossary.php?word=helicity

**Standard Name:** Bunkers_Storm_Motion
**Definition:** Storm motion is defined as a two dimensional velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) Storm motion follows the methodology outlined in Bunkers et al. (2000). It is defined as the average speed of a supercell, and the direction the storm will move from. It is not dependent on the orientation of the ground-relative winds.  
**Units:** m/s
**Source:** https://www.spc.noaa.gov/exper/soundings/help/vectors.html
**Publication source:** Predicting Supercell Motion Using a New Hodograph Technique, Bunkers et al., 2000

**Standard Name:** northward_storm_motion
**Definition:** The northward component of storm_motion.  "Northward" indicates a vector component which is positive when directed northward (negative southward). Storm_motion is defined as the average speed of a storm and the direction the storm will move from.
**Units:** m/s
**Source:**  https://forecast.weather.gov/glossary.php?word=storm%20motion

**Standard Name:**  eastward_storm_motion
**Definition:** The eastward component of storm motion.  “Eastward” indicates a vector component which is positive when directed eastward (negative westward). Storm motion is defined as the average speed of a storm and the direction the storm will move from.
**Units:** m/s
**Source:** https://forecast.weather.gov/glossary.php?word=storm%20motion

**Standard Name:** predominant_vegetation_type_at_surface
**Definition:** A variable with the standard name predominant_vegetation_type_at_surface contains strings which indicate the character of the predominant vegetation type at a location or grid cell. These strings have not yet been standardized. Alternatively, the data variable may contain integers which can be translated to strings using flag_values and flag_meanings attributes. "Vegetation" means any plants e.g. trees, shrubs, grass. The term "plants" refers to the kingdom of plants in the modern classification which excludes fungi. Plants are autotrophs i.e. "producers" of biomass using carbon obtained from carbon dioxide.
**Units:** unitless
**Source:** Followed predominant_precipitation_type example

**Standard Name:** surface_ice_binary_mask
**Definition:** X"_binary_mask" has 1 where condition X is met, 0 elsewhere. The value is 1 where the ice cover area fraction is greater than a threshold, and 0 elsewhere. The threshold must be specified by associating a coordinate variable or scalar coordinate variable with the data variable and giving the coordinate variable a standard name of surface_ice_area_fraction. The values of the coordinate variable are the threshold values for the corresponding subarrays of the data variable.
**Units:** unitless 
**Source:** Followed “surface_snow_binary_mask” CF example

**Standard Name:** surface_ice_area_fraction
**Definition:** "Area fraction" is the fraction of a grid cell's horizontal area that has some characteristic of interest. It is evaluated as the area of interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. The surface called "surface" means the lower boundary of the atmosphere. The phrase "surface_ice" means ice lying on the surface.
**Units:** unitless
**Source:** followed current “surface_snow_area_fraction” CF example

**Comment by JonathanGregory** [comment]
Dear @emilye12

Thanks for your new proposals. I have various comments:

**altimeter_setting**. This quantity is a value of `air_pressure` or `surface_air_pressure`, which are existing standard names. It's not a distinct geophysical quantity. It doesn't seem to me that it should have a standard name.

**atmosphere_helicity**. I agree that this should have a standard name. Your definition agrees with the AMetSoc glossary. Perhaps it should say "air velocity", to be clear.

**storm motion**. I see from web pages that the method of Bunkers et al. (2000) is quite frequently referred to. I'm not an expert, of course, and I wonder whether their method defines a distinct geophysical quantity, or is it a particular method to evaluate a more general concept of storm motion. In the former case it would be appropriate to mention Bunkers in the name, but not in the latter. What are the arguments? If I understand correctly, this is a velocity vector. We don't give standard name to velocities, only to their components, which you have also proposed. I would say these components should be called e.g. `northward|eastward_`[`bunkers_`]`storm_velocity`.

**predominant vegetation type**. Vegetation types are named by the `area_type` table http://cfconventions.org/Data/area-type-table/current/build/area-type-table.html and more could be added. A data variable can therefore be called `area_type` if it identifies the vegetation type. If "predominant" vegetation type means the one with the largest area-fraction, this could be indicated by `cell_methods` of `area: mode`.

**surface ice**. What sort of ice do you have in mind? Again, these are named by the area_type table. The generic `area_fraction` standard name can be used for any of them, with a scalar coordinate variable of `area_type`. We don't currently have a generic `binary_mask` standard name, but would that meet the need?

Best wishes

Jonathan

**Comment by emilye12** [comment]
@JonathanGregory 

Thank you for your quick response here.  I apologize for our much delayed response in return!  We are working through your responses as a group this week and next and I hope to have our feedback submitted here soon.

I will say, you made good points about how to utilize existing standard names to meet our needs for some of these variables, which we had not thought of before.  So this proposal may turn out to be much shorter than our last, which is good!

Thanks!
Emily

**Comment by EricEngle-NOAA** [comment]
Hi @JonathanGregory.  Replying here specifically to our proposed surface_ice_binary_mask name.

Our motivation for this name is due to our use of the snow and ice gridded analyses and their application to statistical post-processing of atmospheric data.  Note that surface_snow_binary_mask already exists in the standard name table.

Our methodology for the name is partly due to their being 5 existing names [cloud,land,sea,sunlit,surface_snow]_binary_mask.  We also consulted the Generic Names section of this page (http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html).

I do see that there are many type of ice definitions in the area type table (http://cfconventions.org/Data/area-type-table/current/build/area-type-table.html).

Would sea_ice_binary_mask be acceptable in this case?  That is a combination of an area type and a generic name.

Thanks,
Eric

**Comment by JonathanGregory** [comment]
Dear @EricEngle-NOAA

Yes, `sea_ice_binary_mask` would be fine, in my opinion. I don't think there is a big danger from overwhelming proliferation of binary masks, with only half a dozen of them so far!

Best wishes

Jonathan

**Comment by emilye12** [comment]
### Updated Proposal - Emily Schlie, Eric Engle, and the CAMPS team (NOAA MDL)
Date: 03/26/2021

**Proposed Standard Name:** altimeter_setting
	We will use “air_pressure” or “surface_air_pressure” as advised. 

**Proposed standard Name:** predominant_vegetation_type_at_surface
	If we use the standard name “area_type”, and the table of the different area_types, can we propose new area_types?  There are definitely some area_types we can use which currently exist, but others are either questionable, or don’t exist.

**Proposed Standard Name:** atmosphere_helicity
**Definition:** One-half the scalar product of the air velocity and vorticity vectors, where vorticity refers to the standard name atmosphere_upward_absolute_vorticity.  Helicity is proportional to the strength of the flow, the amount of vertical wind shear, and the amount of turning in the flow. 
**Units:** m^2/s^2
**Source:** 
https://glossary.ametsoc.org/wiki/Helicity
https://forecast.weather.gov/glossary.php?word=helicity


### Area Fraction Discussion:

**Jonathan Gregory Comment:**  What sort of ice do you have in mind? Again, these are named by the area_type table. The generic area_fraction standard name can be used for any of them, with a scalar coordinate variable of area_type. We don't currently have a generic binary_mask standard name, but would that meet the need?

**Response:** We can definitely use the generic “area_fraction” standard name and then specify based on the area_type table.  We were basing this name off of the current standard name “surface_snow_area_fraction”.  It seemed logical to have a “surface_ice_area_fraction” as well.  Is the snow standard name deprecated?
	
### Binary Mask Discussion:
On the topic of the proposed “surface_ice_binary_mask”, we agreed previously that “sea_ice_binary_mask” would be acceptable here.  Ideally, we would still prefer the name to be “surface_ice_binary_mask’, so then the type of surface is abstract from the standard name. This would be similar to the current CF standard name “surface_snow_binary_mask”. However, for most of our use cases, we are working specifically with sea ice over water, so this seems like a good compromise.  

**Standard Name:** sea_ice_binary_mask (in place of “surface_ice_binary_mask”)
**Definition**: X"_binary_mask" has 1 where condition X is met, 0 elsewhere. The value is 1 where the sea ice cover area fraction is greater than a threshold, and 0 elsewhere. The threshold must be specified by associating a coordinate variable or scalar coordinate variable with the data variable and giving the coordinate variable a standard name of sea_ice_area_fraction. The values of the coordinate variable are the threshold values for the corresponding subarrays of the data variable.
**Units**: unitless 
**Source**: followed “surface_snow_binary_mask” CF example

### Storm Motion Discussion:

**Jonathan Gregory comment:**  
storm motion. I see from web pages that the method of Bunkers et al. (2000) is quite frequently referred to. I'm not an expert, of course, and I wonder whether their method defines a distinct geophysical quantity, or is it a particular method to evaluate a more general concept of storm motion. In the former case it would be appropriate to mention Bunkers in the name, but not in the latter. What are the arguments? If I understand correctly, this is a velocity vector. We don't give standard name to velocities, only to their components, which you have also proposed. I would say these components should be called e.g. northward|eastward_[bunkers_]storm_velocity.


**Response:**
It could be considered both in some regards, but probably falls into the latter category better. Our reasoning for requesting storm_motion is that it is somewhat like the standard name “wind_speed”.  There could be 3 different variables in a file with the standard names; wind speed, x component of wind, and y component of wind.  Perhaps there could be a generic “storm motion” standard name, and then the vector components as well.  The 3 standard names could be: 

*storm_motion - maybe reference bunkers motion in the definition here as the predominant method for evaluating storm motion.
*northward_storm_velocity
*eastward_storm_velocity


**New proposed standard names for storm motion:**
**Standard Name**: Storm_Motion
**Definition**: Storm motion is defined as a two dimensional velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) It is defined as the average speed of a supercell, and the direction the storm will move from. It is not dependent on the orientation of the ground-relative winds.  Storm motion generally follows the methodology outlined in Bunkers et al. (2000)
**Units**: m/s
**Source**: https://www.spc.noaa.gov/exper/soundings/help/vectors.html
Predicting Supercell Motion Using a New Hodograph Technique,    Bunkers et al., 2000

**Standard Name:** northward_storm_velocity
**Definition**: The northward component of storm_motion.  "Northward" indicates a vector component which is positive when directed northward (negative southward). Storm_motion is defined as the average speed of a storm and the direction the storm will move from.
**Units**: m/s
**Source**:  
https://forecast.weather.gov/glossary.php?word=storm%20motion


**Standard Name:**  eastward_storm_velocity
**Definition**: The eastward component of storm motion.  “Eastward” indicates a vector component which is positive when directed eastward (negative westward). Storm motion is defined as the average speed of a storm and the direction the storm will move from.
**Units**: m/s
**Source**:
https://forecast.weather.gov/glossary.php?word=storm%20motion

**Comment by JonathanGregory** [comment]
Dear @emilye12 

  * Yes, you can certainly propose new `area_types`.
  * I suppose we could define a generic `binary_mask` standard name, which would have to be qualified with an `area_type`, like the generic `area_fraction`, if that would help.
  * While the components of storm velocity are fine, you describe storm motion as a vector. There are no standard names for vectors, because they aren't contained in a single netCDF variable, so I don't see the need for this.

Best wishes

Jonathan

**Comment by ngalbraith** [comment]
Would it be preferable to use storm_motion_speed instead of storm_motion? From the units,  can tell that this is a speed, and the example variable name wind_speed does spell this out. Whenever vector components are defined, someone will want to supply them as speed and direction, in my experience.

**Comment by JonathanGregory** [comment]
I agree with with Nan @ngalbraith that `storm_motion_speed` would be a good name, if that's what it means i.e. the magnitude of the vector. Jonathan

**Comment by emilye12** [comment]
@JonathanGregory 

Thank you for all your feedback and assistance with this.  We are happy with the suggestion of "storm_motion_speed" as the name.  Additionally, the other suggestions you have made for editing the standard names we suggested also seem appropriate to us.  

I do have some unfortunate news.  Our project has lost funding for the immediate future.  So it looks like we will, at the very least, need to pause our efforts here.  It would be wonderful to see these standard names make it through, but the team can't really move forward with any formal work on this anymore.  Regardless of our project status, I am certain that the standard names we proposed, and those that have been published, will prove useful to many other groups and organizations wishing to be CF compliant!  

Thank you again for all of your feedback and help with this.  It's been a pleasure working with you on this!
Emily

**Comment by JonathanGregory** [comment]
Dear @emilye12 and colleagues

Thank you for your valuable contributions to CF, and for your willingness and open-mindedness in engaging in discussions in order achieve a consensus. I agree with you that the additions you have proposed will benefit plenty of people. I expect that the ones currently under consideration will be accepted as well. I am sorry you won't have any more time, at least in the immediate future, but perhaps we'll hear from you again in the further future.

Best wishes

Jonathan

**Comment by feggleton** [comment]
Hi all, 

Thank you for this proposal and all your contributions. I think I have got the cfeditor up to date with changes so I will post the most recent decisions below and please let me know if you're happy with them, if they are no longer needed or more discussion is required.

Term: storm_motion_speed
Definition: Storm motion speed is defined as a two dimensional velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.) It is defined as the average speed of a supercell, and the direction the storm will move from. It is not dependent on the orientation of the ground-relative winds. Storm motion speed generally follows the methodology outlined in Bunkers et al. (2000).

Term: atmosphere_helicity
Definition: One-half the scalar product of the air velocity and vorticity vectors, where vorticity refers to the standard name atmosphere_upward_absolute_vorticity. Helicity is proportional to the strength of the flow, the amount of vertical wind shear, and the amount of turning in the flow.

Are the following terms still required?...

Term: eastward_storm_velocity
Definition: The eastward component of storm motion. “Eastward” indicates a vector component which is positive when directed eastward (negative westward). Storm motion is defined as the average speed of a storm and the direction the storm will move from.

Term: northward_storm_velocity
Definition: The northward component of storm_motion. "Northward" indicates a vector component which is positive when directed northward (negative southward). Storm_motion is defined as the average speed of a storm and the direction the storm will move from.

I think the remaining terms were no longer needed due to the area type table and other solutions. These included: surface_ice_area_fraction, altimeter_setting,predominant_vegetation_type_at_surface,sea_ice_binary_mask. However a generic binary_mask term was mentioned as an option?

Let me know if I've got that wrong!

Thanks,

Fran

**Comment by feggleton** [comment]
From what I can make out, storm_motion_speed and atmosphere_helicity have been agreed and the others are not needed.

If there are no further comments on these 2 in the next 7 days then these can be accepted.

**Comment by feggleton** [comment]
storm_motion_speed and atmosphere_helicity have now been accepted.
