### ISSUE TITLE
Standard names: new proposal for viewable_snow_area_fraction in the context of the ESA Snow CCI Project

### ISSUE THREAD

**Issue by awi-gamma** [cf-convention/discuss#94]
**Proposer's name** ESA Snow CCI Project - Andreas Wiesmann
**Date** 2021-01-26
**- Term** viewable_snow_area_fraction
**- Description** "Area fraction" is the fraction of a grid cell's horizontal area that has some characteristic of interest. It is evaluated as the area of interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Viewable snow refers to the snow on objects or the ground, viewable
from a top view. It excludes snow obscured by plants or other objects and falling snowflakes. 
**- Units** 1

The standard name is proposed because the surface_snow_area_fraction is not covering our viewable snow product as it explicitly excludes snow on plants.

**Comment by JonathanGregory** [comment]
Dear Andreas

I appreciate this need. You're right, surface_snow (a phrase in many standard names) means snow lying on the ground. Snow on plants is called canopy_snow (only in one standard name so far, though canopy is in several). Therefore we could make call your quantity canopy_and_surface_snow_amount, to avoid introducing a new word in the CF vocabulary. Would that work?  

Best wishes

Jonathan

**Comment by awi-gamma** [comment]
If preferred we can use canopy_and_surface_snow instead of viewable_snow as proposed by Jonathan with the following new definitions:

Term: "canopy_and_surface_snow_area_fraction" 
Description: "Area fraction" is the fraction of a grid cell's horizontal area that has some characteristic of interest. It is evaluated as the area of interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Canopy and surface snow refers to the snow on the vegetative covering over a surface, and for a surface devoid of any vegetative cover to the snow on the ground, but excludes, for example falling snowflakes and snow on the surface obscured by vegetative cover. The canopy is often considered to be the outer surfaces of the vegetation. Plant height and the distribution, orientation and shape of plant leaves within a canopy influence the atmospheric environment and many plant processes within the canopy. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Canopy.
Unit: 1

cheers
andreas

**Comment by taylor13** [comment]
It could be a bit confusing how "area fraction" should be defined when two overlapping "surfaces" are considered: the earth's surface *and* the canopy surface.  Here one could compute the fraction as the union of the two fractions or the intersection of the two fractions.  "viewable" fraction perhaps better captures what is requested, which is the intersection.  Perhaps this should be specified at least in the definition.

**Comment by awi-gamma** [comment]
So what about the following definition as a compromise?

"Area fraction" is the fraction of a grid cell's horizontal area that
has some characteristic of interest. It is evaluated as the area of
interest divided by the grid cell area. It may be expressed as a
fraction, a percentage, or any other dimensionless representation of a
fraction. Canopy and surface snow area refers to the snow on objects or
the ground, viewable from a top view, but excludes, for example falling
snowflakes and snow on the surface obscured by vegetative cover. The
canopy is often considered to be the outer surfaces of the vegetation.
Plant height and the distribution, orientation and shape of plant
leaves within a canopy influence the atmospheric environment and many
plant processes within the canopy. Reference: AMS Glossary 
http://glossary.ametsoc.org/wiki/Canopy.

**Comment by taylor13** [comment]
I might edit the following sentence: 
```Canopy and surface snow area refers to the snow on objects or the ground, viewable from a top view, but excludes, for example falling snowflakes and snow on the surface obscured by vegetative cover.  ```
so that it reads:
```Canopy and surface snow area refers to the snow on objects or the ground as viewed from above, which excludes, for example, falling snow flakes and surface snow obscured by a canopy, vegetative cover, or other features resting on the surface . ```

I wonder what @JonathanGregory thinks.

**Comment by JonathanGregory** [comment]
I think the above makes good sense. Thank you, @awi-gamma and @taylor13

**Comment by awi-gamma** [comment]
thanks for your feedback and contributions, we can also fully agree. Maybe to summarize here my understanding of the resulting nomination. If you agree on it we can maybe close the discussion and proceed?

Term: "canopy_and_surface_snow_area_fraction"

Description: 
"Area fraction" is the fraction of a grid cell's horizontal area that
has some characteristic of interest. It is evaluated as the area of
interest divided by the grid cell area. It may be expressed as a
fraction, a percentage, or any other dimensionless representation of a
fraction. Canopy and surface snow area refers to the snow on objects or
the ground as viewed from above, which excludes, for example, falling
snow flakes and surface snow obscured by a canopy, vegetative cover, or
other features resting on the surface. The
canopy is often considered to be the outer surfaces of the vegetation.
Plant height and the distribution, orientation and shape of plant
leaves within a canopy influence the atmospheric environment and many
plant processes within the canopy. Reference: AMS Glossary
http://glossary.ametsoc.org/wiki/Canopy.

Units 1

**Comment by taylor13** [comment]
Looks good to me.  Thanks!

**Comment by feggleton** [comment]
Hi all, thanks for this proposal and for the helpful comments and discussion. This term and the associated changes agreed above have now been added to the cfeditor (http://cfeditor.ceda.ac.uk/proposals/1). We already have a standard phrase for surface snow and canopy so we should keep these the same. So changing "Canopy and surface snow area refers to the snow on objects or the ground as viewed from above, which excludes, for example, falling snow flakes and surface snow obscured by a canopy, vegetative cover, or other features resting on the surface. " to " The surface called "surface" means the lower boundary of the atmosphere. Surface snow refers to the snow on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and snow on plants. "Canopy" means the vegetative covering over a surface." This would give:

Term: canopy_and_surface_snow_area_fraction
Definition: "Area fraction" is the fraction of a grid cell's horizontal area that has some characteristic of interest. It is evaluated as the area of interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. The surface called "surface" means the lower boundary of the atmosphere. Surface snow refers to the snow on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and snow on plants. "Canopy" means the vegetative covering over a surface. The canopy is often considered to be the outer surfaces of the vegetation. Plant height and the distribution, orientation and shape of plant leaves within a canopy influence the atmospheric environment and many plant processes within the canopy. Reference: AMS Glossary http://glossary.ametsoc.org/wiki/Canopy.

**Comment by taylor13** [comment]
My understanding is that the requested new standard_name is supposed to be a quantity that does *not* include snow on the ground that cannot be "viewed" directly from above (as indicated by the original proposed name: "viewable_surface_snow_area").  Canopy_and_surface_snow apparently includes snow on the ground that might be hidden by a canopy when viewed from above.  I guess if we can't redefine "canopy and surface snow", then  we need a different standard_name here.  Perhaps "unobscured_surface_snow_fraction", which is similar to the originally proposed "viewable_surface_snow_fraction".  Note this excludes the fraction of surface snow that is hidden by the canopy or other surface features.  The definition of "unobscured surface snow" would be something like "Unobscured surface snow refers to the snow on objects or the ground as viewed from above, which excludes, for example, falling snow flakes and surface snow hidden by a canopy, vegetative cover, or other features resting on the surface."

**Comment by awi-gamma** [comment]
> My understanding is that the requested new standard_name is supposed to be a quantity that does _not_ include snow on the ground that cannot be "viewed" directly from above (as indicated by the original proposed name: "viewable_surface_snow_area"). Canopy_and_surface_snow apparently includes snow on the ground that might be hidden by a canopy when viewed from above. I guess if we can't redefine "canopy and surface snow", then we need a different standard_name here. Perhaps "unobscured_surface_snow_fraction", which is similar to the originally proposed "viewable_surface_snow_fraction". Note this excludes the fraction of surface snow that is hidden by the canopy or other surface features. The definition of "unobscured surface snow" would be something like "Unobscured surface snow refers to the snow on objects or the ground as viewed from above, which excludes, for example, falling snow flakes and surface snow hidden by a canopy, vegetative cover, or other features resting on the surface."

We went this path to avoid introducing a new word in the CF vocabulary. But with unobscured that would be the same issue, not? In that case I propose to go back to our initial proposal.

**Comment by taylor13** [comment]
I agree that we need to introduce a new word into the CF vocabulary.   Either "viewable_snow_area_fraction" or "unobscured_snow_area_fraction" would be acceptable to me, but I'm a little uncomfortable that both terms depend on the location of the observer.  The following option is longer but more explicit: "snow_area_fraction_as_viewed_from_above".  I'll be happy with any of these.  Hope others will express an opinion.

**Comment by awi-gamma** [comment]
we prefer "snow_area_fraction_viewable_from_above"

**Comment by JonathanGregory** [comment]
I agree that `snow_area_fraction_viewable_from_above` is a clear description. Thanks.

**Comment by feggleton** [comment]
Thanks all, @awi-gamma can you confirm the definition?

**Comment by awi-gamma** [comment]
The description could then be simplified as we avoid the term canopy. Here the updated proposal:

Term: "snow_area_fraction_viewable_from_above"

Description:
"Area fraction" is the fraction of a grid cell's horizontal area that has some characteristic of interest. It is evaluated as the area of
interest divided by the grid cell area. It may be expressed as a fraction, a percentage, or any other dimensionless representation of a fraction. Snow "viewable from above" refers to the snow on objects or the ground as viewed from above, which excludes, for example, falling snow flakes and snow obscured by a canopy, vegetative cover, or other features resting on the surface. 

Units 1

**Comment by taylor13** [comment]
looks fine to me.

**Comment by awi-gamma** [comment]
@taylor13 thanks for the feedback, 
@feggleton do you need any further information from my side?

cheers andreas

**Comment by feggleton** [comment]
Hi all,

Apologies for the delay I went on secondment. The editor has been updated with this definition. If there are no further comments in the next 7 days this can be accepted.

**Comment by feggleton** [comment]
This term has now been accepted into the standard name table.

**Comment by japamment** [comment]
Changes applied in version 78 of CF standard name table.
