### ISSUE TITLE
issues with Doppler current profiler descriptions

### ISSUE THREAD

**Issue by jklymak** [cf-convention/discuss#95]
In #56 you very kindly added CF names for acoustic Doppler current profilers, which is super helpful.  This data *needs* to appear in ADCP files to affect meaningful quality control.  

There are some misleading statements in the descriptions that could perhaps be modified.   Reference to https://www.comm-tec.com/Docs/Manuali/RDI/BBPRIME.pdf 

### beam_consistency_indicator_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water

```The "beam_consistency_indicator" is the degree to which the magnitudes of a collection (ensemble) of acoustic signals from multiple underwater acoustic transceivers relate to each other. ```

To me this makes it sound like the pings are compared to each other, but in fact they are being individually correlated with the transmitted pulse.  The strength of the correlation is a signal-to-noise quality, and the phase of the correlation is what is used to measure the Doppler shift:

```
The "beam_consistency_indicator" is the degree to which the received acoustic pulse is correlated with 
the transmitted pulse.  
```

I guess I think this was unfortunately named, but I don't know what your scope is to change this now...

### indicative_error_from_multibeam_acoustic_doppler_velocity_profiler_in_sea_water

```
 It is determined by differencing duplicate error velocity measurements made using different pairs of beams.
```

This isn't correct either.  You can form a solution for u,v, w, with three beams, and the ADCPs usually have 4, so the error velocity is the absolute difference in w between two 3-beam solutions.  Perhaps:

```
It is determined by the difference between the vertical velocity calculated from two 3-beam solutions.
```

Thanks a lot!

**Comment by roy-lowry** [comment]
Many thanks for the clarifications. I support their replacing the existing text in the descriptions.

**Comment by feggleton** [comment]
I have added these changes in the cfeditor (http://cfeditor.ceda.ac.uk/proposals/1). Please comment if there is any further discussion. If there are no further comments in the next 7 days I think these small changes can be accepted in order to clarify the definitions.

**Comment by feggleton** [comment]
These two terms have now been accepted.

**Comment by japamment** [comment]
Changes applied in version 78 of the standard name table.
