### ISSUE TITLE
 Standard names: atmosphere-wave-ocean stress terms

### ISSUE THREAD

**Issue by ukmo-ansaulter** [cf-convention/discuss#96]
**Proposer's name** : Andy Saulter
**Date** : 1st February 2021

**Notes**: Sorry this is a long one! The definitions below aim to describe parameters related to a decomposition of atmosphere-ocean surface stress transfers, when considering transmission via sea surface wave growth and dissipation. Terms for the decomposition at the wavy sea-surface (where wave induced stress dominates and turbulent stress is reduced to zero) are as follows:

(atmospheric) surface stress = viscous stress + wave supported stress

where wave supported stress is a related to the dynamic form drag associated with waves in different sea-states (see also Mete Uz et al., 2002; https://link.springer.com/article/10.1023/A:1013119313063 ), then:

(ocean) surface stress = viscous stress + wave dissipation stress

where wave dissipation stress differs from the wave supported stress. This is because some of the momentum flux from the atmosphere will be absorbed by the waves in building seas, whilst the waves will pass momentum to the ocean through dissipative processes such as whitecapping when seas are both building and in the initial phases of transition from wind-sea to swell dominated conditions. Finally, there is a return flux to the atmosphere, for example swell waves passing through otherwise still airs can cause a disturbance at the atmosphere sea surface boundary.

Based on existing definitions and the recent proposals from Nan Galbraith, hopefully the following are appropriate:

**Term:** surface_downward_eastward_stress_due_to_sea_surface_waves
**Unit:** Pa
The surface called "surface" means the lower boundary of the atmosphere. "Surface stress" means the shear stress (force per unit area) exerted by the wind at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, wind stress can drive near-surface currents. "Downward" indicates a vector component which is positive when directed downward (negative upward). "Eastward" indicates a vector component which is positive when directed northward (negative southward). "Downward eastward" indicates the ZX component of a tensor. A downward eastward stress is a downward flux of eastward momentum, which accelerates the lower medium eastward and the upper medium westward. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Sea surface waves" means the stress associated with form drag over sea surface waves.

**Term:** surface_downward_northward_stress_due_to_sea_surface_waves
**Unit:** Pa
The surface called "surface" means the lower boundary of the atmosphere. "Surface stress" means the shear stress (force per unit area) exerted by the wind at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, wind stress can drive near-surface currents. "Downward" indicates a vector component which is positive when directed downward (negative upward). "Northward" indicates a vector component which is positive when directed northward (negative southward). "Downward northward" indicates the ZY component of a tensor. A downward northward stress is a downward flux of northward momentum, which accelerates the lower medium northward and the upper medium southward. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Sea surface waves" means the stress associated with form drag over sea surface waves.

**Term:** surface_downward_eastward_stress_due_to_viscosity
**Unit:** Pa
The surface called "surface" means the lower boundary of the atmosphere. "Surface stress" means the shear stress (force per unit area) exerted by the wind at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, wind stress can drive near-surface currents. "Downward" indicates a vector component which is positive when directed downward (negative upward). "Eastward" indicates a vector component which is positive when directed northward (negative southward). "Downward eastward" indicates the ZX component of a tensor. A downward eastward stress is a downward flux of eastward momentum, which accelerates the lower medium eastward and the upper medium westward. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Viscosity" means the stress associated with viscous effects at the sea surface and is equivalent to the turbulent stress just outside the viscous sublayer.

**Term:** surface_downward_northward_stress_due_to_viscosity
**Unit:** Pa
The surface called "surface" means the lower boundary of the atmosphere. "Surface stress" means the shear stress (force per unit area) exerted by the wind at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, wind stress can drive near-surface currents. "Downward" indicates a vector component which is positive when directed downward (negative upward). "Northward" indicates a vector component which is positive when directed northward (negative southward). "Downward northward" indicates the ZY component of a tensor. A downward northward stress is a downward flux of northward momentum, which accelerates the lower medium northward and the upper medium southward. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Viscosity" means the stress associated with viscous effects at the sea surface and is equivalent to the turbulent stress just outside the viscous sublayer.

**Term:** sea_surface_downward_eastward_stress_due_to_sea_surface_waves_dissipation
**Unit:** Pa
The surface called "sea surface" means the upper boundary of the ocean. "Surface stress" means the shear stress (force per unit area) exerted at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, surface stress can drive near-surface currents. "Downward" indicates a vector component which is positive when directed downward (negative upward). "Eastward" indicates a vector component which is positive when directed northward (negative southward). "Downward eastward" indicates the ZX component of a tensor. A downward eastward stress is a downward flux of eastward momentum, which accelerates the lower medium eastward and the upper medium westward. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Sea surface waves dissipation" means the stress associated with sea surface waves dissipation processes such as whitecapping.

**Term:** sea_surface_downward_northward_stress_due_to_sea_surface_waves_dissipation
**Unit:** Pa
The surface called "sea surface" means the upper boundary of the ocean. "Surface stress" means the shear stress (force per unit area) exerted at the surface. A downward stress is a downward flux of momentum. Over large bodies of water, surface stress can drive near-surface currents. "Downward" indicates a vector component which is positive when directed downward (negative upward). "Northward" indicates a vector component which is positive when directed northward (negative southward). "Downward northward" indicates the ZY component of a tensor. A downward northward stress is a downward flux of northward momentum, which accelerates the lower medium northward and the upper medium southward. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Sea surface waves dissipation" means the stress associated with sea surface waves dissipation processes such as whitecapping.

**Term:** surface_upward_eastward_stress_due_to_sea_surface_waves
**Unit:** Pa
The surface called "surface" means the lower boundary of the atmosphere. "Surface stress" means the shear stress (force per unit area) exerted at the surface. An upward stress is an upward flux of momentum into the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). "Eastward" indicates a vector component which is positive when directed northward (negative southward). "Upward eastward" indicates the ZX component of a tensor. An upward eastward stress is an upward flux of eastward momentum, which accelerates the upper medium eastward and the lower medium westward. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Sea surface waves" means the stress associated with oscillatory motions of a wavy sea surface.

**Term:** surface_upward_northward_stress_due_to_sea_surface_waves
**Unit:** Pa
The surface called "surface" means the lower boundary of the atmosphere. "Surface stress" means the shear stress (force per unit area) exerted at the surface. An upward stress is an upward flux of momentum into the atmosphere. "Upward" indicates a vector component which is positive when directed upward (negative downward). "Northward" indicates a vector component which is positive when directed northward (negative southward). "Upward northward" indicates the ZY component of a tensor. An upward northward stress is an upward flux of northward momentum, which accelerates the upper medium northward and the lower medium southward. The specification of a physical process by the phrase "due_to_" process means that the quantity named is a single term in a sum of terms which together compose the general quantity named by omitting the phrase. "Sea surface waves" means the stress associated with oscillatory motions of a wavy sea surface.

**Comment by JonathanGregory** [comment]
Dear Andy

Thanks for these proposals, which make sense to me. I think the names you propose are pretty clear, except that it would be better if due_to_viscosity were more informative. Maybe this could be due_to_ocean_viscous_dissipation? Is this molecular viscosity, in a very thin boundary layer, or a turbulent process? Also, I think sea_surface_wave_dissipation would be more normal language than sea_surface_waves_dissipation, or you could consider dissipation_of_sea_surface_waves, like the existing phrase due_to_dissipation_of_orographic_gravity_waves.

Best wishes

Jonathan

**Comment by ukmo-ansaulter** [comment]
Dear @JonathanGregory 

Yes, I believe we could go with due_to_ocean_viscous_dissipation; this is a small scale turbulent process if I understand the literature correctly

Yes, dissipation_of_sea_surface_waves is much better than sea_surface_waves_dissipation, and would be my preferred choice

Cheers
Andy

**Comment by feggleton** [comment]
Hi all, thank you for this proposal and for the help given here. I have now added these terms to the cfeditor (http://cfeditor.ceda.ac.uk/proposals/1) and added the changes agreed above (name changes and the associated definition changes). Any further comments or discussion are welcome. Thank you for adding all relevant phrases to the definitions.

**Comment by feggleton** [comment]
Please do let me know if you're all happy with the terms above and if there is any further discussion to be had. If there are no further comments in the next 7 days then these terms can be accepted.

**Comment by feggleton** [comment]
These terms have now been accepted into the next update.

**Comment by japamment** [comment]
Changes applied in version 78 of the standard name table.
