### ISSUE TITLE
 Standard names: Spelling mistake in "realization" description

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/discuss#99]
Hello,

I have spotted a spelling mistake in the description of the `realization` standard name - the _asa_ in _Realization is used to label a dimension that can be thought of asa statistical sample, e.g., labelling members of a model ensemble._

**Proposer's name** David Hassell
**Date** 2021-02-04

The corrected description is:

**- Term** realization
**- Description** Realization is used to label a dimension that can be thought of as a statistical sample, e.g., labelling members of a model ensemble.
**- Units** 1

Thanks

**Comment by feggleton** [comment]
Thanks David, I have now added this to the cfeditor. I will mark this as accepted to go into the next update as I'm sure there won't be a discussion on this!

**Comment by japamment** [comment]
Changes applied in version 78 of the standard name table.
